// lib/materials/pdf-generator.ts
// PDF generation with kindergarten-appropriate sizing and educational font

import jsPDF from 'jspdf';
import { 
  CardSize, 
  CARD_SIZES, 
  SERIES_COLORS,
  MaterialCard,
  MaterialConfig,
} from './types';
import { AndikaFont, isAndikaFontLoaded } from './fonts/andika';

const A4_WIDTH = 210;
const A4_HEIGHT = 297;
const MARGIN = 10;

// Kindergarten-appropriate font sizes (LARGE for readability)
const KINDERGARTEN_FONT_SIZES: Record<CardSize, number> = {
  small: 40,      // Increased for better readability
  medium: 56,     // Large enough for 3-6 year olds
  large: 80,      // Very large for main cards
  jumbo: 110,     // Jumbo size for emphasis
};

// Sentence strip font size
const SENTENCE_FONT_SIZE = 44; // Large, clear text for reading

export function generateMaterialPDF(
  title: string,
  cards: MaterialCard[],
  config: MaterialConfig
): jsPDF {
  const dimensions = CARD_SIZES[config.cardSize];
  const fontSize = KINDERGARTEN_FONT_SIZES[config.cardSize];
  
  const usableWidth = A4_WIDTH - (MARGIN * 2);
  const usableHeight = A4_HEIGHT - (MARGIN * 2) - 15;
  
  const cardsPerRow = Math.floor(usableWidth / (dimensions.width + 5));
  const cardsPerCol = Math.floor(usableHeight / (dimensions.height + 5));
  
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Register educational font if available
  registerEducationalFont(pdf);

  // Title page
  addTitlePage(pdf, title, config, cards.length);
  
  // Card pages
  let cardIndex = 0;
  let pageNum = 1;
  
  while (cardIndex < cards.length) {
    pdf.addPage();
    pageNum++;
    
    // Page header
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`${title} - Page ${pageNum - 1}`, MARGIN, 8);
    
    for (let row = 0; row < cardsPerCol && cardIndex < cards.length; row++) {
      for (let col = 0; col < cardsPerRow && cardIndex < cards.length; col++) {
        const x = MARGIN + col * (dimensions.width + 5);
        const y = 15 + row * (dimensions.height + 5);
        
        drawCard(pdf, cards[cardIndex], x, y, dimensions.width, dimensions.height, fontSize, config);
        cardIndex++;
      }
    }
    
    addCuttingGuides(pdf, cardsPerRow, cardsPerCol, dimensions);
  }
  
  return pdf;
}

// Register educational font (Andika) if available
function registerEducationalFont(pdf: jsPDF): void {
  if (isAndikaFontLoaded()) {
    try {
      pdf.addFileToVFS('Andika-Regular.ttf', AndikaFont.normal);
      pdf.addFont('Andika-Regular.ttf', 'Andika', 'normal');
    } catch (error) {
      console.warn('Failed to register Andika font, using Helvetica fallback:', error);
    }
  }
}

// Get the appropriate font name (educational font if available, else Helvetica)
function getEducationalFont(): string {
  return isAndikaFontLoaded() ? 'Andika' : 'helvetica';
}

function addTitlePage(
  pdf: jsPDF, 
  title: string, 
  config: MaterialConfig,
  totalCards: number
): void {
  // Background
  const bgColor = hexToRgb(config.backgroundColor);
  pdf.setFillColor(bgColor.r, bgColor.g, bgColor.b);
  pdf.rect(0, 0, A4_WIDTH, A4_HEIGHT, 'F');
  
  // Title - Use educational font if available
  const fontName = getEducationalFont();
  pdf.setFont(fontName, isAndikaFontLoaded() ? 'normal' : 'bold');
  pdf.setFontSize(40);
  const titleColor = hexToRgb(config.color);
  pdf.setTextColor(titleColor.r, titleColor.g, titleColor.b);
  pdf.text(title, A4_WIDTH / 2, 60, { align: 'center' });
  
  // Subtitle
  pdf.setFont(fontName, 'normal');
  pdf.setFontSize(18);
  pdf.setTextColor(100, 100, 100);
  pdf.text('Montessori Language Materials', A4_WIDTH / 2, 78, { align: 'center' });
  
  // Info box
  pdf.setFillColor(255, 255, 255);
  pdf.roundedRect(40, 100, 130, 80, 5, 5, 'F');
  
  pdf.setFontSize(14);
  pdf.setTextColor(60, 60, 60);
  pdf.text(`Total Cards: ${totalCards}`, 50, 120);
  pdf.text(`Card Size: ${config.cardSize.toUpperCase()}`, 50, 138);
  pdf.text(`Print on: A4 Cardstock`, 50, 156);
  
  // Instructions
  pdf.setFontSize(12);
  pdf.setTextColor(100, 100, 100);
  pdf.text('Print at 100% scale, cut along dotted lines, laminate', 50, 200);
  
  // Footer
  pdf.setFontSize(10);
  pdf.text('Generated by Whale Montessori', A4_WIDTH / 2, 280, { align: 'center' });
}

function drawCard(
  pdf: jsPDF,
  card: MaterialCard,
  x: number,
  y: number,
  width: number,
  height: number,
  fontSize: number,
  config: MaterialConfig
): void {
  // Card background
  const bgColor = hexToRgb(config.backgroundColor);
  pdf.setFillColor(bgColor.r, bgColor.g, bgColor.b);
  
  const borderColor = hexToRgb(config.borderColor);
  pdf.setDrawColor(borderColor.r, borderColor.g, borderColor.b);
  pdf.setLineWidth(0.8);
  pdf.roundedRect(x, y, width, height, 4, 4, 'FD');
  
  // MAIN TEXT - Educational font, LARGE, CENTERED
  const fontName = getEducationalFont();
  pdf.setFont(fontName, isAndikaFontLoaded() ? 'normal' : 'bold');
  pdf.setFontSize(fontSize);
  
  const textColor = hexToRgb(config.color);
  pdf.setTextColor(textColor.r, textColor.g, textColor.b);
  
  // Calculate EXACT center
  const centerX = x + (width / 2);
  const centerY = y + (height / 2);
  
  // Draw text at exact center
  pdf.text(card.primary, centerX, centerY, { 
    align: 'center',
    baseline: 'middle',
  });
  
  // Phonetic hint (smaller, at bottom) - only for letter cards
  if (card.phonetic) {
    pdf.setFont(fontName, 'normal');
    pdf.setFontSize(fontSize * 0.25);
    pdf.setTextColor(120, 120, 120);
    pdf.text(card.phonetic, centerX, y + height - 5, {
      align: 'center',
    });
  }
}

function addCuttingGuides(
  pdf: jsPDF,
  cols: number,
  rows: number,
  dimensions: { width: number; height: number }
): void {
  pdf.setDrawColor(200, 200, 200);
  pdf.setLineDashPattern([2, 2], 0);
  pdf.setLineWidth(0.2);
  
  for (let i = 0; i <= cols; i++) {
    const x = MARGIN + i * (dimensions.width + 5) - 2.5;
    pdf.line(x, 12, x, A4_HEIGHT - MARGIN);
  }
  
  for (let i = 0; i <= rows; i++) {
    const y = 15 + i * (dimensions.height + 5) - 2.5;
    pdf.line(MARGIN - 2, y, A4_WIDTH - MARGIN + 2, y);
  }
  
  pdf.setLineDashPattern([], 0);
}

// Helper: Convert hex color to RGB
function hexToRgb(hex: string): { r: number; g: number; b: number } {
  // Remove # if present
  hex = hex.replace('#', '');
  
  // Handle shorthand hex
  if (hex.length === 3) {
    hex = hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2];
  }
  
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);
  
  return { r: r || 0, g: g || 0, b: b || 0 };
}

export { SERIES_COLORS, CARD_SIZES };
