# -*- coding: utf-8 -*-
# NOTE FOR FUTURE SESSIONS: fonts load from the canvas-design skill folder
# (/root/.claude/skills/canvas-design/canvas-fonts/) available in Cowork cloud sessions.
# Art inputs resolve from /mnt/user-data/uploads/... after device_stage_files; all
# Midjourney job UUIDs are in docs/curriculum/satpin-redesign/art-manifest.md.
U='/mnt/user-data/uploads/montree/phonics-images/satpin-v2/books'
BOOKS=[
dict(slug='snake-in-my-sock', title_lines=['Snake in','my SOCK!'], title_accent='SOCK!', title_size=40,
 band='WEEK 1  ·  THE SOUND  /s/', booknum='BOOK ONE OF SIX', cover='bk1/p7.png',
 sound='sss', sound_note='a held snake-hiss — never "ess", never "suh"',
 oral_words='snake · sun · soap · seal · star · sock',
 spreads=[
  dict(text='Sss…', style='drop', art='bk1/p1.png'),
  dict(text='Sss— SUN!', accent='Sss—', accent_first=True, art='bk1/p2.png'),
  dict(text='Sss— SOAP!', accent='Sss—', accent_first=True, art='bk1/p3.png'),
  dict(text='Sss— SEAL!', accent='Sss—', accent_first=True, art='bk1/p4.png'),
  dict(text='Sss— STAR!', accent='Sss—', accent_first=True, art='bk1/p5.png'),
  dict(text='shhh… sss…', style='whisper', art='bk1/p6.png'),
  dict(text=['Snake in','my SOCK!'], accent='SOCK!', size=54, art='bk1/p7.png'),
  dict(art='bk1/p8.png'),
 ]),
dict(slug='an-apple-for-ant', title_lines=['An Apple','for Ant!'], title_accent='Ant!', title_size=40,
 band='WEEK 2  ·  THE SOUND  /a/', booknum='BOOK TWO OF SIX', cover='bk2/p7.png',
 sound='a', sound_note='"ah–ah–ah" — never the letter name',
 oral_words='ant · ax · anchor · astronaut · alligator · apple',
 spreads=[
  dict(text='Ah— ANT!', accent='Ah—', accent_first=True, art='bk2/p1.png'),
  dict(text='An AX!', accent='An', accent_first=True, art='bk2/p2.png'),
  dict(text='An ANCHOR!', accent='An', accent_first=True, size=58, art='bk2/p3.png'),
  dict(text='An ASTRONAUT!', accent='An', accent_first=True, size=50, art='bk2/p4.png'),
  dict(text='shhh… an…', style='whisper', art='bk2/p5.png'),
  dict(text='AH! Ant!', style='drop', art='bk2/p6.png'),
  dict(text='An APPLE!', accent='An', accent_first=True, size=58, art='bk2/p7.png'),
  dict(art='bk2/p8.png'),
 ]),
dict(slug='the-sat', title_lines=['The ___','Sat!'], title_accent='Sat!', title_size=46,
 band='WEEK 3  ·  FIRST DECODE  ·  s a t', booknum='BOOK THREE OF SIX', cover='tiles/SAT-p6.png',
 new='Sat  ·  at', review='a', heart='♥  heart word — a',
 oral_note='the nouns live in the pictures — named aloud, never printed',
 spreads=[
  dict(nar='The ant…', text='Sat!', size=92, art='tiles/SAT-p1.png'),
  dict(nar='The snake…', text='Sat!', size=92, art='tiles/SAT-p2.png'),
  dict(nar='The apple…', text='Sat!', size=92, art='tiles/SAT-p3.png'),
  dict(nar='The sun…', text='Sat!', size=92, art='tiles/SAT-p4.png'),
  dict(nar='The star…', text='Sat!', size=92, art='tiles/SAT-p5.png'),
  dict(nar='The cat…', text='Sat!', size=92, art='tiles/SAT-p6.png'),
  dict(text=['Sat! Sat!','Sat!'], style='drop', size=64, art='tiles/SAT-p7.png'),
  dict(nar='And the…?!', art='tiles/SAT-p8.png'),
 ]),
dict(slug='spat', title_lines=['SPAT!'], title_accent='SPAT!', title_size=64,
 band='WEEK 4  ·  FIRST FULLY DECODABLE BOOK  ·  s a t p', booknum='BOOK FOUR OF SIX',
 cover=U+'/spat/spat-p7-spat-eruption.png',
 new='sap · pat · tap · spat', review=['sat'], heart='♥  heart word — a',
 spreads=[
  dict(text='Sat.', art=U+'/spat/spat-p1.png'),
  dict(text=['Sap.','Sap.','Sap.'], size=58, art=U+'/spat/spat-p2.png'),
  dict(text=['Sap!','Sat! Sat!'], size=58, art=U+'/spat/spat-p3.png'),
  dict(text=['Pat,','pat, pat.'], size=58, art=U+'/spat/spat-p4-sig-patched-webres.jpg'),
  dict(text=['Tap,','tap, tap.'], size=58, art=U+'/spat/spat-p5.png'),
  dict(text='Pat? Pat? Tap?', style='whisper', art='tiles/BK4-p6.png'),
  dict(text='SPAT!', style='drop', size=100, art=U+'/spat/spat-p7-spat-eruption.png'),
  dict(text=['Sat!','Sap! Tap!'], size=58, art=U+'/spat/spat-p8-aftermath.png'),
  dict(art=U+'/spat/spat-p9-wordless-cameo.png'),
 ]),
dict(slug='sit-sit-sit', title_lines=['Sit!','Sit! Sit!'], title_accent='Sit!', title_size=48,
 band='WEEK 5  ·  DECODABLE  ·  s a t p i', booknum='BOOK FIVE OF SIX',
 cover=U+'/sit/sit-sit-sit-p6-webres.jpg',
 new='sit · it · is · sip · pit · spit', review=['sat · pat · tap · sap'], heart='♥  heart word — a',
 spreads=[
  dict(text='Sit! Sit!', art=U+'/sit/sit-sit-sit-p1-webres.jpg'),
  dict(text='It is a pit!', size=58, art=U+'/sit/sit-sit-sit-p2-webres.jpg'),
  dict(text='Sit!', size=88, art=U+'/sit/sit-sit-sit-p3-webres.jpg'),
  dict(text='It is sap!', size=62, art=U+'/sit/sit-sit-sit-p4-webres.jpg'),
  dict(text='Sit! Sit!', art=U+'/sit/sit-sit-sit-p5-webres.jpg'),
  dict(text=['Sip,','sip, sip.'], size=58, art=U+'/sit/sit-sit-sit-p6-webres.jpg'),
  dict(text='Spit it!', style='drop', size=78, art=U+'/sit/sit-sit-sit-p7-webres.jpg'),
  dict(text=['It sits!','It is!'], size=58, art=U+'/sit/sit-sit-sit-p8-webres.jpg'),
  dict(art=U+'/sit/sit-sit-sit-p9-webres.jpg'),
 ]),
dict(slug='nap-ant-nap', title_lines=['Nap, Ant,','Nap!'], title_accent='Nap!', title_size=44,
 band='WEEK 6  ·  DECODABLE  ·  s a t p i n', booknum='BOOK SIX OF SIX',
 cover=U+'/nap/nap-ant-nap-p1-asleep-on-leaf.png',
 new='an · ant · in · nap · naps · pan · tin · nip · snap',
 review=['sit · it · is · pit · sip · spit','sat · pat · tap · sap'],
 heart='♥  heart words — a  ·  I',
 spreads=[
  dict(text=['An ant','naps.'], size=58, art=U+'/nap/nap-ant-nap-p1-asleep-on-leaf.png'),
  dict(text=['An ant naps','in a pan.'], size=46, art=U+'/nap/nap-ant-nap-p2-asleep-under-blanket-in-pan.png'),
  dict(text=['An ant naps','in a tin.'], size=46, art=U+'/nap/nap-ant-nap-p3-asleep-curled-in-tin.png'),
  dict(text=['An ant naps','in a…'], style='whisper', art=U+'/nap/nap-ant-nap-p4-tabby-looms-over-sleeping-ant.png'),
  dict(text='SNAP! Nip!', style='drop', size=64, art=U+'/nap/nap-ant-nap-p5-snap-paw-slam-ant-awake.png'),
  dict(text=['Nap, Ant, nap!','“I nap in it!”'], size=42, art=U+'/nap/nap-ant-nap-p6-ant-asleep-atop-tin-hat-on-pinned-cat.png'),
  dict(text=['An ant','naps.'], size=58, art=U+'/nap/nap-ant-nap-p7-drowsy-ant-on-teacher-potato.png'),
 ]),
]
