# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead.

NOTE (2026-08-02 curated rebuild): gen_dp_paperwork.py no longer exists in
the repo; this shim was hand-edited to match its established output exactly
when anchor+ambulance were dropped for anteater (p1-apple is the new
establishing page and is intentionally excluded here, same as the frame noun
was always excluded before; p5-recap is excluded too, matching every other
book's shim)."""
from dpbuild import build

BOOK = dict(
    slug='ant-on-my-apple',
    spreads=[
        dict(text='An ant on my apple!', art='p2-ant.png'),
        dict(text='An alligator on my apple!', art='p3-alligator.png'),
        dict(text='An anteater on my apple!', art='p4-anteater.png'),
    ],
)

build(BOOK)
