# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='ant-on-my-apple',
    spreads=[
        dict(text='An ant on my apple!', art='p1-ant.png'),
        dict(text='An anchor on my apple!', art='p2-anchor.png'),
        dict(text='An alligator on my apple!', art='p3-alligator.png'),
        dict(text='An ambulance on my apple!', art='p4-ambulance.png'),
    ],
)

build(BOOK)
