# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='bear-in-the-boat',
    spreads=[
        dict(text='A ball in the boat!', art='p1-ball.png'),
        dict(text='A banana in the boat!', art='p2-banana.png'),
        dict(text='A bell in the boat!', art='p3-bell.png'),
        dict(text='A bear in the boat!', art='p4-bear.png'),
    ],
)

build(BOOK)
