# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='cow-on-the-car',
    spreads=[
        dict(text='A cat on the car!', art='p1-cat.png'),
        dict(text='A cup on the car!', art='p2-cup.png'),
        dict(text='A comb on the car!', art='p3-comb.png'),
        dict(text='A cow on the car!', art='p4-cow.png'),
    ],
)

build(BOOK)
