# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='dinosaur-on-a-drum',
    spreads=[
        dict(text='A dog on a drum!', art='p1-dog.png'),
        dict(text='A doll on a drum!', art='p2-doll.png'),
        dict(text='A duck on a drum!', art='p3-duck.png'),
        dict(text='A dinosaur on a drum?!', art='p4-dinosaur.png'),
    ],
)

build(BOOK)
