# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='elephant-sat-on-the-egg',
    spreads=[
        dict(text='The hen sat on the egg.', art='p1-hen.png'),
        dict(text='The eagle sat on the egg.', art='p2-eagle.png'),
        dict(text='The elephant sat on the egg.', art='p3-elephant.png'),
    ],
)

build(BOOK)
