# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='fox-in-a-box',
    spreads=[
        dict(text='A fox in a box!', art='p1-fox.png'),
        dict(text='An ox in a box!', art='p2-ox.png'),
        dict(text='A xylophone in a box!', art='p3-xylophone.png'),
    ],
)

build(BOOK)
