# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='frog-on-the-fan',
    spreads=[
        dict(text='A frog on the fan!', art='p1-frog.png'),
        dict(text='A fish on the fan!', art='p2-fish.png'),
        dict(text='A feather on the fan!', art='p3-feather.png'),
        dict(text='A fork on the fan!', art='p4-fork.png'),
    ],
)

build(BOOK)
