# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='horse-in-my-hat',
    spreads=[
        dict(text='A hen in my hat!', art='p1-hen.png'),
        dict(text='A hammer in my hat!', art='p2-hammer.png'),
        dict(text='A heart in my hat!', art='p3-heart.png'),
        dict(text='A horse in my hat!', art='p4-horse.png'),
    ],
)

build(BOOK)
