# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='in-the-igloo',
    spreads=[
        dict(text='An iguana in the igloo!', art='p1-iguana.png'),
        dict(text='An insect in the igloo!', art='p2-insect.png'),
        dict(text='An inchworm in the igloo!', art='p3-inchworm.png'),
        dict(text='An infant in the igloo!', art='p4-infant.png'),
    ],
)

build(BOOK)
