# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='jellyfish-in-the-jar',
    spreads=[
        dict(text='A jug in the jar!', art='p1-jug.png'),
        dict(text='A jacket in the jar!', art='p2-jacket.png'),
        dict(text='A jet in the jar!', art='p3-jet.png'),
        dict(text='A jellyfish in the jar!', art='p4-jellyfish.png'),
    ],
)

build(BOOK)
