# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='koala-in-the-pocket',
    spreads=[
        dict(text='A key in the pocket!', art='p1-key.png'),
        dict(text='A kite in the pocket!', art='p2-kite.png'),
        dict(text='A kettle in the pocket!', art='p3-kettle.png'),
        dict(text='A koala in the pocket!', art='p4-koala.png'),
    ],
)

build(BOOK)
