# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='monkey-in-my-mug',
    spreads=[
        dict(text='A mouse in my mug!', art='p1-mouse.png'),
        dict(text='A mushroom in my mug!', art='p2-mushroom.png'),
        dict(text='A magnet in my mug!', art='p3-magnet.png'),
        dict(text='A monkey in my mug!', art='p4-monkey.png'),
    ],
)

build(BOOK)
