# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='not-in-my-nest',
    spreads=[
        dict(text='A nut in the nest!', art='p1-nut.png'),
        dict(text='A net in the nest!', art='p2-net.png'),
        dict(text='A nail in the nest!', art='p3-nail.png'),
        dict(text='A napkin in the nest!', art='p4-napkin.png'),
    ],
)

build(BOOK)
