# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='oh-no-lion',
    spreads=[
        dict(text='The lion licks a lemon!', art='p1-lemon.png'),
        dict(text='The lion licks a leaf!', art='p2-leaf.png'),
        dict(text='The lion licks a ladder!', art='p3-ladder.png'),
        dict(text='The lion licks a lizard!', art='p4-lizard.png'),
    ],
)

build(BOOK)
