# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='owl-ate-an-orange',
    spreads=[
        dict(text='An owl ate an orange!', art='p1-owl.png'),
        dict(text='An otter ate an orange!', art='p2-otter.png'),
        dict(text='An ostrich ate an orange!', art='p3-ostrich.png'),
        dict(text='An octopus ate an orange!', art='p4-octopus.png'),
    ],
)

build(BOOK)
