# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='on-a-rock',
    spreads=[
        dict(text='A duck on a rock!', art='p1-duck.png'),
        dict(text='A chick on a rock!', art='p2-chick.png'),
        dict(text='A clock on a rock!', art='p3-clock.png'),
        dict(text='A sock on a rock!', art='p4-sock.png'),
    ],
)

build(BOOK)
