# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='oh-no-goat',
    spreads=[
        dict(text='The goat ate my grapes!', art='p1-grapes.png'),
        dict(text='The goat ate my gloves!', art='p2-gloves.png'),
        dict(text='The goat ate my gift!', art='p3-gift.png'),
        dict(text='The goat plays my guitar?!', art='p4-guitar.png'),
    ],
)

build(BOOK)
