# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='pig-ate-a-pineapple',
    spreads=[
        dict(text='The pig ate a pineapple.', art='p1-pineapple.png'),
        dict(text='The pig ate a pen.', art='p2-pen.png'),
        dict(text='The pig ate a pencil.', art='p3-pencil.png'),
        dict(text='The pig ate a pan.', art='p4-pan.png'),
    ],
)

build(BOOK)
