# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='queen-on-the-quilt',
    spreads=[
        dict(text='A quill on the quilt!', art='p1-quill.png'),
        dict(text='A quarter on the quilt!', art='p2-quarter.png'),
        dict(text='A quail on the quilt!', art='p3-quail.png'),
        dict(text='A queen on the quilt!', art='p4-queen.png'),
    ],
)

build(BOOK)
