# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='rabbit-in-the-rocket',
    spreads=[
        dict(text='A rabbit in the rocket!', art='p1-rabbit.png'),
        dict(text='A robot in the rocket!', art='p2-robot.png'),
        dict(text='A rose in the rocket!', art='p3-rose.png'),
        dict(text='A ring in the rocket!', art='p4-ring.png'),
    ],
)

build(BOOK)
