# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='snake-in-my-sock',
    spreads=[
        dict(text='A snake in my sock!', art='p1-snake.png'),
        dict(text='A star in my sock!', art='p2-star.png'),
        dict(text='A soap in my sock!', art='p3-soap.png'),
        dict(text='A seal in my sock!', art='p4-seal.png'),
    ],
)

build(BOOK)
