# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead.

NOTE (2026-08-16 rebuild): gen_dp_paperwork.py no longer exists in the repo;
this shim was hand-edited again, reverting the 2026-08-01 sloth
simplification back to the original snake/star/soap/seal cast (p1-sock is
the establishing page and is intentionally excluded here, same as the frame
noun was always excluded before; p6-recap and the new p7-potato-twist bonus
page are excluded too, matching every other book's shim)."""
from dpbuild import build

BOOK = dict(
    slug='snake-in-my-sock',
    spreads=[
        dict(text='Snake in my sock!', art='p2-snake.png'),
        dict(text='Star in my sock!', art='p3-star.png'),
        dict(text='Soap in my sock!', art='p4-soap.png'),
        dict(text='Seal in my sock!', art='p5-seal.png'),
    ],
)

build(BOOK)
