# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='tiger-in-the-taxi',
    spreads=[
        dict(text='A turtle in the taxi!', art='p1-turtle.png'),
        dict(text='A tomato in the taxi!', art='p2-tomato.png'),
        dict(text='A toothbrush in the taxi!', art='p3-toothbrush.png'),
        dict(text='A tiger in the taxi!', art='p4-tiger.png'),
    ],
)

build(BOOK)
