# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='under-my-umbrella',
    spreads=[
        dict(text='A unicorn under my umbrella!', art='p1-unicorn.png'),
        dict(text='A ukulele under my umbrella!', art='p2-ukulele.png'),
        dict(text='A unicycle under my umbrella!', art='p3-unicycle.png'),
        dict(text='An urchin under my umbrella!', art='p4-urchin.png'),
    ],
)

build(BOOK)
