# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='volcano-in-the-van',
    spreads=[
        dict(text='A violin in the van!', art='p1-violin.png'),
        dict(text='A vase in the van!', art='p2-vase.png'),
        dict(text='A vest in the van!', art='p3-vest.png'),
        dict(text='A volcano in the van!', art='p4-volcano.png'),
    ],
)

build(BOOK)
