# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='whale-in-the-wagon',
    spreads=[
        dict(text='A worm in the wagon!', art='p1-worm.png'),
        dict(text='A watch in the wagon!', art='p2-watch.png'),
        dict(text='A wolf in the wagon!', art='p3-wolf.png'),
        dict(text='A whale in the wagon!', art='p4-whale.png'),
    ],
)

build(BOOK)
