# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='yak-on-the-yacht',
    spreads=[
        dict(text='A yak on the yacht!', art='p1-yak.png'),
        dict(text='A yam on the yacht!', art='p2-yam.png'),
        dict(text='A yo-yo on the yacht!', art='p3-yoyo.png'),
        dict(text='Yarn on the yacht!', art='p4-yarn.png'),
    ],
)

build(BOOK)
