# -*- coding: utf-8 -*-
"""Auto-generated by gen_dp_paperwork.py — data-only shim exposing this
book's spreads[] for build_tracing.py's bookScript loader. Do not hand-edit;
regenerate from scripts/curriculum/dark-phonics-storybooks/manifest.json
instead."""
from dpbuild import build

BOOK = dict(
    slug='zzz-at-the-zoo',
    spreads=[
        dict(text='A zebra at the zoo!', art='p1-zebra.png'),
        dict(text='A zipper at the zoo!', art='p2-zipper.png'),
        dict(text='A zucchini at the zoo!', art='p3-zucchini.png'),
        dict(text='A zeppelin at the zoo!', art='p4-zeppelin.png'),
    ],
)

build(BOOK)
