#!/usr/bin/env python3
"""
Pink Phase generator — POINTER + ARCHITECTURE NOTES.

The Pink Phase HTML (`public/whale-reading-content.html` and
`public/language-area-lessons.html`) was generated by a Python script
that lived at `/sessions/.../outputs/lesson-content/build.py` in
Session 112's sandbox. That sandbox is preserved per-session under
`~/Library/Application Support/Claude/local-agent-mode-sessions/...`
but is not committed to git.

This file documents the architecture so the Pink content is
reproducible — and any future edits to Pink content should follow the
SAME shape as the Blue and Green generators in this directory.

# Phase data structure (canonical, same across Pink / Blue / Green)

PHASE_DATA = [
    {
        'num': int,                  # lesson number (5..128)
        'letter' or 'pattern': str,  # what's being taught
        'sound': str,                # IPA-style sound
        'pool': str,                 # cumulative letter pool (Pink only)
        'rule' or 'articulation': str,  # how to present
        'spell': [str, ...],         # encoding words (movable alphabet)
        'read':  [str, ...],         # decoding words (word cards)
        'phrases': [str, ...],       # phrase cards
        'sentences': [str, ...],     # decodable sentences
        'pictures': [(word, hint), ...],  # picture-sourcing prompts
        'esl': str,                  # Mandarin-L1 articulation note
        'heart_words_intro': [str, ...],  # high-frequency irregulars
    },
    ...
]

# Audit gates (locked in Session 112, canonical for all phases)

1. Every word in every lesson MUST be decodable from the cumulative
   letter/pattern pool through that lesson.
2. No blends before L47 in any Pink/Blue lesson.
3. No silent letters before L104.
4. No vowel teams before L84.
5. Encoding before decoding (spell list rendered before read list).
6. Mandarin-L1 notes mandatory on any sound with documented L1
   transfer problems.
7. Heart-word coding canonical (black regular, RED irregular, small
   red heart icon below each red letter).

# How to re-render Pink Phase

The canonical HTML is already shipped at:
  - public/whale-reading-content.html        (Whale-branded admin copy)
  - public/language-area-lessons.html        (neutral Montree library copy)

To EDIT the content, the simplest path is:
  1. Copy build_blue.py or build_green.py as a template.
  2. Replace the data tables with Pink lesson data (L5-L53).
  3. Replace the pattern-integrity audit with Pink's letter-pool audit:
       cumulative = set(); for lesson in PHASE_DATA:
           cumulative.update(lesson['pool'].split(', '))
           for word in lesson['spell'] + lesson['read']:
               for c in word:
                   if c.isalpha() and c.lower() not in cumulative: REJECT
  4. Re-render. Diff against the current public/*.html to verify nothing
     unintended changed. Ship.

# The original build.py — recovery path

If you need the byte-exact original script, it survives at:
  ~/Library/Application Support/Claude/local-agent-mode-sessions/<session-id>/
    local_c6ad1b0f-cd3c-4572-b672-4b0b2817ca0f/outputs/lesson-content/build.py

(The exact path inside `local-agent-mode-sessions` varies per machine;
look for the directory that contains a `lesson-content/build.py` from
Session 112.)

If those sandboxes are gone, reconstruct from the Blue/Green pattern
+ this file's notes.
"""

# This script intentionally has no executable body.  Pink content is
# canonical-as-shipped at public/whale-reading-content.html.
# Re-rendering would require porting the full data tables from the
# Session 112 sandbox.  Until that's done, this script is a no-op.

if __name__ == '__main__':
    print(__doc__)
