-- Migration: Create home_master_curriculum table with 66 curated Montessori home works
-- Description: Master reference table for all 66 home Montessori works across 5 curriculum areas
-- This table stores the complete curriculum definition for the home Montessori learning environment

-- Create table
CREATE TABLE IF NOT EXISTS public.home_master_curriculum (
  id TEXT PRIMARY KEY,
  work_name TEXT NOT NULL,
  area_key TEXT NOT NULL,
  area_name TEXT NOT NULL,
  area_icon TEXT,
  area_color TEXT,
  description TEXT,
  age_range TEXT DEFAULT '3-6',
  sequence INTEGER,
  home_sequence INTEGER NOT NULL,
  home_priority TEXT NOT NULL DEFAULT 'recommended',
  home_tip TEXT,
  buy_or_make TEXT,
  estimated_cost TEXT,
  home_age_start TEXT,
  materials JSONB DEFAULT '[]'::jsonb,
  direct_aims JSONB DEFAULT '[]'::jsonb,
  indirect_aims JSONB DEFAULT '[]'::jsonb,
  control_of_error TEXT,
  prerequisites JSONB DEFAULT '[]'::jsonb,
  levels JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create index on area_key for efficient filtering
CREATE INDEX IF NOT EXISTS idx_home_master_curriculum_area_key ON public.home_master_curriculum(area_key);

-- Enable Row Level Security
ALTER TABLE public.home_master_curriculum ENABLE ROW LEVEL SECURITY;

-- Create RLS policy for service_role (full access)
DROP POLICY IF EXISTS service_role_policy_home_master_curriculum ON public.home_master_curriculum;
CREATE POLICY service_role_policy_home_master_curriculum
  ON public.home_master_curriculum
  FOR SELECT
  TO service_role
  USING (true);

-- Create RLS policy for anon role (read-only)
DROP POLICY IF EXISTS anon_policy_home_master_curriculum ON public.home_master_curriculum;
CREATE POLICY anon_policy_home_master_curriculum
  ON public.home_master_curriculum
  FOR SELECT
  TO anon
  USING (is_active = true);

-- Add comment to table
COMMENT ON TABLE public.home_master_curriculum IS 'Master reference table for 66 curated Montessori home curriculum works spanning Practical Life, Sensorial, Mathematics, Language, and Cultural Studies areas. Each work includes complete details on materials, aims, levels, costs, and implementation guidance for home learning environments.';

-- Insert PRACTICAL LIFE works (20 works)
INSERT INTO public.home_master_curriculum (id, work_name, area_key, area_name, area_icon, area_color, description, age_range, sequence, home_sequence, home_priority, home_tip, buy_or_make, estimated_cost, home_age_start, materials, direct_aims, indirect_aims, control_of_error, prerequisites, levels, is_active) VALUES
('pl_carrying_tray', 'Carrying a Tray', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Carrying a tray with objects balanced and stable', 'primary_year1', 1, 1, 'essential', 'Start with a wooden tray and lightweight objects like pompoms or soft balls. Keep it light and fun!', 'buy', '$8-15', '2.5', '["Small tray", "Various objects"]'::jsonb, '["Balance", "Coordination"]'::jsonb, '["Concentration", "Care of materials"]'::jsonb, 'Objects fall or slide', '[]'::jsonb, '[{"level": 1, "name": "Empty Tray", "description": "Carry empty tray with proper grip", "videoSearchTerms": ["montessori carrying tray"]}, {"level": 2, "name": "Tray with Light Objects", "description": "Carry with lightweight objects", "videoSearchTerms": ["montessori tray carrying objects"]}, {"level": 3, "name": "Tray with Fragile Objects", "description": "Carry tray with glass or breakable items", "videoSearchTerms": ["montessori tray fragile objects"]}]'::jsonb, true),
('pl_walking_line', 'Walking on the Line', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Walking carefully on a line marked on the floor', 'primary_year1', 2, 2, 'essential', 'Use painter''s tape to create a spiral or circle on the floor. Start with basic walking, gradually add challenges.', 'make', '$3-5', '3', '["Tape/painted line on floor", "Various objects", "Bell", "Glass of water", "Flag", "Basket on head"]'::jsonb, '["Balance", "Control of movement"]'::jsonb, '["Concentration", "Self-discipline"]'::jsonb, 'Stepping off the line', '[]'::jsonb, '[{"level": 1, "name": "Basic Walking", "description": "Walk slowly heel-to-toe on line", "videoSearchTerms": ["montessori walking on line"]}, {"level": 2, "name": "Walking with Hands Out", "description": "Arms extended for balance", "videoSearchTerms": ["montessori walking line balance"]}, {"level": 3, "name": "Walking with Bell", "description": "Carry bell without making sound", "videoSearchTerms": ["montessori walking line bell"]}]'::jsonb, true),
('pl_silence_game', 'The Silence Game', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Group activity to practice being completely still and silent', 'primary_year1', 3, 3, 'essential', 'Start with 1-2 minutes. Use a special bell or chime to signal beginning and end. Great for self-regulation!', 'make', 'Free', '3', '["Silence board/sign"]'::jsonb, '["Self-control", "Awareness"]'::jsonb, '["Concentration", "Community building", "Inner peace"]'::jsonb, 'Making any sound', '[]'::jsonb, '[{"level": 1, "name": "Basic Silence", "description": "Remain silent for short periods", "videoSearchTerms": ["montessori silence game"]}, {"level": 2, "name": "Extended Silence", "description": "Longer periods, listen for subtle sounds", "videoSearchTerms": ["montessori silence game extended"]}]'::jsonb, true),
('pl_pouring_dry', 'Pouring Dry Materials', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Pouring dry materials between pitchers', 'primary_year1', 4, 5, 'essential', 'Start with pasta, move to rice, then sand. Use child-sized pitchers. Set on a tray to contain spills.', 'either', '$10-20 (supplies in home)', '2.5', '["Two pitchers", "Dry materials", "Tray"]'::jsonb, '["Wrist control", "Coordination"]'::jsonb, '["Preparation for wet pouring", "Concentration"]'::jsonb, 'Spilled materials', '[]'::jsonb, '[{"level": 1, "name": "Large Grains", "description": "Pour large beans or pasta", "videoSearchTerms": ["montessori pouring dry large"]}, {"level": 2, "name": "Medium Grains", "description": "Pour rice or lentils", "videoSearchTerms": ["montessori pouring rice dry"]}, {"level": 3, "name": "Fine Materials", "description": "Pour sand or semolina", "videoSearchTerms": ["montessori pouring sand"]}]'::jsonb, true),
('pl_pouring_water', 'Pouring Water', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Pouring water between containers', 'primary_year1', 5, 6, 'essential', 'Use lightweight metal or plastic pitchers. Keep a sponge nearby for spills. This builds real independence!', 'buy', '$15-25', '3', '["Pitchers", "Glasses", "Sponge", "Tray"]'::jsonb, '["Wrist control", "Concentration"]'::jsonb, '["Independence", "Self-service"]'::jsonb, 'Spilled water', '[]'::jsonb, '[{"level": 1, "name": "Pitcher to Pitcher", "description": "Pour between two pitchers", "videoSearchTerms": ["montessori wet pouring pitcher"]}, {"level": 2, "name": "Pitcher to Large Glass", "description": "Pour into wide glass", "videoSearchTerms": ["montessori pouring into glass"]}, {"level": 3, "name": "Pitcher to Small Glass", "description": "Pour into narrow glass", "videoSearchTerms": ["montessori pouring small glass"]}]'::jsonb, true),
('pl_spooning', 'Spooning', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Transferring materials using a spoon', 'primary_year1', 6, 7, 'essential', 'Use wooden spoons and bowls. Start with large items, progress to rice. Excellent fine motor preparation!', 'buy', '$8-12', '2.5', '["Two bowls", "Spoon", "Dry materials (rice, beans, lentils)"]'::jsonb, '["Fine motor control", "Spoon grip"]'::jsonb, '["Preparation for self-feeding", "Concentration"]'::jsonb, 'Materials spill', '[]'::jsonb, '[{"level": 1, "name": "Large Spoon - Large Materials", "description": "Large spoon with beans/pasta", "videoSearchTerms": ["montessori spooning lesson"]}, {"level": 2, "name": "Large Spoon - Small Materials", "description": "Large spoon with rice/lentils", "videoSearchTerms": ["montessori spooning rice"]}, {"level": 3, "name": "Small Spoon - Large Materials", "description": "Teaspoon with beans", "videoSearchTerms": ["montessori small spoon transfer"]}]'::jsonb, true),
('pl_tonging', 'Tonging', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Transferring with various tongs', 'primary_year1', 7, 8, 'recommended', 'Start with salad tongs and cotton balls. Very engaging and builds hand strength for writing!', 'buy', '$10-15', '3', '["Two bowls", "Various tongs", "Objects to transfer"]'::jsonb, '["Hand strength", "Pincer grip development"]'::jsonb, '["Preparation for writing", "Concentration"]'::jsonb, 'Objects drop', '[]'::jsonb, '[{"level": 1, "name": "Salad Tongs - Large", "description": "Large tongs with cotton balls", "videoSearchTerms": ["montessori tongs transfer large"]}, {"level": 2, "name": "Salad Tongs - Medium", "description": "Tongs with pompoms", "videoSearchTerms": ["montessori tongs transfer pompoms"]}, {"level": 3, "name": "Ice Cube Tongs", "description": "Smaller tongs with small objects", "videoSearchTerms": ["montessori ice cube tongs"]}]'::jsonb, true),
('pl_frame_large_buttons', 'Large Buttons Frame', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Large button fastening', 'primary_year1', 8, 9, 'essential', 'Can purchase or DIY with fabric and large buttons. Critical for dressing independence!', 'either', '$15-20 or $5-8 DIY', '3', '["Large buttons dressing frame"]'::jsonb, '["Buttoning skill", "Bilateral coordination"]'::jsonb, '["Independence", "Fine motor"]'::jsonb, 'Buttons misaligned', '[]'::jsonb, '[{"level": 1, "name": "Unbuttoning", "description": "Open all buttons", "videoSearchTerms": ["montessori large button frame unbuttoning"]}, {"level": 2, "name": "Buttoning", "description": "Close all buttons", "videoSearchTerms": ["montessori large button dressing frame"]}]'::jsonb, true),
('pl_frame_zipper', 'Zipper Frame', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Separating and non-separating zippers', 'primary_year1', 9, 10, 'essential', 'DIY friendly! Mount zipper on fabric board. Essential for jacket independence!', 'either', '$12-18 or $3-5 DIY', '3', '["Zipper dressing frames"]'::jsonb, '["Zipper manipulation", "Bilateral coordination"]'::jsonb, '["Independence", "Dressing self"]'::jsonb, 'Zipper gets stuck', '[]'::jsonb, '[{"level": 1, "name": "Non-Separating Zipper", "description": "Zip up and down", "videoSearchTerms": ["montessori zipper frame"]}, {"level": 2, "name": "Separating Zipper", "description": "Connect and separate zipper", "videoSearchTerms": ["montessori separating zipper frame"]}]'::jsonb, true),
('pl_bow_tying_frame', 'Bow Tying Frame', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Tying bows', 'primary_year2', 10, 11, 'recommended', 'Easy DIY - fabric with ribbon sewn on. Great for shoe-tying prep!', 'either', '$8-12 or $2 DIY', '4', '["Bow tying dressing frame"]'::jsonb, '["Bow tying skill", "Bilateral coordination"]'::jsonb, '["Independence", "Fine motor mastery"]'::jsonb, 'Bow doesn''t hold', '[]'::jsonb, '[{"level": 1, "name": "Tying a Bow", "description": "Tie ribbon into bow", "videoSearchTerms": ["montessori bow tying dressing frame"]}]'::jsonb, true),
('pl_hand_washing', 'Hand Washing', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Complete hand washing procedure', 'primary_year1', 11, 13, 'essential', 'Set up a child-height wash station. Use a step stool. Essential daily life skill!', 'either', '$25-40 (supplies) or DIY with basin', '2.5', '["Basin", "Pitcher", "Soap", "Nail brush", "Hand towel", "Apron", "Bucket for dirty water"]'::jsonb, '["Hygiene", "Independence"]'::jsonb, '["Sequencing", "Concentration"]'::jsonb, 'Soap residue or dirt remains', '[]'::jsonb, '[{"level": 1, "name": "Basic Hand Washing", "description": "Wet, soap, scrub, rinse, dry", "videoSearchTerms": ["montessori hand washing"]}]'::jsonb, true),
('pl_dressing_self', 'Dressing Oneself', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Putting on and removing clothing', 'primary_year1', 12, 14, 'essential', 'Use the flip jacket method. Store clothes in accessible, labeled drawers. Patience is key!', 'make', 'Free (organize existing clothes)', '2.5', '["Child''s own clothing"]'::jsonb, '["Independence", "Self-sufficiency"]'::jsonb, '["Sequencing", "Body awareness"]'::jsonb, 'Clothing inside out or backwards', '[]'::jsonb, '[{"level": 1, "name": "Putting On Jacket", "description": "Flip method for jacket", "videoSearchTerms": ["montessori putting on jacket flip"]}, {"level": 2, "name": "Putting On Shoes", "description": "Identify left/right, put on", "videoSearchTerms": ["montessori putting on shoes"]}, {"level": 3, "name": "Full Dressing", "description": "Complete outfit independently", "videoSearchTerms": ["montessori dressing independently"]}]'::jsonb, true),
('pl_sweeping', 'Sweeping', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Using broom and dustpan', 'primary_year1', 13, 15, 'essential', 'Child-sized broom and dustpan are essential. Kids love helping! Builds responsibility beautifully.', 'buy', '$15-25', '3', '["Child-sized broom", "Dustpan", "Hand brush", "Waste basket"]'::jsonb, '["Coordination", "Care of environment"]'::jsonb, '["Responsibility", "Order"]'::jsonb, 'Debris remains visible', '[]'::jsonb, '[{"level": 1, "name": "Hand Brush and Pan", "description": "Sweep small area", "videoSearchTerms": ["montessori sweeping hand brush"]}, {"level": 2, "name": "Full Broom - Small Area", "description": "Sweep designated space", "videoSearchTerms": ["montessori sweeping small area"]}]'::jsonb, true),
('pl_plant_care', 'Plant Care', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Caring for classroom plants', 'primary_year1', 14, 16, 'recommended', 'Start with hardy plants like succulents. Low-maintenance but teaches care and responsibility.', 'buy', '$15-30 (plants and supplies)', '3', '["Plants", "Watering can", "Spray bottle", "Cloth for leaves", "Small shovel"]'::jsonb, '["Care of living things", "Responsibility"]'::jsonb, '["Biology awareness", "Nurturing"]'::jsonb, 'Dry soil, wilting, dusty leaves', '[]'::jsonb, '[{"level": 1, "name": "Watering", "description": "Water with appropriate amount", "videoSearchTerms": ["montessori watering plants"]}, {"level": 2, "name": "Leaf Wiping", "description": "Clean dust from leaves", "videoSearchTerms": ["montessori wiping plant leaves"]}]'::jsonb, true),
('pl_flower_arranging', 'Flower Arranging', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Cutting and arranging flowers', 'primary_year1', 15, 17, 'enrichment', 'Use real flowers from yard or market. Safety scissors for cutting. Beautiful practical activity!', 'make', '$5-10 per week (flowers)', '3.5', '["Flowers", "Vase", "Scissors", "Pitcher", "Funnel", "Sponge", "Apron", "Newspaper"]'::jsonb, '["Aesthetic appreciation", "Sequencing"]'::jsonb, '["Care of environment", "Concentration"]'::jsonb, 'Arrangement unbalanced', '[]'::jsonb, '[{"level": 1, "name": "Simple Arrangement", "description": "Arrange pre-cut flowers", "videoSearchTerms": ["montessori flower arranging simple"]}, {"level": 2, "name": "Complete Process", "description": "Cut, prepare vase, arrange", "videoSearchTerms": ["montessori flower arranging complete"]}]'::jsonb, true),
('pl_table_manners', 'Table Manners', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Proper behavior during meals', 'primary_year1', 16, 18, 'essential', 'Model behavior consistently. Make mealtimes peaceful and structured. Grace and courtesy happen naturally!', 'make', 'Free (model behavior)', '2.5', '["Table setting materials", "Placemat", "Dishes", "Utensils"]'::jsonb, '["Dining etiquette", "Social skills"]'::jsonb, '["Cultural awareness", "Self-control"]'::jsonb, 'Social feedback, visual template', '[]'::jsonb, '[{"level": 1, "name": "Sitting Properly", "description": "Sit correctly at table", "videoSearchTerms": ["montessori table manners sitting"]}, {"level": 2, "name": "Using Utensils", "description": "Proper utensil handling", "videoSearchTerms": ["montessori using utensils"]}]'::jsonb, true),
('pl_setting_table', 'Setting the Table', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Complete place setting', 'primary_year1', 17, 19, 'essential', 'Create a placemat template with outlines. Child places items in correct spots. Great sequencing practice!', 'make', '$3-5', '3', '["Placemat template", "Plate", "Cup", "Fork", "Knife", "Spoon", "Napkin"]'::jsonb, '["Sequencing", "Spatial awareness"]'::jsonb, '["Contribution", "Order"]'::jsonb, 'Items don''t match template', '[]'::jsonb, '[{"level": 1, "name": "Basic Setting", "description": "Place setting with template", "videoSearchTerms": ["montessori table setting"]}]'::jsonb, true),
('pl_cutting_soft', 'Cutting Soft Foods', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Cutting with child-safe knife', 'primary_year1', 18, 20, 'essential', 'Child-safe knives with round tips essential. Start with very soft foods. Real food prep is wonderful!', 'buy', '$8-15', '3.5', '["Cutting board", "Child-safe knife", "Soft foods (banana, cheese, cucumber)"]'::jsonb, '["Knife skills", "Coordination"]'::jsonb, '["Independence", "Safety awareness"]'::jsonb, 'Uneven slices', '[]'::jsonb, '[{"level": 1, "name": "Cutting Banana", "description": "Slice banana into rounds", "videoSearchTerms": ["montessori cutting banana"]}, {"level": 2, "name": "Cutting Cheese", "description": "Cut cheese into cubes", "videoSearchTerms": ["montessori cutting cheese"]}]'::jsonb, true),
('pl_making_snack', 'Making a Snack', 'practical_life', 'Practical Life', '🌱', '#4CAF50', 'Preparing complete simple snacks', 'primary_year1', 19, 21, 'essential', 'Simple snacks: crackers & cheese, apple slices, fruit plate. Real independence and life skill!', 'make', 'Free-$5 (snack supplies)', '3', '["Various snack ingredients", "Utensils", "Plate"]'::jsonb, '["Sequencing", "Independence"]'::jsonb, '["Self-care", "Planning"]'::jsonb, 'Snack not complete', '[]'::jsonb, '[{"level": 1, "name": "Crackers with Spread", "description": "Prepare crackers with topping", "videoSearchTerms": ["montessori snack preparation crackers"]}, {"level": 2, "name": "Fruit Plate", "description": "Cut and arrange fruits", "videoSearchTerms": ["montessori fruit plate preparation"]}]'::jsonb, true);

-- Insert SENSORIAL works (10 works)
INSERT INTO public.home_master_curriculum (id, work_name, area_key, area_name, area_icon, area_color, description, age_range, sequence, home_sequence, home_priority, home_tip, buy_or_make, estimated_cost, home_age_start, materials, direct_aims, indirect_aims, control_of_error, prerequisites, levels, is_active) VALUES
('se_cylinder_block_1', 'Cylinder Block 1', 'sensorial', 'Sensorial', '👁️', '#FF9800', 'Cylinders varying in diameter only (same height)', 'primary_year1', 1, 1, 'essential', 'Core Montessori material. Builds fine motor and visual discrimination skills essential for writing.', 'buy', '$35-50', '2.5', '["Cylinder Block 1 with 10 cylinders"]'::jsonb, '["Visual discrimination of diameter", "Fine motor - pencil grip"]'::jsonb, '["Preparation for writing", "Concentration", "Mathematical mind"]'::jsonb, 'Cylinders don''t fit or one left over', '[]'::jsonb, '[{"level": 1, "name": "Basic Presentation", "description": "Remove and replace cylinders randomly", "videoSearchTerms": ["montessori cylinder block 1 presentation"]}, {"level": 2, "name": "In Order", "description": "Replace in sequence", "videoSearchTerms": ["montessori cylinder block 1 order"]}]'::jsonb, true),
('se_pink_tower', 'Pink Tower', 'sensorial', 'Sensorial', '👁️', '#FF9800', 'Ten pink wooden cubes graduating from 1cm³ to 10cm³', 'primary_year1', 2, 2, 'essential', 'Iconic Montessori material. Develops spatial awareness, visual discrimination, and concentration.', 'buy', '$40-60', '2.5', '["10 Pink Cubes"]'::jsonb, '["Visual discrimination of size in three dimensions", "Vocabulary: large/small"]'::jsonb, '["Mathematical mind (cube numbers)", "Coordination", "Concentration"]'::jsonb, 'Tower falls or looks incorrect', '[]'::jsonb, '[{"level": 1, "name": "Vertical Tower", "description": "Build tower largest to smallest", "videoSearchTerms": ["montessori pink tower presentation"]}, {"level": 2, "name": "Horizontal Layout", "description": "Arrange cubes in line", "videoSearchTerms": ["montessori pink tower horizontal"]}]'::jsonb, true),
('se_brown_stair', 'Brown Stair (Broad Stair)', 'sensorial', 'Sensorial', '👁️', '#FF9800', 'Ten brown wooden prisms with constant length but varying width/height from 1cm to 10cm', 'primary_year1', 3, 3, 'essential', 'Works beautifully alongside Pink Tower. Can combine for extensions. Develops spatial awareness.', 'buy', '$35-50', '3', '["10 Brown Prisms"]'::jsonb, '["Visual discrimination of width/thickness", "Vocabulary: thick/thin, wide/narrow"]'::jsonb, '["Mathematical mind (square numbers)", "Coordination"]'::jsonb, 'Stair uneven or incorrect sequence', '[]'::jsonb, '[{"level": 1, "name": "Building Stair", "description": "Arrange thickest to thinnest", "videoSearchTerms": ["montessori brown stair presentation"]}, {"level": 2, "name": "Vertical Stair", "description": "Build stair going up", "videoSearchTerms": ["montessori brown stair vertical"]}]'::jsonb, true),
('se_red_rods', 'Red Rods (Long Rods)', 'sensorial', 'Sensorial', '👁️', '#FF9800', 'Ten red wooden rods varying in length from 10cm to 1 meter', 'primary_year1', 4, 4, 'essential', 'Direct preparation for Number Rods. Excellent gross motor and visual discrimination work.', 'buy', '$30-45', '3', '["10 Red Rods"]'::jsonb, '["Visual discrimination of length", "Vocabulary: long/short"]'::jsonb, '["Preparation for number rods", "Spatial awareness", "Coordination"]'::jsonb, 'Rods don''t align at one end, stair uneven', '[]'::jsonb, '[{"level": 1, "name": "Building Stair", "description": "Arrange longest to shortest aligned at one end", "videoSearchTerms": ["montessori red rods presentation"]}, {"level": 2, "name": "Maze Pattern", "description": "Create maze with alternating alignment", "videoSearchTerms": ["montessori red rods maze"]}]'::jsonb, true),
('se_color_box_1', 'Color Box 1 (Primary Colors)', 'sensorial', 'Sensorial', '👁️', '#FF9800', 'Three pairs of color tablets - red, yellow, blue', 'primary_year1', 5, 5, 'essential', 'Start here before Box 2. Great for vocabulary and visual matching. Very affordable DIY option.', 'either', '$12-18 or $3-5 DIY', '2.5', '["Color Box 1 with 6 tablets"]'::jsonb, '["Color recognition", "Visual matching", "Vocabulary: red, yellow, blue"]'::jsonb, '["Concentration", "Visual discrimination"]'::jsonb, 'Colors don''t match', '[]'::jsonb, '[{"level": 1, "name": "Matching Primary Colors", "description": "Match the three pairs", "videoSearchTerms": ["montessori color box 1 presentation"]}, {"level": 2, "name": "Naming Colors", "description": "Learn color names", "videoSearchTerms": ["montessori color box 1 naming"]}]'::jsonb, true),
('se_color_box_2', 'Color Box 2 (Secondary Colors)', 'sensorial', 'Sensorial', '👁️', '#FF9800', 'Eleven pairs of color tablets including primary, secondary, and other colors', 'primary_year1', 6, 6, 'recommended', 'Progression from Color Box 1. Introduces orange, green, purple, pink, brown, black, white, gray.', 'either', '$18-25 or $5-8 DIY', '3', '["Color Box 2 with 22 tablets"]'::jsonb, '["Color discrimination", "Extended color vocabulary"]'::jsonb, '["Visual memory", "Concentration"]'::jsonb, 'Colors don''t match', '[]'::jsonb, '[{"level": 1, "name": "Matching All Colors", "description": "Match all 11 pairs", "videoSearchTerms": ["montessori color box 2 presentation"]}, {"level": 2, "name": "Naming All Colors", "description": "Name all colors", "videoSearchTerms": ["montessori color box 2 naming"]}]'::jsonb, true),
('se_geometric_cabinet', 'Geometric Cabinet', 'sensorial', 'Sensorial', '👁️', '#FF9800', 'Cabinet with six drawers containing 35 geometric shape insets', 'primary_year1', 7, 7, 'essential', 'Beautiful material for geometry vocabulary and shape discrimination. Quality investment!', 'buy', '$80-120', '3', '["Geometric Cabinet", "Presentation tray", "Three sets of matching cards"]'::jsonb, '["Visual discrimination of geometric forms", "Shape vocabulary"]'::jsonb, '["Preparation for geometry", "Fine motor", "Concentration"]'::jsonb, 'Shapes don''t fit in frames', '[]'::jsonb, '[{"level": 1, "name": "Presentation Tray", "description": "Circle, square, triangle introduction", "videoSearchTerms": ["montessori geometric cabinet presentation tray"]}]'::jsonb, true),
('se_touch_boards', 'Touch Boards', 'sensorial', 'Sensorial', '👁️', '#FF9800', 'Boards with contrasting textures', 'primary_year1', 8, 8, 'recommended', 'Excellent DIY project! Use sandpaper and wood. Develops finger sensitivity for writing.', 'either', '$15-25 or $5 DIY', '3', '["Touch Boards (3 boards)"]'::jsonb, '["Tactile discrimination", "Vocabulary: rough/smooth"]'::jsonb, '["Preparation for writing (finger sensitivity)", "Concentration"]'::jsonb, 'Texture difference is clearly felt', '[]'::jsonb, '[{"level": 1, "name": "Board 1 - Two Halves", "description": "Half sandpaper, half smooth wood", "videoSearchTerms": ["montessori touch board 1 rough smooth"]}]'::jsonb, true),
('se_binomial_cube', 'Binomial Cube', 'sensorial', 'Sensorial', '👁️', '#FF9800', 'Puzzle representing the cube of a binomial (a+b)³', 'primary_year1', 9, 9, 'enrichment', 'Beautiful puzzle! Introduces algebra concepts through play. Wonderful for older 3-6 children.', 'buy', '$45-65', '3.5', '["Binomial Cube in box"]'::jsonb, '["Visual discrimination", "3D spatial reasoning"]'::jsonb, '["Preparation for algebra", "Concentration"]'::jsonb, 'Pieces don''t fit in box, pattern doesn''t match lid', '[]'::jsonb, '[{"level": 1, "name": "Building in Box", "description": "Reconstruct cube following lid pattern", "videoSearchTerms": ["montessori binomial cube presentation"]}]'::jsonb, true),
('se_mystery_bag', 'Mystery Bag', 'sensorial', 'Sensorial', '👁️', '#FF9800', 'Bag containing objects to identify by touch', 'primary_year1', 10, 10, 'recommended', 'Super easy DIY! Use any drawstring bag and household objects. Develops tactile discrimination beautifully.', 'make', 'Free (use household items)', '3', '["Mystery Bag (cloth bag)", "Various familiar objects"]'::jsonb, '["Stereognostic sense development", "Mental visualization"]'::jsonb, '["Concentration", "Vocabulary"]'::jsonb, 'Object identification incorrect', '[]'::jsonb, '[{"level": 1, "name": "Familiar Objects", "description": "Identify common classroom objects", "videoSearchTerms": ["montessori mystery bag familiar objects"]}]'::jsonb, true);

-- Insert MATHEMATICS works (15 works)
INSERT INTO public.home_master_curriculum (id, work_name, area_key, area_name, area_icon, area_color, description, age_range, sequence, home_sequence, home_priority, home_tip, buy_or_make, estimated_cost, home_age_start, materials, direct_aims, indirect_aims, control_of_error, prerequisites, levels, is_active) VALUES
('ma_number_rods', 'Number Rods', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Ten red and blue rods representing quantities 1-10', 'primary_year1', 1, 1, 'essential', 'Foundation of Montessori math. Can DIY with dowels and paint. Teaches quantity visually!', 'either', '$35-50 or $8 DIY', '3', '["Number Rods (10 rods from 10cm to 1m)"]'::jsonb, '["Understanding quantity 1-10", "Number names", "Visual representation of quantity"]'::jsonb, '["Preparation for addition", "Linear counting"]'::jsonb, 'Rods don''t align correctly', '[]'::jsonb, '[{"level": 1, "name": "Introduction", "description": "Name quantities 1-10", "videoSearchTerms": ["montessori number rods introduction"]}, {"level": 2, "name": "Building Stair", "description": "Arrange in order 1-10", "videoSearchTerms": ["montessori number rods stair"]}]'::jsonb, true),
('ma_sandpaper_numerals', 'Sandpaper Numerals', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Textured numerals 0-9 for tracing', 'primary_year1', 2, 2, 'essential', 'Easy DIY with sandpaper and cardboard! Teaches numeral formation through touch. Critical for math readiness!', 'either', '$10-15 or $2 DIY', '3', '["Sandpaper Numerals 0-9"]'::jsonb, '["Numeral recognition", "Numeral formation", "Association of symbol to quantity"]'::jsonb, '["Preparation for writing numerals"]'::jsonb, 'Texture provides tactile feedback', '[]'::jsonb, '[{"level": 1, "name": "Tracing 1-3", "description": "Trace and name first numerals", "videoSearchTerms": ["montessori sandpaper numerals 1 2 3"]}]'::jsonb, true),
('ma_spindle_box', 'Spindle Boxes', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Box with compartments 0-9 for counting spindles', 'primary_year1', 3, 3, 'essential', 'Excellent one-to-one correspondence work. Can DIY with box and dowels. Teaches zero beautifully!', 'either', '$20-30 or $5 DIY', '3.5', '["Spindle Box", "45 spindles", "Rubber bands (optional)"]'::jsonb, '["One-to-one correspondence", "Concept of zero", "Counting loose objects"]'::jsonb, '["Understanding zero as empty set"]'::jsonb, 'Wrong number of spindles left over', '[]'::jsonb, '[{"level": 1, "name": "Counting Spindles", "description": "Place correct quantity in each compartment", "videoSearchTerms": ["montessori spindle box presentation"]}]'::jsonb, true),
('ma_cards_counters', 'Cards and Counters', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Numeral cards 1-10 with 55 counters', 'primary_year1', 4, 4, 'essential', 'Perfect for understanding quantity-symbol relationship and discovering odd/even. DIY very easy!', 'either', '$10-15 or $2 DIY', '3.5', '["Numeral cards 1-10", "55 counters (red discs)"]'::jsonb, '["Quantity-symbol association", "Odd and even concept", "Counting and arranging"]'::jsonb, '["Order", "Pattern recognition", "Division readiness"]'::jsonb, 'Wrong number of counters', '[]'::jsonb, '[{"level": 1, "name": "Placing Counters", "description": "Place counters in pairs under cards", "videoSearchTerms": ["montessori cards counters placing"]}, {"level": 2, "name": "Odd and Even", "description": "Discover odd/even pattern", "videoSearchTerms": ["montessori cards counters odd even"]}]'::jsonb, true),
('ma_short_bead_stair', 'Short Bead Stair', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Colored bead bars representing 1-9', 'primary_year1', 5, 5, 'essential', 'Beautiful material combining color and quantity. Prepares for addition and multiplication.', 'buy', '$40-60', '3', '["Short Bead Stair (colored bead bars 1-9)"]'::jsonb, '["Quantity visualization", "Color-number association"]'::jsonb, '["Preparation for operations", "Skip counting"]'::jsonb, 'Incorrect count', '[]'::jsonb, '[{"level": 1, "name": "Introduction", "description": "Learn bead bar colors and values", "videoSearchTerms": ["montessori short bead stair introduction"]}, {"level": 2, "name": "Building Stair", "description": "Arrange 1-9 in order", "videoSearchTerms": ["montessori short bead stair building"]}]'::jsonb, true),
('ma_golden_beads_intro', 'Introduction to Golden Beads', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Introduction to units, tens, hundreds, thousands', 'primary_year1', 6, 6, 'essential', 'Cornerstone of Montessori math! Beautiful concrete representation of decimal system. Quality investment!', 'buy', '$80-120', '3.5', '["Golden Bead Material (units, ten-bars, hundred-squares, thousand-cubes)"]'::jsonb, '["Understanding place value hierarchy", "Vocabulary: unit, ten, hundred, thousand"]'::jsonb, '["Mathematical mind", "Decimal system foundation"]'::jsonb, 'Incorrect naming', '[]'::jsonb, '[{"level": 1, "name": "Quantity Introduction", "description": "Learn unit, ten, hundred, thousand", "videoSearchTerms": ["montessori golden beads introduction"]}]'::jsonb, true),
('ma_large_numeral_cards', 'Large Numeral Cards', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Cards for units (1-9), tens (10-90), hundreds (100-900), thousands (1000-9000)', 'primary_year1', 7, 7, 'essential', 'Works with Golden Beads to show symbol-quantity relationship. Color-coded for place value.', 'buy', '$15-25', '3.5', '["Large Numeral Cards (green units, blue tens, red hundreds, green thousands)"]'::jsonb, '["Symbol recognition for large numbers", "Place value in written form"]'::jsonb, '["Reading large numbers", "Color-coding place value"]'::jsonb, 'Cards don''t stack correctly', '[]'::jsonb, '[{"level": 1, "name": "Introduction to Cards", "description": "Learn card colors and values", "videoSearchTerms": ["montessori large numeral cards introduction"]}]'::jsonb, true),
('ma_association_quantity_symbol', 'Association of Quantity and Symbol', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Connecting golden bead quantities with numeral cards', 'primary_year1', 8, 8, 'essential', 'Bridge between concrete beads and abstract numerals. Critical for understanding number.', 'buy', 'Included with Golden Beads set', '4', '["Golden Bead Material", "Large Numeral Cards"]'::jsonb, '["Symbol-quantity association for large numbers"]'::jsonb, '["Concrete to abstract transition"]'::jsonb, 'Symbol doesn''t match quantity', '[]'::jsonb, '[{"level": 1, "name": "Matching", "description": "Match quantities to symbols", "videoSearchTerms": ["montessori golden beads quantity symbol association"]}]'::jsonb, true),
('ma_exchange_game', 'Exchange Game (Change Game)', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Understanding exchange between place values', 'primary_year1', 9, 9, 'essential', 'Concrete introduction to carrying/regrouping. Essential foundation for addition/subtraction!', 'buy', 'Included with Golden Beads', '4', '["Golden Bead Material", "Dice or numeral cards"]'::jsonb, '["Understanding exchange (10 units = 1 ten, etc.)", "Carrying concept"]'::jsonb, '["Preparation for operations"]'::jsonb, 'Quantities don''t match after exchange', '[]'::jsonb, '[{"level": 1, "name": "Basic Exchange", "description": "Exchange 10 units for 1 ten", "videoSearchTerms": ["montessori exchange game basic"]}]'::jsonb, true),
('ma_teen_board_1', 'Teen Board 1 (Seguin Board A)', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Board for learning 11-19 with quantity', 'primary_year1', 10, 10, 'essential', 'Essential for understanding teen numbers. Shows 10+unit structure concretely with beads.', 'buy', '$20-30', '4', '["Teen Board 1", "Golden ten-bar", "Colored bead bars 1-9"]'::jsonb, '["Understanding teen numbers", "Vocabulary: eleven through nineteen"]'::jsonb, '["Place value understanding"]'::jsonb, 'Beads don''t match numeral', '[]'::jsonb, '[{"level": 1, "name": "Introduction", "description": "Learn names 11-19 with beads", "videoSearchTerms": ["montessori teen board 1 introduction"]}]'::jsonb, true),
('ma_hundred_board', 'Hundred Board', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Board with tiles 1-100', 'primary_year1', 11, 11, 'essential', 'Excellent for number sequence and pattern discovery. Can DIY. Great independent work!', 'either', '$20-35 or $5 DIY', '4', '["Hundred Board", "Number tiles 1-100"]'::jsonb, '["Number sequence 1-100", "Pattern recognition"]'::jsonb, '["Concentration", "Order", "Skip counting"]'::jsonb, 'Tiles don''t fit or sequence incorrect', '[]'::jsonb, '[{"level": 1, "name": "Filling the Board", "description": "Place all tiles 1-100", "videoSearchTerms": ["montessori hundred board filling"]}, {"level": 2, "name": "Skip Counting by 10s", "description": "Identify 10s column", "videoSearchTerms": ["montessori hundred board skip counting 10s"]}]'::jsonb, true),
('ma_addition_snake_game', 'Addition Snake Game', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Adding colored bead bars using the snake game', 'primary_year2', 12, 12, 'recommended', 'Concrete addition with beads. Shows combining and regrouping naturally. Leads to addition facts!', 'buy', 'Included with bead materials', '4', '["Colored bead bars", "Black and white bead stair", "Golden ten-bars", "Notched card"]'::jsonb, '["Addition practice", "Making tens"]'::jsonb, '["Addition fact memorization"]'::jsonb, 'Final count doesn''t match', '[]'::jsonb, '[{"level": 1, "name": "Basic Snake", "description": "Add bead bars making tens", "videoSearchTerms": ["montessori addition snake game"]}]'::jsonb, true),
('ma_stamp_game', 'Stamp Game', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Colored stamps representing place value for all operations', 'primary_year2', 13, 13, 'recommended', 'Bridge between concrete (beads) and abstract (pencil/paper). Shows carrying beautifully!', 'buy', '$40-60', '4.5', '["Stamp Game box with colored stamps", "Skittles for division"]'::jsonb, '["Abstract operations with symbolic materials"]'::jsonb, '["Bridge to pencil and paper"]'::jsonb, 'Result incorrect', '[]'::jsonb, '[{"level": 1, "name": "Static Addition", "description": "Add without exchanging", "videoSearchTerms": ["montessori stamp game addition static"]}, {"level": 2, "name": "Dynamic Addition", "description": "Add with exchanging", "videoSearchTerms": ["montessori stamp game addition dynamic"]}]'::jsonb, true),
('ma_fraction_circles', 'Fraction Insets (Metal or Plastic)', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Circle insets divided into fractions', 'primary_year2', 14, 14, 'recommended', 'Concrete introduction to fractions. Shows parts of whole visually and tangibly.', 'buy', '$25-40', '4.5', '["Fraction Insets (1 whole through 1/10)"]'::jsonb, '["Understanding fractions as parts of whole", "Fraction vocabulary"]'::jsonb, '["Preparation for fraction operations"]'::jsonb, 'Pieces don''t fit', '[]'::jsonb, '[{"level": 1, "name": "Introduction", "description": "Name fractions: whole, halves, thirds...", "videoSearchTerms": ["montessori fraction circles introduction"]}, {"level": 2, "name": "Equivalence", "description": "Discover equivalent fractions", "videoSearchTerms": ["montessori fraction equivalence"]}]'::jsonb, true),
('ma_clock', 'Clock Work', 'mathematics', 'Mathematics', '🔢', '#2196F3', 'Learning to tell time', 'primary_year2', 15, 15, 'recommended', 'Teaches practical skill - telling time. Great for understanding daily schedule and routines.', 'buy', '$12-20', '4.5', '["Learning clock", "Time cards"]'::jsonb, '["Telling time", "Hour and minute hands"]'::jsonb, '["Time awareness", "Skip counting by 5s"]'::jsonb, 'Time doesn''t match cards', '[]'::jsonb, '[{"level": 1, "name": "Hour Hand Only", "description": "Read hours on the clock", "videoSearchTerms": ["montessori clock hours"]}, {"level": 2, "name": "Half Hours", "description": "Read half past times", "videoSearchTerms": ["montessori clock half hours"]}]'::jsonb, true);

-- Insert LANGUAGE works (12 works)
INSERT INTO public.home_master_curriculum (id, work_name, area_key, area_name, area_icon, area_color, description, age_range, sequence, home_sequence, home_priority, home_tip, buy_or_make, estimated_cost, home_age_start, materials, direct_aims, indirect_aims, control_of_error, prerequisites, levels, is_active) VALUES
('la_sound_games', 'Sound Games (I Spy)', 'language', 'Language', '📚', '#E91E63', 'Phonemic awareness activities isolating sounds in words', 'primary_year1', 1, 1, 'essential', 'FREE and essential! No materials needed. Play I Spy during meals, car rides, walks. Critical for reading!', 'make', 'Free', '2.5', '["Objects with distinct sounds", "Sound baskets", "Elkonin boxes", "Counters/chips"]'::jsonb, '["Phonemic awareness", "Sound isolation", "Auditory discrimination", "Sound blending", "Sound segmenting"]'::jsonb, '["Preparation for reading and writing"]'::jsonb, 'Incorrect sound identification', '[]'::jsonb, '[{"level": 1, "name": "Initial Sounds - Objects", "description": "I spy something beginning with /m/", "videoSearchTerms": ["montessori I spy initial sounds"]}, {"level": 2, "name": "Sound Blending", "description": "Blend /c/-/a/-/t/ to hear ''cat'' (robot talk)", "videoSearchTerms": ["montessori sound blending", "phonemic awareness blending"]}, {"level": 3, "name": "Sound Segmenting", "description": "Break ''cat'' into /c/-/a/-/t/ using Elkonin boxes", "videoSearchTerms": ["montessori sound segmenting", "elkonin boxes"]}]'::jsonb, true),
('la_metal_insets', 'Metal Insets', 'language', 'Language', '📚', '#E91E63', 'Geometric frames for developing pencil control and lightness of touch', 'primary_year1', 2, 2, 'essential', 'Critical for writing prep! Teaches pencil grip and control through art. Beautiful Montessori material!', 'buy', '$40-60', '3', '["Metal Insets (10 shapes)", "Colored pencils", "Inset paper", "Pencil holder"]'::jsonb, '["Pencil grip", "Pencil control", "Lightness of touch", "Hand-eye coordination"]'::jsonb, '["Preparation for letter formation", "Artistic expression"]'::jsonb, 'Lines go outside shape', '[]'::jsonb, '[{"level": 1, "name": "Tracing Frame", "description": "Trace around outside of frame", "videoSearchTerms": ["montessori metal insets tracing frame"]}, {"level": 2, "name": "Filling In - Horizontal", "description": "Fill shape with horizontal lines", "videoSearchTerms": ["montessori metal insets filling horizontal"]}]'::jsonb, true),
('la_sandpaper_letters', 'Sandpaper Letters', 'language', 'Language', '📚', '#E91E63', 'Tactile letters for learning letter sounds and formation', 'primary_year1', 3, 3, 'essential', 'Easy DIY with sandpaper and cardboard! Combines letter sound with tactile formation. Critical for literacy!', 'either', '$15-25 or $3 DIY', '3', '["Sandpaper Letters (lowercase)", "Sand tray (optional)"]'::jsonb, '["Letter-sound association", "Letter formation through touch", "Phonetic sounds"]'::jsonb, '["Muscle memory for writing", "Reading preparation"]'::jsonb, 'Texture provides tactile feedback on correct path', '[]'::jsonb, '[{"level": 1, "name": "First Group (c, m, a, t)", "description": "Introduce first consonants and vowel", "videoSearchTerms": ["montessori sandpaper letters first group"]}, {"level": 2, "name": "Second Group (s, r, i, p)", "description": "Second set of letters", "videoSearchTerms": ["montessori sandpaper letters second group"]}]'::jsonb, true),
('la_moveable_alphabet', 'Moveable Alphabet', 'language', 'Language', '📚', '#E91E63', 'Wooden or plastic letters for word building', 'primary_year1', 4, 4, 'essential', 'Beautiful bridge between sounds and symbols. Child writes words phonetically BEFORE reading instruction!', 'buy', '$25-40', '3.5', '["Large Moveable Alphabet (blue consonants, red vowels)"]'::jsonb, '["Encoding words", "Spelling", "Word building"]'::jsonb, '["Reading preparation", "Phonetic analysis"]'::jsonb, 'Word doesn''t match intended word', '[]'::jsonb, '[{"level": 1, "name": "CVC Words - Objects", "description": "Build words for objects", "videoSearchTerms": ["montessori moveable alphabet CVC objects"]}, {"level": 2, "name": "CVC Words - Pictures", "description": "Build words for pictures", "videoSearchTerms": ["montessori moveable alphabet CVC pictures"]}, {"level": 3, "name": "Phonetic Words", "description": "Build 4-5 letter phonetic words", "videoSearchTerms": ["montessori moveable alphabet phonetic words"]}]'::jsonb, true),
('la_pink_series', 'Pink Series (CVC Words)', 'language', 'Language', '📚', '#E91E63', 'Complete reading series for 3-letter phonetic words', 'primary_year1', 5, 5, 'essential', 'Structured phonetic reading program. Can use free online versions or DIY with cards. Builds confident readers!', 'either', '$30-50 or Free online', '3.5', '["Pink Series materials: picture cards, word cards, phrases, sentences, booklets"]'::jsonb, '["Reading CVC words fluently", "Building reading confidence"]'::jsonb, '["Decoding skills", "Comprehension"]'::jsonb, 'Words don''t match pictures', '[]'::jsonb, '[{"level": 1, "name": "Picture-Word Matching", "description": "Match CVC words to pictures", "videoSearchTerms": ["montessori pink series picture word matching"]}, {"level": 2, "name": "Word Lists", "description": "Read lists of CVC words", "videoSearchTerms": ["montessori pink series word lists"]}, {"level": 3, "name": "Phrases", "description": "Read pink phrases", "videoSearchTerms": ["montessori pink series phrases"]}, {"level": 4, "name": "Sentences", "description": "Read pink sentences", "videoSearchTerms": ["montessori pink series sentences"]}, {"level": 5, "name": "Stories/Booklets", "description": "Read pink booklets", "videoSearchTerms": ["montessori pink series books"]}]'::jsonb, true),
('la_blue_series', 'Blue Series (Blends)', 'language', 'Language', '📚', '#E91E63', 'Reading series for words with consonant blends', 'primary_year1', 6, 6, 'essential', 'Progression from Pink Series. Introduces blends (st, fl, br, etc.). Expands reading complexity naturally!', 'either', '$30-50 or Free online', '4', '["Blue Series materials: picture cards, word cards, phrases, sentences, booklets"]'::jsonb, '["Reading words with blends", "Decoding longer words"]'::jsonb, '["Reading fluency", "Phonemic awareness"]'::jsonb, 'Words don''t decode correctly', '[]'::jsonb, '[{"level": 1, "name": "Initial Blends", "description": "Words starting with bl, cl, fl, etc.", "videoSearchTerms": ["montessori blue series initial blends"]}, {"level": 2, "name": "Final Blends", "description": "Words ending with nd, mp, etc.", "videoSearchTerms": ["montessori blue series final blends"]}]'::jsonb, true),
('la_green_series', 'Green Series (Phonograms)', 'language', 'Language', '📚', '#E91E63', 'Reading series for words with phonograms', 'primary_year2', 7, 7, 'recommended', 'Introduces phonograms (th, ch, sh, oa, etc.). Teaches irregular phonetic patterns. For fluent readers!', 'either', '$30-50 or Free online', '4.5', '["Green Series materials organized by phonogram"]'::jsonb, '["Reading words with phonograms", "Phonogram recognition in context"]'::jsonb, '["Reading fluency", "Spelling patterns"]'::jsonb, 'Words don''t decode correctly', '[]'::jsonb, '[{"level": 1, "name": "Picture-Word Matching", "description": "Match phonogram words to pictures", "videoSearchTerms": ["montessori green series matching"]}, {"level": 2, "name": "Word Lists by Phonogram", "description": "Read sorted word lists", "videoSearchTerms": ["montessori green series word lists"]}]'::jsonb, true),
('la_puzzle_words', 'Puzzle Words (Sight Words)', 'language', 'Language', '📚', '#E91E63', 'High-frequency words that don''t follow phonetic rules', 'primary_year1', 8, 8, 'essential', 'Sight words for fluency. Start with most common (the, and, a). Critical for reading speed!', 'either', '$10-20 or Free online', '3.5', '["Puzzle word cards", "Puzzle word booklets"]'::jsonb, '["Automatic recognition of common words", "Reading fluency"]'::jsonb, '["Comprehension", "Reading speed"]'::jsonb, 'Word not recognized', '[]'::jsonb, '[{"level": 1, "name": "First Set", "description": "the, a, is, to, and, etc.", "videoSearchTerms": ["montessori puzzle words first"]}, {"level": 2, "name": "Second Set", "description": "was, were, said, have, etc.", "videoSearchTerms": ["montessori puzzle words second"]}]'::jsonb, true),
('la_noun_intro', 'Introduction to the Noun', 'language', 'Language', '📚', '#E91E63', 'Understanding nouns as naming words', 'primary_year2', 9, 9, 'recommended', 'First grammar concept. Simple: nouns are naming words. Use household objects. Can DIY easily!', 'make', 'Free', '4', '["Noun lesson materials", "Black triangle symbol", "Objects and labels"]'::jsonb, '["Understanding nouns name things", "Noun identification"]'::jsonb, '["Grammar awareness", "Vocabulary"]'::jsonb, 'Incorrect classification', '[]'::jsonb, '[{"level": 1, "name": "Naming Objects", "description": "Everything has a name", "videoSearchTerms": ["montessori noun introduction"]}, {"level": 2, "name": "Common Nouns", "description": "General naming words", "videoSearchTerms": ["montessori common nouns"]}]'::jsonb, true),
('la_verb_intro', 'Introduction to the Verb', 'language', 'Language', '📚', '#E91E63', 'Understanding verbs as action words', 'primary_year2', 10, 10, 'recommended', 'Second grammar concept. Verbs show action. Use movement and real verbs. Very engaging!', 'make', 'Free', '4', '["Verb materials", "Large red circle symbol", "Action cards"]'::jsonb, '["Understanding verbs show action", "Verb identification"]'::jsonb, '["Sentence building"]'::jsonb, 'Action doesn''t match verb', '[]'::jsonb, '[{"level": 1, "name": "Action Verbs", "description": "Words that show action", "videoSearchTerms": ["montessori verb introduction action"]}, {"level": 2, "name": "Command Game", "description": "Read and perform verbs", "videoSearchTerms": ["montessori verb command game"]}]'::jsonb, true),
('la_classified_cards', 'Classified Cards (Nomenclature Cards)', 'language', 'Language', '📚', '#E91E63', 'Picture cards organized by category for vocabulary building', 'primary_year1', 11, 11, 'recommended', 'Build vocabulary through pictures. Can DIY with magazine cutouts. Great for language development!', 'either', '$15-25 or DIY free', '2.5', '["Classified card sets (animals, plants, vehicles, etc.)"]'::jsonb, '["Vocabulary in categories", "Visual discrimination"]'::jsonb, '["Reading preparation", "Classification skills"]'::jsonb, 'Incorrect classification', '[]'::jsonb, '[{"level": 1, "name": "Single Category", "description": "Name items in one category", "videoSearchTerms": ["montessori classified cards single category"]}, {"level": 2, "name": "Multiple Categories", "description": "Sort items across categories", "videoSearchTerms": ["montessori classified cards sorting"]}]'::jsonb, true),
('la_enrichment_vocabulary', 'Vocabulary Enrichment', 'language', 'Language', '📚', '#E91E63', 'Building vocabulary through conversation and objects', 'primary_year1', 12, 13, 'essential', 'Natural and daily! Talk about what you do. Name objects. Use precise language. Feeds all learning!', 'make', 'Free', '2', '["Real objects", "Pictures", "Books"]'::jsonb, '["Vocabulary expansion", "Precise language use"]'::jsonb, '["Communication skills", "Cognitive development"]'::jsonb, 'Incorrect naming', '[]'::jsonb, '[{"level": 1, "name": "Naming Objects", "description": "Learn names of classroom objects", "videoSearchTerms": ["montessori vocabulary enrichment objects"]}, {"level": 2, "name": "Descriptive Language", "description": "Use adjectives to describe", "videoSearchTerms": ["montessori descriptive vocabulary"]}]'::jsonb, true);

-- Insert CULTURAL works (10 works)
INSERT INTO public.home_master_curriculum (id, work_name, area_key, area_name, area_icon, area_color, description, age_range, sequence, home_sequence, home_priority, home_tip, buy_or_make, estimated_cost, home_age_start, materials, direct_aims, indirect_aims, control_of_error, prerequisites, levels, is_active) VALUES
('cu_globe_land_water', 'Globe - Land and Water', 'cultural', 'Cultural Studies', '🌍', '#9C27B0', 'Sandpaper globe', 'primary_year1', 1, 1, 'essential', 'Tactile introduction to Earth. Child discovers most of Earth is water through touch. Beautiful foundation!', 'buy', '$35-50', '3', '["Sandpaper Globe"]'::jsonb, '["Land/water distinction"]'::jsonb, '["Earth awareness"]'::jsonb, 'Texture difference', '[]'::jsonb, '[{"level": 1, "name": "Introduction", "description": "Feel land and water", "videoSearchTerms": ["montessori sandpaper globe"]}]'::jsonb, true),
('cu_globe_continents', 'Globe - Continents', 'cultural', 'Cultural Studies', '🌍', '#9C27B0', 'Colored continent globe', 'primary_year1', 2, 2, 'essential', 'Color-coded continents. Progression from sandpaper globe. World geography begins here!', 'buy', '$30-45', '3.5', '["Colored Globe"]'::jsonb, '["Continent names"]'::jsonb, '["World awareness"]'::jsonb, 'Colors', '[]'::jsonb, '[{"level": 1, "name": "Continent Names", "description": "Learn 7 continents", "videoSearchTerms": ["montessori colored globe"]}]'::jsonb, true),
('cu_puzzle_map_world', 'Puzzle Map - World', 'cultural', 'Cultural Studies', '🌍', '#9C27B0', 'World map with continent pieces', 'primary_year1', 3, 3, 'essential', 'Child builds world map! Teaches shapes and locations of continents. Wonderful geography foundation!', 'buy', '$40-60', '3.5', '["World Puzzle Map"]'::jsonb, '["Continent shapes"]'::jsonb, '["Map reading"]'::jsonb, 'Pieces don''t fit', '[]'::jsonb, '[{"level": 1, "name": "Building Map", "description": "Place all continents", "videoSearchTerms": ["montessori world puzzle map"]}, {"level": 2, "name": "Naming", "description": "Name continents", "videoSearchTerms": ["montessori world map naming"]}]'::jsonb, true),
('cu_land_water_forms', 'Land and Water Forms', 'cultural', 'Cultural Studies', '🌍', '#9C27B0', '3D models of landforms', 'primary_year1', 4, 4, 'essential', 'Three-dimensional landform models. Island, peninsula, cape, bay, etc. Vocabulary through modeling!', 'buy', '$50-70', '4', '["Land/Water Form trays"]'::jsonb, '["Landform vocabulary"]'::jsonb, '["Geography concepts"]'::jsonb, 'Water placement', '[]'::jsonb, '[{"level": 1, "name": "Island/Lake", "description": "First pair", "videoSearchTerms": ["montessori island lake"]}, {"level": 2, "name": "Peninsula/Gulf", "description": "Second pair", "videoSearchTerms": ["montessori peninsula gulf"]}, {"level": 3, "name": "All Forms", "description": "All pairs together", "videoSearchTerms": ["montessori land water forms"]}]'::jsonb, true),
('cu_living_nonliving', 'Living vs Non-Living', 'cultural', 'Cultural Studies', '🌍', '#9C27B0', 'Classification', 'primary_year1', 5, 5, 'essential', 'First classification. Living things grow, move, eat. Non-living don''t. Easy DIY with pictures!', 'either', '$8-12 or DIY free', '3', '["Sorting cards"]'::jsonb, '["Classification"]'::jsonb, '["Scientific thinking"]'::jsonb, 'Incorrect sorting', '[]'::jsonb, '[{"level": 1, "name": "Sorting", "description": "Sort living/non-living", "videoSearchTerms": ["montessori living non-living"]}]'::jsonb, true),
('cu_parts_plant', 'Parts of a Plant', 'cultural', 'Cultural Studies', '🌍', '#9C27B0', 'Plant anatomy', 'primary_year1', 6, 6, 'essential', 'Root, stem, leaf, flower. Start with real plant observations! Much more engaging than puzzles.', 'either', '$15-25 or DIY with drawing', '3.5', '["Plant puzzle", "Nomenclature cards"]'::jsonb, '["Plant vocabulary"]'::jsonb, '["Biology"]'::jsonb, 'Parts mislabeled', '[]'::jsonb, '[{"level": 1, "name": "Plant Puzzle", "description": "Root, stem, leaf, flower", "videoSearchTerms": ["montessori parts plant puzzle"]}, {"level": 2, "name": "Real Plants", "description": "Find parts on real plants", "videoSearchTerms": ["montessori plant observation"]}]'::jsonb, true),
('cu_plant_life_cycle', 'Plant Life Cycle', 'cultural', 'Cultural Studies', '🌍', '#9C27B0', 'Seed to plant to seed', 'primary_year1', 7, 7, 'essential', 'Grow real seeds at home! Fascinatingly simple. Child witnesses seed->sprout->plant->flower->seed!', 'make', '$5-10', '3.5', '["Life cycle cards", "Planting materials"]'::jsonb, '["Life cycle stages"]'::jsonb, '["Time concepts"]'::jsonb, 'Stages order', '[]'::jsonb, '[{"level": 1, "name": "Life Cycle Cards", "description": "Sequence stages", "videoSearchTerms": ["montessori plant life cycle"]}, {"level": 2, "name": "Growing Plants", "description": "Observe growth", "videoSearchTerms": ["montessori growing plants"]}]'::jsonb, true),
('cu_five_classes', 'Five Classes of Vertebrates', 'cultural', 'Cultural Studies', '🌍', '#9C27B0', 'Fish, amphibian, reptile, bird, mammal', 'primary_year1', 8, 8, 'recommended', 'Classify animals by characteristics. Fish have gills, birds have feathers, mammals have fur. DIY with pictures!', 'either', '$12-20 or DIY free', '4', '["Classification cards"]'::jsonb, '["Animal classification"]'::jsonb, '["Vocabulary"]'::jsonb, 'Incorrect sorting', '[]'::jsonb, '[{"level": 1, "name": "Fish", "description": "Gills, scales, fins", "videoSearchTerms": ["montessori fish classification"]}, {"level": 2, "name": "Amphibians", "description": "Moist skin, metamorphosis", "videoSearchTerms": ["montessori amphibian"]}, {"level": 3, "name": "Reptiles", "description": "Scales, cold-blooded", "videoSearchTerms": ["montessori reptile"]}, {"level": 4, "name": "Birds", "description": "Feathers, beaks", "videoSearchTerms": ["montessori bird classification"]}, {"level": 5, "name": "Mammals", "description": "Fur, milk", "videoSearchTerms": ["montessori mammal"]}]'::jsonb, true),
('cu_sink_float', 'Sink and Float', 'cultural', 'Cultural Studies', '🌍', '#9C27B0', 'Density exploration', 'primary_year1', 9, 9, 'recommended', 'Simple water experiment. Predict, test, observe. Teaches scientific thinking through play!', 'make', '$2-5', '3', '["Water basin", "Various objects"]'::jsonb, '["Density concept"]'::jsonb, '["Scientific method"]'::jsonb, 'Object sinks/floats', '[]'::jsonb, '[{"level": 1, "name": "Predict and Test", "description": "Predict then test", "videoSearchTerms": ["montessori sink float"]}]'::jsonb, true),
('cu_magnetic', 'Magnetic/Non-Magnetic', 'cultural', 'Cultural Studies', '🌍', '#9C27B0', 'Magnetism exploration', 'primary_year1', 10, 10, 'recommended', 'Explore what magnets attract. Great hands-on science! Teaches prediction and observation.', 'make', '$3-8', '3.5', '["Magnets", "Various objects"]'::jsonb, '["Magnetism concept"]'::jsonb, '["Scientific method"]'::jsonb, 'Attracts or not', '[]'::jsonb, '[{"level": 1, "name": "Predict and Test", "description": "Test with magnet", "videoSearchTerms": ["montessori magnetic"]}]'::jsonb, true);
