-- Migration 138: Per-Classroom Visual Memory for Smart Capture Self-Learning
-- Stores visual descriptions of works as seen in each classroom, enabling Sonnet
-- to learn what materials look like from teacher corrections and photo history.

-- Table: Per-classroom visual descriptions of works
-- One entry per work per classroom. Built from teacher corrections + first-photo captures.
-- Injected into Smart Capture prompt so the model "remembers" what each work looks like.
CREATE TABLE IF NOT EXISTS montree_visual_memory (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  classroom_id UUID NOT NULL,
  work_name TEXT NOT NULL,
  work_key TEXT,
  area TEXT,
  is_custom BOOLEAN DEFAULT false,
  -- Visual description: "wooden tray with colored beads sorted into compartments"
  -- Generated by Sonnet from the photo at correction time, or manually by teacher
  visual_description TEXT NOT NULL,
  -- Source tracking
  source TEXT DEFAULT 'correction', -- 'correction', 'first_capture', 'teacher_manual'
  source_media_id UUID, -- the photo this description was generated from
  photo_url TEXT, -- snapshot of the photo URL for reference
  -- Quality tracking
  description_confidence NUMERIC DEFAULT 0.8, -- how reliable is this description
  times_used INT DEFAULT 0, -- how many times injected into prompt
  times_correct INT DEFAULT 0, -- how many times the work was correctly identified after injection
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  -- One description per work per classroom (upsert-friendly)
  UNIQUE(classroom_id, work_name)
);

CREATE INDEX IF NOT EXISTS idx_visual_memory_classroom ON montree_visual_memory(classroom_id);
CREATE INDEX IF NOT EXISTS idx_visual_memory_custom ON montree_visual_memory(classroom_id, is_custom) WHERE is_custom = true;

-- RLS
ALTER TABLE montree_visual_memory ENABLE ROW LEVEL SECURITY;

-- Also add visual_description column to corrections table for reference
-- (keeps the raw description alongside the correction record)
ALTER TABLE montree_guru_corrections ADD COLUMN IF NOT EXISTS visual_description TEXT;
ALTER TABLE montree_guru_corrections ADD COLUMN IF NOT EXISTS photo_url TEXT;

-- RPC: Increment times_used for visual memory entries (called when descriptions are injected into prompt)
CREATE OR REPLACE FUNCTION increment_visual_memory_used(
  p_classroom_id UUID,
  p_work_names TEXT[]
) RETURNS VOID AS $$
BEGIN
  UPDATE montree_visual_memory
  SET times_used = times_used + 1,
      updated_at = NOW()
  WHERE classroom_id = p_classroom_id
    AND work_name = ANY(p_work_names);
END;
$$ LANGUAGE plpgsql;

-- RPC: Increment times_correct for a single visual memory entry (called on teacher confirm)
CREATE OR REPLACE FUNCTION increment_visual_memory_correct(
  p_classroom_id UUID,
  p_work_name TEXT
) RETURNS VOID AS $$
BEGIN
  UPDATE montree_visual_memory
  SET times_correct = times_correct + 1,
      updated_at = NOW()
  WHERE classroom_id = p_classroom_id
    AND work_name = p_work_name;
END;
$$ LANGUAGE plpgsql;
