-- Migration 147: Smart Learning System — Extend visual_memory for per-classroom learning
-- Adds columns needed for reference photos, rich descriptions, and CLIP re-embedding.
-- photo_url already exists from migration 138 — NOT added here.

-- Reference photo for teacher-uploaded "teach the AI" photos (distinct from source_media_id snapshot)
ALTER TABLE montree_visual_memory ADD COLUMN IF NOT EXISTS reference_photo_url TEXT;

-- Rich parent-facing description generated by Sonnet from reference photo
ALTER TABLE montree_visual_memory ADD COLUMN IF NOT EXISTS parent_description TEXT;

-- "Why it matters" explanation for parent reports
ALTER TABLE montree_visual_memory ADD COLUMN IF NOT EXISTS why_it_matters TEXT;

-- Key materials list for matching (e.g. ["wooden tray", "colored beads", "compartments"])
ALTER TABLE montree_visual_memory ADD COLUMN IF NOT EXISTS key_materials TEXT[];

-- Negative descriptions for CLIP negative embeddings (e.g. ["NOT fabric swatches", "NOT soft cloth"])
ALTER TABLE montree_visual_memory ADD COLUMN IF NOT EXISTS negative_descriptions TEXT[];

-- When per-classroom CLIP embedding was last generated from this description
ALTER TABLE montree_visual_memory ADD COLUMN IF NOT EXISTS embedding_generated_at TIMESTAMPTZ;

-- Index for finding stale embeddings (description updated after last embedding)
CREATE INDEX IF NOT EXISTS idx_visual_memory_stale_embeddings
  ON montree_visual_memory(classroom_id)
  WHERE embedding_generated_at IS NULL
     OR embedding_generated_at < updated_at;
