-- Migration 181: AI report tier flags (free / haiku / sonnet)
--
-- Defines two feature flags that control which Anthropic model powers a
-- school's weekly Teacher Report + Parent Narrative generation:
--
--   ai_tier_haiku   → claude-haiku-4-5    ("Montree Standard" — cheap tier)
--   ai_tier_sonnet  → claude-sonnet-4-6   ("Montree Premium"  — high tier)
--
-- Neither flag = free tier (no AI calls, reports endpoint returns 402).
-- Sonnet takes precedence over Haiku if somehow both are enabled.
--
-- Resolution happens per-request in lib/montree/reports/resolve-model.ts
-- and is wired into app/api/montree/reports/weekly-wrap/route.ts.
--
-- Both default OFF for safety. Whale Class is enabled on Haiku immediately.

INSERT INTO montree_feature_definitions (
  feature_key, name, description, icon, category, is_premium, default_enabled
) VALUES (
  'ai_tier_haiku',
  'AI Reports — Standard',
  'Weekly Teacher Reports + Parent Narratives generated by Claude Haiku. Fast, affordable AI tier. Target pricing: ~$4/student/month.',
  '⚡',
  'ai_tier',
  true,
  false
) ON CONFLICT (feature_key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  category = EXCLUDED.category,
  is_premium = EXCLUDED.is_premium;

INSERT INTO montree_feature_definitions (
  feature_key, name, description, icon, category, is_premium, default_enabled
) VALUES (
  'ai_tier_sonnet',
  'AI Reports — Premium',
  'Weekly Teacher Reports + Parent Narratives generated by Claude Sonnet. Richer, warmer, more detailed prose. Target pricing: ~$8/student/month.',
  '✨',
  'ai_tier',
  true,
  false
) ON CONFLICT (feature_key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  category = EXCLUDED.category,
  is_premium = EXCLUDED.is_premium;

-- Enable Haiku tier for Whale Class
DO $$
DECLARE
  whale_school_id UUID;
BEGIN
  SELECT school_id INTO whale_school_id
  FROM montree_classrooms
  WHERE id = '51e7adb6-cd18-4e03-b707-eceb0a1d2e69'
  LIMIT 1;

  IF whale_school_id IS NOT NULL THEN
    INSERT INTO montree_school_features (school_id, feature_key, enabled, enabled_by)
    VALUES (whale_school_id, 'ai_tier_haiku', true, 'migration_181')
    ON CONFLICT (school_id, feature_key) DO UPDATE SET enabled = true, enabled_by = 'migration_181';

    -- Ensure Sonnet is explicitly OFF for Whale Class so precedence resolution
    -- is crystal clear and doesn't depend on row absence.
    INSERT INTO montree_school_features (school_id, feature_key, enabled, enabled_by)
    VALUES (whale_school_id, 'ai_tier_sonnet', false, 'migration_181')
    ON CONFLICT (school_id, feature_key) DO UPDATE SET enabled = false, enabled_by = 'migration_181';
  END IF;
END $$;
