-- Migration 209 — Three-rail inbound payments architecture.
--
-- Mirrors migration 205 (outbound agent payouts) inverted onto schools.
-- See docs/handoffs/INBOUND_PAYMENTS_PLAN.md for the full architecture.
--
-- Three rails on montree_schools.payment_method:
--   stripe_subscription (default) → Stripe Checkout + Customer Portal, card-only,
--                                   auto-renewing. Shipped in Phase 4 (Session 93).
--                                   Western markets + supported Asia.
--   alipay_invoice                → Monthly Stripe invoice with Alipay + WeChat Pay
--                                   QR codes. Cron-driven (Phase B).
--                                   Mainland China + HK + Macau + Taiwan + anyone
--                                   wanting to pay in CNY without a foreign card.
--   manual_invoice                → Super-admin issues PDF invoice → school SWIFT
--                                   wires to Wallex HK → super-admin records receipt
--                                   via ⚡ Record incoming wire (Phase C).
--                                   Russia / Argentina / Iran / Lebanon / wherever.
--
-- billing_cadence supports monthly (default) or annual prepayment with discount.
-- See architectural rule #86: annual writes 12 monthly finance_tx rows at once.
--
-- manual_invoice_details JSONB shape (free-form, UI-validated):
-- {
--   "billing_contact_name": "School treasurer",
--   "billing_email_override": "treasurer@school.cn",
--   "currency_preference": "USD" | "CNY" | "EUR" | ...,
--   "payment_terms_days": 14,
--   "invoice_notes": "free text"
-- }
--
-- Idempotent — IF NOT EXISTS / DROP CONSTRAINT IF EXISTS.

BEGIN;

ALTER TABLE montree_schools
  ADD COLUMN IF NOT EXISTS payment_method TEXT NOT NULL DEFAULT 'stripe_subscription',
  ADD COLUMN IF NOT EXISTS manual_invoice_details JSONB,
  ADD COLUMN IF NOT EXISTS manual_invoice_details_updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS billing_cadence TEXT NOT NULL DEFAULT 'monthly',
  ADD COLUMN IF NOT EXISTS next_invoice_due_at TIMESTAMPTZ;

ALTER TABLE montree_schools
  DROP CONSTRAINT IF EXISTS montree_schools_payment_method_check;
ALTER TABLE montree_schools
  ADD CONSTRAINT montree_schools_payment_method_check
  CHECK (payment_method IN ('stripe_subscription', 'alipay_invoice', 'manual_invoice'));

ALTER TABLE montree_schools
  DROP CONSTRAINT IF EXISTS montree_schools_billing_cadence_check;
ALTER TABLE montree_schools
  ADD CONSTRAINT montree_schools_billing_cadence_check
  CHECK (billing_cadence IN ('monthly', 'annual'));

-- Partial index for the daily alipay-invoice cron picking up schools needing fresh invoices.
-- Cron logic: WHERE payment_method='alipay_invoice'
--                AND subscription_status IN ('active','past_due','trialing')
--                AND (next_invoice_due_at IS NULL OR next_invoice_due_at <= NOW() + INTERVAL '7 days')
CREATE INDEX IF NOT EXISTS idx_schools_alipay_active
  ON montree_schools(id, current_period_end, next_invoice_due_at)
  WHERE payment_method = 'alipay_invoice'
    AND subscription_status IN ('active', 'past_due', 'trialing');

-- Partial index for super-admin's "manual invoice schools" filter.
CREATE INDEX IF NOT EXISTS idx_schools_manual_invoice_active
  ON montree_schools(id)
  WHERE payment_method = 'manual_invoice'
    AND subscription_status IN ('active', 'past_due', 'trialing');

COMMENT ON COLUMN montree_schools.payment_method IS
  'Which rail bills this school. stripe_subscription = automated Stripe Checkout + Customer Portal. alipay_invoice = monthly Stripe invoice with Alipay/WeChat QR. manual_invoice = super-admin issues PDF invoice, school SWIFT wires, super-admin records receipt. Default stripe_subscription. Flipped only via /api/montree/super-admin/schools/[id]/payment-config (refuses silent flip from active stripe_subscription).';

COMMENT ON COLUMN montree_schools.manual_invoice_details IS
  'JSONB with school billing contact + invoice preferences for manual_invoice rail. NULL for stripe_subscription / alipay_invoice schools. Shape: { billing_contact_name, billing_email_override, currency_preference, payment_terms_days, invoice_notes }.';

COMMENT ON COLUMN montree_schools.billing_cadence IS
  'monthly (default) or annual. Annual = one upfront prepayment per year with 10% discount. Writes 12 monthly finance_tx rows at once per architectural rule #86. Common for Chinese schools whose treasurer prefers single transaction per year.';

COMMENT ON COLUMN montree_schools.next_invoice_due_at IS
  'For alipay_invoice rail: when the next Stripe invoice should be generated by cron. NULL means "generate immediately on next cron run". Bumped forward 30 days (monthly) or 365 days (annual) after each successful payment.';

COMMIT;

-- ── Verification queries ───────────────────────────────────────────────────
-- SELECT payment_method, billing_cadence, count(*) FROM montree_schools GROUP BY payment_method, billing_cadence;
-- SELECT id, name, payment_method, billing_cadence, subscription_status, current_period_end, next_invoice_due_at
--   FROM montree_schools ORDER BY created_at DESC LIMIT 20;
