-- =============================================================================
-- 267  COACH FAMILY BRAIN — seal-preserving family-pattern layer
-- Run in the MONTREE project (dmfncjjtsoxrnvcdnvjq) Supabase SQL Editor.
-- ADDITIVE + IDEMPOTENT.
-- =============================================================================
--
-- "Individual coaches → Family Brain → pattern interruption → nobody surveilled,
--  everyone held." The Family Brain sits above the individual coaches and gently
--  interrupts converging family stress patterns — WITHOUT ever reading anyone's
--  sealed conversation.
--
-- 🔒 THE SEAL — THE LOAD-BEARING INVARIANT FOR EVERY TABLE HERE
--   No table in this migration stores a single word from anyone's sealed coach
--   conversation, diary, or memory. The Family Brain only ever sees:
--     • ABSTRACTED SIGNALS  — a structured {type, intensity, domain} flag, with
--       NO free text. A child's signal is emitted ONLY with the child's consent
--       (consented = true is required for source_role 'child'); it is never
--       mined silently from the sealed room.
--     • the captain's OWN context notes (story_coach_context_notes — already
--       parent-authored, parent-owned; read elsewhere, not stored here).
--   Its OUTPUTS are:
--     • NUDGES — an abstracted tonal reframe about HOW to coach the recipient
--       (e.g. "lead with extra warmth about household load this week"). A nudge
--       NEVER names or describes another family member (enforced in app + here it
--       is just text the brain generated, not anyone's words).
--     • a parent-query OBSERVATION — pattern-level only, never attributed; stored
--       ENCRYPTED in the brain log.
--
-- ACCESS LADDER (enforced in app): child < 16 → individual coach only, NEVER the
--   Family Brain; parent → query access; 16 → read own observations; 18 → full
--   ownership transfer. birthdate (added here, nullable) drives the age gates.
--
-- WHY THIS IS SAFE
--   • New tables are RLS-enabled + FORCEd with NO policies (service-role only).
--   • Signals carry NO free text. Nudges/observations are brain-generated, not
--     anyone's words; observations are additionally encrypted at rest.
--   • birthdate defaults NULL → no behaviour change for existing rows.
-- =============================================================================

BEGIN;

-- Age ladder source (16 → read own; 18 → ownership transfer). Nullable.
ALTER TABLE story_admin_users ADD COLUMN IF NOT EXISTS birthdate date;

-- 1. SIGNALS — abstracted, consent-gated. NO conversation content. ------------
CREATE TABLE IF NOT EXISTS story_coach_family_signals (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  family_key   text NOT NULL,                          -- the family this belongs to
  source_space text NOT NULL,                          -- whose coach emitted it
  source_role  text NOT NULL DEFAULT 'adult'
               CHECK (source_role IN ('adult', 'parent', 'child')),
  signal_type  text NOT NULL,                          -- e.g. overloaded | low_mood | conflict_cycle | under_pressure | withdrawn | disconnected
  intensity    int  NOT NULL DEFAULT 1 CHECK (intensity BETWEEN 1 AND 3),
  domain       text,                                   -- optional bucket: household_load | school | sleep | mood | conflict | connection
  consented    boolean NOT NULL DEFAULT true,          -- a child signal MUST be true (enforced in app)
  created_at   timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL DEFAULT (now() + interval '14 days')
);
CREATE INDEX IF NOT EXISTS idx_family_signals_active ON story_coach_family_signals (family_key, expires_at, created_at DESC);

ALTER TABLE story_coach_family_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE story_coach_family_signals FORCE  ROW LEVEL SECURITY;

-- 2. NUDGES — abstracted tonal reframes the brain hands to a member's coach. ---
--    shift_text is generated by the Family Brain and describes HOW to coach the
--    RECIPIENT. It must never name/describe another member (enforced in app).
CREATE TABLE IF NOT EXISTS story_coach_family_nudges (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  family_key     text NOT NULL,
  target_space   text NOT NULL,                        -- whose coach receives the tonal shift
  shift_text     text NOT NULL,                        -- abstracted reframe (no other-member content)
  source_pattern text,                                 -- short label e.g. 'family_stress' (non-sensitive)
  created_at     timestamptz NOT NULL DEFAULT now(),
  expires_at     timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  consumed_at    timestamptz
);
CREATE INDEX IF NOT EXISTS idx_family_nudges_active ON story_coach_family_nudges (target_space, expires_at, created_at DESC);

ALTER TABLE story_coach_family_nudges ENABLE ROW LEVEL SECURITY;
ALTER TABLE story_coach_family_nudges FORCE  ROW LEVEL SECURITY;

-- 3. BRAIN LOG — the parent-query observations the brain produced (encrypted). -
--    This is the brain's OWN output (pattern-level, never attributed), not
--    anyone's words — but encrypted at rest anyway, like every story_* record.
CREATE TABLE IF NOT EXISTS story_coach_family_brain_log (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  family_key      text NOT NULL,
  queried_by_space text NOT NULL,
  observation_enc text NOT NULL,                        -- AES-256-GCM 'gcm:iv:tag:ct'
  cipher_version  int NOT NULL DEFAULT 1,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_family_brain_log_recent ON story_coach_family_brain_log (family_key, created_at DESC);

ALTER TABLE story_coach_family_brain_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE story_coach_family_brain_log FORCE  ROW LEVEL SECURITY;

COMMIT;

-- =============================================================================
-- DONE. Verify (optional):
--   SELECT to_regclass('story_coach_family_signals'),
--          to_regclass('story_coach_family_nudges'),
--          to_regclass('story_coach_family_brain_log');
--   SELECT column_name FROM information_schema.columns
--     WHERE table_name='story_admin_users' AND column_name='birthdate';
-- =============================================================================
