import type { WorkSignature } from './work-signatures';

export const LANGUAGE_SIGNATURES: WorkSignature[] = [
  // ===== ORAL LANGUAGE DEVELOPMENT =====
  {
    work_key: 'la_enrichment_vocabulary',
    name: 'Vocabulary Enrichment',
    area_key: 'language',
    category: 'Oral Language Development',
    visual_description: 'Real classroom OBJECTS (scissors, pencil, eraser, paper cup, wooden spoon, metal fork) arranged on a natural surface with CLEAR ISOLATION from other items. Each object is everyday, realistic, full-sized 3D items. Child\'s hands holding or touching individual object, fingers pointing, mouth slightly open mid-speech. NOT drawings or photos—these are REAL 3D objects in classroom lighting. Teacher or adult at child\'s eye level, listening engaged.',
    key_materials: ['Real classroom objects', 'Scissors and pencils', 'Cups and utensils', 'Paper items'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_classified_cards',
    name: 'Classified Cards (Nomenclature Cards)',
    area_key: 'language',
    category: 'Oral Language Development',
    visual_description: 'LAMINATED PICTURE CARDS (2x3 inches) in neat organized STACKS or ROWS by category. Each card displays ONE CLEAR COLOR ILLUSTRATION (dog, cat, bird, car, truck, shirt, pants, hat). Illustrations are REALISTIC drawings in bright saturated colors on WHITE BACKGROUND. Child\'s fingers separating or sorting cards by category. Cards are glossy, lay flat on table surface. Clear category separation visible in spatial arrangement.',
    key_materials: ['Laminated picture cards', 'Card sets by category', 'Card baskets or trays'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_object_picture_matching',
    name: 'Object to Picture Matching',
    area_key: 'language',
    category: 'Oral Language Development',
    visual_description: 'MINIATURE 3D OBJECTS (1-2 inches tall, ceramic or plastic animals, vehicles, household items) arranged in ROWS on white surface alongside their MATCHING PICTURE CARDS. Objects are REALISTIC MINIATURES—detailed tiny dog, tiny car, tiny cup. Picture cards show IDENTICAL objects as illustrations. Clear spatial PAIRING—each object placed directly next to matching card. Child\'s hand hovering or reaching to match object to card. Strong shadows showing 3D form of miniatures.',
    key_materials: ['Miniature ceramic objects', 'Matching picture cards', 'White work tray'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_sound_games',
    name: 'Sound Games (I Spy)',
    area_key: 'language',
    category: 'Oral Language Development',
    visual_description: 'BASKET or TRAY containing 12-15 SMALL OBJECTS with distinct initial sounds: muffin, apple, bear, dog, cat, fan, sun, pen, man, rat, pig. Objects are REALISTIC MINIATURES or CLEAR PHOTOGRAPHS. Child\'s INDEX FINGER pointing directly to selected object while saying the INITIAL SOUND aloud. Classroom background visible. Basket or tray at child\'s table height. Multiple attempts visible showing object displacement.',
    key_materials: ['Sound objects in basket', 'Objects for initial sounds', 'Classroom setting'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_rhyming',
    name: 'Rhyming Activities',
    area_key: 'language',
    category: 'Oral Language Development',
    visual_description: 'PICTURE CARDS or MINIATURE OBJECTS showing RHYMING PAIRS (cat-hat, dog-log, sun-bun, moon-spoon) laid flat or standing in clear PAIRS on table. Cards are 2x3 inches with BRIGHT CLEAR ILLUSTRATIONS of single rhyming objects. Child\'s hands selecting TWO MATCHING RHYME cards, holding them near mouth as if speaking them aloud. Visual shows cards in PAIRED arrangement with clear spatial separation between different rhyme sets.',
    key_materials: ['Rhyming card pairs', 'Rhyming object sets', 'Picture cards'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_storytelling',
    name: 'Storytelling and Sequencing',
    area_key: 'language',
    category: 'Oral Language Development',
    visual_description: 'SEQUENCE CARDS (4-6 cards, 3x4 inches each) showing clear STORY PROGRESSION: child waking up / eating breakfast / getting dressed / going to school. Each card shows BRIGHT CARTOON-STYLE ILLUSTRATIONS (not photographs) with one action per card. Cards laid out in LINEAR LEFT-TO-RIGHT sequence on table surface. Child\'s hand pointing to each card in order while mouth moves mid-speech. Story action is OBVIOUS and SEQUENTIAL.',
    key_materials: ['Sequence story cards', 'Story props', 'Felt board optional'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_poems_songs',
    name: 'Poems, Songs, and Fingerplays',
    area_key: 'language',
    category: 'Oral Language Development',
    visual_description: 'LARGE POSTER or CHART (visible from classroom distance) showing POEM or SONG LYRICS in BLACK TEXT (12-18pt font) with COLORFUL ILLUSTRATED BORDERS. Paper or foam board backing. Teacher or children pointing to WORDS with fingers/pointer stick while singing or reciting. CHILDREN\'S HANDS doing FINGERPLAY MOTIONS (touching forehead, clapping, arms raised, touching nose) visible simultaneously. Group of 2-5 children visible. Chart is clearly readable and prominently positioned.',
    key_materials: ['Song poster or chart', 'Poetry cards with illustrations', 'Pointer stick'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_conversation',
    name: 'Conversation and Discussion',
    area_key: 'language',
    category: 'Oral Language Development',
    visual_description: 'SMALL GROUP of 2-4 children sitting in CIRCLE FORMATION on floor or in small chairs, FACING each other at equal eye level. NO table required. Child\'s MOUTH OPEN mid-speech. HAND GESTURES visible—hands raised, pointing, moving expressively. Adult sitting at child\'s level, listening. Informal classroom setting. INTIMATE COMPOSITION—show faces and body language of engaged discussion. Eyes meeting between speakers. NOT formal presentation, NOT lecture.',
    key_materials: ['Discussion prompts', 'Conversation circle', 'Child-height seating'],
    difficulty: 'easy',
  },

  // ===== WRITING PREPARATION =====
  {
    work_key: 'la_metal_insets',
    name: 'Metal Insets',
    area_key: 'language',
    category: 'Writing Preparation',
    visual_description: 'SET of 10 GEOMETRIC METAL FRAMES (circle, square, triangle, rectangle, oval, diamond, pentagon, hexagon, star, trapezoid) in SHINY BRASS or STEEL. 14cm square boards. Each frame has MATCHING CUT-OUT PIECE. Child\'s PENCIL HELD in tripod grip, drawing COLORED PENCIL LINES tracing METAL FRAME EDGES on WHITE PAPER below. On completed paper: CLEAN GEOMETRIC SHAPE OUTLINES with FILL PATTERNS (horizontal lines, vertical lines, diagonal crossing lines). Metal frame is CLEARLY REFLECTIVE. Child\'s posture shows FOCUSED CONCENTRATION on pencil control.',
    key_materials: ['Metal inset frames', 'Matching inset pieces', 'Colored pencils', 'White inset paper'],
    confusion_pairs: ['sensorial_geometric_cabinet'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_sandpaper_letters',
    name: 'Sandpaper Letters',
    area_key: 'language',
    category: 'Writing Preparation',
    visual_description: 'INDIVIDUAL LETTER mounted on WOODEN or CARDBOARD BASE (6x8 inches). LETTER SHAPE is ROUGH TEXTURED SANDPAPER (coarse grain visible, NOT smooth painted letter). PINK or RED BASE for CONSONANTS, BLUE BASE for VOWELS. Child\'s INDEX AND MIDDLE FINGERS TRACING SANDPAPER LETTER OUTLINE, clearly FEELING the TEXTURE. Close-up shows FINGER TIPS on ROUGH SANDPAPER SURFACE with TACTILE PRESSURE. Lowercase CURSIVE letters (c, m, a, t, s, r). CONTRAST between smooth painted base and rough textured letter visible. Child\'s face often close to letter, eyes sometimes closed.',
    key_materials: ['Sandpaper letters lowercase', 'Pink/red consonant bases', 'Blue vowel bases'],
    confusion_pairs: ['math_sandpaper_numerals'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_sand_tray',
    name: 'Sand Tray Writing',
    area_key: 'language',
    category: 'Writing Preparation',
    visual_description: 'WOODEN TRAY (12x18 inches) FILLED with SMOOTH FINE COLORED SAND (blue, tan, or white sand, 2-3 inches deep). Child\'s FINGER or SMALL STICK DRAGGING through sand to FORM LARGE LETTERS. CLEAR DARK TRACKS visible in sand showing LETTER SHAPE. Close-up shows FINGER-WIDTH GROOVES in sand. Multiple LETTER ATTEMPTS visible in same tray (some complete, some partially erased). Smooth sand surface without water. TACTILE impression visible showing depression depth.',
    key_materials: ['Wooden sand tray', 'Smooth colored sand', 'Sand tray tools'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_chalkboard_writing',
    name: 'Chalkboard Writing',
    area_key: 'language',
    category: 'Writing Preparation',
    visual_description: 'WOODEN or SLATE CHALKBOARD (2x3 feet) MOUNTED at CHILD\'S SHOULDER HEIGHT on wall or easel. CHILD\'S ARM FULLY EXTENDED, drawing LARGE WHITE or COLORED CHALK lines (8+ inches tall per letter). CHALK MARKS show BRIGHT WHITE LINES on BLACK SURFACE. Whole-arm motion visible from shoulder—NOT just finger movement. Large motor movement is OBVIOUS. CHALK DUST visible. Chalkboard ERASER hanging to side. Vertical surface position shown. Letters are LARGE and VISIBLE across classroom distance.',
    key_materials: ['Wooden or slate chalkboard', 'Colored chalk', 'Chalkboard eraser'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_moveable_alphabet',
    name: 'Moveable Alphabet',
    area_key: 'language',
    category: 'Writing Preparation',
    visual_description: 'LARGE WOODEN BOX with 26 COMPARTMENTS containing CUT-OUT PLASTIC or WOODEN LETTERS. BLUE CONSONANTS, RED VOWELS. Letters are 2 inches tall, lowercase cursive. Child pulling individual letters from compartments and ARRANGING them on flat surface to SPELL WORDS: C-A-T, D-O-G, R-U-N. CLEAR COLOR CONTRAST visible between BLUE consonants and RED vowels laid left-to-right on mat. Letters are PHYSICAL MANIPULABLE PIECES, not handwritten. Proper LETTER SPACING visible. Multiple words visible showing letter arrangement.',
    key_materials: ['Large moveable alphabet box', 'Blue consonant letters', 'Red vowel letters'],
    confusion_pairs: ['language_sandpaper_letters'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_handwriting_paper',
    name: 'Handwriting on Paper',
    area_key: 'language',
    category: 'Writing Preparation',
    visual_description: 'LINED HANDWRITING PAPER with 4 LINES: top solid, middle DASHED, bottom solid, BASELINE. Child\'s HANDWRITTEN lowercase LETTERS sitting on baseline between bottom and middle dashed line. PENCIL HELD in TRIPOD GRIP (thumb and two fingers). Letters are SMALL, properly-sized for primary handwriting (0.5-0.75 inches tall). PROPER SPACING between letters and words visible. Pencil is SHARP, standard #2. Paper shows multiple letters or simple CVC words. NO CRAYON or MARKER—standard pencil only.',
    key_materials: ['Lined handwriting paper', 'Standard #2 pencils', 'Letter formation guides'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_creative_writing',
    name: 'Creative Writing',
    area_key: 'language',
    category: 'Writing Preparation',
    visual_description: 'BLANK WRITING JOURNAL or PAGE showing child\'s HANDWRITTEN ORIGINAL COMPOSITION (not copying from a model). PENCIL-WRITTEN TEXT in child\'s natural handwriting. Sentences are SELF-COMPOSED, showing child\'s OWN IDEAS. Lines show LEGIBLE SPELLING with CONSISTENT SPACING. Paper shows CHILD-AUTHORED WORDS—NOT dictation or tracing. May include TEACHER\'S LIGHT PENCIL MARKS for gentle correction. Writing shows ORIGINAL THOUGHT, not repeated text.',
    key_materials: ['Writing journals', 'Blank paper', 'Pencils', 'Writing prompts'],
    difficulty: 'medium',
  },

  // ===== READING =====
  {
    work_key: 'la_pink_object_box',
    name: 'Pink Object Box',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'WOODEN BOX containing 20-30 MINIATURE OBJECTS (cat, dog, fan, bat, mop, pot, bed, pan, rat, pig, sun, hat, mat, pin, pen). Alongside each object: SMALL LABEL CARD with CVC WORD in LOWERCASE (c-a-t, d-o-g, f-a-n, b-a-t). Objects are REALISTIC MINIATURES (ceramic or plastic). Labels are CLEAN BLACK TEXT on WHITE CARD STOCK. Child picking object, reading label card aloud, confirming match. Objects arranged in NEAT ROWS with labels visible. PINK theme on box. NOT picture cards—these are PHYSICAL 3D OBJECTS.',
    key_materials: ['Pink object box', 'Miniature objects', 'CVC word label cards'],
    confusion_pairs: ['language_blue_object_box', 'language_green_object_box'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_pink_series',
    name: 'Pink Series (CVC Words)',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'PINK-SPINED READING BOOKS or CARD DECKS containing CVC (consonant-vowel-consonant) words: cat, dog, bat, mat, pig, sit, hop, run. Materials include PICTURE-WORD CARDS, WORD-ONLY CARDS, PHRASE CARDS (\'the cat\'), SENTENCE CARDS (\'The cat sat.\'), SMALL ILLUSTRATED BOOKLETS. PINK BINDING or COVER visible. Child READING TEXT aloud while FINGER FOLLOWS along line. Simple COLOR ILLUSTRATIONS of CVC objects. Text in LOWERCASE, clearly printed. Each page shows one CVC word or phrase.',
    key_materials: ['Pink series picture cards', 'Pink series word cards', 'Pink series phrases and sentences', 'Pink booklets'],
    confusion_pairs: ['language_blue_series', 'language_green_series'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_blue_object_box',
    name: 'Blue Object Box',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'WOODEN BOX containing 20-30 MINIATURE OBJECTS matching CONSONANT BLEND words (clock, block, flag, plant, star, step, stop, spider, snail, skate, slip, snap). Alongside each: LABEL CARD with BLEND WORD in LOWERCASE (c-l-o-c-k, f-l-a-g, s-t-a-r, s-p-i-d-e-r). Objects are REALISTIC MINIATURES. Labels show BLEND PATTERNS clearly visible (CL, BL, FL, ST, SN, SP). BLUE-THEMED BOX and materials. Child reading blend labels. Objects and cards organized and legible.',
    key_materials: ['Blue object box', 'Miniature blend objects', 'Blend word label cards'],
    confusion_pairs: ['language_pink_object_box', 'language_green_object_box'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_blue_series',
    name: 'Blue Series (Blends)',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'BLUE-SPINED READING BOOKS or CARD DECKS featuring words with CONSONANT BLENDS: black, block, flag, plant, star, stop, spider, sleep, green, smile, snow, fly. Materials include PICTURE-WORD CARDS, WORD-ONLY CARDS, PHRASE CARDS, SENTENCE CARDS, SMALL ILLUSTRATED BOOKLETS. BLUE BINDING or COVER visible. Child READING BLEND WORDS aloud. BLEND CONSONANT CLUSTERS (bl, cl, fl, st, sn, sp) shown prominently. Simple illustrations. Text in LOWERCASE. Each page shows blend words or short phrases.',
    key_materials: ['Blue series picture cards', 'Blue series word cards', 'Blue series phrases and sentences', 'Blue booklets'],
    confusion_pairs: ['language_pink_series', 'language_green_series'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_phonogram_intro',
    name: 'Phonogram Introduction',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'SANDPAPER PHONOGRAMS or CARDBOARD CARDS showing TWO-LETTER COMBINATIONS that make ONE NEW SOUND (ee, oo, sh, ch, th, wh, ai, ay, ea, oa, ar, er, ou, ow, oi, oy, aw). Each phonogram is 2-3 inches tall. May have TEXTURED letters (sandpaper) or PLAIN printing on GREEN CARDS. Child\'s FINGER TRACING phonogram and SAYING the SOUND aloud. Multiple phonograms visible on tray. DOUBLE-LETTER FORMAT—these are COMBINATION SOUNDS, not single letters.',
    key_materials: ['Sandpaper phonograms', 'Phonogram cards on green', 'Phonogram trays'],
    confusion_pairs: ['language_sandpaper_letters'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_green_object_box',
    name: 'Green Object Box',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'WOODEN BOX containing 20-30 MINIATURE OBJECTS matching PHONOGRAM WORDS (sheep, tree, moon, rain, boat, star, spoon, book, shell, chain, fish, queen, foot, mouse, owl, boy, tail, key). Alongside each: LABEL CARD with PHONOGRAM WORD in LOWERCASE (sh-ee-p, tr-ee, m-oo-n, r-ai-n, b-oa-t). Objects are REALISTIC MINIATURES. GREEN-THEMED BOX and materials. Labels show PHONOGRAM COMBINATIONS clearly. Child reading phonogram labels with complex letter patterns.',
    key_materials: ['Green object box', 'Miniature phonogram objects', 'Phonogram word label cards'],
    confusion_pairs: ['language_pink_object_box', 'language_blue_object_box'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_green_series',
    name: 'Green Series (Phonograms)',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'GREEN-SPINED READING BOOKS or CARD DECKS featuring words with PHONOGRAMS: sheep, tree, boat, rain, moon, shell, chain, fish, spoon, book, queen, owl, tail, snow, fly. Materials include PICTURE-WORD CARDS, WORD-ONLY CARDS, PHRASE CARDS, SENTENCE CARDS, SMALL ILLUSTRATED BOOKLETS. GREEN BINDING or COVER visible. PHONOGRAM LETTER COMBINATIONS (sh, ee, oa, ai) often HIGHLIGHTED or COLOR-CODED. Child reading complex phonogram words. Advanced phonetic reading level.',
    key_materials: ['Green series picture cards', 'Green series word cards', 'Green series phrases and sentences', 'Green booklets'],
    confusion_pairs: ['language_pink_series', 'language_blue_series'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_puzzle_words',
    name: 'Puzzle Words (Sight Words)',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'CARDS or BOOKLETS featuring NON-PHONETIC high-frequency words: the, a, is, to, and, was, were, said, have, do, does, water. Words PRINTED on CARD STOCK in LOWERCASE. Words do NOT follow phonetic DECODING rules—must be MEMORIZED visually. Materials may include PUZZLE-CUT shapes (word pieces INTERLOCK physically, hence \'puzzle\' words). Child READING SIGHT WORDS from cards. Irregular spelling patterns visible. NOT decodable phonetically.',
    key_materials: ['Puzzle word cards', 'Puzzle word booklets', 'Puzzle-cut materials'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_reading_analysis',
    name: 'Reading Analysis',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'Child READING a COMPLEX WORD and ANALYZING which PHONOGRAMS are present using PHONOGRAM CHART on wall showing all learned phonograms. Child\'s FINGER POINTING to chart while identifying PHONOGRAM COMPONENTS in words on card. Analysis shows DECOMPOSITION—BREAKING WORDS into phonogram PATTERNS. Paper or chart showing COLOR-CODED or HIGHLIGHTED phonogram identification. NOT simple reading—this is ANALYTICAL reading with EXPLICIT phonogram IDENTIFICATION and BREAKDOWN.',
    key_materials: ['Reading analysis materials', 'Phonogram charts', 'Colored word cards'],
    difficulty: 'hard',
  },
  {
    work_key: 'la_reading_classification',
    name: 'Reading Classification',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'WORD CARDS to be CLASSIFIED by CATEGORY while READING. Cards labeled \'ANIMALS\', \'FOOD\', \'CLOTHING\', and child SORTS WORD CARDS into CORRECT CATEGORIES by reading and understanding MEANING. SORTED WORD CARDS in NEAT PILES by category on table. CATEGORY LABELS visible. Multiple categories visible with clear spatial separation. READING COMPREHENSION shown through accurate CLASSIFICATION—understanding word meaning AND category membership.',
    key_materials: ['Classification reading cards', 'Category label cards', 'Word sorting materials'],
    difficulty: 'hard',
  },
  {
    work_key: 'la_command_cards',
    name: 'Command Cards (Action Reading)',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'COMMAND CARDS showing IMPERATIVE SENTENCES (3x5 inch cards) with text: \'Stand up\', \'Hop on one foot\', \'Touch your nose\', \'Clap your hands three times\', \'Walk to the door\'. Text PRINTED in LOWERCASE on WHITE CARD STOCK. Child HOLDING CARD, READING command, IMMEDIATELY PERFORMING the action. Visual shows child MID-ACTION after reading: jumping, hopping, clapping, walking, touching. Card visible in child\'s hand. Child\'s body position showing action execution.',
    key_materials: ['Command cards', 'Action reading cards', 'Simple command cards'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_interpretive_reading',
    name: 'Interpretive Reading',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'Child READING ALOUD from POETRY BOOK or SHORT STORY with EXPRESSION and EMOTION. Reader\'s FACIAL EXPRESSION and VOICE INFLECTION changing with TEXT MEANING. HAND GESTURES matching text mood and actions. Child\'s mouth clearly moving with varied intonation. Open book visible. May show child reading to small audience. EXPRESSIVE BODY LANGUAGE visible. NOT monotone reading—this is EMOTIONAL INTERPRETIVE reading showing comprehension through VOCAL and PHYSICAL expression.',
    key_materials: ['Poetry books', 'Short story collections', 'Drama scripts'],
    difficulty: 'hard',
  },
  {
    work_key: 'la_silent_reading',
    name: 'Silent Reading',
    area_key: 'language',
    category: 'Reading',
    visual_description: 'Child SITTING AT TABLE or in READING CORNER with OPEN CHAPTER BOOK or LEVELED READER. Child\'s EYES SCANNING PAGES silently (NO VOICE), HAND occasionally turning page. QUIET CLASSROOM environment. Child ALONE with book—not being taught, not answering questions, just READING INDEPENDENTLY. INDEPENDENT READING posture shown (sitting upright, focused eyes on page). NOT guided reading, NOT read-aloud, NOT interpretive performance.',
    key_materials: ['Leveled books', 'Chapter books', 'Reading corner'],
    difficulty: 'hard',
  },

  // ===== GRAMMAR =====
  {
    work_key: 'la_noun_intro',
    name: 'Introduction to the Noun',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'Teacher or child HOLDING REAL OBJECTS (pencil, book, desk, chair) with BLACK TRIANGLE SYMBOL placed ABOVE each object. BLACK SOLID EQUILATERAL TRIANGLE (Montessori grammar symbol) clearly visible. Child SORTING CARDS into NOUN and NON-NOUN CATEGORIES. WORD CARDS with BLACK TRIANGLES placed above NOUN words. Multiple objects or cards visible showing NOUN IDENTIFICATION. NOT verb circles, NOT adjective triangles—specifically BLACK TRIANGLE for NOUNS.',
    key_materials: ['Noun lesson materials', 'Black triangle symbol', 'Real classroom objects'],
    confusion_pairs: ['language_grammar_boxes'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_article_intro',
    name: 'Introduction to the Article',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'ARTICLES (a, an, the) shown on LIGHT BLUE SMALL TRIANGLE SYMBOL (distinct from NOUN\'s larger BLACK triangle). Child POINTING to object while SAYING ARTICLE + NOUN: \'a book\', \'an apple\', \'the chair\'. WORD CARDS with LIGHT BLUE triangles placed above ARTICLE words. Simple sentence structure: ARTICLE + NOUN visible. NOT noun triangle (black, larger). NOT adjective (dark blue, medium). LIGHT BLUE SMALL TRIANGLE = ARTICLE.',
    key_materials: ['Article lesson materials', 'Light blue triangle symbol', 'Article word cards'],
    confusion_pairs: ['language_noun_intro', 'language_adjective_intro'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_adjective_intro',
    name: 'Introduction to the Adjective',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'Child playing \'DETECTIVE GAME\': \'Which one? The BLUE pencil! The BIG book!\' ADJECTIVES shown on MEDIUM DARK BLUE TRIANGLE SYMBOL (size between article and noun). Multiple SIMILAR OBJECTS in different COLORS or SIZES (red/blue/yellow pencils; big/small books) and child CHOOSING based on ADJECTIVE described. WORD CARDS with DARK BLUE triangles. Phrase: \'THE [ADJECTIVE] [NOUN]\' visible. NOT noun (black), NOT article (light blue small). DARK BLUE MEDIUM TRIANGLE = ADJECTIVE.',
    key_materials: ['Adjective lesson materials', 'Medium dark blue triangle', 'Adjective game objects'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_verb_intro',
    name: 'Introduction to the Verb',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'Child READING COMMAND CARD and PERFORMING ACTION: RUNNING, HOPPING, SITTING, CLAPPING, JUMPING. VERBS shown on LARGE RED CIRCLE SYMBOL (Montessori verb symbol = action). Child\'s BODY IN MOTION performing action. ACTION CARD visible with RED CIRCLE above VERB word. Multiple action examples shown. Classroom space visible for movement. LARGE RED CIRCLE = VERB symbol. NOT triangle (nouns/adjectives). NOT small orange (adverbs).',
    key_materials: ['Verb lesson materials', 'Large red circle symbol', 'Action command cards'],
    confusion_pairs: ['language_command_cards'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_adverb_intro',
    name: 'Introduction to the Adverb',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'Child DEMONSTRATING ADVERB modifying VERB: \'Walk SLOWLY\' (exaggerated slow steps), \'Walk QUICKLY\' (fast steps), \'Walk HAPPILY\' (bouncy steps with smile). ADVERBS shown on SMALL ORANGE CIRCLE SYMBOL. Child performing SAME ACTION (walking) in different ADVERB WAYS. BODY LANGUAGE and EXPRESSION changing with ADVERB. SMALL ORANGE CIRCLE = ADVERB. NOT large red circle (verb). NOT triangle symbols.',
    key_materials: ['Adverb lesson materials', 'Small orange circle symbol', 'Adverb game activities'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_pronoun_intro',
    name: 'Introduction to the Pronoun',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'Child SAYING: \'Maria has a pencil. SHE has a pencil.\' PRONOUNS shown on PURPLE or VIOLET TRIANGLE SYMBOL (similar shape to NOUN but purple). Child POINTING to self saying \'I\', to friend saying \'You\', to child across room saying \'He/She\'. WORD CARDS with PURPLE triangles. PRONOUNS REPLACE NOUNS while meaning stays same. PURPLE TRIANGLE = PRONOUN. NOT black triangle (noun). NOT other colored triangles.',
    key_materials: ['Pronoun lesson materials', 'Purple/violet triangle symbol', 'Pronoun word cards'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_preposition_intro',
    name: 'Introduction to the Preposition',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'Child DEMONSTRATING POSITION words with REAL OBJECTS: pencil \'in the box\', \'on the table\', \'under the chair\', \'behind the door\'. PREPOSITIONS shown on GREEN CRESCENT or BRIDGE SYMBOL. Child\'s HAND and OBJECT showing SPATIAL RELATIONSHIP. Multiple position examples visible. GREEN CRESCENT = PREPOSITION. NOT circle (verb/adverb). NOT triangle (noun/adjective/article).',
    key_materials: ['Preposition lesson materials', 'Green crescent symbol', 'Preposition game objects'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_conjunction_intro',
    name: 'Introduction to the Conjunction',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'TWO SENTENCE CARDS JOINED with CONJUNCTION CARD in middle: \'The cat is black AND the dog is brown.\' CONJUNCTIONS shown on PINK RECTANGLE SYMBOL. COMPLETE COMPOUND SENTENCE written out showing AND/BUT/OR HIGHLIGHTED. Conjunction CONNECTS two independent IDEAS. PINK RECTANGLE = CONJUNCTION. NOT other grammar symbols. SENTENCE BUILDING with physical cards showing conjunction JOINING two sentence halves.',
    key_materials: ['Conjunction lesson materials', 'Pink rectangle symbol', 'Conjunction sentence cards'],
    difficulty: 'hard',
  },
  {
    work_key: 'la_interjection_intro',
    name: 'Introduction to the Interjection',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'Child EXCLAIMING: \'Oh! I found my pencil!\' \'Wow! That\'s amazing!\' \'Ouch! That hurt!\' INTERJECTIONS shown on GOLD or YELLOW KEYHOLE SYMBOL. Child\'s FACE showing STRONG EMOTION (surprise, joy, pain, excitement) while SAYING interjection. EXCLAMATION MARK visible. GOLD KEYHOLE = INTERJECTION (unique shape, stands alone). NOT other grammar symbols.',
    key_materials: ['Interjection lesson materials', 'Gold keyhole symbol', 'Interjection word cards'],
    difficulty: 'hard',
  },
  {
    work_key: 'la_grammar_boxes',
    name: 'Grammar Boxes',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'SET of 8 WOODEN BOXES (Grammar Boxes I-VIII), each containing SENTENCE CARDS with ONE WORD MISSING. Child FILLS IN missing word from provided WORD CARDS. Box I (articles): \'The ___ is red.\' Child SELECTS correct article. SENTENCES MAKE SENSE only when CORRECT part of speech INSERTED. WOODEN BOXES with removable lids, CARD STOCK sentence strips and WORD CARDS inside. Child reading sentence and SELECTING correct word. NOT single grammar symbol introduction—this is ANALYTICAL sentence WORK with MULTIPLE BOXES.',
    key_materials: ['Grammar Boxes I-VIII', 'Filling boxes', 'Sentence cards', 'Word cards'],
    confusion_pairs: ['language_sentence_analysis'],
    difficulty: 'hard',
  },
  {
    work_key: 'la_sentence_analysis',
    name: 'Sentence Analysis',
    area_key: 'language',
    category: 'Grammar',
    visual_description: 'Child READING a SENTENCE and ANALYZING its STRUCTURE using QUESTION ARROWS: \'WHO is doing it? (subject)\' \'WHAT is it doing? (predicate)\' \'WHAT is receiving the action? (object)\'. SENTENCE written on card with COLORED ARROWS pointing to SENTENCE PARTS. CHART or PAPER showing COLOR-CODED grammatical functions. NOT grammar boxes (those fill words). NOT part-of-speech symbols. This is DEEP STRUCTURAL ANALYSIS with ARROWS and QUESTIONS.',
    key_materials: ['Sentence analysis charts', 'Question arrows', 'Sentence strips with analysis'],
    difficulty: 'hard',
  },

  // ===== WORD STUDY =====
  {
    work_key: 'la_word_families',
    name: 'Word Families',
    area_key: 'language',
    category: 'Word Study',
    visual_description: 'WORD FAMILY CLUSTERS on CARDS or CHART: AT FAMILY (cat, bat, hat, sat, mat, fat, rat), AN FAMILY (can, fan, pan, ran, man, tan), IG FAMILY (big, dig, fig, jig, pig, rig, wig). Each word on SMALL CARD or CHART FORMAT. Child ARRANGING RHYMING WORDS by FAMILY. Multiple WORD CARDS GROUPED IN FAMILY STACKS or CHART with FAMILY NAMES (AT, AN, AP) listed with words GROUPED UNDER each. Words SHARING ENDING SOUND and SPELLING PATTERN grouped together. NOT rhyming activities (those use objects). NOT phonogram work.',
    key_materials: ['Word family cards', 'Word family charts', 'Family name labels'],
    difficulty: 'easy',
  },
  {
    work_key: 'la_spelling_rules',
    name: 'Spelling Rules',
    area_key: 'language',
    category: 'Word Study',
    visual_description: 'CHART or CARDS showing SPELLING RULES with EXAMPLES: DOUBLING RULE (\'hop\' + \'ing\' = \'hopping\'), SILENT E RULE (\'made\' drops e = \'making\'), Y TO I RULE (\'happy\' = \'happier\'). COLOR-CODED CHART listing RULES and EXAMPLES, or CARD PAIRS showing BEFORE and AFTER spelling. Child READING RULE and APPLYING it to NEW WORDS. PATTERN RECOGNITION—consistent spelling rule PATTERNS visible. NOT word families. NOT phonograms.',
    key_materials: ['Spelling rule charts', 'Word sorting materials', 'Rule example cards'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_compound_words',
    name: 'Compound Words',
    area_key: 'language',
    category: 'Word Study',
    visual_description: 'CARDS showing COMPOUND WORD PARTS that COMBINE: sun + flower = sunflower, rain + bow = rainbow, butter + fly = butterfly, tooth + brush = toothbrush. TWO WORD CARDS JOINED BY PLUS SIGN, then FINAL COMPOUND WORD displayed. PICTURE-WORD CARDS matching COMPOUND to IMAGE. Child MATCHING TWO WORD PARTS to CREATE REAL COMPOUND WORD. COMPOSITION—two SMALLER WORDS CREATE one LARGER WORD. NOT prefixes/suffixes (those modify, not combine equal parts).',
    key_materials: ['Compound word cards', 'Compound word matching materials', 'Picture cards'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_prefixes_suffixes',
    name: 'Prefixes and Suffixes',
    area_key: 'language',
    category: 'Word Study',
    visual_description: 'CARDS showing WORD PARTS: PREFIXES (un-, re-, pre-, dis-, in-) and SUFFIXES (-ed, -ing, -er, -est, -ly, -tion). ROOT WORD with PREFIX and SUFFIX CARDS sliding BEFORE and AFTER: \'un\' + \'happy\' = \'unhappy\', \'play\' + \'ing\' = \'playing\'. POSSIBLY COLOR-CODED (prefixes one color, roots another, suffixes third). Child BUILDING NEW WORDS by ADDING PARTS. MORPHOLOGY—adding WORD PARTS CHANGES meaning. NOT compound words (those combine equal words).',
    key_materials: ['Prefix/suffix cards', 'Root word cards', 'Word building materials'],
    difficulty: 'hard',
  },
  {
    work_key: 'la_synonyms_antonyms',
    name: 'Synonyms and Antonyms',
    area_key: 'language',
    category: 'Word Study',
    visual_description: 'CARD PAIRS showing SAME MEANING (synonyms: big/large, happy/joyful) or OPPOSITE MEANING (antonyms: hot/cold, fast/slow, happy/sad). TWO WORD CARDS placed NEXT TO each other (synonyms) or on OPPOSITE SIDES (antonyms). CHART with \'SAME\' and \'OPPOSITE\' columns. Child MATCHING WORD PAIRS by SEMANTIC RELATIONSHIP. NOT homonyms (those sound the same). NOT word families (those share spelling patterns).',
    key_materials: ['Synonym/antonym cards', 'Semantic relationship matching games', 'Comparison charts'],
    difficulty: 'medium',
  },
  {
    work_key: 'la_homonyms',
    name: 'Homonyms',
    area_key: 'language',
    category: 'Word Study',
    visual_description: 'CARDS or PICTURES showing words that SOUND SAME but MEAN DIFFERENT THINGS: to/two/too, their/there/they\'re, here/hear, see/sea, sun/son, knight/night. PICTURE CARDS showing MEANING DIFFERENCES (beach ocean = \'sea\' vs letter C = \'see\'). Child MATCHING homophones to DIFFERENT MEANINGS. ONE SOUND, MULTIPLE MEANINGS shown with ILLUSTRATIONS. NOT synonyms/antonyms (those have different sounds). NOT word families.',
    key_materials: ['Homonym cards with pictures', 'Homophone matching materials', 'Picture meaning cards'],
    difficulty: 'medium',
  },
];
