import type { WorkSignature } from './work-signatures';

export const PRACTICAL_LIFE_SIGNATURES: WorkSignature[] = [
  // --- Preliminary Exercises ---
  {
    work_key: "pl_carrying_mat",
    name: "Carrying a Mat",
    area_key: "practical_life",
    category: "Preliminary Exercises",
    visual_description: "SOFT WOVEN FABRIC work mat (typically tan/beige canvas roll, ~18x24 inches) being held horizontally with BOTH HANDS at corners. Child carries it without dragging edge on floor. NOT a basket. NOT a tray. Small rolled fabric, rectangular shape.",
    key_materials: ["Woven work mat"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_carrying_chair",
    name: "Carrying a Chair",
    area_key: "practical_life",
    category: "Preliminary Exercises",
    visual_description: "WOODEN CHILD-SIZED CHAIR (small, ~12-14 inches tall, typically stained wood or painted) being lifted and carried with BOTH HANDS gripping the backrest and seat. Chair moves silently without hitting objects. NOT a table. NOT an adult chair.",
    key_materials: ["Child-sized wooden chair"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_carrying_tray",
    name: "Carrying a Tray",
    area_key: "practical_life",
    category: "Preliminary Exercises",
    visual_description: "FLAT WOODEN OR PLASTIC TRAY (typically 12x18 inches, wooden edges, handles on sides) being held level with both hands. May contain lightweight objects (shells, pompoms). Child carries without objects sliding or falling. NOT a basket. NOT a table. Shallow rectangular container.",
    key_materials: ["Small wooden/plastic tray", "Various lightweight objects"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_carrying_table",
    name: "Carrying a Table",
    area_key: "practical_life",
    category: "Preliminary Exercises",
    visual_description: "TWO CHILDREN TOGETHER lifting and carrying a SMALL WOODEN TABLE (child-sized, ~2 feet x 1.5 feet, lightweight wood). One child on each long side, table held level, moves silently. Demonstrates COOPERATION. NOT done by one child. NOT solo activity.",
    key_materials: ["Child-sized wooden table"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_opening_closing_door",
    name: "Opening and Closing a Door",
    area_key: "practical_life",
    category: "Preliminary Exercises",
    visual_description: "CLASSROOM WOODEN DOOR with visible HANDLE/DOORKNOB. Child opens door by gripping handle, pulling smoothly WITHOUT SLAMMING, closes door silently by controlling swing. NOT forceful. NOT banging. Real classroom infrastructure.",
    key_materials: ["Classroom door"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_walking_line",
    name: "Walking on the Line",
    area_key: "practical_life",
    category: "Preliminary Exercises",
    visual_description: "BLACK OR RED TAPE/PAINTED LINE on floor (~15-20 feet long loop, 3-4 inches wide). Child walks HEEL-TO-TOE along line with ARMS OUTSTRETCHED for balance OR holding various objects (bell, flag, water glass, basket). Control of movement, perfect balance. NOT running. NOT stepping off line.",
    key_materials: ["Tape or painted line", "Various challenge objects"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_sitting_standing",
    name: "Sitting and Standing at a Table",
    area_key: "practical_life",
    category: "Preliminary Exercises",
    visual_description: "WOODEN CHILD-SIZED CHAIR at WOODEN TABLE. Child pulls out chair silently (no scraping), sits down carefully, maintains posture, then stands by pushing in chair quietly. Grace and courtesy. NOT slamming. NOT dragging furniture.",
    key_materials: ["Child-sized chair and table"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_silence_game",
    name: "The Silence Game",
    area_key: "practical_life",
    category: "Preliminary Exercises",
    visual_description: "GROUP OF CHILDREN sitting COMPLETELY STILL AND SILENT in classroom, often on floor or at tables. Not moving, not making any sound. Sometimes adult rings BELL or whispers child's name to signal. Inner peace. NOT playing noisily. NOT fidgeting.",
    key_materials: ["Silence board/sign (optional)", "Bell (optional)"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_turning_pages",
    name: "Turning Pages of a Book",
    area_key: "practical_life",
    category: "Preliminary Exercises",
    visual_description: "CLOTH OR PAPER-BOUND BOOK held with two hands. Child gently grasps top-right corner of page, lifts slowly, turns page one at a time. Pages stay flat. NO TEARING. NO CRUMPLING. Fine motor control with delicate materials.",
    key_materials: ["Various books"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_folding_cloth",
    name: "Folding Cloths",
    area_key: "practical_life",
    category: "Preliminary Exercises",
    visual_description: "SMALL CLOTH OR NAPKIN (typically white or colored linen, ~12x12 inches) being folded PRECISELY by child. Multiple levels: fold in half horizontally, fold in half vertically, fold in quarters, diagonal folds. Edges ALIGN PERFECTLY. NOT messy. NOT crumpled.",
    key_materials: ["Napkins", "Small cloths"],
    confusion_pairs: [],
    difficulty: "easy",
  },

  // --- Transfer Activities ---
  {
    work_key: "pl_dry_transfer_hand",
    name: "Dry Transfer - Hands",
    area_key: "practical_life",
    category: "Transfer Activities",
    visual_description: "TWO BOWLS on tray or table. Child uses BARE HANDS to pick up LARGE DRY OBJECTS (cotton balls, pompoms, wooden eggs, ~2-3 inches) from left bowl, transfer to right bowl. Objects visible, easy to grip. Many repetitions. NOT drops outside bowl. NOT using tools.",
    key_materials: ["Two bowls", "Large dry objects (cotton balls, pompoms)"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_spooning",
    name: "Spooning",
    area_key: "practical_life",
    category: "Transfer Activities",
    visual_description: "TWO BOWLS with DRY MATERIAL (rice, beans, lentils visible). METAL SPOON with handle (~8-10 inches). Child scoops material INTO spoon, lifts carefully, transfers to second bowl. Some grains fall back into first bowl. Progressive: large spoon → small spoon, coarse → fine materials.",
    key_materials: ["Two bowls", "Spoon", "Dry materials (rice, beans)"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_tonging",
    name: "Tonging",
    area_key: "practical_life",
    category: "Transfer Activities",
    visual_description: "TWO BOWLS with transfer objects. METAL TONGS (spring-loaded, visible handles) with open/close mechanism. Child squeezes handles to grasp LARGE OBJECTS (cotton balls, pompoms, ~2 inches), lifts, transfers to second bowl. Objects must fit between tongs. Progressive: salad tongs → sugar tongs.",
    key_materials: ["Two bowls", "Various tongs", "Objects to transfer"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_tweezers",
    name: "Tweezers Transfer",
    area_key: "practical_life",
    category: "Transfer Activities",
    visual_description: "TWO BOWLS with VERY SMALL OBJECTS (beads, seeds, pompoms ~0.5 inches). TWEEZERS (metal, pinching action) requiring PRECISE GRIP AND FINE MOTOR CONTROL. Child grasps tiny object between tips, lifts carefully, transfers. HIGH PRECISION REQUIRED. NOT dropping.",
    key_materials: ["Two bowls", "Tweezers", "Small objects"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_chopsticks",
    name: "Chopsticks Transfer",
    area_key: "practical_life",
    category: "Transfer Activities",
    visual_description: "TWO BOWLS with VARIOUS OBJECTS (large → small). WOODEN CHOPSTICKS (2 sticks, held together or separately, child grip, ~8-10 inches). Child uses pincher motion to grasp objects, lift, transfer. Cultural tool. Progressive: training chopsticks (connected) → regular chopsticks.",
    key_materials: ["Two bowls", "Chopsticks", "Various objects"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_pouring_dry",
    name: "Pouring Dry Materials",
    area_key: "practical_life",
    category: "Transfer Activities",
    visual_description: "TWO METAL OR CERAMIC PITCHERS on tray. DRIED GRAINS (rice, lentils, beans, sand visible ~2-3 inches of material in pitcher). Child tips pitcher at angle, POURS into second pitcher or containers. Wrist control critical. Some spillage expected. NOT wet. NOT colored water.",
    key_materials: ["Two pitchers", "Dry materials", "Tray"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_pouring_water",
    name: "Pouring Water",
    area_key: "practical_life",
    category: "Transfer Activities",
    visual_description: "CLEAR METAL OR CERAMIC PITCHER with WATER (visible liquid level ~half full). GLASSES or bowls nearby. Child POURS water into glasses at correct angle without spilling. Wrist control refined. Pitcher has handle, spout visible. May practice equal distribution to multiple glasses.",
    key_materials: ["Pitcher", "Glasses", "Sponge", "Tray"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_sponging",
    name: "Sponging",
    area_key: "practical_life",
    category: "Transfer Activities",
    visual_description: "TWO BOWLS with WATER (one full, one empty). NATURAL SPONGE (yellow/tan, ~3x3 inches, rectangular). Child SQUEEZES sponge into water in first bowl, absorbs water, then SQUEEZES water into second bowl. Water transfers via sponge absorption. NOT dry transfer.",
    key_materials: ["Two bowls", "Sponge", "Water", "Tray"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_basting",
    name: "Basting (Turkey Baster)",
    area_key: "practical_life",
    category: "Transfer Activities",
    visual_description: "TWO BOWLS with WATER. RUBBER TURKEY BASTER (red/clear, bulbous top with rubber squeeze, ~4 inches tall). Child SQUEEZES baster to create suction, submerges in water, RELEASES to fill, lifts, transfers water to second bowl. Squeeze-release coordination.",
    key_materials: ["Two bowls", "Turkey baster", "Water"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_dropper",
    name: "Eye Dropper",
    area_key: "practical_life",
    category: "Transfer Activities",
    visual_description: "SMALL GLASS OR PLASTIC EYE DROPPER (bulb + thin stem ~2-3 inches, holds ~0.5ml). CONTAINERS (bowl, ice cube tray with 12 compartments visible). COLORED WATER (blue/red visible in dropper). Child SQUEEZES bulb to fill dropper, RELEASES drops ONE AT A TIME into containers. Fine motor precision. NOT spraying.",
    key_materials: ["Eye dropper", "Small containers", "Ice cube tray", "Colored water"],
    confusion_pairs: [],
    difficulty: "hard",
  },

  // --- Dressing Frames ---
  {
    work_key: "pl_frame_velcro",
    name: "Velcro Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "FABRIC PANEL (~18x18 inches, canvas/felt) with VELCRO STRIPS on both sides (fuzzy + rough sides visible, contrasting colors like white/black). Child pulls open (rough sound), presses closed. Easiest dressing skill. NOT buttons. NOT zippers. Self-adhering fasteners.",
    key_materials: ["Velcro dressing frame"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_frame_snaps",
    name: "Snaps Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "FABRIC PANEL with SNAP FASTENERS (metal dome buttons, ~0.5 inch diameter, 4-6 snaps visible, typically on striped or solid fabric). Child PRESSES down to close (click sound), POPS up to open. Pinching action required. NOT velcro. NOT buttons.",
    key_materials: ["Snaps dressing frame"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_frame_large_buttons",
    name: "Large Buttons Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "FABRIC PANEL with OVERSIZED BUTTONS (1.5-2 inches diameter, wooden or plastic, clearly visible holes 2-4 per button). BUTTONHOLES are visible slits. Child opens by pulling button through hole (bilateral coordination), closes by pushing button back through. NOT small buttons. NOT snaps.",
    key_materials: ["Large buttons dressing frame"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_frame_small_buttons",
    name: "Small Buttons Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "FABRIC PANEL with SMALL BUTTONS (0.5-0.75 inch diameter, 2-4 holes per button, clearly visible holes). BUTTONHOLES are precisely fitted slits. Child must manipulate with thumb + forefinger to push button through hole. Requires fine motor precision and patience. Progressive from large buttons.",
    key_materials: ["Small buttons dressing frame"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_frame_zipper",
    name: "Zipper Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "FABRIC PANEL with ZIPPER (metal or plastic teeth visible, ~6-8 inches long, runs vertically). METAL ZIPPER PULL (square or round handle). Child PULLS handle down to separate, SLIDES back up to join. May have SEPARATING ZIPPER (can completely open at bottom). Child controls smooth motion. NOT stuck.",
    key_materials: ["Zipper dressing frames"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_frame_hook_eye",
    name: "Hook and Eye Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "FABRIC PANEL with HOOK-AND-EYE FASTENERS (small metal hook ~0.5 inch on one side, metal loop/eye on other side, 3-4 sets visible). Child SEPARATES by lifting hook out of eye, CLOSES by hooking back in. Requires precision to align hook into eye loop.",
    key_materials: ["Hook and eye dressing frame"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_frame_buckles",
    name: "Buckles Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "FABRIC PANEL with BELT BUCKLES (metal frame + prong, ~1 inch wide, 2-3 sets visible). Fabric strap threads through buckle frame, then prong goes through hole to fasten. Child OPENS by pulling prong out of hole, THREADS strap back through, FASTENS by inserting prong.",
    key_materials: ["Buckles dressing frame"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_frame_safety_pins",
    name: "Safety Pins Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "FABRIC PANEL with SAFETY PINS (metal curved pins ~1.5 inches, 2-3 safety pins visible, closed position shows coiled spring clasp). Child OPENS clasp by pulling, THREADS through holes in overlapped fabric, CLOSES pin back. Requires coordination and safety awareness.",
    key_materials: ["Safety pins dressing frame"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_frame_lacing",
    name: "Lacing Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "FABRIC PANEL (typically brown/tan, ~12x18 inches) with EVENLY SPACED EYELETS (metal-rimmed holes, ~0.5 inch diameter, 8-12 visible in parallel columns). CORD OR SHOELACE with PLASTIC STIFFENED TIP (~36 inches). Child THREADS lace through eyelets in alternating criss-cross pattern. NOT tying bow (that's separate).",
    key_materials: ["Lacing dressing frame"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_frame_bow_tying",
    name: "Bow Tying Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "FABRIC PANEL with RIBBON or LACE (striped pattern typical, ~12 inches long). Child TIES ribbon into BOW (two loops, center knot). Both hands grip ribbon, creates loops, tightens. This is INDEPENDENT OF LACING - child already knows how to lace, now learns to tie bow.",
    key_materials: ["Bow tying dressing frame"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_shoe_polishing",
    name: "Shoe Polishing",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "LEATHER OR CANVAS SHOES (child-sized, typically black or brown, slightly dirty/scuffed). SHOE POLISH (tin, dark cream/wax visible), BRUSHES (stiff brush, soft brush), CLOTH (white or tan), NEWSPAPER (spread on work surface). Child applies polish with brush, buffs with soft cloth. Shoes become SHINY. Multiple tools.",
    key_materials: ["Shoes", "Polish", "Brushes", "Cloth", "Newspaper"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_braiding",
    name: "Braiding Frame",
    area_key: "practical_life",
    category: "Dressing Frames",
    visual_description: "WOODEN FRAME (~12x18 inches) with THREE COLORED RIBBONS OR ROPES anchored at top (red, yellow, blue, ~18 inches long each, visible strands). Child WEAVES three strands by crossing alternately: right over center, left over center, right over center. Creates BRAID PATTERN going down frame. Requires pattern following.",
    key_materials: ["Braiding frame with ribbons or rope"],
    confusion_pairs: [],
    difficulty: "hard",
  },

  // --- Care of Self ---
  {
    work_key: "pl_hand_washing",
    name: "Hand Washing",
    area_key: "practical_life",
    category: "Care of Self",
    visual_description: "SINK/BASIN with WATER (pitcher to pour or faucet), BAR SOAP (visible), TOWEL, BUCKET below for dirty water. Child WETS hands with water, APPLIES soap (white/cream foam visible), SCRUBS thoroughly (fingers, palms, backs, forearms), RINSES with clean water, DRIES with towel. Optional: NAIL BRUSH for scrubbing nails. Complete hygiene routine.",
    key_materials: ["Basin", "Pitcher", "Soap", "Nail brush", "Towel"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_face_washing",
    name: "Face Washing",
    area_key: "practical_life",
    category: "Care of Self",
    visual_description: "BASIN with WATER, WASHCLOTH (white/colored, ~12x12 inches), MIRROR (reflects child's face). Child WETS cloth in water, APPLIES soap (optional), WASHES face (cheeks, forehead, chin, nose), RINSES cloth, WIPES face clean. MIRROR shows if face is clean. Child DRIES with towel.",
    key_materials: ["Basin", "Pitcher", "Washcloth", "Towel", "Mirror"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_teeth_brushing",
    name: "Teeth Brushing",
    area_key: "practical_life",
    category: "Care of Self",
    visual_description: "TOOTHBRUSH (small, child-sized bristles visible), TOOTHPASTE (white cream in tube), CUP (for water/rinsing), MIRROR (reflects mouth). Child APPLIES toothpaste to brush, BRUSHES all tooth surfaces (upper, lower, inside, outside), RINSES mouth with water, SPITS into sink. Taste indicates rinsing complete. Dental hygiene.",
    key_materials: ["Toothbrush", "Toothpaste", "Cup", "Mirror"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_nose_blowing",
    name: "Nose Blowing",
    area_key: "practical_life",
    category: "Care of Self",
    visual_description: "BOX OF TISSUES (white, visible dispenser), WASTE BASKET below. Child TAKES one tissue from box, HOLDS to nose, BLOWS (expels air), DISPOSES tissue in waste basket. MIRROR available to check if nose is clean. Simple hygiene task.",
    key_materials: ["Tissues", "Waste basket", "Mirror"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_coughing_sneezing",
    name: "Covering Coughs and Sneezes",
    area_key: "practical_life",
    category: "Care of Self",
    visual_description: "CHILD at table or standing. When coughing or sneezing, COVERS MOUTH AND NOSE by RAISING ELBOW/ARM to face (into bend of arm/elbow NOT into hand, to avoid spreading germs). No tissues needed. Polite gesture. NOT sneezing into hand. NOT uncovered.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_hair_brushing",
    name: "Hair Brushing/Combing",
    area_key: "practical_life",
    category: "Care of Self",
    visual_description: "HAIRBRUSH OR COMB (wooden or plastic, visible teeth/bristles), MIRROR (child's head visible). Child HOLDS brush, BRUSHES hair from scalp to ends (multiple strokes), WATCHES in mirror to see grooming progress. Hair becomes NEAT AND SMOOTH. NOT tangled.",
    key_materials: ["Brush", "Comb", "Mirror"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_hair_washing",
    name: "Hair Washing",
    area_key: "practical_life",
    category: "Care of Self",
    visual_description: "BASIN/SINK with WATER, SHAMPOO (liquid, visible bottle), TOWEL, sometimes practiced first on DOLL with hair (to practice). Child WETS hair with water, APPLIES shampoo (white/colored foam visible), LATHERS (hands in hair creating bubbles), RINSES with clean water (multiple rinses), DRIES with towel. NOT yet independent - adult assists often.",
    key_materials: ["Basin", "Pitcher", "Shampoo", "Towel", "Doll with hair (optional)"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_dressing_self",
    name: "Dressing Oneself",
    area_key: "practical_life",
    category: "Care of Self",
    visual_description: "CHILD'S OWN CLOTHING (jacket, shirt, pants, shoes). Child PUTS ON items independently: jacket using flip-method (hold at neckline, flip overhead), shoes (identifies left/right by sole, feet into shoes), socks. Later: full outfit matching. NOT adult help. Independence goal.",
    key_materials: ["Child's own clothing"],
    confusion_pairs: [],
    difficulty: "hard",
  },

  // --- Care of Environment ---
  {
    work_key: "pl_dusting",
    name: "Dusting",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "FLAT SURFACES (shelves, tables). DUSTER (feather duster with long handle OR dusting cloth, tan/yellow visible bristles/fabric). Child SWEEPS duster across surfaces to remove dust particles (visible dust cloud optional). Surfaces become CLEAN. NOT water. NOT wet. Dry dust removal.",
    key_materials: ["Duster or dusting cloth", "Basket for materials"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_sweeping",
    name: "Sweeping",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "CLASSROOM FLOOR with DEBRIS (crumbs, dust visible). CHILD-SIZED BROOM (proportional handle ~36 inches, bristles ~8 inches wide), DUSTPAN (metal or plastic, handle visible), HAND BRUSH (small, for final cleanup). Child SWEEPS debris into pile, uses hand brush + dustpan to collect, disposes in waste basket. Floor becomes CLEAN.",
    key_materials: ["Child-sized broom", "Dustpan", "Hand brush", "Waste basket"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_mopping",
    name: "Mopping",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "CHILD-SIZED MOP (wooden handle ~36 inches, cotton or microfiber head, ~12 inches across), BUCKET with WATER (clear water visible, ~half full), WRINGER (for squeezing water out). Child DUNKS mop in water, WRINGS to remove excess water, MOPS floor in wide sweeping motions. Floor becomes WET then DRIES CLEAN.",
    key_materials: ["Child-sized mop", "Bucket", "Water"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_table_scrubbing",
    name: "Table Scrubbing",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "WOODEN TABLE with VISIBLE DIRT/SPILLS. BASIN with SOAPY WATER (white/cream foam visible), PITCHER (for clean water), SCRUB BRUSH (stiff bristles, ~6 inches), SPONGE, TOWEL. Child SCRUBS table with soapy water + brush, RINSES with clean water, DRIES with towel. Complete sequence: wet → soap → scrub → rinse → dry.",
    key_materials: ["Table", "Basin", "Pitcher", "Soap", "Scrub brush", "Sponge", "Towel"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_window_washing",
    name: "Window Washing",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "GLASS WINDOW or MIRROR with VISIBLE DUST/STREAKS. SPRAY BOTTLE (blue liquid visible, ammonia-based cleaner), SQUEEGEE (rubber blade ~8 inches wide on handle), CLOTH (white or tan, lint-free). Child SPRAYS surface, WIPES with squeegee (downward strokes), DRIES with cloth. Glass becomes TRANSPARENT AND SHINY.",
    key_materials: ["Spray bottle", "Squeegee", "Cloth"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_polishing_wood",
    name: "Wood Polishing",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "WOODEN OBJECTS (shelf, frame, low furniture, natural wood visible). WOOD POLISH OR OIL (brown/golden liquid in tin/bottle), SOFT CLOTH (white or tan, lint-free). Child APPLIES polish with cloth (circular motions), BUFFS with clean area of cloth. Wood becomes SHINY AND SMOOTH. NOT water-based.",
    key_materials: ["Wooden objects", "Wood polish/oil", "Soft cloths"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_polishing_metal",
    name: "Metal Polishing",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "METAL OBJECTS (brass bells, candle holders, silver utensils, slightly tarnished visible). METAL POLISH (brown/cream-colored in tin, smelly), SOFT CLOTHS (white, lint-free), COTTON BALLS (optional). Child APPLIES polish with cloth/cotton ball, RUBS thoroughly, BUFFS with clean cloth. Metal becomes SHINY. Requires patience - takes effort.",
    key_materials: ["Metal objects", "Metal polish", "Soft cloths", "Cotton balls"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_polishing_glass",
    name: "Glass Polishing",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "GLASS OBJECTS (vases, glasses, picture frames, transparent). GLASS CLEANER (spray bottle, blue liquid visible) OR damp cloth + paper. Child SPRAYS/WIPES glass, DRIES with cloth to prevent streaks. Glass becomes CLEAR AND TRANSPARENT. Fragile handling required. NOT rough treatment.",
    key_materials: ["Glass objects", "Glass cleaner", "Soft cloths"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_plant_care",
    name: "Plant Care",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "POTTED PLANT with SOIL (visible green leaves or flowers, pot ~6-8 inches diameter). WATERING CAN with NARROW SPOUT (metal or plastic, ~8 inches tall), SPRAY BOTTLE for misting (optional), CLOTH for leaf-wiping. Child POURS water slowly at soil level (NOT leaves), MISTS leaves if desired, WIPES dust from leaves. Care of living things.",
    key_materials: ["Plants", "Watering can", "Spray bottle", "Cloth"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_flower_arranging",
    name: "Flower Arranging",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "FLOWERS (fresh cut, stems visible, 5-10 stems, various colors or single type), VASE (ceramic or glass, ~8 inches tall), SCISSORS (child-safe blade), PITCHER with WATER, NEWSPAPER (spread on work surface). Child ARRANGES flowers by height/color in vase, adding water. Aesthetic appreciation. Flowers arranged in BALANCED, ATTRACTIVE pattern.",
    key_materials: ["Flowers", "Vase", "Scissors", "Pitcher", "Sponge", "Newspaper"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_animal_care",
    name: "Animal Care",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "CLASSROOM PET (fish in bowl, hamster/guinea pig in cage, rabbit, bird in cage). FOOD DISH or FEEDER, WATER DISH, SUPPLIES (pellets, seeds, hay visible). Child PROVIDES fresh water daily (pours from pitcher), FEEDS pet (portion-controlled), CLEANS habitat occasionally. Care of living animals. Responsibility and empathy.",
    key_materials: ["Pet", "Pet supplies", "Food", "Water dish"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_dish_washing",
    name: "Dish Washing",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "TWO BASINS (one with SOAPY WATER visible white/cream foam, one with CLEAN RINSE WATER), DISHES (plates, bowls, cups, used/dirty), SPONGE or BRUSH (visible bristles), DRYING RACK or TOWEL. Child WASHES dishes in soapy water (scrubbing visible), RINSES in clean water, DRIES with towel or air-dries in rack. Complete washing sequence.",
    key_materials: ["Dishes", "Two basins", "Dish soap", "Sponge/brush", "Drying rack", "Towel"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_laundry",
    name: "Laundry - Hand Washing",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "SMALL CLOTH ITEMS (napkins, handkerchiefs, small towels, ~12x12 inches). BASIN with WATER, WASHBOARD (wooden, ridged surface visible), SOAP (bar or liquid), CLOTHESPINS, DRYING RACK or clothesline. Child WETS cloth in water, APPLIES soap, SCRUBS on washboard (producing friction), RINSES in clean water, HANGS with clothespins to dry.",
    key_materials: ["Basin", "Washboard", "Soap", "Clothespins", "Drying rack/line"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_folding_laundry",
    name: "Folding Laundry",
    area_key: "practical_life",
    category: "Care of Environment",
    visual_description: "CLEAN CLOTHING ITEMS (washcloths, towels, napkins, t-shirts, pants, various sizes and textures visible). Child FOLDS items with PRECISE EDGES: simple squares (washcloths), rectangles (towels), more complex (shirts, pants). Progressive difficulty from simple to complex. Organization and care of belongings.",
    key_materials: ["Various clothing items"],
    confusion_pairs: [],
    difficulty: "medium",
  },

  // --- Grace and Courtesy ---
  {
    work_key: "pl_greetings",
    name: "Greetings",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "TWO PEOPLE MEETING (child greeting adult or peer). Child LOOKS IN EYES, SPEAKS CLEARLY 'Hello' or 'Good morning', SHAKES HANDS with proper grip (not limp, not crushing), SMILES. Social skills. NOT shy or mumbling. NOT distant.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_introductions",
    name: "Introductions",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "TWO OR THREE PEOPLE in formal greeting. Child INTRODUCES SELF: 'My name is [name], nice to meet you' with eye contact and handshake. Introducing OTHERS: 'This is [person's name]'. Respectful tone, clear speech. Community building skill.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_please_thank_you",
    name: "Please and Thank You",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "CHILD REQUESTING OBJECT or BEING SERVED: says 'Please' when asking, 'Thank you' when receiving. CHILD AT TABLE: says 'Thank you' to server/peer. Polite words used at CORRECT MOMENTS. Natural flow, not mechanical. Social awareness.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_excuse_me",
    name: "Saying Excuse Me",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "CHILD NEEDING TO PASS THROUGH or INTERRUPT: says 'Excuse me' with eye contact. CHILD AT WORK: says 'Excuse me' when someone is in the way. Awareness of others' space. Polite tone, not demanding.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_interrupting",
    name: "How to Interrupt",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "CHILD NEEDING ADULT'S ATTENTION while adult is busy: PLACES HAND on adult's shoulder/arm GENTLY, WAITS QUIETLY without talking or pulling, MAINTAINS patience. NOT tugging. NOT talking. Adult acknowledges when ready. Respect for others' work.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_offering_help",
    name: "Offering and Accepting Help",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "CHILD A (struggling with task) and CHILD B (watching). CHILD B ASKS: 'Would you like help?' CHILD A ACCEPTS: 'Yes, thank you' or DECLINES: 'No, I'll try again' (politely). CHILD B HELPS or LEAVES respectfully. Empathy and choice.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_apologizing",
    name: "Apologizing",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "CHILD WHO MADE MISTAKE or HURT SOMEONE: LOOKS IN EYES, SAYS SINCERELY 'I'm sorry for [action]' (not just 'sorry'). CHILD ACCEPTS apology: 'I forgive you'. Genuine emotional tone, not rote. Taking responsibility.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_table_manners",
    name: "Table Manners",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "CHILDREN AT TABLE WITH FOOD (plates, cups, utensils visible). SITTING POSTURE: upright, feet on floor or footrest. UTENSIL USE: correct grip on fork/spoon/knife. PASSING FOOD: 'please pass the [item]', accepts with 'thank you'. CONVERSATION: speaks softly, listens. Dining etiquette.",
    key_materials: ["Table setting materials", "Placemat", "Dishes", "Utensils"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_table_setting",
    name: "Setting the Table",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "EMPTY TABLE with PLACEMAT (often laminated, shows outline of correct placement). CHILD PLACES: plate centered, fork to left, knife/spoon to right, cup above knife, napkin on plate or left. Each item in CORRECT POSITION. Matches template. Sequencing and spatial awareness.",
    key_materials: ["Placemat template", "Plate", "Cup", "Fork", "Knife", "Spoon", "Napkin"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_observing_work",
    name: "Observing Another's Work",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "CHILD A DOING WORK at table/shelf. CHILD B WATCHING from nearby without TOUCHING, TALKING, or INTERFERING. SILENT OBSERVATION. Respects child A's concentration. Learning by watching. NOT disruptive.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_walking_around_work",
    name: "Walking Around Someone's Work",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "CHILD A WORKING on FLOOR MAT (visible work spread on mat). OTHER CHILDREN PASSING BY: STEP CAREFULLY AROUND mat, NEVER stepping on edge or materials. Respects personal work space. Awareness of others.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_sharing",
    name: "Sharing and Taking Turns",
    area_key: "practical_life",
    category: "Grace and Courtesy",
    visual_description: "POPULAR MATERIAL (puzzle, beads, activity) available to ONE CHILD. OTHER CHILDREN WAITING. FIRST CHILD FINISHES, offers to next child OR next child ASKS politely 'May I have a turn?' Child WAITS without complaining. Fairness and patience.",
    key_materials: [],
    confusion_pairs: [],
    difficulty: "easy",
  },

  // --- Food Preparation ---
  {
    work_key: "pl_washing_produce",
    name: "Washing Fruits and Vegetables",
    area_key: "practical_life",
    category: "Food Preparation",
    visual_description: "FRESH PRODUCE (apples, carrots, berries, visible dirt/debris). BASIN with WATER, COLANDER (metal strainer with holes). Child PLACES produce in water, RUBS gently to remove dirt particles (visible in water), RINSES in colander, DRIES with towel. Food safety. NOT using soap.",
    key_materials: ["Basin", "Colander", "Various produce", "Towel"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_spreading",
    name: "Spreading",
    area_key: "practical_life",
    category: "Food Preparation",
    visual_description: "BREAD or CRACKERS (flat, visible surface), SPREAD (butter, peanut butter, jam in container, visible in jar), SPREADING KNIFE (dull blade, ~6 inches). Child DIPS knife into spread, APPLIES to bread surface in EVEN LAYER without TEARING bread. Consistency matters. Fine motor control.",
    key_materials: ["Bread/crackers", "Spread", "Spreading knife", "Plate"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_peeling_easy",
    name: "Peeling - Easy Items",
    area_key: "practical_life",
    category: "Food Preparation",
    visual_description: "SOFT FRUITS (banana visible with characteristic shape and peel, orange with textured peel, hardboiled egg in shell visible). Child HOLDS fruit, PEELS BACK layers by hand without tools (using fingernails and pulling motion). Peel comes away. BOWL for discarded peels. NOT using knife.",
    key_materials: ["Bananas", "Hard-boiled eggs", "Oranges", "Bowl"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_peeling_tool",
    name: "Peeling - With Peeler",
    area_key: "practical_life",
    category: "Food Preparation",
    visual_description: "VEGETABLE PEELER (metal handle ~3 inches, sharp horizontal blade visible, handle loop). FIRM VEGETABLES (carrot, cucumber, potato, visible whole). Child HOLDS vegetable in one hand, PEELER in other, STROKES blade downward/away to remove thin peel layer. Repeats in rows. Peel falls away. Safety awareness - don't cut fingers.",
    key_materials: ["Vegetable peeler", "Carrots", "Cucumbers", "Potatoes", "Cutting board"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_cutting_soft",
    name: "Cutting Soft Foods",
    area_key: "practical_life",
    category: "Food Preparation",
    visual_description: "SOFT FOODS (banana visible as yellow fruit, cheese as pale cube, cucumber as green vegetable, all easy to knife). CHILD-SAFE KNIFE (dull blade ~4 inches, safe grip handle), CUTTING BOARD (wood or plastic, ~8x6 inches). Child HOLDS food with one hand, CUTS with rocking/sawing motion. Pieces SEPARATE. NOT jagged.",
    key_materials: ["Cutting board", "Child-safe knife", "Soft foods"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_cutting_hard",
    name: "Cutting Harder Foods",
    area_key: "practical_life",
    category: "Food Preparation",
    visual_description: "FIRMER PRODUCE (apple visible as red/green fruit, celery as green stalk with strings, carrot as orange vegetable). SHARP KNIFE (age-appropriate, real blade ~5-6 inches, child supervised). Child POSITIONS food on BOARD, CUTS with rocking/chopping motion. Adult nearby for safety. Harder than soft food.",
    key_materials: ["Cutting board", "Knife", "Various vegetables"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_grating",
    name: "Grating",
    area_key: "practical_life",
    category: "Food Preparation",
    visual_description: "GRATER (metal, 4-sided ~4 inches tall, different hole sizes visible, handle at top). FOOD BLOCK (cheese visible as pale block, vegetables like carrot visible as firm orange). BOWL below. Child HOLDS grater firmly on board, STROKES food DOWN the holes (not back-and-forth). Food SHREDS into bowl. Careful not to grate fingers.",
    key_materials: ["Grater", "Cheese", "Vegetables", "Bowl", "Cutting board"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_juicing",
    name: "Juicing",
    area_key: "practical_life",
    category: "Food Preparation",
    visual_description: "HAND JUICER (metal or wood, 2-handled squeezer, ~6 inches long, tapered cone in center visible). CITRUS FRUIT (lemon or orange halved, white/yellow flesh visible, juice visible in fruit). Child PLACES fruit half into juicer cone, SQUEEZES handles firmly. Juice FLOWS into cup below. Repeats, flips fruit. Hand strength.",
    key_materials: ["Hand juicer", "Citrus fruits", "Cup", "Strainer"],
    confusion_pairs: [],
    difficulty: "medium",
  },
  {
    work_key: "pl_cracking_eggs",
    name: "Cracking Eggs",
    area_key: "practical_life",
    category: "Food Preparation",
    visual_description: "EGGS (brown or white, whole, ~2 inches long). BOWL (for egg white/yolk). Child HOLDS egg in one hand, TAPS on edge of bowl to CRACK shell (audible cracking sound), PULLS shell apart (2 pieces visible), SEPARATES yolk/white into bowl. Shell fragments into separate small dish. Shell management critical.",
    key_materials: ["Eggs", "Bowl", "Small dish for shells"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_making_snack",
    name: "Making a Snack",
    area_key: "practical_life",
    category: "Food Preparation",
    visual_description: "COMPLETE SNACK PREP (crackers + spread visible, or fruit cut into bowl visible, or veggies + dip). Child SELECTS ingredients, ASSEMBLES snack using previously-learned skills (spreading, cutting, arranging). Plated snack is COMPLETE and PRESENTABLE. Independence in food prep.",
    key_materials: ["Various snack ingredients", "Utensils", "Plate"],
    confusion_pairs: [],
    difficulty: "medium",
  },

  // --- Sewing and Needlework ---
  {
    work_key: "pl_threading_beads",
    name: "Threading Beads",
    area_key: "practical_life",
    category: "Sewing and Needlework",
    visual_description: "BEADS (wooden, various sizes from 1-3 inches diameter, HOLES visible through center, colorful). CORD or STRING (with STIFFENED TIP at one end - often plastic straw or wrapped wire ~0.25 inch diameter). Child HOLDS string, SELECTS bead, INSERTS string through hole, SLIDES bead down string. Repeats. Sequence may follow pattern (color/shape alternating visible).",
    key_materials: ["Beads of various sizes", "String/cord with stiff end", "Container"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_sewing_cards",
    name: "Sewing Cards",
    area_key: "practical_life",
    category: "Sewing and Needlework",
    visual_description: "FLAT CARD (often shaped like fish, animal, or simple object, ~6x8 inches, colorful). HOLES PUNCHED through outline (visible holes, dark circles, evenly spaced). LACE OR YARN with PLASTIC TIP (~24 inches). Child THREADS lace through holes in sequence (following outline/pattern). Laces form OUTLINE OF SHAPE. Bilateral coordination.",
    key_materials: ["Sewing cards with holes", "Laces/yarn with plastic tip"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_punching",
    name: "Paper Punching",
    area_key: "practical_life",
    category: "Sewing and Needlework",
    visual_description: "PAPER PUNCH (typically red/blue plastic, squeezable handles, ~2 inches, metal holes visible). PAPER (white or colored, ~8x10 inches). Child ALIGNS paper in punch, SQUEEZES handles firmly (audible punch sound), RELEASES. HOLE appears in paper (circular, ~0.25 inch). Repeats freely OR along drawn outline.",
    key_materials: ["Paper punch", "Paper", "Mat"],
    confusion_pairs: [],
    difficulty: "easy",
  },
  {
    work_key: "pl_running_stitch",
    name: "Running Stitch",
    area_key: "practical_life",
    category: "Sewing and Needlework",
    visual_description: "LOOSE-WEAVE FABRIC (burlap visible with visible grid, ~6x6 inches). EMBROIDERY HOOP holding fabric taut. BLUNT NEEDLE (large eye, ~1 inch, safe for children). COLORED THREAD (~36 inches, visible in needle). Child PUSHES needle down through fabric, back up, repeating in LINE. Creates dotted LINE of stitches. Even spacing.",
    key_materials: ["Burlap or loose-weave fabric", "Embroidery hoop", "Blunt needle", "Embroidery thread"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_cross_stitch",
    name: "Cross Stitch",
    area_key: "practical_life",
    category: "Sewing and Needlework",
    visual_description: "AIDA CLOTH (grid-like weave visible, ~6x6 inches, even-weave with tiny holes). EMBROIDERY HOOP. NEEDLE (with colored thread). Child STITCHES X PATTERN by going diagonally down-right, back up-left, then crossing (creating visible X shape). Repeats to fill area or pattern.",
    key_materials: ["Aida cloth", "Embroidery hoop", "Blunt needle", "Thread"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_button_sewing",
    name: "Sewing a Button",
    area_key: "practical_life",
    category: "Sewing and Needlework",
    visual_description: "FABRIC PIECE (~6x6 inches) with BUTTON (visible as pale dome, 2-4 HOLES through center). NEEDLE with THREAD (~18 inches), SCISSORS. Child POKES needle through one hole, back up through adjacent hole, repeats (creating visible stitch pattern). Completes 4-6 passes. Button becomes SECURED to fabric.",
    key_materials: ["Fabric", "Buttons", "Needle", "Thread", "Scissors"],
    confusion_pairs: [],
    difficulty: "hard",
  },
  {
    work_key: "pl_weaving",
    name: "Weaving",
    area_key: "practical_life",
    category: "Sewing and Needlework",
    visual_description: "WEAVING LOOM (wooden frame, ~6x8 inches) with VERTICAL WARP THREADS (parallel strings, clearly visible, white/neutral color). HORIZONTAL YARN OR STRIPS (colored, ~12 inches long). Child PULLS yarn through, over-under-over-under (alternating), repeats on next row (reversing over/under). Creates WOVEN PATTERN visible in center.",
    key_materials: ["Weaving loom or paper", "Yarn or strips"],
    confusion_pairs: [],
    difficulty: "medium",
  },
];
