import type { WorkSignature } from './work-signatures';

export const PRACTICAL_LIFE_SIGNATURES: WorkSignature[] = [
  // --- Preliminary Exercises ---
  {
    work_key: 'pl_carrying_mat',
    name: 'Carrying a Mat',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'Tan or beige WOVEN CANVAS WORK MAT (typically 18x24 inches, rolled into a cylinder ~4 inches diameter). Child holds it HORIZONTALLY with BOTH HANDS at the corners or edges, carrying without the mat dragging on the floor. The rolled fabric is clearly visible against the child\'s body. Material shows woven texture. NOT a basket. NOT a tray. Pure rolled fabric.',
    key_materials: ['Woven canvas work mat', 'Rolled cylindrical shape'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_carrying_chair',
    name: 'Carrying a Chair',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'WOODEN CHILD-SIZED CHAIR (small, typically 12-14 inches tall, wood stained or painted, clearly visible seat ~10x10 inches and vertical backrest slats). Child grips the backrest and seat with BOTH HANDS, lifts the chair off the floor, and carries it without the legs hitting anything. The chair moves silently through the classroom. NOT an adult chair. NOT a table.',
    key_materials: ['Child-sized wooden chair', 'Small seat', 'Vertical backrest'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_carrying_tray',
    name: 'Carrying a Tray',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'FLAT WOODEN OR PLASTIC TRAY (typically 12x18 inches, wooden borders/frame, handles visible on the short sides, shallow depth ~1 inch). Tray held level with BOTH HANDS at the handles or on sides. May contain lightweight objects (shells, pompoms, felt balls) that stay balanced inside. Child moves slowly without objects sliding or falling. NOT a basket. NOT a table.',
    key_materials: ['Wooden or plastic tray', 'Handles on sides', 'Shallow container shape'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_carrying_table',
    name: 'Carrying a Table',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'TWO CHILDREN TOGETHER lifting and carrying a SMALL WOODEN TABLE (child-sized, approximately 2 feet x 1.5 feet, lightweight wood construction). One child on each long side, gripping the table legs or frame, table held LEVEL and moving silently through the classroom. Demonstrates COOPERATION and coordination between two people. NOT a solo activity. NOT a single child.',
    key_materials: ['Child-sized wooden table', 'Two children working together'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_opening_closing_door',
    name: 'Opening and Closing a Door',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'CLASSROOM WOODEN DOOR with clearly visible HANDLE or DOORKNOB. Child reaches out, grasps the handle, pulls the door SMOOTHLY open WITHOUT SLAMMING or forcing, then closes the door gently by controlling the swing motion. The door movement is deliberate and silent. NOT banging. NOT forcing. Real classroom infrastructure.',
    key_materials: ['Classroom door', 'Metal or wooden handle', 'Door frame'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_walking_line',
    name: 'Walking on the Line',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'BLACK OR RED TAPE/PAINTED LINE on classroom floor creating a loop (~15-20 feet long, 3-4 inches wide, clearly visible). Child walks HEEL-TO-TOE along the line with ARMS OUTSTRETCHED for balance OR holding various challenge objects (bell, flag, water glass in pitcher, basket on head). Perfect balance and control. NOT stepping off the line. NOT running.',
    key_materials: ['Tape or painted line on floor', 'Various challenge objects'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_sitting_standing',
    name: 'Sitting and Standing at a Table',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'WOODEN CHILD-SIZED CHAIR at WOODEN TABLE. Child pulls out the chair SILENTLY (no scraping sound), sits down carefully while maintaining good posture, works at the table, then stands by pushing the chair back in QUIETLY. Grace and courtesy in movement. NOT slamming. NOT dragging furniture.',
    key_materials: ['Child-sized chair', 'Child-sized table', 'Workspace'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_silence_game',
    name: 'The Silence Game',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'GROUP OF CHILDREN sitting COMPLETELY STILL AND SILENT in the classroom, maintaining perfect stillness for extended time. Children often sit on floor or at tables, not moving at all. Sometimes adult rings a BELL or whispers a child\'s name VERY QUIETLY to signal the end or to call a child. Pure inner peace and self-control. NOT playing noisily. NOT fidgeting.',
    key_materials: ['Group of children', 'Silence board or sign (optional)', 'Bell (optional)'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_turning_pages',
    name: 'Turning Pages of a Book',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'CLOTH OR PAPER-BOUND BOOK (various sizes and types) held with two hands. Child gently grasps the top-right corner of a page using thumb and forefinger, lifts the page slowly and deliberately, turns it to the left side. Pages stay FLAT and SMOOTH. Zero tearing or crumpling. Fine motor control with delicate materials.',
    key_materials: ['Various books', 'Paper or cloth pages'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_folding_cloth',
    name: 'Folding Cloths',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'SMALL CLOTH OR LINEN NAPKIN (typically white or pastel colored, approximately 12x12 inches, visible woven texture). Child folds it with PRECISE MOVEMENTS: fold in half horizontally, fold in half vertically, fold in quarters, or diagonal folds. All edges ALIGN PERFECTLY, corners touch exactly. NOT messy. NOT crumpled. Progressive difficulty in fold complexity.',
    key_materials: ['Napkins', 'Linen cloths', 'Small textiles'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_folding_laundry',
    name: 'Folding Laundry',
    area_key: 'practical_life',
    category: 'Preliminary Exercises',
    visual_description: 'REAL CLOTHING ITEMS (washcloths, towels, t-shirts, pants) laid flat on a work surface or basket. Child picks up item, folds it methodically into organized rectangles or squares. Progression from simple items (washcloths) to more complex (t-shirts with sleeves, pants with multiple folds). Items are organized and ready to store. Care of belongings.',
    key_materials: ['Clothing items', 'Washcloths', 'Towels', 'T-shirts', 'Pants'],
    confusion_pairs: ['pl_folding_cloth'],
    difficulty: 'medium',
  },

  // --- Transfer Activities ---
  {
    work_key: 'pl_dry_transfer_hand',
    name: 'Dry Transfer - Hands',
    area_key: 'practical_life',
    category: 'Transfer Activities',
    visual_description: 'TWO BOWLS positioned on a tray or work surface. Child uses BARE HANDS to pick up LARGE DRY OBJECTS (cotton balls, pompoms, wooden eggs ~2-3 inches in diameter) from the left bowl, transfers to the right bowl. Objects are visible and easy to grip. Child repeats many times. Many objects fall back. NOT using tools. NOT water involved.',
    key_materials: ['Two bowls', 'Cotton balls', 'Pompoms', 'Wooden eggs'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_spooning',
    name: 'Spooning',
    area_key: 'practical_life',
    category: 'Transfer Activities',
    visual_description: 'TWO BOWLS with DRY GRANULAR MATERIAL (rice, lentils, or beans clearly visible ~2-3 inches of material in first bowl). METAL SPOON with handle (approximately 8-10 inches long). Child scoops the spoon INTO the material, lifts spoon carefully, transfers to the second bowl. Some grains fall back. Progressive: large spoon with large grains → small spoon with fine materials.',
    key_materials: ['Two bowls', 'Metal spoon', 'Rice', 'Beans', 'Lentils'],
    confusion_pairs: ['pl_dry_transfer_hand'],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_tonging',
    name: 'Tonging',
    area_key: 'practical_life',
    category: 'Transfer Activities',
    visual_description: 'TWO BOWLS containing transfer objects. METAL TONGS with spring-loaded mechanism and open/close handles (visible pivot point, ~6-8 inches long). Child squeezes the handles to open tongs, grasps LARGE OBJECTS (cotton balls, pompoms ~1.5-2 inches), lifts, transfers to second bowl. Objects must fit between tong tips. Progressive: large salad tongs → smaller sugar tongs.',
    key_materials: ['Two bowls', 'Metal tongs', 'Cotton balls', 'Pompoms'],
    confusion_pairs: ['pl_dry_transfer_hand'],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_tweezers',
    name: 'Tweezers Transfer',
    area_key: 'practical_life',
    category: 'Transfer Activities',
    visual_description: 'TWO BOWLS with VERY SMALL OBJECTS (beads ~0.5 inches, seeds, small pompoms). METAL TWEEZERS with pinching action and fine points. Child grasps tiny object between the tips using VERY PRECISE GRIP AND FINE MOTOR CONTROL, lifts carefully, transfers to second bowl. HIGH PRECISION. Objects easily drop. NOT dropping.',
    key_materials: ['Two bowls', 'Metal tweezers', 'Beads', 'Seeds', 'Small pompoms'],
    confusion_pairs: ['pl_tonging'],
    difficulty: 'hard',
  },
  {
    work_key: 'pl_chopsticks',
    name: 'Chopsticks Transfer',
    area_key: 'practical_life',
    category: 'Transfer Activities',
    visual_description: 'TWO BOWLS with VARIOUS OBJECTS (progression from large to small). WOODEN CHOPSTICKS (2 sticks, either connected with training bridge or separate, ~8-10 inches long, held together like a pincher). Child uses pincher motion with chopsticks to grasp objects, lift, and transfer. Cultural tool. Progressive: training chopsticks with connector → regular chopsticks.',
    key_materials: ['Two bowls', 'Wooden chopsticks', 'Various objects', 'Training chopsticks (optional)'],
    confusion_pairs: ['pl_tweezers'],
    difficulty: 'hard',
  },
  {
    work_key: 'pl_pouring_dry',
    name: 'Pouring Dry Materials',
    area_key: 'practical_life',
    category: 'Transfer Activities',
    visual_description: 'TWO METAL OR CERAMIC PITCHERS positioned on a tray. DRIED GRAINS (rice, lentils, beans, or sand) clearly visible in the first pitcher (~2-3 inches of material). Child tips the first pitcher at an angle, POURS the material into the second pitcher or containers below. Wrist control is critical for smooth pouring. Some spillage expected and normal. NOT wet. NOT colored water.',
    key_materials: ['Two pitchers', 'Dried grains', 'Rice', 'Sand', 'Beans', 'Tray'],
    confusion_pairs: ['pl_pouring_water'],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_pouring_water',
    name: 'Pouring Water',
    area_key: 'practical_life',
    category: 'Transfer Activities',
    visual_description: 'CLEAR METAL OR CERAMIC PITCHER with WATER visible inside (~half full, liquid level clearly visible). GLASSES or small bowls positioned nearby. Child POURS water from pitcher into glasses at correct angle, controlling the stream WITHOUT SPILLING. Refined wrist control. Pitcher has visible handle and spout. Child may practice pouring equal amounts into multiple glasses.',
    key_materials: ['Metal or ceramic pitcher', 'Clear glasses', 'Water', 'Bowls'],
    confusion_pairs: ['pl_pouring_dry'],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_sponging',
    name: 'Sponging',
    area_key: 'practical_life',
    category: 'Transfer Activities',
    visual_description: 'TWO BOWLS with WATER (one bowl full, one empty, water visible). NATURAL SPONGE (yellow or tan color, rectangular ~3x3 inches, spongy texture visible with pores). Child SQUEEZES sponge into the water-filled bowl to absorb water, lifts sponge full of water, SQUEEZES water into the second bowl. Water transfers via sponge absorption. NOT dry transfer.',
    key_materials: ['Two bowls', 'Natural sponge', 'Water', 'Tray'],
    confusion_pairs: ['pl_pouring_water'],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_basting',
    name: 'Basting (Turkey Baster)',
    area_key: 'practical_life',
    category: 'Transfer Activities',
    visual_description: 'TWO BOWLS with WATER. RUBBER TURKEY BASTER (red or clear plastic, bulbous squeeze top with rubber material, approximately 4 inches tall with thin stem). Child SQUEEZES the baster bulb to create suction, submerges the stem in water, RELEASES the bulb to fill with water, lifts the baster, transfers water to second bowl. Squeeze-release bilateral coordination.',
    key_materials: ['Two bowls', 'Turkey baster', 'Water'],
    confusion_pairs: ['pl_dropper'],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_dropper',
    name: 'Eye Dropper',
    area_key: 'practical_life',
    category: 'Transfer Activities',
    visual_description: 'SMALL GLASS OR PLASTIC EYE DROPPER (bulb + thin stem, ~2-3 inches tall, holds approximately 0.5ml). CONTAINERS (bowl, ice cube tray with 12 compartments visible). COLORED WATER (blue or red visible in dropper). Child SQUEEZES bulb to fill dropper, RELEASES drops ONE AT A TIME into containers. Fine motor precision required. NOT spraying. Progressive difficulty with smaller containers.',
    key_materials: ['Eye dropper', 'Small containers', 'Ice cube tray', 'Colored water'],
    confusion_pairs: ['pl_basting'],
    difficulty: 'hard',
  },

  // --- Dressing Frames ---
  {
    work_key: 'pl_frame_velcro',
    name: 'Velcro Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'FABRIC PANEL (approximately 18x18 inches, canvas or felt in neutral color). VELCRO STRIPS on both sides (fuzzy side + rough/hook side, contrasting colors like white + black, clearly visible). Child pulls the two sides apart (rough sound), presses closed together (sticking sound). Easiest dressing skill. Self-adhering fasteners. NOT buttons. NOT zippers.',
    key_materials: ['Velcro frame', 'Fabric panel', 'Velcro strips'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_frame_snaps',
    name: 'Snaps Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'FABRIC PANEL with SNAP FASTENERS (metal dome buttons, approximately 0.5 inch diameter, 4-6 snaps visible, typically on striped or solid colored fabric). Child PRESSES down to close (metallic click sound), POPS up or pries off to open. Pinching action required with thumb and fingers. NOT velcro. NOT buttons with holes.',
    key_materials: ['Snaps frame', 'Metal snap fasteners', 'Fabric panel'],
    confusion_pairs: ['pl_frame_velcro'],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_frame_large_buttons',
    name: 'Large Buttons Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'FABRIC PANEL with OVERSIZED BUTTONS (1.5-2 inches diameter, wooden or plastic, clearly visible holes 2-4 per button with large openings). BUTTONHOLES are visible slits on opposite side. Child opens by pulling button through the hole (bilateral coordination), closes by pushing button back through. NOT small buttons. NOT snaps.',
    key_materials: ['Large buttons frame', 'Oversized buttons', 'Buttonholes', 'Fabric panel'],
    confusion_pairs: ['pl_frame_small_buttons'],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_frame_small_buttons',
    name: 'Small Buttons Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'FABRIC PANEL with SMALL BUTTONS (0.5-0.75 inch diameter, 2-4 holes per button with clearly visible but small holes). BUTTONHOLES are precisely fitted slits on opposite side. Child must manipulate with thumb and forefinger to push button through hole. Requires fine motor precision and patience. Progressive from large buttons.',
    key_materials: ['Small buttons frame', 'Small buttons', 'Buttonholes', 'Fabric panel'],
    confusion_pairs: ['pl_frame_large_buttons'],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_frame_zipper',
    name: 'Zipper Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'FABRIC PANEL with a FULL-LENGTH METAL ZIPPER (approximately 12-14 inches, visible metal slider, metal teeth clearly visible on both sides). Child pulls the slider UP to close the zipper, then pulls DOWN to open. Two-directional motion. Bilateral coordination with hand positioning. NOT buttons. NOT snaps.',
    key_materials: ['Zipper frame', 'Metal zipper', 'Metal slider', 'Fabric panel'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_frame_hook_eye',
    name: 'Hook and Eye Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'FABRIC PANEL with HOOK AND EYE FASTENERS (metal hook on one side, small metal loop on opposite side, 3-5 pairs visible). Child lifts fabric, positions hook over the eye, fastens together. Requires fine dexterity and alignment. NOT buttons. NOT snaps. Small metal hardware visible.',
    key_materials: ['Hook and eye frame', 'Metal hooks', 'Metal eyes', 'Fabric panel'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'pl_frame_buckles',
    name: 'Buckles Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'FABRIC PANEL with a PLASTIC OR METAL BUCKLE FASTENER (approximately 1-2 inches wide, with visible prongs or snap mechanism). Child threads fabric through buckle, pulls to tighten. Requires hand-over-hand coordination and understanding of buckle mechanics. NOT buttons. Real buckle hardware.',
    key_materials: ['Buckle frame', 'Plastic or metal buckle', 'Fabric panel', 'Strap'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'pl_frame_lacing',
    name: 'Lacing Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'FABRIC PANEL with PRE-DRILLED HOLES (~0.25 inch diameter, arranged in two columns, typically 8-10 holes per column). FABRIC LACE (cord or thin fabric strip, ~0.5 inches wide, threaded with plastic aglet). Child laces the cord through holes in crossover pattern, then pulls to tighten. Progressive from large holes to small.',
    key_materials: ['Lacing frame', 'Fabric with holes', 'Lacing cord', 'Aglet'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'pl_frame_safety_pins',
    name: 'Safety Pins Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'WOODEN DRESSING FRAME with TWO FABRIC FLAPS joined by METAL SAFETY PINS (4-6 pins, ~2 inches long, shiny silver metal). Child opens each safety pin by pressing the clasp, threading the pin point through the opposite fabric flap, then closing the clasp securely. Requires precise fine motor control and awareness of sharp pin point. NOT buttons or snaps (safety pins have a visible spring mechanism and pointed tip). NOT hook and eye (safety pins are larger with a visible coiled spring).',
    key_materials: ['Wooden dressing frame', 'Metal safety pins', 'Fabric flaps', 'Spring clasp mechanism'],
    confusion_pairs: ['pl_frame_hook_eye'],
    difficulty: 'hard',
  },
  {
    work_key: 'pl_frame_bow_tying',
    name: 'Bow Tying Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'WOODEN DRESSING FRAME with TWO FABRIC FLAPS connected by 4-5 WIDE RIBBON STRIPS (each ~1 inch wide, often in contrasting colors). Child ties each pair of ribbons into a BOW KNOT — cross, loop, wrap, pull through. Finished frame shows a column of neat bows down the center. NOT lacing (no holes — ribbons are sewn to fabric edges). NOT braiding (two-strand bow, not three-strand weave). The most advanced dressing frame requiring bilateral hand coordination.',
    key_materials: ['Wooden dressing frame', 'Wide fabric ribbons', 'Fabric flaps'],
    confusion_pairs: ['pl_frame_lacing', 'pl_tying_shoes'],
    difficulty: 'hard',
  },
  {
    work_key: 'pl_shoe_polishing',
    name: 'Shoe Polishing',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'COMPLETE SHOE CARE KIT on a TRAY or CLOTH: a REAL SHOE (leather or faux leather, typically dark), a TIN OF SHOE POLISH (round metal tin with colored wax), one or two BRUSHES (stiff bristle applicator brush and soft buffing brush), a POLISHING CLOTH (soft cotton rag), and NEWSPAPER spread underneath to protect the surface. Child applies polish with brush, buffs with cloth in circular motions until shoe is SHINY. NOT a dressing frame (uses actual shoe and polish products). Distinct smell of shoe wax.',
    key_materials: ['Real shoe', 'Shoe polish tin', 'Bristle brushes', 'Polishing cloth', 'Newspaper'],
    confusion_pairs: ['pl_polishing_metal'],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_braiding',
    name: 'Braiding Frame',
    area_key: 'practical_life',
    category: 'Dressing Frames',
    visual_description: 'WOODEN FRAME or STAND with THREE LONG STRANDS of THICK RIBBON, ROPE, or YARN (each ~12-18 inches long, often in three different colors for visual tracking). Strands are attached at the top of the frame. Child crosses outer strand over middle strand alternately from left and right, creating a WOVEN BRAID pattern visible as an interlocking diagonal weave. NOT bow tying (three strands woven, not two tied). NOT lacing (no holes — strands interweave freely). Three-strand pattern is the key visual identifier.',
    key_materials: ['Wooden braiding frame', 'Three colored ribbons or cords', 'Mounting clips'],
    confusion_pairs: ['pl_frame_bow_tying', 'pl_weaving'],
    difficulty: 'hard',
  },

  // --- Care of Self ---
  {
    work_key: 'pl_washing_hands',
    name: 'Washing Hands',
    area_key: 'practical_life',
    category: 'Care of Self',
    visual_description: 'BATHROOM OR CLASSROOM SINK with RUNNING WATER, SOAP, and TOWEL visible. Child fills hands with water, applies SOAP (bar or liquid), rubs hands together creating LATHER/BUBBLES visible on skin, rinses under running water, dries hands with towel. Complete sequence. NOT splashing. NOT wasting water.',
    key_materials: ['Sink', 'Running water', 'Soap', 'Towel'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_brushing_teeth',
    name: 'Brushing Teeth',
    area_key: 'practical_life',
    category: 'Care of Self',
    visual_description: 'CHILD AT BATHROOM SINK with TOOTHBRUSH, TOOTHPASTE, and CUP for rinsing. Child applies PASTE to brush, brushes TEETH in various motions (circular, up/down), rinses mouth with water from cup. Mirror visible showing child\'s face. Complete hygiene routine. Healthy habit.',
    key_materials: ['Toothbrush', 'Toothpaste', 'Bathroom sink', 'Cup', 'Mirror'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_washing_face',
    name: 'Washing Face',
    area_key: 'practical_life',
    category: 'Care of Self',
    visual_description: 'CHILD AT BATHROOM SINK with WATER, SOAP, and TOWEL. Child fills hands with water, applies SOAP, rubs FACE in circular motions covering all areas (cheeks, forehead, chin), rinses with clean water, dries with towel. Clean, fresh appearance. Care of self.',
    key_materials: ['Bathroom sink', 'Water', 'Soap', 'Towel'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_nose_blowing',
    name: 'Nose Blowing',
    area_key: 'practical_life',
    category: 'Care of Self',
    visual_description: 'CHILD holding a TISSUE or HANDKERCHIEF to their NOSE. Child closes one nostril with a finger, blows out through open nostril into tissue. Proper nose blowing technique. Sanitary practice. NOT messy. Demonstrates self-care hygiene.',
    key_materials: ['Tissue', 'Handkerchief'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_combing_hair',
    name: 'Combing Hair',
    area_key: 'practical_life',
    category: 'Care of Self',
    visual_description: 'CHILD holding a COMB or BRUSH, looking in a MIRROR. Child combs through HAIR using smooth downward strokes from scalp to hair ends. Hair becomes untangled and neat. Both long and short hair visible. Care of appearance. Mirror shows results.',
    key_materials: ['Comb', 'Brush', 'Mirror'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_using_handkerchief',
    name: 'Using a Handkerchief',
    area_key: 'practical_life',
    category: 'Care of Self',
    visual_description: 'CHILD holding a CLOTH HANDKERCHIEF (folded or unfolded). Child brings it to nose/face when needed, blows gently, folds it away, or places in pocket. Sanitary practice. Cloth material visible. Proper technique for before tissue boxes.',
    key_materials: ['Cloth handkerchief'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_clothing_care_simple',
    name: 'Clothing Care - Simple Tasks',
    area_key: 'practical_life',
    category: 'Care of Self',
    visual_description: 'CHILD PERFORMING simple clothing care: putting on shoes by pushing feet into shoes with hands, straightening shirt or sweater, tucking in shirts, rolling up sleeves. Independent dressing tasks. Clothing becomes properly arranged.',
    key_materials: ['Clothing items', 'Shoes', 'Sleeves', 'Shirts'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_tying_shoes',
    name: 'Tying Shoes',
    area_key: 'practical_life',
    category: 'Care of Self',
    visual_description: 'CHILD SITTING DOWN with LACED SHOES. Child takes LACES (one in each hand), creates LOOP/BUNNY EARS, crosses them, pulls tight, ties a KNOT. Bilateral coordination. Can also use practice frames with OVERSIZED LACES first. Footwear secured properly.',
    key_materials: ['Shoes with laces', 'Lacing practice frame (optional)'],
    confusion_pairs: [],
    difficulty: 'hard',
  },

  // --- Care of Environment ---
  {
    work_key: 'pl_sweeping',
    name: 'Sweeping',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD-SIZED BROOM with SHORT HANDLE (~2.5-3 feet tall, bristles clearly visible) and DUSTPAN. Child sweeps FLOOR using sweeping motions, pushing accumulated dust and debris into a pile, then sweeping into dustpan. Floor becomes clean. Bristles move across floor. Care of classroom environment.',
    key_materials: ['Child-sized broom', 'Bristles', 'Dustpan', 'Floor'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_dusting',
    name: 'Dusting',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD using a CLOTH (dust cloth or soft rag) to wipe SURFACES (shelf, table, furniture). Child makes circular or linear wiping motions, collecting dust on cloth. Surfaces become clean and shiny. Cloth shows accumulated dust. Care of materials.',
    key_materials: ['Soft cloth', 'Dust cloth', 'Furniture', 'Shelves'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_window_cleaning',
    name: 'Window Cleaning',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CLASSROOM WINDOW (low enough for child to reach). BUCKET with WATER, CLOTH, and optional SQUEEGEE. Child wipes window glass using cloth with circular motions, removes water with squeegee if used. Glass becomes clear and visible. Water drips down window. Care of classroom.',
    key_materials: ['Classroom window', 'Water', 'Cloth', 'Squeegee (optional)', 'Bucket'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_mopping',
    name: 'Mopping',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD-SIZED MOP with HANDLE and STRING STRANDS or CLOTH at bottom. BUCKET with WATER. Child dips mop into water, wrings out excess water (bucket has wringer if present), pushes mop across FLOOR in long strokes. Floor becomes wet and clean. Water visible on floor. Care of classroom.',
    key_materials: ['Child-sized mop', 'Bucket with water', 'Mop wringer (optional)', 'Floor'],
    confusion_pairs: ['pl_sweeping'],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_scrubbing',
    name: 'Scrubbing',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD with a SCRUB BRUSH (stiff bristles, wooden handle ~6 inches long) and BUCKET of WATER. Child dips brush in water, scrubs FLOOR or SURFACE using back-and-forth or circular motions. Stubborn dirt comes loose. Brush bristles move vigorously. Surfaces become clean.',
    key_materials: ['Scrub brush', 'Stiff bristles', 'Bucket', 'Water', 'Floor or surface'],
    confusion_pairs: ['pl_sweeping'],
    difficulty: 'hard',
  },
  {
    work_key: 'pl_polishing_metal',
    name: 'Polishing Metal',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD with METAL POLISH (cream or liquid), CLOTH, and METAL OBJECT (silver frame, bells, trays, utensils). Child applies polish to cloth, rubs metal in circular motions. Metal becomes shiny and reflective. Polish visible on cloth. Care of materials.',
    key_materials: ['Metal polish', 'Cloth', 'Metal objects'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_watering_plants',
    name: 'Watering Plants',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD holding a WATERING CAN with SPOUT (metal or plastic, typically 1-2 liter capacity). Child fills can with water, pours water around base of CLASSROOM PLANT or flower in pot. Soil becomes moist. Water visible in can. Care of living things.',
    key_materials: ['Watering can', 'Plant', 'Pot with soil', 'Water'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_arranging_flowers',
    name: 'Arranging Flowers',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD with a VASE of WATER, SCISSORS, and CUT FLOWERS (fresh, various colors and types visible). Child trims stems at angle, removes lower leaves, arranges flowers in vase by height and color. Flowers are organized and beautiful. Care of beauty in environment.',
    key_materials: ['Vase', 'Water', 'Fresh flowers', 'Scissors', 'Flower stems'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_replacing_materials',
    name: 'Replacing Materials on Shelf',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD placing work materials BACK on the CLASSROOM SHELF in their designated spot. WOODEN SHELF with labeled sections. Child carries materials (boxes, trays, frame) and places them neatly in correct location. Shelf remains organized. Order and care.',
    key_materials: ['Classroom shelf', 'Work materials', 'Containers'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_organizing_materials',
    name: 'Organizing Work Materials',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD sorting and ORGANIZING MATERIALS in containers or on shelves. MATERIALS grouped by type (buttons together, beads together, etc.). CONTAINERS or BASKETS holding materials. Child arranges items systematically. Classroom becomes orderly and functional.',
    key_materials: ['Work materials', 'Containers', 'Baskets', 'Shelf space'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_trash_management',
    name: 'Managing Trash',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD gathering TRASH and WASTE materials from classroom or table. TRASH BASKET or BIN visible. Child places waste in trash, may empty trash into larger bin. Classroom becomes clean and organized. Care of environment hygiene.',
    key_materials: ['Trash basket', 'Trash bin', 'Waste materials'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_composting',
    name: 'Composting',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD placing ORGANIC WASTE (food scraps, plant material, paper) into a COMPOST CONTAINER or BIN. COMPOST PILE or BARREL visible. Child understands decomposition and recycling. Care of environment and natural cycles.',
    key_materials: ['Compost bin', 'Organic waste', 'Food scraps'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_recycling',
    name: 'Recycling',
    area_key: 'practical_life',
    category: 'Care of Environment',
    visual_description: 'CHILD sorting RECYCLABLE MATERIALS (paper, plastic, glass, metal) into SEPARATE CONTAINERS or BINS. RECYCLING BINS labeled with symbols or colors. Child separates materials according to type. Environmental responsibility. Care of planet.',
    key_materials: ['Recycling bins', 'Recyclable materials', 'Paper', 'Plastic', 'Glass'],
    confusion_pairs: [],
    difficulty: 'medium',
  },

  // --- Grace and Courtesy ---
  {
    work_key: 'pl_greetings',
    name: 'Greetings',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD greeting another person (teacher or peer) with VERBAL and NON-VERBAL communication. Child says "Good morning" or similar, makes EYE CONTACT, may offer HANDSHAKE (firm grip, visible hand contact). Both people smile. Appropriate distance. Social skills.',
    key_materials: [],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_introductions',
    name: 'Introductions',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD introducing themselves or introducing two people to each other. Child says their NAME clearly, listens to others\' names, makes EYE CONTACT, may shake hands. New people meet. Social confidence. Community building.',
    key_materials: [],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_please_thank_you',
    name: 'Please and Thank You',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD using polite WORDS in appropriate contexts. Child says "Please" when asking for something, "Thank you" when receiving something, "You\'re welcome" when thanked. Spoken clearly. Other people respond positively. Social awareness and courtesy.',
    key_materials: [],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_excuse_me',
    name: 'Saying Excuse Me',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD saying "Excuse me" when needing to pass someone, interrupting gently, or when accidentally bumping someone. Child waits for response, moves past respectfully. Other person acknowledges. Polite and aware of others\' space.',
    key_materials: [],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_interrupting',
    name: 'How to Interrupt',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD interrupting an adult respectfully. Child approaches, places hand gently on adult\'s shoulder or arm, waits QUIETLY without making noise. Adult finishes speaking and acknowledges the child. Patient and respectful. NOT shouting. NOT interrupting impatiently.',
    key_materials: [],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_offering_help',
    name: 'Offering and Accepting Help',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD offering help to another person: "Can I help you?" or "Would you like help?". Person accepts or declines graciously. If accepted, child helps. If declined, child says "OK" and leaves respectfully. Helpfulness and community.',
    key_materials: [],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_apologizing',
    name: 'Apologizing',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD apologizing sincerely when making a mistake or hurting someone. Child says "I\'m sorry" clearly, looks at the person, explains what they did wrong, and may offer to fix it. Other person accepts apology. Taking responsibility.',
    key_materials: [],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_table_manners',
    name: 'Table Manners',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD eating at a table with proper ETIQUETTE. Child sits properly with good POSTURE, uses UTENSILS correctly (fork, knife, spoon visible), chews with MOUTH CLOSED, passes food to others, engages in conversation at appropriate volume. Napkin on lap. Dining grace.',
    key_materials: ['Table', 'Utensils', 'Plate', 'Food', 'Napkin'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_table_setting',
    name: 'Setting the Table',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD arranging a COMPLETE PLACE SETTING. PLACEMAT, PLATE, FORK on left, KNIFE and SPOON on right, NAPKIN folded neatly, CUP positioned correctly. Items aligned properly. TEMPLATE may show correct placement. Care of dining environment.',
    key_materials: ['Placemat', 'Plate', 'Fork', 'Knife', 'Spoon', 'Napkin', 'Cup', 'Template (optional)'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_observing_work',
    name: 'Observing Another\'s Work',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD watching another child or adult work without TOUCHING or TALKING. Child stands or sits quietly at appropriate distance from the WORK MAT. Eyes watching attentively. Respects the working person\'s space and concentration. Learning by observation.',
    key_materials: ['Work mat', 'Working person'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_walking_around_work',
    name: 'Walking Around Someone\'s Work',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD walking through classroom, carefully avoiding stepping on another child\'s WORK MAT. Child walks AROUND the mat edges, never stepping across the work surface. Respects others\' materials and space. Care of community.',
    key_materials: ['Work mat', 'Classroom floor'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_sharing',
    name: 'Sharing and Taking Turns',
    area_key: 'practical_life',
    category: 'Grace and Courtesy',
    visual_description: 'CHILD WAITING for a work material that another child is using. Child observes patiently, does not grab or interrupt. When the first child finishes, they offer the material or set it down. Second child picks it up and begins working. Patience and community living.',
    key_materials: ['Work material', 'Two or more children'],
    confusion_pairs: [],
    difficulty: 'easy',
  },

  // --- Food Preparation ---
  {
    work_key: 'pl_washing_produce',
    name: 'Washing Fruits and Vegetables',
    area_key: 'practical_life',
    category: 'Food Preparation',
    visual_description: 'CHILD at SINK with COLANDER, FRESH PRODUCE (carrots, apples, lettuce), and WATER. Child places produce in colander, rinses under RUNNING WATER, rubs produce gently to remove dirt, drains water. Produce becomes clean. Water visible on vegetables. Food safety and independence.',
    key_materials: ['Colander', 'Running water', 'Fresh produce', 'Towel'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_spreading',
    name: 'Spreading',
    area_key: 'practical_life',
    category: 'Food Preparation',
    visual_description: 'CHILD with SPREADING KNIFE, BREAD or CRACKERS, and SPREAD (butter, jam, peanut butter visible). Child applies spread to bread in even layer using knife, covers surface without holes. Bread does not tear. Food becomes prepared. Fine motor control.',
    key_materials: ['Spreading knife', 'Bread or crackers', 'Spread', 'Plate'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_peeling_easy',
    name: 'Peeling - Easy Items',
    area_key: 'practical_life',
    category: 'Food Preparation',
    visual_description: 'CHILD peeling SOFT PRODUCE by hand. BANANA being peeled from stem, or HARD-BOILED EGG being peeled, or ORANGE being peeled. Peel comes off in strips. Food becomes ready to eat. Hands do the work. No tools needed initially.',
    key_materials: ['Bananas', 'Hard-boiled eggs', 'Oranges', 'Bowl for peels'],
    confusion_pairs: ['pl_peeling_tool'],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_peeling_tool',
    name: 'Peeling - With Peeler',
    area_key: 'practical_life',
    category: 'Food Preparation',
    visual_description: 'CHILD using a VEGETABLE PEELER (sharp blade, wooden handle, approximately 4-5 inches long). FRESH VEGETABLES (carrots, cucumbers, potatoes) held over a CUTTING BOARD. Child moves peeler from stem to tip, removing thin peel. Peel strips fall into bin. Tool use and food preparation.',
    key_materials: ['Vegetable peeler', 'Vegetables', 'Cutting board', 'Compost bin'],
    confusion_pairs: ['pl_peeling_easy'],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_cutting_soft',
    name: 'Cutting Soft Foods',
    area_key: 'practical_life',
    category: 'Food Preparation',
    visual_description: 'CHILD with CHILD-SAFE KNIFE (blunt blade, wooden handle ~6-8 inches, clearly safe but effective), CUTTING BOARD, and SOFT FOOD (banana, cheese, cucumber visible). Child cuts food into pieces. Blade visible moving through soft food. Food becomes portioned. Fine motor skill.',
    key_materials: ['Child-safe knife', 'Cutting board', 'Soft foods'],
    confusion_pairs: ['pl_cutting_hard'],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_cutting_hard',
    name: 'Cutting Harder Foods',
    area_key: 'practical_life',
    category: 'Food Preparation',
    visual_description: 'CHILD with REAL KNIFE (serrated or sharp blade ~6-8 inches, wooden handle), CUTTING BOARD, and FIRMER FOODS (apple, carrot, celery). Child cuts with BILATERAL COORDINATION, pressing knife down steadily. Food cuts into slices. Hand position safe. Advanced knife skills.',
    key_materials: ['Sharp knife', 'Cutting board', 'Apples', 'Carrots', 'Celery'],
    confusion_pairs: ['pl_cutting_soft'],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_grating',
    name: 'Grating',
    area_key: 'practical_life',
    category: 'Food Preparation',
    visual_description: 'CHILD with a GRATER (metal, four-sided ~4 inches tall, visible sharp grating surfaces). CHEESE BLOCK or VEGETABLES (carrots, zucchini) being held, BOWL positioned underneath. Child rubs cheese/vegetable against grating surface. Shredded pieces fall into bowl. Hand position safe.',
    key_materials: ['Grater', 'Cheese or vegetables', 'Bowl'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_juicing',
    name: 'Juicing',
    area_key: 'practical_life',
    category: 'Food Preparation',
    visual_description: 'CHILD holding a HAND JUICER (metal or plastic, ~6 inches, two handles for squeezing). CITRUS FRUIT (orange, lemon cut in half) placed in juicer. Child squeezes handles with HAND STRENGTH, juice flows into GLASS or CONTAINER below. Fresh juice visible. Nutrition and food preparation.',
    key_materials: ['Hand juicer', 'Citrus fruits', 'Glass', 'Strainer (optional)'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_cracking_eggs',
    name: 'Cracking Eggs',
    area_key: 'practical_life',
    category: 'Food Preparation',
    visual_description: 'CHILD holding an EGG, tapping it gently against edge of BOWL or SURFACE, pulling shell apart over BOWL. Egg YOLK and WHITE drop into bowl. Shell pieces separated carefully. Bowl ready for cooking. Fine motor precision.',
    key_materials: ['Eggs', 'Bowl', 'Small dish for shells'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_making_snack',
    name: 'Making a Snack',
    area_key: 'practical_life',
    category: 'Food Preparation',
    visual_description: 'CHILD preparing a COMPLETE SIMPLE SNACK independently. Combination of skills: spreading crackers with topping, arranging fruit on plate, or cutting vegetables with dip. Child sequences steps, gathers materials, prepares food, cleans up. Self-sufficiency and independence.',
    key_materials: ['Various snack ingredients', 'Utensils', 'Plate', 'Cutting board (optional)'],
    confusion_pairs: [],
    difficulty: 'hard',
  },

  // --- Sewing and Needlework ---
  {
    work_key: 'pl_threading_beads',
    name: 'Threading Beads',
    area_key: 'practical_life',
    category: 'Sewing and Needlework',
    visual_description: 'CHILD with BEADS (wooden, various sizes, clearly visible holes), STRING or CORD with STIFF END (plastic aglet or waxed thread), and CONTAINER for beads. Child picks up bead, threads string through hole, continues adding beads. String fills progressively. Hand-eye coordination and concentration.',
    key_materials: ['Beads', 'String or cord', 'Aglet', 'Container'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_sewing_cards',
    name: 'Sewing Cards',
    area_key: 'practical_life',
    category: 'Sewing and Needlework',
    visual_description: 'CHILD with CARDBOARD CARDS having PRE-PUNCHED HOLES (~0.25 inch diameter, arranged in line or pattern). LACING CORD or YARN with PLASTIC TIP threaded through holes in CRISSCROSS PATTERN. Child laces methodically, holes appear connected. Bilateral coordination. Picture or design emerges.',
    key_materials: ['Sewing cards', 'Pre-punched holes', 'Lacing cord', 'Plastic aglet'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_punching',
    name: 'Paper Punching',
    area_key: 'practical_life',
    category: 'Sewing and Needlework',
    visual_description: 'CHILD with a PAPER PUNCH (hand-operated, ~2-3 inches, hole punch mechanism visible). PAPER (white or colored) placed under punch. Child squeezes handles, PUNCH creates hole. Paper punch WORKS. Holes appear as circles. Fine motor and hand strength.',
    key_materials: ['Paper punch', 'Paper'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'pl_running_stitch',
    name: 'Running Stitch',
    area_key: 'practical_life',
    category: 'Sewing and Needlework',
    visual_description: 'CHILD with EMBROIDERY HOOP holding BURLAP or LOOSE-WEAVE FABRIC, BLUNT NEEDLE, and EMBROIDERY THREAD. Child makes small stitches moving needle in and out of fabric. THREAD visible creating line of stitches. Stitches are relatively even. Basic sewing skill.',
    key_materials: ['Burlap or loose-weave fabric', 'Embroidery hoop', 'Blunt needle', 'Embroidery thread'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'pl_cross_stitch',
    name: 'Cross Stitch',
    area_key: 'practical_life',
    category: 'Sewing and Needlework',
    visual_description: 'CHILD with AIDA CLOTH (counted cross-stitch fabric with visible grid), EMBROIDERY HOOP, BLUNT NEEDLE, and COLORED THREAD. Child creates X-SHAPED STITCHES by going diagonally one way then back. Multiple X\'s form pattern or picture. Advanced stitching.',
    key_materials: ['Aida cloth', 'Embroidery hoop', 'Blunt needle', 'Colored thread'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'pl_button_sewing',
    name: 'Sewing a Button',
    area_key: 'practical_life',
    category: 'Sewing and Needlework',
    visual_description: 'CHILD with FABRIC, BUTTON (2-hole or 4-hole, clearly visible holes), NEEDLE, THREAD (approximately 12-18 inches), and SCISSORS. Child threads needle, positions button on fabric, stitches through holes repeatedly, knots thread on back. Button becomes SECURELY ATTACHED.',
    key_materials: ['Fabric', 'Buttons', 'Needle', 'Thread', 'Scissors'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'pl_weaving',
    name: 'Weaving',
    area_key: 'practical_life',
    category: 'Sewing and Needlework',
    visual_description: 'CHILD with a WEAVING LOOM or PAPER with VERTICAL STRIPS already cut, and YARN or FABRIC STRIPS for horizontal weaving. Child weaves yarn OVER and UNDER the vertical threads, creating a woven pattern. Colors mix and pattern emerges. Creating something beautiful.',
    key_materials: ['Weaving loom or paper', 'Yarn or fabric strips', 'Scissors'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
];
