import type { WorkSignature } from './work-signatures';

export const MATHEMATICS_SIGNATURES: WorkSignature[] = [
  // === ma_numeration (Introduction to Numbers 1-10) ===
  {
    work_key: 'ma_number_rods',
    name: 'Number Rods',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Ten graduated wooden rods with red and blue alternating segments, stacked in a clear pyramid arrangement. Rods increase in length from 10cm to 1m, each marked with distinct color bands. Child is arranging or comparing the rods in order.',
    key_materials: ['red and blue wooden rods', 'graduated lengths 10cm to 1m'],
    confusion_pairs: ['se_red_rods'],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_sandpaper_numerals',
    name: 'Sandpaper Numerals',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Tan or light-colored wooden tiles with sandpaper numerals 0-9 adhered to the surface. Each numeral has a distinct tactile texture. Child is tracing numerals with fingertips, developing muscle memory for numeral formation.',
    key_materials: ['wooden tiles', 'sandpaper numerals 0-9', 'textured surface'],
    confusion_pairs: ['la_sandpaper_letters'],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_number_rods_numerals',
    name: 'Number Rods with Numerals',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Number Rods arranged in a stair pattern alongside small printed numeral cards 1-10, matching each rod to its corresponding numeral. A child is placing cards or pointing at the matching pairs.',
    key_materials: ['number rods', 'printed numeral cards 1-10'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_spindle_box',
    name: 'Spindle Boxes',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Wooden box divided into 10 compartments labeled 0-9 at the top. Child is placing thin wooden spindles (matchstick-like dowels) into each compartment in the quantity matching the numeral above. Rubber bands may be bundling groups of spindles.',
    key_materials: ['wooden box compartments', 'thin wooden spindles', 'numerical labels 0-9'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_cards_counters',
    name: 'Cards and Counters',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Printed numeral cards 1-10 with small red counters (discs) arranged beneath each card showing the quantity. A child is placing counters in rows or pairs, or discovering patterns of odd and even numbers.',
    key_materials: ['printed numeral cards 1-10', 'red counter discs'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_memory_game',
    name: 'Memory Game of Numbers',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Numeral cards displayed briefly, then hidden. Child is fetching a corresponding quantity of small objects (shells, beads, stones) from a basket, demonstrating counting accuracy from memory.',
    key_materials: ['numeral cards', 'small counting objects'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_number_puzzles',
    name: 'Number Puzzles and Games',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Wooden or cardboard puzzles with numerals and quantities that must be matched or completed. Child is fitting puzzle pieces or matching cards to reinforce numeral recognition.',
    key_materials: ['number puzzle pieces', 'matching game cards'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_short_bead_stair',
    name: 'Short Bead Stair',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Nine colored bead bars (strung beads on wire or rod) representing quantities 1-9, arranged in a descending staircase pattern. Each color represents a different quantity. Child is counting beads or arranging in order.',
    key_materials: ['colored beads on wires', 'beads 1-9 quantities', 'distinct color per quantity'],
    confusion_pairs: ['se_bead_bars'],
    difficulty: 'easy',
  },

  // === ma_decimal (Decimal System) ===
  {
    work_key: 'ma_golden_beads_intro',
    name: 'Introduction to Golden Beads',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Golden-colored beads organized into four distinct units: single beads (units), rods of ten beads (tens), flat squares of 100 beads in a grid (hundreds), and large cubes of 1000 beads (thousands). Child is identifying and naming each category.',
    key_materials: ['golden beads (units)', 'golden bead rods (tens)', 'golden bead squares (hundreds)', 'golden bead cubes (thousands)'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_golden_beads_tray',
    name: 'Golden Bead Tray Exercises',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Golden bead materials (units, tens, hundreds, thousands) organized on trays. Child is fetching or arranging requested quantities of each category, organizing materials by place value on the tray.',
    key_materials: ['golden beads in all four categories', 'tray for organization'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_large_numeral_cards',
    name: 'Large Numeral Cards',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Color-coded card sets with numerals: green cards for units (1-9), blue cards for tens (10-90), red cards for hundreds (100-900), green cards for thousands (1000-9000). Cards are stacked or superimposed to form multi-digit numbers.',
    key_materials: ['color-coded numeral cards (green/blue/red/green)', 'numerals 1-9, 10-90, 100-900, 1000-9000'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_formation_quantity',
    name: 'Formation of Quantity',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Child is building multi-digit quantities with golden beads on a tray, gathering requested amounts of units, tens, hundreds, and thousands beads. Labels showing the number are placed alongside the quantity.',
    key_materials: ['golden beads (all categories)', 'labels/numbers'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_formation_symbol',
    name: 'Formation of Symbol',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Large numeral cards are superimposed (stacked with offset) to build multi-digit numbers. A child is creating numbers by layering green, blue, red, and green cards to show place value in written form.',
    key_materials: ['large numeral cards (color-coded)'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_association_quantity_symbol',
    name: 'Association of Quantity and Symbol',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Golden bead quantities are displayed alongside their matching superimposed numeral cards. Child is matching the concrete materials to the abstract symbols, understanding that both represent the same value.',
    key_materials: ['golden beads (all categories)', 'large numeral cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_exchange_game',
    name: 'Exchange Game (Change Game)',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Golden beads arranged on a tray with 10 units being exchanged for 1 ten-rod, or 10 tens exchanged for 1 hundred-square. A dice or numeral card determines how many beads to roll/select, triggering exchanges when reaching 10 in any category.',
    key_materials: ['golden beads (all categories)', 'dice or numeral cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_golden_beads_addition',
    name: 'Golden Bead Addition',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Two quantities built with golden beads are combined, child is gathering all materials together and performing exchanges (10 units → 1 ten, etc.) to find the sum. Problem cards guide the operation.',
    key_materials: ['golden beads (all categories)', 'problem cards', 'trays for organization'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_golden_beads_subtraction',
    name: 'Golden Bead Subtraction',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Child begins with a golden bead quantity and removes another quantity, performing exchanges in reverse (1 ten-rod → 10 units) when needed to complete the subtraction.',
    key_materials: ['golden beads (all categories)', 'problem cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_golden_beads_multiplication',
    name: 'Golden Bead Multiplication',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'A quantity of golden beads is repeated multiple times (e.g., 2 ten-rods taken 3 times), then all gathered and organized with exchanges to find the product.',
    key_materials: ['golden beads (all categories)', 'small numeral cards for multiplier', 'problem cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_golden_beads_division',
    name: 'Golden Bead Division',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'A quantity of golden beads is distributed equally among multiple groups (represented by skittles or dividers). Child performs exchanges as needed to complete the sharing and finds the quotient.',
    key_materials: ['golden beads (all categories)', 'skittles or dividers', 'problem cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },

  // === ma_teens_tens (Teens and Tens) ===
  {
    work_key: 'ma_teen_board_1',
    name: 'Teen Board 1 (Seguin Board A)',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'Wooden board with a fixed golden ten-bar on the left and columns (0-9) for adding colored bead bars to show numbers 11-19. Child places colored bead bars in sequence to show quantities.',
    key_materials: ['wooden board with ten-bar slot', 'colored bead bars 1-9', 'golden ten-bar'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_teen_board_2',
    name: 'Teen Board 2 (Seguin Board B)',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'Wooden board with columns for numeral placement showing 11-19 without beads. Child is placing or matching numeral cards representing the teen numbers.',
    key_materials: ['wooden board with numeral slots', 'numeral cards for teens'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_ten_board_1',
    name: 'Ten Board 1 (Seguin Board C)',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'Wooden board with columns showing 10, 20, 30... 90. Golden ten-bars are placed in the columns to represent each tens quantity. Child is skip-counting by tens with beads.',
    key_materials: ['wooden board', 'golden ten-bars'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_ten_board_2',
    name: 'Ten Board 2 (Seguin Board D)',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'Wooden board showing all numbers 11-99 with multiple columns. Golden ten-bars and colored bead bars are placed to form all numbers in the range.',
    key_materials: ['wooden board (large)', 'golden ten-bars', 'colored bead bars 1-9'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_hundred_board',
    name: 'Hundred Board',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'Wooden board with 100 numbered squares arranged in a 10×10 grid (1-100). Child is placing numbered tiles in sequence or discovering patterns by skipping every 2nd, 5th, or 10th number.',
    key_materials: ['wooden board with 100 squares', 'numbered tiles 1-100'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_hundred_chain',
    name: 'Hundred Chain',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'Ten golden ten-bars connected end-to-end in a chain forming 100 beads in linear form. Labeled arrow cards (1-100) are placed along the chain at intervals, highlighting the sequence and patterns.',
    key_materials: ['hundred chain (100 beads)', 'arrow label cards 1-100'],
    confusion_pairs: ['ma_thousand_chain'],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_thousand_chain',
    name: 'Thousand Chain',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'Very long chain of 1000 golden beads (100 ten-bars connected) laid out on the ground or in a large loop. Arrow cards are placed to mark every 100 beads. Child counts and marks patterns.',
    key_materials: ['thousand chain (1000 beads)', 'arrow cards 1-1000'],
    confusion_pairs: ['ma_hundred_chain'],
    difficulty: 'medium',
  },

  // === ma_linear (Linear Counting - Bead Chains) ===
  {
    work_key: 'ma_short_chains',
    name: 'Short Bead Chains (Squares)',
    area_key: 'mathematics',
    category: 'Linear Counting (Bead Chains)',
    visual_description: 'Nine colored bead chains of increasing length arranged in a stair pattern: chain-of-2 (4 beads), chain-of-3 (9 beads), chain-of-4 (16 beads), up to chain-of-10 (100 beads). Arrow labels show the square values. Child counts beads or arranges chains.',
    key_materials: ['colored bead chains (1²-10²)', 'arrow label cards', 'distinctly colored chain'],
    confusion_pairs: ['ma_long_chains'],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_long_chains',
    name: 'Long Bead Chains (Cubes)',
    area_key: 'mathematics',
    category: 'Linear Counting (Bead Chains)',
    visual_description: 'Nine colored bead chains representing cubes: chain-of-2 (8 beads), chain-of-3 (27 beads), chain-of-4 (64 beads), up to chain-of-10 (1000 beads). Chains are very long and coiled in containers. Arrow labels mark cubic values.',
    key_materials: ['colored bead chains (1³-10³)', 'arrow label cards', 'storage containers'],
    confusion_pairs: ['ma_short_chains'],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_bead_cabinet',
    name: 'Bead Cabinet',
    area_key: 'mathematics',
    category: 'Linear Counting (Bead Chains)',
    visual_description: 'Wooden cabinet with multiple drawers and compartments storing all short and long bead chains, golden bead materials, and color-coded cards. Organized storage showing the complete bead system.',
    key_materials: ['wooden cabinet with drawers', 'all bead materials organized'],
    confusion_pairs: [],
    difficulty: 'medium',
  },

  // === ma_memorization (Memorization of Math Facts) ===
  {
    work_key: 'ma_addition_snake_game',
    name: 'Addition Snake Game',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'Colored bead bars are arranged in a line and continuously combined to make sums, trading 10 beads for golden ten-bars. A black and white bead stair shows the running total. Child is practicing addition and making tens.',
    key_materials: ['colored bead bars', 'black and white bead stair', 'golden ten-bars', 'notched cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_subtraction_snake_game',
    name: 'Subtraction Snake Game',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'Colored bead bars are placed with gray bead bars of the same length subtracted from them, working across multiple bars in sequence. Child is practicing subtraction with physical materials.',
    key_materials: ['colored bead bars', 'gray bead bars', 'black and white bead stair'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_addition_strip_board',
    name: 'Addition Strip Board',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'Wooden board with a fixed red strip (addend 1-9) and sliding blue strips (addend 1-9) to show all addition combinations. Child is working through the board, finding sums and recording them.',
    key_materials: ['wooden board with strips', 'blue and red strips', 'addition tables booklet'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_addition_charts',
    name: 'Addition Charts (Finger Charts)',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'Series of charts (1-6) showing progressive abstraction of addition facts: Chart 1 shows all answers, Chart 2-3 have blank spaces for answers, Chart 4-6 show only equations. Child points to answers or fills in missing sums.',
    key_materials: ['addition charts 1-6', 'progressive abstraction'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_subtraction_strip_board',
    name: 'Subtraction Strip Board',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'Wooden board with a fixed minuend and sliding subtrahend strips showing all subtraction combinations. Child is working through combinations and recording facts.',
    key_materials: ['wooden board with strips', 'subtraction tables booklet'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_subtraction_charts',
    name: 'Subtraction Charts',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'Charts 1-4 showing progressive abstraction of subtraction facts, from all answers shown to completely blank for mental recall.',
    key_materials: ['subtraction charts 1-4'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_multiplication_bead_board',
    name: 'Multiplication Bead Board',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'Wooden board with 9 columns and color-coded rows for multiplier and multiplicand. Red beads are placed in rows to show multiplication, totaled at the bottom. Child explores all multiplication combinations.',
    key_materials: ['wooden board with columns', 'red beads', 'numeral cards', 'red disc for marking'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_multiplication_charts',
    name: 'Multiplication Charts',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'Charts 1-5 showing multiplication facts with progressive abstraction from complete table to blank for mental recall.',
    key_materials: ['multiplication charts 1-5'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_unit_division_board',
    name: 'Unit Division Board',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'Wooden board with rows and columns for division facts. Green beads are distributed equally among green skittles (divisor markers). Child records quotients.',
    key_materials: ['wooden board with columns', 'green beads', 'green skittles (divisors)', 'numeral cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_division_charts',
    name: 'Division Charts',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'Charts 1-3 showing division facts with progressive abstraction from complete table to blank for mental recall.',
    key_materials: ['division charts 1-3'],
    confusion_pairs: [],
    difficulty: 'medium',
  },

  // === ma_operations_abstract (Passage to Abstraction) ===
  {
    work_key: 'ma_stamp_game',
    name: 'Stamp Game',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'Wooden box containing color-coded stamp sets: gold squares (units), green bars (tens), blue bars (hundreds), red cubes (thousands). Child uses stamps to represent numbers and perform all four operations, exchanging stamps when needed.',
    key_materials: ['color-coded stamps (gold/green/blue/red)', 'skittles for division'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_dot_game',
    name: 'Dot Game',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'Child is drawing dots on paper in color-coded groups (gold dots for units, green for tens, blue for hundreds, red for thousands) to represent numbers and perform operations, gradually transitioning from dots to numerals.',
    key_materials: ['dotted paper', 'colored pencils (gold/green/blue/red)'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_small_bead_frame',
    name: 'Small Bead Frame',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'Abacus-style frame with 4 horizontal wires: bottom wire (units/1s), second (tens/10s), third (hundreds/100s), top (thousands/1000s). Beads slide left and right to form numbers. Child performs all four operations.',
    key_materials: ['wooden abacus frame (4 wires)', 'beads on wires'],
    confusion_pairs: ['ma_large_bead_frame'],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_large_bead_frame',
    name: 'Large Bead Frame',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'Extended abacus frame with 7 wires: representing units through millions. Beads slide to form large numbers. Child performs complex operations with large quantities.',
    key_materials: ['wooden abacus frame (7 wires)', 'beads on wires'],
    confusion_pairs: ['ma_small_bead_frame'],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_checkerboard',
    name: 'Checkerboard (Multiplication)',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'Wooden checkerboard with 9×9 grid of colored squares. Colored bead bars and golden beads are placed to show multi-digit multiplication, with partial products in specific color-coded columns.',
    key_materials: ['wooden checkerboard (9×9 grid)', 'colored bead bars', 'golden beads', 'number tiles'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_racks_tubes',
    name: 'Racks and Tubes (Long Division)',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'Racks holding upright test tubes with beads inside. Child divides quantities by removing beads in equal groups (represented by skittles), distributing the beads among tubes to show long division.',
    key_materials: ['racks with test tubes', 'beads', 'skittles (divisor markers)'],
    confusion_pairs: [],
    difficulty: 'hard',
  },

  // === ma_fractions (Fractions) ===
  {
    work_key: 'ma_fraction_circles',
    name: 'Fraction Insets (Metal or Plastic)',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'Set of metal or plastic circle frames with insets divided into equal parts: 1 whole, 2 halves, 3 thirds, 4 fourths, up to 10 tenths. Each piece is distinct and colored. Child is fitting pieces or discovering equivalences.',
    key_materials: ['circular insets (1/1 through 1/10)', 'metal or plastic frames'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_fraction_addition',
    name: 'Fraction Addition',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'Child is using fraction insets to add fractions with the same or different denominators, placing pieces together to discover sums, finding common denominators.',
    key_materials: ['fraction insets', 'paper for recording'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_fraction_subtraction',
    name: 'Fraction Subtraction',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'Child is using fraction insets to subtract fractions, removing pieces to show differences, working with same and different denominators.',
    key_materials: ['fraction insets', 'paper for recording'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_fraction_multiplication',
    name: 'Fraction Multiplication',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'Child is multiplying fractions by whole numbers and by other fractions using insets, showing the product as a fraction of a fraction.',
    key_materials: ['fraction insets', 'paper for recording'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_fraction_division',
    name: 'Fraction Division',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'Child is dividing fractions using insets, showing how many times one fraction fits into another.',
    key_materials: ['fraction insets', 'paper for recording'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_fraction_skittles',
    name: 'Fraction Skittles',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'Sets of small bowling pins (skittles) in different quantities representing fractions (e.g., 3 skittles out of 9 total = 3/9 = 1/3). Child is discovering the connection between division and fractions.',
    key_materials: ['fraction skittles (various sets)'],
    confusion_pairs: [],
    difficulty: 'hard',
  },

  // === ma_geometry_intro (Introduction to Geometry) ===
  {
    work_key: 'ma_geometry_sticks',
    name: 'Geometry Sticks',
    area_key: 'mathematics',
    category: 'Introduction to Geometry',
    visual_description: 'Wooden or bamboo sticks of various lengths and colors organized in a box. Child is constructing geometric shapes: triangles, quadrilaterals, pentagons, creating closed figures and counting vertices/sides.',
    key_materials: ['colored wooden sticks (various lengths)', 'storage box'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_classified_nomenclature',
    name: 'Geometry Nomenclature',
    area_key: 'mathematics',
    category: 'Introduction to Geometry',
    visual_description: 'Cards with geometry vocabulary showing lines (straight, curved, perpendicular, parallel), angles (acute, obtuse, right), triangles (scalene, isosceles, equilateral), and quadrilaterals. Child is reading labels and matching to illustrations.',
    key_materials: ['nomenclature cards with illustrations and labels'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_area_introduction',
    name: 'Introduction to Area',
    area_key: 'mathematics',
    category: 'Introduction to Geometry',
    visual_description: 'Yellow wooden triangles of a standard size arranged to cover geometric shapes, showing that area can be measured by counting how many triangles fit. Child is finding the area of rectangles, triangles, and other polygons.',
    key_materials: ['yellow triangles (standard size)', 'geometric insets or shapes'],
    confusion_pairs: [],
    difficulty: 'medium',
  },

  // === ma_time_money (Time and Money) ===
  {
    work_key: 'ma_clock',
    name: 'Clock Work',
    area_key: 'mathematics',
    category: 'Time and Money',
    visual_description: 'Learning clock with movable hour and minute hands. Time cards show different times. Child is setting the clock hands to match times or reading the time shown.',
    key_materials: ['learning clock (plastic or wooden)', 'time cards'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_money',
    name: 'Money Work',
    area_key: 'mathematics',
    category: 'Time and Money',
    visual_description: 'Play coins or real coins of various denominations arranged for practice. Price tags and shop materials for role-play. Child is recognizing coins, counting mixed amounts, and making change.',
    key_materials: ['play coins or real coins', 'price tags', 'shop materials'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_calendar',
    name: 'Calendar Work',
    area_key: 'mathematics',
    category: 'Time and Money',
    visual_description: 'Large calendar with day, week, and month labels. Date cards to place. Child is identifying days of the week, months of the year, and finding specific dates on the calendar.',
    key_materials: ['calendar board', 'date cards', 'day/month labels'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
];
