import type { WorkSignature } from './work-signatures';

export const LANGUAGE_SIGNATURES: WorkSignature[] = [
  // ===== ORAL LANGUAGE DEVELOPMENT =====
  {
    work_key: "language_enrichment_vocabulary",
    name: "Vocabulary Enrichment",
    area_key: "language",
    category: "Oral Language Development",
    visual_description: "Real classroom objects (scissors, pencil, eraser, paper, cup, spoon, fork) and color photographs of familiar items. Child picks object or photo, teacher names it aloud while child listens and repeats. Visual shows bright, clear, isolated OBJECTS on simple backgrounds—not drawings. Objects are everyday, easily recognized items from classroom. Child's hands touching/holding object while speaking the word. NOT diagrams or abstract symbols.",
    key_materials: ["Real objects", "Photographs", "Picture books"],
    difficulty: "easy",
  },
  {
    work_key: "language_classified_cards",
    name: "Classified Cards (Nomenclature Cards)",
    area_key: "language",
    category: "Oral Language Development",
    visual_description: "Laminated picture cards organized into categories (Animals: dog, cat, bird, fish; Vehicles: car, bus, truck, train; Clothing: shirt, pants, hat, shoes). Each card shows ONE clear color illustration on white background. Cards are typically 2x3 inches, arranged in neat stacks or rows by category. Child sorts cards into category piles, then names each picture. Images are realistic illustrations, NOT photographs. Bright, vibrant colors. Child's fingers pointing to or sorting individual cards. NOT mixed with other materials.",
    key_materials: ["Classified card sets", "Baskets or boxes for sorting"],
    difficulty: "easy",
  },
  {
    work_key: "language_object_picture_matching",
    name: "Object to Picture Matching",
    area_key: "language",
    category: "Oral Language Development",
    visual_description: "Miniature objects (tiny ceramic or plastic animals, vehicles, household items) arranged on a tray alongside matching picture cards. Objects are 1-2 inches tall, realistic miniatures. Picture cards show the same objects as clear illustrations. Child matches each 3D object to its 2D picture representation. On white surface, clear spatial separation showing object and picture paired together. Bright lighting showing object detail. Child's hand reaching to match objects to pictures. NOT large full-size objects.",
    key_materials: ["Miniature objects", "Picture cards"],
    difficulty: "easy",
  },
  {
    work_key: "language_sound_games",
    name: "Sound Games (I Spy)",
    area_key: "language",
    category: "Oral Language Development",
    visual_description: "Collection of small objects (muffin, apple, bear, dog, cat, fan, sun, pen, man, rat, pig) in a basket or on a tray. Teacher says 'I spy something that begins with /m/' and child finds object. Objects are realistic miniatures or clear photographs. Child's fingers pointing to objects while saying initial sound. Visual shows classroom setting with basket of sound objects visible. NOT abstract symbols or letters on paper.",
    key_materials: ["Objects with distinct initial/ending sounds", "Sound baskets", "Elkonin boxes", "Counters/chips"],
    difficulty: "easy",
  },
  {
    work_key: "language_rhyming",
    name: "Rhyming Activities",
    area_key: "language",
    category: "Oral Language Development",
    visual_description: "Cards or picture objects showing rhyming pairs (cat-hat, dog-log, sun-bun, moon-spoon). Each picture is clear, bright illustration of a familiar object. Rhyming object sets (real miniatures or picture cards) arranged so child can match rhyming pairs. Child holds two cards that rhyme (bat, cat) and says them aloud. Visual shows cards lying flat or standing in pairs, with child's hands selecting matching rhymes. Pictures are simple, single-object illustrations on white background. NOT abstract phonetic symbols.",
    key_materials: ["Rhyming card sets", "Rhyming objects"],
    difficulty: "easy",
  },
  {
    work_key: "language_storytelling",
    name: "Storytelling and Sequencing",
    area_key: "language",
    category: "Oral Language Development",
    visual_description: "Sequence cards (4-6 cards) showing story steps: child waking up, eating breakfast, getting dressed, going to school. Each card is 3x4 inches with clear illustration showing action in order. Cards may include felt board characters or props. Child arranges cards in correct order, then retells story. Visual shows cards laid out in sequence on flat surface (table or floor), with child pointing to each card while narrating. Bright, simple illustrations. NOT photographs, but clear cartoon-style drawings.",
    key_materials: ["Sequence cards", "Story props", "Felt board"],
    difficulty: "easy",
  },
  {
    work_key: "language_poems_songs",
    name: "Poems, Songs, and Fingerplays",
    area_key: "language",
    category: "Oral Language Development",
    visual_description: "Poster or chart showing poem or song lyrics in large, clear print (often with simple illustrations). Paper or board format, text visible from classroom distance. Teacher and children pointing to words while singing or reciting. Visual shows group of children sitting or standing together, some with hands up doing fingerplay motions (touching fingers to forehead, clapping), facing the chart. Bright poster with readable text and colorful borders. NOT just children's faces—show the CHART and children interacting with it.",
    key_materials: ["Song charts", "Poetry posters"],
    difficulty: "easy",
  },
  {
    work_key: "language_conversation",
    name: "Conversation and Discussion",
    area_key: "language",
    category: "Oral Language Development",
    visual_description: "Small group of 2-4 children sitting in chairs or on carpet in circle formation, facing each other. Teacher or adult seated at equal level moderating. NO table needed. Children are talking, some with hands gesturing expressively. Visual is intimate, showing faces and body language of engaged conversation. Focus is on child's mouths moving and hand gestures. Background is classroom wall or neutral. NOT formal presentation, NOT large group—this is intimate peer discussion.",
    key_materials: ["Discussion prompts", "Conversation starters"],
    difficulty: "easy",
  },

  // ===== WRITING PREPARATION =====
  {
    work_key: "language_metal_insets",
    name: "Metal Insets",
    area_key: "language",
    category: "Writing Preparation",
    visual_description: "SET of 10 geometric METAL frames (circle, square, triangle, rectangle, oval, diamond, pentagon, hexagon, star, trapezoid) in pink/red metal. Each inset is a brass or steel frame with matching cut-out piece. Child traces around metal frame edge with COLORED PENCIL, then traces inset piece. On white paper, you see child's colored pencil lines forming geometric shape outlines and fill patterns (horizontal, vertical, diagonal). Metal frames are shiny, 14cm square. Child's hand holding pencil over frame, concentrating on control. NOT fuzzy or overlapping lines. NOT sandpaper letters.",
    key_materials: ["Metal insets (10 shapes)", "Colored pencils", "Inset paper", "Pencil holder"],
    confusion_pairs: ["sensorial_geometric_cabinet"],
    difficulty: "easy",
  },
  {
    work_key: "language_sandpaper_letters",
    name: "Sandpaper Letters",
    area_key: "language",
    category: "Writing Preparation",
    visual_description: "Individual letter mounted on wooden or cardboard base (approx 6x8 inches). LETTER SHAPE is TEXTURED—made of rough SANDPAPER (NOT smooth). Pink/red board for consonants, blue board for vowels. Child traces letter outline with fingertips, feeling the sandpaper texture guide the correct letter formation path. Close-up shows child's index and middle finger tracing ROUGH TEXTURE of letter. Letter is lowercase cursive (c, m, a, t, s, r). Sandpaper contrast visible against smooth painted board. NOT looking at letter, but FEELING it with eyes sometimes closed. NOT sandpaper numerals (those show numbers not letters).",
    key_materials: ["Sandpaper letters (lowercase)", "Wooden or cardboard bases"],
    confusion_pairs: ["math_sandpaper_numerals"],
    difficulty: "easy",
  },
  {
    work_key: "language_sand_tray",
    name: "Sand Tray Writing",
    area_key: "language",
    category: "Writing Preparation",
    visual_description: "Wooden tray (approx 12x18 inches) filled with smooth, fine COLORED SAND (often blue, tan, or white). Child drags finger or small stick through sand to form letter shapes. SAND TRACKS are clearly visible—dark lines against lighter sand surface. Close-up shows child's fingers drawing LARGE letter in sand, with sand displacement creating clear letter outline. Tray sits on table at child's working height. Multiple letter attempts visible in sand. Smooth, flowing sand with no water. NOT a regular writing exercise on paper.",
    key_materials: ["Sand tray with colored sand", "Tracing tools"],
    difficulty: "easy",
  },
  {
    work_key: "language_chalkboard_writing",
    name: "Chalkboard Writing",
    area_key: "language",
    category: "Writing Preparation",
    visual_description: "Small wooden or slate CHALKBOARD (2x3 feet) mounted at child's shoulder height on wall or easel. Child holds white or colored CHALK and writes LARGE letters (8 inches tall or larger). Chalk marks visible as white lines on black surface. Child's whole arm extended, drawing from shoulder, NOT just fingers. Large motor movement visible. Chalkboard eraser hanging nearby. NOT tiny pencil writing—this is LARGE, VISIBLE, FULL-ARM writing on a vertical surface.",
    key_materials: ["Chalkboard", "Chalk", "Eraser"],
    difficulty: "easy",
  },
  {
    work_key: "language_moveable_alphabet",
    name: "Moveable Alphabet",
    area_key: "language",
    category: "Writing Preparation",
    visual_description: "Large wooden box with 26 compartments containing cut-out PLASTIC or WOODEN letters. Blue CONSONANTS, red VOWELS. Letters are approx 2 inches tall, lowercase cursive. Child pulls out letters and arranges them on flat surface to spell words: 'CAT', 'DOG'. Visible contrast: BLUE consonants and RED vowels placed in sequence left-to-right on mat or table. Child's hands arranging individual letter pieces. Letters are clearly readable, properly spaced. NOT handwritten—these are PHYSICAL LETTER OBJECTS being arranged. NOT sandpaper letters (these are loose, moveable pieces).",
    key_materials: ["Large moveable alphabet (blue consonants, red vowels)", "Trays", "Work mat"],
    confusion_pairs: ["language_sandpaper_letters"],
    difficulty: "medium",
  },
  {
    work_key: "language_handwriting_paper",
    name: "Handwriting on Paper",
    area_key: "language",
    category: "Writing Preparation",
    visual_description: "Lined handwriting paper (4 lines: top solid, middle dashed, bottom solid, baseline) showing child's HANDWRITTEN letters sitting on the baseline. Letters are small, proper size for primary handwriting. Paper shows proper spacing between letters and words. Child's hand holding pencil in tripod grip (thumb and two fingers), writing individual letters or simple words. Pencil is sharpened, standard #2 pencil on lined paper. NOT crayon or marker. NOT chalkboard or sand tray.",
    key_materials: ["Lined handwriting paper", "Pencils", "Letter formation cards"],
    difficulty: "medium",
  },
  {
    work_key: "language_creative_writing",
    name: "Creative Writing",
    area_key: "language",
    category: "Writing Preparation",
    visual_description: "Blank writing journal or paper with child's HANDWRITTEN original text (sometimes with illustration above). Paper shows pencil writing forming sentences. Lines show child's own composition, NOT copying from a card. Handwriting is legible, spacing is consistent. May show teacher's light pencil markings for correction. This is CHILD-AUTHORED writing on paper, not dictation or copying.",
    key_materials: ["Writing paper", "Journals", "Writing prompts"],
    difficulty: "medium",
  },

  // ===== READING =====
  {
    work_key: "language_pink_object_box",
    name: "Pink Object Box",
    area_key: "language",
    category: "Reading",
    visual_description: "Wooden box containing 20-30 miniature OBJECTS (cat, dog, fan, bat, mop, pot, bed, pan, rat, pig, sun, hat, mat, pin, pen). Alongside each object is a small LABEL CARD with CVC word written in lowercase (c-a-t, d-o-g, f-a-n). Child picks object, reads label card, and confirms match. On surface you see miniature objects arranged in rows with small label cards next to each. Objects are realistic miniatures (ceramic or plastic). Labels are clean, legible, black lowercase text on white card stock. NOT picture cards—these are 3D OBJECTS with word labels. NOT blue or green series.",
    key_materials: ["Pink object box with miniatures", "CVC word labels"],
    confusion_pairs: ["language_blue_object_box", "language_green_object_box"],
    difficulty: "easy",
  },
  {
    work_key: "language_pink_series",
    name: "Pink Series (CVC Words)",
    area_key: "language",
    category: "Reading",
    visual_description: "PINK-BOUND reading books or card decks featuring CVC (consonant-vowel-consonant) words: cat, dog, bat, mat, pig, sit, hop, run. Materials include picture-word cards, word-only cards, phrase cards ('the cat'), sentence cards ('The cat sat.'), and small booklets. Each book/deck has PINK spine or cover. Child reading text aloud while following with finger. Simple illustrations of CVC objects. Text is lowercase, clearly printed. NOT blue or green series. Pink = simplest phonetic level.",
    key_materials: ["Pink series materials: picture cards, word cards, phrases, sentences, booklets"],
    confusion_pairs: ["language_blue_series", "language_green_series"],
    difficulty: "easy",
  },
  {
    work_key: "language_blue_object_box",
    name: "Blue Object Box",
    area_key: "language",
    category: "Reading",
    visual_description: "Wooden box containing 20-30 miniature OBJECTS matching consonant BLEND words (clock, block, flag, plant, star, step, stop, spider, snail, skate, slip, snap). Alongside each object is a LABEL CARD with BLEND WORD in lowercase (c-l-o-c-k, f-l-a-g). Child picks object, reads label identifying the initial blend sound. Miniature objects and small label cards with BLEND patterns (CL, BL, FL, ST, SN, SP). Objects are realistic miniatures. BLUE-themed box and materials. NOT pink series (those are CVC). NOT green series (those are phonograms).",
    key_materials: ["Blue object box with miniatures", "Blend word labels"],
    confusion_pairs: ["language_pink_object_box", "language_green_object_box"],
    difficulty: "medium",
  },
  {
    work_key: "language_blue_series",
    name: "Blue Series (Blends)",
    area_key: "language",
    category: "Reading",
    visual_description: "BLUE-BOUND reading books or card decks featuring words with consonant BLENDS: black, block, flag, plant, star, stop, spider, sleep, green, smile, snow, fly. Materials include picture-word cards, word-only cards, phrases, sentences, and small booklets. Each book/deck has BLUE spine or cover. Child reading blend words aloud. Blend consonant clusters (bl, cl, fl, st, sn, sp) shown prominently. NOT pink series (CVC). NOT green series (phonograms). Blue = intermediate phonetic level with consonant blends.",
    key_materials: ["Blue series materials: picture cards, word cards, phrases, sentences, booklets"],
    confusion_pairs: ["language_pink_series", "language_green_series"],
    difficulty: "medium",
  },
  {
    work_key: "language_phonogram_intro",
    name: "Phonogram Introduction",
    area_key: "language",
    category: "Reading",
    visual_description: "SANDPAPER PHONOGRAMS or cardboard cards showing two-letter combinations that make one NEW SOUND (ee, oo, sh, ch, th, wh, ai, ay, ea, oa, ar, er, ou, ow, oi, oy, aw). Each phonogram is 2-3 inches tall, may have TEXTURED letters (sandpaper) or plain printed on green cards. Child traces phonogram outline and says the SOUND it makes. Multiple phonograms visible on tray. NOT single sandpaper letters—these are DOUBLE-LETTER combinations. NOT moveable alphabet.",
    key_materials: ["Sandpaper phonograms", "Phonogram cards"],
    confusion_pairs: ["language_sandpaper_letters"],
    difficulty: "medium",
  },
  {
    work_key: "language_green_object_box",
    name: "Green Object Box",
    area_key: "language",
    category: "Reading",
    visual_description: "Wooden box containing 20-30 miniature OBJECTS matching PHONOGRAM words (sheep, tree, moon, rain, boat, star, spoon, book, shell, chain, fish, queen, foot, mouse, owl, boy, tail, key). Alongside each object is a LABEL CARD with PHONOGRAM WORD in lowercase (sh-ee-p, tr-ee, m-oo-n, r-ai-n). Child picks object, reads label using phonogram knowledge. GREEN-themed box and materials. Labels show phonogram COMBINATIONS clearly. NOT pink (CVC) or blue (blends). Green = advanced phonetic level with phonograms.",
    key_materials: ["Green object box with miniatures", "Phonogram word labels"],
    confusion_pairs: ["language_pink_object_box", "language_blue_object_box"],
    difficulty: "medium",
  },
  {
    work_key: "language_green_series",
    name: "Green Series (Phonograms)",
    area_key: "language",
    category: "Reading",
    visual_description: "GREEN-BOUND reading books or card decks featuring words with PHONOGRAMS: sheep, tree, boat, rain, moon, shell, chain, fish, spoon, book, queen, owl, tail, snow, fly. Materials include picture-word cards, word-only cards, phrases, sentences, and small booklets. Each book/deck has GREEN spine or cover. Phonogram letter combinations (sh, ee, oa, ai) are often highlighted or color-coded. NOT pink or blue series. Green = most advanced phonetic reading level.",
    key_materials: ["Green series materials: picture cards, word cards, phrases, sentences, booklets"],
    confusion_pairs: ["language_pink_series", "language_blue_series"],
    difficulty: "medium",
  },
  {
    work_key: "language_puzzle_words",
    name: "Puzzle Words (Sight Words)",
    area_key: "language",
    category: "Reading",
    visual_description: "Cards or booklets featuring NON-PHONETIC high-frequency words: the, a, is, to, and, was, were, said, have, do, does, water. Words printed on card stock in lowercase. Words do NOT follow phonetic rules—child must memorize them visually. Materials may include PUZZLE-CUT shapes (word pieces interlock, hence 'puzzle' words). Child reading sight words from cards. NOT phonetic reading—these are SIGHT WORDS learned by visual memory. NOT moveable alphabet.",
    key_materials: ["Puzzle word cards", "Puzzle word booklets"],
    difficulty: "medium",
  },
  {
    work_key: "language_reading_analysis",
    name: "Reading Analysis",
    area_key: "language",
    category: "Reading",
    visual_description: "Child reading a complex word and ANALYZING which phonograms are present. May use phonogram chart on wall showing all learned phonograms, or word cards with phonograms COLOR-CODED or highlighted. Child points to chart while identifying phonogram components in words. Analysis shows DECOMPOSITION—breaking words into phonogram patterns. NOT simple reading—this is ANALYTICAL reading with explicit phonogram identification.",
    key_materials: ["Reading analysis materials", "Phonogram charts"],
    difficulty: "hard",
  },
  {
    work_key: "language_reading_classification",
    name: "Reading Classification",
    area_key: "language",
    category: "Reading",
    visual_description: "Cards showing words to be CLASSIFIED by category while reading. Cards labeled 'ANIMALS', 'FOOD', 'CLOTHING', and child sorts word cards into correct categories by reading and understanding meaning. Visual shows sorted word cards in neat piles by category on table. Multiple categories visible with labels. Classification shows READING COMPREHENSION—understanding word meaning AND category membership. NOT just phonetic decoding.",
    key_materials: ["Classification reading cards", "Category labels"],
    difficulty: "hard",
  },
  {
    work_key: "language_command_cards",
    name: "Command Cards (Action Reading)",
    area_key: "language",
    category: "Reading",
    visual_description: "Cards showing IMPERATIVE sentences (commands) that child reads and PERFORMS: 'Stand up', 'Hop on one foot', 'Touch your nose', 'Clap your hands three times', 'Walk to the door'. Text is printed in lowercase on white card stock (3x5 inches). Child holds card, reads silently or aloud, then PERFORMS the action. Visual shows child MID-ACTION after reading: jumping, hopping, clapping, walking. Card visible in child's hand or on table. NOT grammar boxes or sentence analysis—these are simple ACTION commands.",
    key_materials: ["Command cards at various levels"],
    difficulty: "easy",
  },
  {
    work_key: "language_interpretive_reading",
    name: "Interpretive Reading",
    area_key: "language",
    category: "Reading",
    visual_description: "Child reading aloud from a POETRY book or SHORT STORY with EXPRESSION and EMOTION. Reader's facial expression and voice inflection change with text meaning. May show child reading to small audience. Visual shows open book, child's engaged expression, hand gestures matching text mood. NOT monotone reading—this is EXPRESSIVE, INTERPRETIVE reading with emotional understanding visible. NOT silent reading.",
    key_materials: ["Poetry", "Short stories", "Drama scripts"],
    difficulty: "hard",
  },
  {
    work_key: "language_silent_reading",
    name: "Silent Reading",
    area_key: "language",
    category: "Reading",
    visual_description: "Child sitting at table or in reading corner with open CHAPTER BOOK or leveled READER, eyes scanning pages silently (no voice), hand occasionally turning page. Quiet environment. Child is ALONE with book—not being taught, not answering questions, just reading independently. This is INDEPENDENT READING, not guided reading or read-aloud. NOT interpretive reading (that's performed aloud).",
    key_materials: ["Leveled books", "Book corner"],
    difficulty: "hard",
  },

  // ===== GRAMMAR =====
  {
    work_key: "language_noun_intro",
    name: "Introduction to the Noun",
    area_key: "language",
    category: "Grammar",
    visual_description: "Teacher or child holding real objects (pencil, book, desk, chair) with BLACK TRIANGLE SYMBOL labeled 'NOUN'. Child sorting cards into NOUN and NON-NOUN categories. Black solid equilateral triangle = Montessori NOUN symbol. Word cards with black triangles placed above noun words. Multiple objects or cards visible. NOT verb circles or adjective triangles—specifically BLACK TRIANGLE for nouns.",
    key_materials: ["Noun lesson materials", "Black triangle symbol", "Objects and labels"],
    confusion_pairs: ["language_grammar_boxes"],
    difficulty: "medium",
  },
  {
    work_key: "language_article_intro",
    name: "Introduction to the Article",
    area_key: "language",
    category: "Grammar",
    visual_description: "Articles (a, an, the) shown on LIGHT BLUE small TRIANGLE SYMBOL. Child pointing to object while saying article + noun: 'a book', 'an apple', 'the chair'. Word cards with light blue triangles placed above article words. Simple sentence structure: 'ARTICLE + NOUN'. NOT noun triangle (that's black and larger). NOT adjective (dark blue, medium triangle).",
    key_materials: ["Article materials", "Light blue triangle symbol"],
    confusion_pairs: ["language_noun_intro", "language_adjective_intro"],
    difficulty: "medium",
  },
  {
    work_key: "language_adjective_intro",
    name: "Introduction to the Adjective",
    area_key: "language",
    category: "Grammar",
    visual_description: "Child playing 'DETECTIVE GAME': 'Which one? The BLUE pencil!' Adjectives shown on MEDIUM DARK BLUE TRIANGLE SYMBOL. Multiple similar objects (red/blue/yellow pencils; big/small books) and child choosing based on ADJECTIVE described. Word cards with dark blue triangles. Simple phrase: 'THE [ADJECTIVE] [NOUN]'. NOT noun (black triangle). NOT article (light blue, smaller). Dark blue medium triangle = ADJECTIVE.",
    key_materials: ["Adjective materials", "Medium dark blue triangle", "Detective adjective game"],
    confusion_pairs: ["language_noun_intro", "language_article_intro"],
    difficulty: "medium",
  },
  {
    work_key: "language_verb_intro",
    name: "Introduction to the Verb",
    area_key: "language",
    category: "Grammar",
    visual_description: "Child reading COMMAND CARD and PERFORMING action: RUNNING, HOPPING, SITTING, CLAPPING, JUMPING. Verbs shown on LARGE RED CIRCLE SYMBOL (sphere). Child's body in motion performing action. Action card visible with red circle above verb word. Multiple action examples shown. Classroom space visible for movement. LARGE RED CIRCLE = verb symbol. NOT triangle (those are nouns/articles/adjectives). NOT command cards alone (this teaches the grammar SYMBOL).",
    key_materials: ["Verb materials", "Large red circle symbol", "Action cards"],
    confusion_pairs: ["language_command_cards"],
    difficulty: "medium",
  },
  {
    work_key: "language_adverb_intro",
    name: "Introduction to the Adverb",
    area_key: "language",
    category: "Grammar",
    visual_description: "Child demonstrating ADVERB modifying VERB: 'Walk SLOWLY' (exaggerated slow steps), 'Walk QUICKLY' (fast steps), 'Walk HAPPILY' (bouncy steps with smile). Adverbs shown on SMALL ORANGE CIRCLE SYMBOL. Child performing SAME ACTION (walking) in different ADVERB WAYS. Body language and expression change with adverb. SMALL ORANGE CIRCLE = adverb. NOT large red circle (that's verb). NOT triangle symbols.",
    key_materials: ["Adverb materials", "Small orange circle", "Adverb game"],
    confusion_pairs: ["language_verb_intro"],
    difficulty: "medium",
  },
  {
    work_key: "language_pronoun_intro",
    name: "Introduction to the Pronoun",
    area_key: "language",
    category: "Grammar",
    visual_description: "Child saying: 'Maria has a pencil. SHE has a pencil.' Pronouns shown on PURPLE/VIOLET TRIANGLE SYMBOL (like noun but purple). Child pointing to self saying 'I', to friend saying 'You', to child across room saying 'He/She'. Word cards with purple triangles. Pronouns REPLACE nouns while meaning stays same. PURPLE TRIANGLE = pronoun. NOT black triangle (that's noun). NOT other colored triangles.",
    key_materials: ["Pronoun materials", "Purple/violet triangle"],
    confusion_pairs: ["language_noun_intro"],
    difficulty: "medium",
  },
  {
    work_key: "language_preposition_intro",
    name: "Introduction to the Preposition",
    area_key: "language",
    category: "Grammar",
    visual_description: "Child demonstrating POSITION words with real objects: pencil 'in the box', 'on the table', 'under the chair', 'behind the door'. Prepositions shown on GREEN CRESCENT/BRIDGE SYMBOL. Child's hand and object showing spatial relationship. Multiple position examples visible. GREEN CRESCENT = preposition. NOT circle (verb/adverb). NOT triangle (noun/adjective/article).",
    key_materials: ["Preposition materials", "Green crescent symbol", "Preposition game"],
    difficulty: "medium",
  },
  {
    work_key: "language_conjunction_intro",
    name: "Introduction to the Conjunction",
    area_key: "language",
    category: "Grammar",
    visual_description: "Two SENTENCE CARDS joined with conjunction card in middle: 'The cat is black AND the dog is brown.' Conjunctions shown on PINK RECTANGLE SYMBOL. Complete compound sentence written out showing AND/BUT/OR highlighted. Conjunction connects two independent ideas. PINK RECTANGLE = conjunction. NOT other grammar symbols. Sentence building with physical cards showing conjunction joining two halves.",
    key_materials: ["Conjunction materials", "Pink rectangle symbol"],
    difficulty: "hard",
  },
  {
    work_key: "language_interjection_intro",
    name: "Introduction to the Interjection",
    area_key: "language",
    category: "Grammar",
    visual_description: "Child exclaiming: 'Oh! I found my pencil!' 'Wow! That's amazing!' 'Ouch! That hurt!' Interjections shown on GOLD/YELLOW KEYHOLE SYMBOL. Child's face showing strong EMOTION (surprise, joy, pain, excitement) while saying interjection. Exclamation mark visible. GOLD KEYHOLE = interjection (unique shape, stands alone). NOT other grammar symbols.",
    key_materials: ["Interjection materials", "Gold keyhole symbol"],
    difficulty: "hard",
  },
  {
    work_key: "language_grammar_boxes",
    name: "Grammar Boxes",
    area_key: "language",
    category: "Grammar",
    visual_description: "SET of 8 WOODEN BOXES (Grammar Boxes I-VIII), each containing sentence cards with ONE WORD MISSING. Child fills in missing word from provided word cards. Box I (articles): 'The ___ is red.' Child selects correct word. Sentences make sense only when correct part of speech inserted. Wooden boxes with removable lids, card stock sentence strips and word cards inside. Child reading sentence and selecting correct word. NOT single grammar symbol introduction—this is ANALYTICAL sentence work with multiple boxes.",
    key_materials: ["Grammar boxes I-VIII", "Filling boxes", "Sentence cards", "Word cards"],
    confusion_pairs: ["language_sentence_analysis"],
    difficulty: "hard",
  },
  {
    work_key: "language_sentence_analysis",
    name: "Sentence Analysis",
    area_key: "language",
    category: "Grammar",
    visual_description: "Child reading a SENTENCE and ANALYZING its structure using QUESTION ARROWS: 'WHO is doing it? (subject)' 'WHAT is it doing? (predicate)' 'WHAT is receiving the action? (object)'. Sentence written on card with colored arrows pointing to sentence parts. Chart or paper showing color-coded grammatical functions. NOT grammar boxes (those fill in words). NOT part-of-speech symbols. This is DEEP STRUCTURAL ANALYSIS with arrows and questions.",
    key_materials: ["Sentence analysis charts", "Question arrows", "Sentence strips"],
    confusion_pairs: ["language_grammar_boxes"],
    difficulty: "hard",
  },

  // ===== WORD STUDY =====
  {
    work_key: "language_word_families",
    name: "Word Families",
    area_key: "language",
    category: "Word Study",
    visual_description: "Card set showing WORD FAMILY clusters: AT FAMILY (cat, bat, hat, sat, mat, fat, rat), AN FAMILY (can, fan, pan, ran, man, tan), IG FAMILY (big, dig, fig, jig, pig, rig, wig). Each word on small card or chart format. Child arranges RHYMING WORDS by family. Multiple word cards grouped in family stacks or chart with family names (AT, AN, AP) with words listed under each. Words sharing ending sound/spelling pattern grouped together. NOT rhyming activities (those use objects). NOT phonogram work.",
    key_materials: ["Word family cards", "Word family charts"],
    difficulty: "easy",
  },
  {
    work_key: "language_spelling_rules",
    name: "Spelling Rules",
    area_key: "language",
    category: "Word Study",
    visual_description: "CHART or CARDS showing SPELLING RULES with examples: DOUBLING RULE ('hop' + 'ing' = 'hopping'), SILENT E RULE ('made' drops e = 'making'), Y TO I RULE ('happy' = 'happier'). Color-coded chart listing rules and examples, or card pairs showing BEFORE and AFTER spelling. Child reading rule and applying it to new words. PATTERN RECOGNITION—consistent spelling rule patterns. NOT word families. NOT phonograms.",
    key_materials: ["Spelling rule charts", "Word sorting materials"],
    difficulty: "medium",
  },
  {
    work_key: "language_compound_words",
    name: "Compound Words",
    area_key: "language",
    category: "Word Study",
    visual_description: "Cards showing COMPOUND WORD PARTS that combine: sun + flower = sunflower, rain + bow = rainbow, butter + fly = butterfly, tooth + brush = toothbrush. Two word cards joined by plus sign, then final COMPOUND word. Picture-word cards matching compound to image. Child matching two word parts to create real compound word. COMPOSITION—two smaller words CREATE one larger word. NOT prefixes/suffixes (those modify, not combine equal parts).",
    key_materials: ["Compound word cards", "Matching materials"],
    difficulty: "medium",
  },
  {
    work_key: "language_prefixes_suffixes",
    name: "Prefixes and Suffixes",
    area_key: "language",
    category: "Word Study",
    visual_description: "Cards showing WORD PARTS: PREFIXES (un-, re-, pre-, dis-, in-) and SUFFIXES (-ed, -ing, -er, -est, -ly, -tion). Root word with prefix/suffix cards sliding before/after: 'un' + 'happy' = 'unhappy', 'play' + 'ing' = 'playing'. Possibly color-coded (prefixes one color, roots another, suffixes third). Child building new words by adding parts. MORPHOLOGY—adding word parts CHANGES meaning. NOT compound words (those combine equal words).",
    key_materials: ["Prefix/suffix cards", "Word building materials"],
    difficulty: "hard",
  },
  {
    work_key: "language_synonyms_antonyms",
    name: "Synonyms and Antonyms",
    area_key: "language",
    category: "Word Study",
    visual_description: "Card pairs showing SAME MEANING (synonyms: big/large, happy/joyful) or OPPOSITE MEANING (antonyms: hot/cold, fast/slow, happy/sad). Two word cards placed NEXT TO each other (synonyms) or on OPPOSITE sides (antonyms). Chart with 'SAME' and 'OPPOSITE' columns. Child matching word pairs by semantic relationship. NOT homonyms (those sound the same). NOT word families (those share spelling patterns).",
    key_materials: ["Synonym/antonym cards", "Matching games"],
    difficulty: "medium",
  },
  {
    work_key: "language_homonyms",
    name: "Homonyms",
    area_key: "language",
    category: "Word Study",
    visual_description: "Cards or pictures showing words that SOUND SAME but MEAN DIFFERENT THINGS: to/two/too, their/there/they're, here/hear, see/sea, sun/son, knight/night. Picture cards showing meaning differences (beach ocean = 'sea' vs letter C = 'see'). Child matching homophones to DIFFERENT MEANINGS. One SOUND, multiple MEANINGS shown with illustrations. NOT synonyms/antonyms (those have different sounds). NOT word families.",
    key_materials: ["Homonym cards with pictures"],
    difficulty: "medium",
  },
];
