import type { WorkSignature } from './work-signatures';

export const MATHEMATICS_SIGNATURES: WorkSignature[] = [
  // === Introduction to Numbers (1-10) ===
  {
    work_key: 'ma_number_rods',
    name: 'Number Rods',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Ten wooden rods of graduated lengths arranged in a clear staircase pattern on a mat or table. Each rod is painted with alternating RED and BLUE segments - unit-length bands of solid color - NOT solid red like Red Rods. The shortest rod is about 10cm (representing 1), the longest about 1m (representing 10). A child\'s hands are touching, arranging, or comparing the rods, sometimes holding them vertically to see the height differences.',
    key_materials: ['alternating red and blue wooden rods', 'graduated 10cm to 1m', 'clear staircase arrangement'],
    confusion_pairs: ['se_red_rods'],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_sandpaper_numerals',
    name: 'Sandpaper Numerals',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Light tan or cream-colored wooden tiles, each bearing a single numeral 0-9 made of SANDPAPER adhered to the surface. The sandpaper numerals have a rough, tactile texture visible against the smooth wood background. A child\'s fingertip or hand is tracing the sandpaper numeral, following the direction and shape of the number for muscle memory development.',
    key_materials: ['tan wooden tiles', 'sandpaper numerals 0-9', 'textured tactile surface'],
    confusion_pairs: ['la_sandpaper_letters'],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_number_rods_numerals',
    name: 'Number Rods with Numerals',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Number Rods arranged in their descending staircase pattern on one side, with small printed NUMERAL CARDS (1-10) placed or being placed alongside each rod in a matching exercise. The arrangement creates a clear visual correspondence: 1-unit rod next to card "1", 2-unit rod next to card "2", etc. A child is holding or pointing to cards, making the matches.',
    key_materials: ['number rods in staircase', 'printed numeral cards 1-10', 'alignment showing one-to-one correspondence'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_spindle_box',
    name: 'Spindle Boxes',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Wooden box divided by vertical dividers into 10 compartments labeled 0-9 across the top. Each compartment contains THIN WOODEN SPINDLES (matchstick-like dowels). The child is placing spindles into compartments, with the exact quantity matching the numeral label: 0 spindles in the "0" compartment, 1 in the "1" compartment, etc. Red rubber bands may bundle groups of 5 spindles together.',
    key_materials: ['wooden box with 10 compartments', 'thin wooden spindles (dowels)', 'numerical labels 0-9 at top', 'red rubber bands for bundling'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_cards_counters',
    name: 'Cards and Counters',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Printed numeral cards 1-10 arranged in a row on a mat, each with RED COUNTER DISCS (circular tokens) placed directly below in quantities matching the numeral. The child is arranging counters in neat rows or observing patterns: odd numbers have an unpaired counter in the middle (odd pattern), even numbers pair up evenly.',
    key_materials: ['printed numeral cards 1-10', 'red circular counter discs', 'organized rows of counters'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_memory_game',
    name: 'Memory Game of Numbers',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'A numeral card is shown briefly to the child, then hidden or turned face-down. The child is selecting or fetching a corresponding quantity of small objects (shells, beads, stones, buttons) from a basket to demonstrate counting accuracy FROM MEMORY. The small objects are arranged on the mat showing the counted quantity.',
    key_materials: ['numeral cards 1-10', 'small counting objects (shells/beads/stones)', 'basket for storage', 'mat for display'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_number_puzzles',
    name: 'Number Puzzles and Games',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Wooden puzzle boards or cardboard puzzle cards with numerals and corresponding dot patterns or objects that must be matched or fitted together. The child is inserting puzzle pieces or aligning matching cards to reinforce the connection between numeral symbols and quantities.',
    key_materials: ['wooden or cardboard puzzle pieces', 'numeral and quantity matching', 'puzzle board or assembly cards'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_short_bead_stair',
    name: 'Short Bead Stair',
    area_key: 'mathematics',
    category: 'Introduction to Numbers (1-10)',
    visual_description: 'Nine colored bead bars (multiple beads threaded on a wire or wooden rod) representing quantities 1 through 9, arranged in a clear STAIRCASE pattern descending left to right. Each bar has a DISTINCT COLOR: the 1-bar is red (1 bead), the 2-bar is green (2 beads), the 3-bar is pink (3 beads), etc. The child is counting beads on each bar or arranging them in sequence.',
    key_materials: ['colored bead bars 1-9', 'distinct color per quantity', 'staircase arrangement', 'beads on wire/rod'],
    confusion_pairs: ['se_bead_bars'],
    difficulty: 'easy',
  },

  // === Decimal System ===
  {
    work_key: 'ma_golden_beads_intro',
    name: 'Introduction to Golden Beads',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'FOUR DISTINCT GOLDEN-COLORED BEAD FORMS displayed on a mat or tray: (1) Single UNIT BEADS (tiny individual beads), (2) TEN-BARS or TEN-RODS (10 golden beads strung together in a line forming a rod), (3) HUNDRED-SQUARES (100 beads arranged in a 10×10 flat grid pattern), (4) THOUSAND-CUBES (1000 beads in a large 10×10×10 cubic block). A child is handling, identifying, and naming each category with a guide.',
    key_materials: ['golden unit beads', 'golden ten-bars (10-rod)', 'golden hundred-squares (10×10 grid)', 'golden thousand-cubes (10×10×10)'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_golden_beads_tray',
    name: 'Golden Bead Tray Exercises',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Multiple GOLDEN BEAD MATERIALS (units, tens, hundreds, thousands) displayed on wooden trays or baskets for organization. The child is FETCHING REQUESTED QUANTITIES, arranging them by place value on the tray (thousands on left, hundreds, tens, units on right), and organizing the materials according to instructions from a guide or cards.',
    key_materials: ['golden beads in all four place values', 'wooden trays or baskets', 'organized by denomination'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_large_numeral_cards',
    name: 'Large Numeral Cards',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'COLOR-CODED card sets displayed or being stacked: GREEN cards showing units (1-9), BLUE cards showing tens (10-90), RED cards showing hundreds (100-900), and GREEN cards showing thousands (1000-9000). The cards are SUPERIMPOSED or STACKED with offset to show multi-digit numbers. A child is layering cards to build numbers like 3,452 by stacking 3000+400+50+2.',
    key_materials: ['green unit cards 1-9', 'blue tens cards 10-90', 'red hundreds cards 100-900', 'green thousands cards 1000-9000', 'stacked/superimposed arrangement'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_formation_quantity',
    name: 'Formation of Quantity',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'A child is BUILDING MULTI-DIGIT QUANTITIES with golden beads on a wooden tray. The guide gives a number (e.g., "2,345"), and the child gathers: 2 thousand-cubes, 3 hundred-squares, 4 ten-bars, and 5 unit beads, arranging them on the tray from left to right. Numeral labels may be placed alongside showing the written number.',
    key_materials: ['golden beads in all four categories', 'wooden tray', 'numeral labels or problem cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_formation_symbol',
    name: 'Formation of Symbol',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'LARGE NUMERAL CARDS are being SUPERIMPOSED with careful alignment to build multi-digit numbers written symbolically. A child is layering green (thousands) + red (hundreds) + blue (tens) + green (units) cards with offset to create the visual representation of a number like 4,326, showing the place value system in card form.',
    key_materials: ['large numeral cards (color-coded)', 'superimposed/stacked arrangement', 'place value alignment'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_association_quantity_symbol',
    name: 'Association of Quantity and Symbol',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'GOLDEN BEAD MATERIALS (actual physical beads showing a quantity like 2,345: 2 thousand-cubes, 3 hundred-squares, 4 ten-bars, 5 unit beads) are displayed alongside the corresponding SUPERIMPOSED NUMERAL CARDS showing "2,345". The child is matching concrete materials to abstract symbols, understanding equivalence.',
    key_materials: ['golden beads showing quantity', 'large numeral cards showing symbol', 'side-by-side comparison'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_exchange_game',
    name: 'Exchange Game (Change Game)',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'Golden bead materials are arranged on a tray. A dice is rolled or a numeral card shown to determine how many UNIT BEADS to take. The child gathers that quantity, and whenever 10 units accumulate, they are EXCHANGED for 1 ten-bar. When 10 tens accumulate, they are exchanged for 1 hundred-square. The child is performing these exchanges repeatedly, learning the decimal system.',
    key_materials: ['golden beads in all categories', 'dice or numeral cards', 'tray for organization', 'exchange mechanism'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_golden_beads_addition',
    name: 'Golden Bead Addition',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'TWO QUANTITIES are built with golden beads on separate sections of a tray (e.g., 2,345 + 1,234). The child is COMBINING ALL MATERIALS, gathering them together, then performing EXCHANGES: 10 units→1 ten, 10 tens→1 hundred, 10 hundreds→1 thousand. The final quantity shows the sum with materials organized by place value.',
    key_materials: ['golden beads in all categories', 'problem cards or written problems', 'trays for separate quantities', 'exchange mechanism'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_golden_beads_subtraction',
    name: 'Golden Bead Subtraction',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'The child STARTS with a golden bead quantity (e.g., 3,456) and is REMOVING another quantity (e.g., 1,234). When there aren\'t enough materials in a place value, the child performs REVERSE EXCHANGES (1 ten-bar→10 units) to complete the subtraction. The remaining materials show the difference.',
    key_materials: ['golden beads in all categories', 'problem cards', 'exchange mechanism for breaking down'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_golden_beads_multiplication',
    name: 'Golden Bead Multiplication',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'A child is REPEATING a golden bead quantity multiple times. For example, to multiply 25 × 3, the child builds the quantity 25 (2 ten-bars + 5 units) THREE SEPARATE TIMES on the tray, then gathers all materials together and performs exchanges to find the product (75).',
    key_materials: ['golden beads in all categories', 'problem cards', 'small numeral cards showing multiplier'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_golden_beads_division',
    name: 'Golden Bead Division',
    area_key: 'mathematics',
    category: 'Decimal System',
    visual_description: 'A quantity of golden beads is DISTRIBUTED EQUALLY among multiple groups. Small wooden SKITTLES or dividers represent the divisor (e.g., 3 skittles for dividing by 3). The child is sharing out the materials, starting with larger denominations and performing reverse exchanges as needed. Each group gets an equal share (the quotient).',
    key_materials: ['golden beads in all categories', 'wooden skittles or dividers (divisors)', 'problem cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },

  // === Teens and Tens ===
  {
    work_key: 'ma_teen_board_1',
    name: 'Teen Board 1 (Seguin Board A)',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'WOODEN BOARD with a FIXED GOLDEN TEN-BAR on the left side and ten COLUMNS labeled 1-9 on the right. COLORED BEAD BARS representing 1-9 are placed in sequence in the columns alongside the fixed ten-bar to show numbers 11-19. A child is inserting bead bars or arranging them to demonstrate teen numbers.',
    key_materials: ['wooden board with ten-bar slot', 'golden ten-bar (fixed)', 'colored bead bars 1-9', 'columns for units'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_teen_board_2',
    name: 'Teen Board 2 (Seguin Board B)',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'WOODEN BOARD with columns showing visual placeholders for teen numbers 11-19, but WITHOUT physical bead bars. PRINTED NUMERAL CARDS or WOODEN NUMERAL TILES representing 11-19 are placed in the columns. A child is reading or matching teen number symbols.',
    key_materials: ['wooden board with numeral columns', 'numeral cards/tiles for teens (11-19)', 'visual column structure'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_ten_board_1',
    name: 'Ten Board 1 (Seguin Board C)',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'WOODEN BOARD with columns labeled 10, 20, 30, 40, 50, 60, 70, 80, 90. GOLDEN TEN-BARS are placed in the columns in quantities: 1 ten-bar in the "10" column, 2 in the "20" column, up to 9 in the "90" column. A child is skip-counting by tens using the physical bead bars.',
    key_materials: ['wooden board with ten columns', 'golden ten-bars (1-9 per column)', 'place value labels (10, 20...90)'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_ten_board_2',
    name: 'Ten Board 2 (Seguin Board D)',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'LARGE WOODEN BOARD showing numbers 11-99 arranged in a grid. GOLDEN TEN-BARS and COLORED BEAD BARS are placed in cells to represent all numbers in the range. A child is building numbers like 47 (4 golden tens + 7 colored units) by selecting appropriate materials.',
    key_materials: ['large wooden board (11-99)', 'golden ten-bars', 'colored bead bars 1-9'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_hundred_board',
    name: 'Hundred Board',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'WOODEN BOARD divided into 100 squares arranged in a 10×10 GRID, numbered 1-100. SMALL NUMBERED TILES or WOODEN DISCS are placed in sequence in cells. A child is filling in the board in order or discovering PATTERNS by highlighting every 2nd, 5th, or 10th number, or identifying prime numbers.',
    key_materials: ['wooden 100-square grid board', 'numbered tiles 1-100', 'optional pattern markers'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_hundred_chain',
    name: 'Hundred Chain',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'TEN GOLDEN TEN-BARS connected end-to-end in a single CHAIN forming 100 beads in LINEAR form laid horizontally on the ground or table. PRINTED ARROW LABEL CARDS (1, 10, 20, 30... 100) are placed at intervals along the chain. A child is counting and discovering linear patterns of the hundred.',
    key_materials: ['hundred chain (100 beads in 10 ten-bars)', 'arrow label cards 1-100', 'linear ground layout'],
    confusion_pairs: ['ma_thousand_chain'],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_thousand_chain',
    name: 'Thousand Chain',
    area_key: 'mathematics',
    category: 'Teens and Tens',
    visual_description: 'VERY LONG CHAIN of 1000 GOLDEN BEADS (100 ten-bars connected) laid out on the classroom ground in a large loop or spiral, or displayed in coils in a container. ARROW LABEL CARDS mark major intervals (100, 200, 300... 1000). A child is walking along the chain, counting, and observing the magnitude of 1000.',
    key_materials: ['thousand chain (1000 beads)', 'arrow label cards 1-1000', 'large ground/loop layout', 'storage container for coiling'],
    confusion_pairs: ['ma_hundred_chain'],
    difficulty: 'medium',
  },

  // === Linear Counting (Bead Chains) ===
  {
    work_key: 'ma_short_chains',
    name: 'Short Bead Chains (Squares)',
    area_key: 'mathematics',
    category: 'Linear Counting (Bead Chains)',
    visual_description: 'NINE COLORED BEAD CHAINS arranged in a STAIRCASE pattern, each chain representing a PERFECT SQUARE: 1-chain (1 bead), 2-chain (4 beads), 3-chain (9 beads), 4-chain (16 beads), up to 10-chain (100 beads). Each chain has a DISTINCT COLOR. ARROW LABEL CARDS show the square values (1², 4, 9, 16... 100). A child is handling chains or arranging them.',
    key_materials: ['colored bead chains 1²-10²', 'arrow label cards', 'staircase arrangement', 'distinct color per chain'],
    confusion_pairs: ['ma_long_chains'],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_long_chains',
    name: 'Long Bead Chains (Cubes)',
    area_key: 'mathematics',
    category: 'Linear Counting (Bead Chains)',
    visual_description: 'NINE COLORED BEAD CHAINS representing PERFECT CUBES: 1-chain (1 bead), 2-chain (8 beads), 3-chain (27 beads), up to 10-chain (1000 beads). These chains are VERY LONG and often coiled in STORAGE CONTAINERS. Each chain has a unique color. ARROW LABEL CARDS mark cubic values (1³, 8, 27, 64... 1000). A child is exploring cube numbers.',
    key_materials: ['colored bead chains 1³-10³', 'arrow label cards', 'storage containers for long chains', 'distinct color per chain'],
    confusion_pairs: ['ma_short_chains'],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_bead_cabinet',
    name: 'Bead Cabinet',
    area_key: 'mathematics',
    category: 'Linear Counting (Bead Chains)',
    visual_description: 'WOODEN CABINET with multiple DRAWERS and COMPARTMENTS storing the complete bead system: golden beads (units, tens, hundreds, thousands), colored bead bars, short and long bead chains, hundred chain, thousand chain. The cabinet is a comprehensive storage and organization system showing all bead materials.',
    key_materials: ['wooden cabinet with drawers', 'golden beads (all categories)', 'colored bead bars', 'short and long chains', 'organized compartments'],
    confusion_pairs: [],
    difficulty: 'medium',
  },

  // === Memorization of Math Facts ===
  {
    work_key: 'ma_addition_snake_game',
    name: 'Addition Snake Game',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'COLORED BEAD BARS are laid out in a LINE in various colors (red, green, pink, yellow, etc.), creating a "snake" pattern. The child is continuously COMBINING bars by trading 10 units for 1 golden ten-bar. A BLACK AND WHITE BEAD STAIR runs parallel showing the RUNNING TOTAL. The child is performing addition facts and consolidating understanding of place value through the exchange mechanism.',
    key_materials: ['colored bead bars (assorted colors)', 'black and white bead stair (1-10)', 'golden ten-bars for exchange', 'notched or problem cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_subtraction_snake_game',
    name: 'Subtraction Snake Game',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'COLORED BEAD BARS are arranged in a sequence on a mat. GRAY BEAD BARS (or lighter-colored bars) of matching lengths are placed alongside, being SUBTRACTED from the colored bars. The child is working across multiple bar combinations in sequence, practicing subtraction with physical materials showing the diminishing quantity.',
    key_materials: ['colored bead bars', 'gray bead bars (same lengths)', 'black and white bead stair', 'sequential arrangement'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_addition_strip_board',
    name: 'Addition Strip Board',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'WOODEN BOARD with a FIXED RED STRIP on the left (showing addend 1-9) and SLIDING BLUE STRIPS that move horizontally (showing addend 1-9). The red strip stays still while blue strips slide to show all addition combinations (1+1, 1+2... 9+9). PRINTED ANSWER TABLES are provided. A child is sliding strips and recording or discovering sums.',
    key_materials: ['wooden board', 'fixed red strip (addends 1-9)', 'sliding blue strips (addends 1-9)', 'addition tables booklet'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_addition_charts',
    name: 'Addition Charts (Finger Charts)',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'SERIES OF PROGRESSIVE CHARTS (1-6) showing addition facts with increasing abstraction. Chart 1 shows complete addition table with all answers filled in. Charts 2-3 have BLANK SPACES for answers. Charts 4-6 show ONLY EQUATIONS without answers. A child is pointing to answers (Chart 1), finding blanks to fill (Charts 2-3), or recalling mentally (Charts 4-6).',
    key_materials: ['addition charts 1-6', 'progressive abstraction from complete to blank', 'finger pointing for tactile memory'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_subtraction_strip_board',
    name: 'Subtraction Strip Board',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'WOODEN BOARD with a FIXED MINUEND (the starting number, shown as a strip) and SLIDING SUBTRAHEND STRIPS (numbers being subtracted). The strips show all subtraction combinations for a given minuend. PRINTED ANSWER TABLES are available. A child is sliding strips and recording subtraction facts.',
    key_materials: ['wooden board', 'fixed minuend strip', 'sliding subtrahend strips', 'subtraction tables booklet'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_subtraction_charts',
    name: 'Subtraction Charts',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'SERIES OF PROGRESSIVE CHARTS (1-4) showing subtraction facts with increasing abstraction. Chart 1 shows complete subtraction table. Charts 2-3 have blank spaces. Chart 4 is completely blank requiring full mental recall. A child is using charts to memorize subtraction facts progressively.',
    key_materials: ['subtraction charts 1-4', 'progressive abstraction to blank', 'finger pointing and memory aids'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_multiplication_bead_board',
    name: 'Multiplication Bead Board',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'WOODEN BOARD with 9 VERTICAL COLUMNS and COLOR-CODED ROWS. RED BEADS are placed in rows to create arrays showing multiplication: to show 3×4, the child places 4 red beads in each of 3 rows. The beads are totaled at the bottom showing the product. A COLORED DISC or MARKER highlights the current combination being explored.',
    key_materials: ['wooden board with 9 columns', 'red beads for arrays', 'numeral cards', 'colored disc for marking'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_multiplication_charts',
    name: 'Multiplication Charts',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'SERIES OF PROGRESSIVE CHARTS (1-5) showing multiplication facts with increasing abstraction. Chart 1 shows complete multiplication table. Charts 2-4 have progressively more blanks. Chart 5 is completely blank. A child is memorizing multiplication facts through progressive abstraction and finger-pointing.',
    key_materials: ['multiplication charts 1-5', 'progressive abstraction to blank', 'finger tracing'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_unit_division_board',
    name: 'Unit Division Board',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'WOODEN BOARD with ROWS and COLUMNS for division facts. GREEN BEADS are distributed equally among GREEN SKITTLES (small pins or markers representing the divisor). To show 12÷3, the child places 12 beads and distributes them among 3 skittles equally. The quotient is recorded.',
    key_materials: ['wooden board with rows and columns', 'green beads', 'green skittles (divisor markers)', 'numeral cards'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_division_charts',
    name: 'Division Charts',
    area_key: 'mathematics',
    category: 'Memorization of Math Facts',
    visual_description: 'SERIES OF PROGRESSIVE CHARTS (1-3) showing division facts with increasing abstraction. Chart 1 is complete. Chart 2 has blanks. Chart 3 is completely blank requiring mental division. A child is progressively memorizing division facts.',
    key_materials: ['division charts 1-3', 'progressive abstraction', 'finger-pointing memory'],
    confusion_pairs: [],
    difficulty: 'medium',
  },

  // === Passage to Abstraction ===
  {
    work_key: 'ma_stamp_game',
    name: 'Stamp Game',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'WOODEN BOX containing COLORED STAMP SETS: GOLD SQUARES (representing units), GREEN RECTANGLES/BARS (tens), BLUE RECTANGLES/BARS (hundreds), RED CUBES (thousands). Each stamp is a raised symbol with its place value. A child is USING STAMPS to represent numbers and PERFORMING ALL FOUR OPERATIONS (addition, subtraction, multiplication, division). When stamps accumulate (10 ones), they are EXCHANGED for a larger denomination stamp.',
    key_materials: ['wooden box with stamp sets', 'gold unit stamps (1s)', 'green tens stamps (10s)', 'blue hundreds stamps (100s)', 'red thousands stamps (1000s)', 'skittles for division'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_dot_game',
    name: 'Dot Game',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'A child is DRAWING DOTS on special DOT PAPER in COLOR-CODED GROUPS: GOLD DOTS for units, GREEN DOTS for tens, BLUE DOTS for hundreds, RED DOTS for thousands. The child builds numbers with dots and performs operations, gradually transitioning from concrete dots to numerals as understanding develops.',
    key_materials: ['dotted paper with colored sections', 'colored pencils (gold/green/blue/red)', 'work cards or problem sheets', 'gradual transition from dots to numerals'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_small_bead_frame',
    name: 'Small Bead Frame',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'ABACUS-STYLE FRAME with 4 HORIZONTAL WIRES mounted on a wooden base. BOTTOM WIRE represents units (10 beads), 2nd wire tens (10 beads), 3rd wire hundreds (10 beads), TOP WIRE thousands (10 beads). BEADS SLIDE left and right along wires to form numbers (e.g., sliding 3 beads on thousands wire + 4 on hundreds = 3,400). A child is performing all four operations by sliding beads.',
    key_materials: ['wooden abacus frame (4 wires)', 'beads on wires (10 per wire)', 'left/right sliding mechanism'],
    confusion_pairs: ['ma_large_bead_frame'],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_large_bead_frame',
    name: 'Large Bead Frame',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'EXTENDED ABACUS FRAME with 7 HORIZONTAL WIRES representing units through millions (ones, tens, hundreds, thousands, ten-thousands, hundred-thousands, millions). BEADS SLIDE to form large numbers. A child is performing complex operations with large quantities using this extended frame.',
    key_materials: ['wooden abacus frame (7 wires)', 'beads on wires', 'left/right sliding mechanism'],
    confusion_pairs: ['ma_small_bead_frame'],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_checkerboard',
    name: 'Checkerboard (Multiplication)',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'WOODEN CHECKERBOARD with a 9×9 GRID of alternating colored squares. COLORED BEAD BARS and GOLDEN BEADS are placed in specific squares to show multi-digit multiplication. Partial products appear in specific color-coded COLUMNS. A child is building multiplication problems like 23×45, seeing the partial products and final product emerge.',
    key_materials: ['wooden checkerboard (9×9 grid)', 'colored bead bars', 'golden beads', 'number tiles', 'color-coded columns for partial products'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_racks_tubes',
    name: 'Racks and Tubes (Long Division)',
    area_key: 'mathematics',
    category: 'Passage to Abstraction',
    visual_description: 'WOODEN RACKS holding UPRIGHT TEST TUBES in a row. BEADS are placed inside tubes. To perform division, the child DISTRIBUTES BEADS equally among tubes (represented by SKITTLES as divisor markers). Reverse exchanges occur as needed (removing beads from a tube, breaking a ten-bar to get units). The quotient is determined by the number of beads in each tube.',
    key_materials: ['racks with test tubes', 'beads (various types)', 'skittles (divisor markers)', 'problem cards or work sheets'],
    confusion_pairs: [],
    difficulty: 'hard',
  },

  // === Fractions ===
  {
    work_key: 'ma_fraction_circles',
    name: 'Fraction Insets (Metal or Plastic)',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'SET OF CIRCULAR INSETS with frames: one whole circle, two halves, three thirds, four fourths, up to ten tenths. Each fractional piece is a DISTINCT COLOR and fits precisely into the circular frame. A child is FITTING PIECES TOGETHER or REMOVING PIECES to discover equivalences (2 halves = 1 whole, 3 thirds = 1 whole, etc.).',
    key_materials: ['circular insets (1/1 through 1/10)', 'metal or plastic frames', 'distinct color per fraction', 'fitting mechanism'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_fraction_addition',
    name: 'Fraction Addition',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'A child is USING FRACTION INSETS to ADD FRACTIONS. Pieces are PLACED TOGETHER to show sums. For example, adding 1/4 + 1/4 means placing two fourths together and discovering they equal 1/2. Common denominators are found by fitting pieces together.',
    key_materials: ['fraction insets', 'problem cards', 'paper for recording equations'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_fraction_subtraction',
    name: 'Fraction Subtraction',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'A child is USING FRACTION INSETS to SUBTRACT FRACTIONS. Starting with a piece (e.g., one whole), pieces are REMOVED to show differences. For example, 1 whole − 1/4 means removing a fourth and seeing the result is three-fourths.',
    key_materials: ['fraction insets', 'problem cards', 'paper for recording'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_fraction_multiplication',
    name: 'Fraction Multiplication',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'A child is MULTIPLYING FRACTIONS using insets. For example, 1/2 × 1/4 means finding what fraction of 1/4 is 1/2 of it. The pieces are arranged or nested to show the concept of "a fraction of a fraction."',
    key_materials: ['fraction insets', 'problem cards', 'paper for recording'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_fraction_division',
    name: 'Fraction Division',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'A child is DIVIDING FRACTIONS using insets. For example, 1/2 ÷ 1/4 asks "How many fourths fit into one-half?" The pieces are arranged to show how many times one fraction contains another.',
    key_materials: ['fraction insets', 'problem cards', 'paper for recording'],
    confusion_pairs: [],
    difficulty: 'hard',
  },
  {
    work_key: 'ma_fraction_skittles',
    name: 'Fraction Skittles',
    area_key: 'mathematics',
    category: 'Fractions',
    visual_description: 'SETS OF SMALL BOWLING PINS (SKITTLES) in various quantities representing fractions. For example, one set has 9 skittles total (3 are marked or colored to show 3/9 = 1/3). A child is discovering the connection between DIVISION and FRACTIONS by working with skittle sets.',
    key_materials: ['fraction skittles (various sets)', 'divided into fractional groupings'],
    confusion_pairs: [],
    difficulty: 'hard',
  },

  // === Introduction to Geometry ===
  {
    work_key: 'ma_geometry_sticks',
    name: 'Geometry Sticks',
    area_key: 'mathematics',
    category: 'Introduction to Geometry',
    visual_description: 'WOODEN OR BAMBOO STICKS of VARIOUS LENGTHS and COLORS organized in a wooden or plastic storage box. A child is CONSTRUCTING GEOMETRIC SHAPES: forming triangles (3 sticks), quadrilaterals (4 sticks), pentagons (5 sticks). The child COUNTS VERTICES (corner points) and SIDES, learning geometric properties through hands-on construction.',
    key_materials: ['colored wooden or bamboo sticks (various lengths)', 'storage box with compartments', 'distinct colors for different lengths'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_classified_nomenclature',
    name: 'Geometry Nomenclature',
    area_key: 'mathematics',
    category: 'Introduction to Geometry',
    visual_description: 'NOMENCLATURE CARDS showing geometric vocabulary with ILLUSTRATIONS and PRINTED LABELS. Cards display: LINES (straight, curved, perpendicular, parallel), ANGLES (acute, obtuse, right), TRIANGLES (scalene, isosceles, equilateral), QUADRILATERALS (square, rectangle, rhombus, trapezoid). A child is READING LABELS and MATCHING cards to corresponding illustrations.',
    key_materials: ['nomenclature cards with illustrations', 'printed labels', 'geometric vocabulary', 'matching activity format'],
    confusion_pairs: [],
    difficulty: 'medium',
  },
  {
    work_key: 'ma_area_introduction',
    name: 'Introduction to Area',
    area_key: 'mathematics',
    category: 'Introduction to Geometry',
    visual_description: 'YELLOW WOODEN TRIANGLES of a standard size (equilateral or isosceles) are ARRANGED TOGETHER to COVER geometric shapes (rectangles, triangles, parallelograms). The child is COUNTING HOW MANY TRIANGLES FIT to discover area: a rectangle covering 12 triangles has an area of 12 triangle-units. This demonstrates area measurement through concrete covering.',
    key_materials: ['yellow wooden triangles (standard size)', 'geometric insets or drawn shapes', 'covering/tiling method'],
    confusion_pairs: [],
    difficulty: 'medium',
  },

  // === Time and Money ===
  {
    work_key: 'ma_clock',
    name: 'Clock Work',
    area_key: 'mathematics',
    category: 'Time and Money',
    visual_description: 'LEARNING CLOCK with MOVABLE HOUR and MINUTE HANDS mounted on a wooden or plastic face with numbers 1-12 clearly marked. TIME CARDS display different times (e.g., "3:30", "10:15"). A child is SETTING THE CLOCK HANDS to match times on cards, or READING times shown by the hands.',
    key_materials: ['learning clock (plastic or wooden)', 'movable hour and minute hands', 'time cards', 'numeral face 1-12'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_money',
    name: 'Money Work',
    area_key: 'mathematics',
    category: 'Time and Money',
    visual_description: 'PLAY COINS or REAL COINS of VARIOUS DENOMINATIONS (pennies, nickels, dimes, quarters) are arranged on a mat. PRICE TAGS show different amounts. SHOP MATERIALS and ROLE-PLAY ITEMS are available. A child is RECOGNIZING COIN VALUES, COUNTING MIXED AMOUNTS, and MAKING CHANGE in simulated or real transactions.',
    key_materials: ['play coins or real coins (multiple denominations)', 'price tags', 'shop materials', 'role-play items for store'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
  {
    work_key: 'ma_calendar',
    name: 'Calendar Work',
    area_key: 'mathematics',
    category: 'Time and Money',
    visual_description: 'LARGE CALENDAR BOARD showing a complete month with 30 or 31 cells. DAY-OF-WEEK LABELS (Sunday-Saturday), MONTH LABELS, and DATE CARDS are displayed. A child is PLACING DATE CARDS, IDENTIFYING DAYS OF THE WEEK, NAMING MONTHS, and FINDING SPECIFIC DATES on the calendar.',
    key_materials: ['calendar board', 'date cards (1-31)', 'day of week labels', 'month labels', 'tracking current date'],
    confusion_pairs: [],
    difficulty: 'easy',
  },
];
