'use client';

// components/montree/class-documents/DocumentPaper.tsx
// ============================================================================
// THE MONTREE PRINT WRAPPER. CMS phase 6 — the bridge.
// ============================================================================
// Montree's answer to `components/cms/documents/PrintFrame.tsx`: dark-forest
// screen chrome above, the SAME white A4 sheet below.
//
// 🚨 WHY THIS IS NOT PrintFrame. PrintFrame's toolbar is Harbor — `.cms-btn`,
// `bg-harbor-canvas`, a Harbor back-link. Harbor is a PROTECTED BRAND and its
// classes must never render outside `app/cms/**`, exactly as Montree's `.btn`
// must never render inside it. So the SCREEN is rebuilt here in Montree's own
// register (dark forest, glass, `.btn btn-*`) and only the PAPER is shared.
//
// 🚨 PAPER IS WHITE — a house rule in both products and not a theme
// (`lib/onboarding-core/print/LabelSheets.tsx` says it first). The ink rules
// come from `components/cms/documents/print-css.ts`, injected as a <style> tag
// on this page rather than in globals.css, because `@page` cannot be scoped to
// a selector and a global A4 rule would hijack every print in the repo.
//
// The screen chrome carries BOTH `print:hidden` (Montree's convention — the
// dashboard header uses it, which is why the app shell does not print) and
// `cms-doc-screen` (the shared stylesheet's own hook). Either alone would do;
// both together mean neither convention can be quietly dropped.

import type { ReactNode } from 'react';
import { Printer, ArrowLeft } from 'lucide-react';
import { DOCUMENT_PRINT_CSS } from '@/components/cms/documents/print-css';
import type { DocumentMeta } from '@/lib/cms/engine/doc-generator';
import type { TFunction } from '@/lib/cms/i18n/t';

/** Montree-only additions. The dark shell has to become white paper, and the
 *  glow layer behind it has to stop existing, the moment a printer is asked. */
const MONTREE_PRINT_CSS = `
@media print {
  .mt-doc-shell {
    background: #ffffff !important;
    padding: 0 !important;
    min-height: 0 !important;
  }
  .mt-doc-glow { display: none !important; }
}
`;

export interface DocumentPaperProps {
  meta: DocumentMeta;
  /** Localised document title — CMS labels, because it prints. */
  title: string;
  /** Localised date, formatted by the page. */
  dateLabel: string;
  /** CMS translator — the paper's own language (see catalogue.ts). */
  t: TFunction;
  /**
   * The footer's brand line. Montree-supplied on purpose: CMS's own
   * `doc.generatedBy` reads "Generated by CMS", which must never print on a
   * Montree teacher's sheet. The one string on this paper that names a product
   * comes from the product whose paper it is.
   */
  generatedByLabel: string;
  /** Montree-language chrome labels. Chrome is screen, screen is Montree. */
  backLabel: string;
  printLabel: string;
  roomsLabel: string;
  onBack: () => void;
  /** Room switcher for a teacher with more than one classroom. */
  rooms?: { id: string; name: string }[];
  activeRoomId?: string;
  onSelectRoom?: (roomId: string) => void;
  children: ReactNode;
}

export default function DocumentPaper({
  meta,
  title,
  dateLabel,
  t,
  generatedByLabel,
  backLabel,
  printLabel,
  roomsLabel,
  onBack,
  rooms = [],
  activeRoomId,
  onSelectRoom,
  children,
}: DocumentPaperProps) {
  return (
    <div className="mt-doc-shell min-h-screen bg-[#0a1a0f] py-5 px-4 sm:px-6 relative">
      <style dangerouslySetInnerHTML={{ __html: DOCUMENT_PRINT_CSS + MONTREE_PRINT_CSS }} />

      <div
        aria-hidden
        className="mt-doc-glow fixed inset-0 pointer-events-none print:hidden"
        style={{
          background: 'radial-gradient(circle at 50% 0%, rgba(39,129,90,0.32), transparent 60%)',
        }}
      />

      {/* ── screen-only Montree toolbar ────────────────────────────────── */}
      <div className="cms-doc-screen print:hidden relative max-w-[190mm] mx-auto mb-5 flex flex-wrap items-center gap-2.5">
        <button type="button" onClick={onBack} className="btn btn-ghost btn-sm">
          <ArrowLeft className="w-4 h-4" />
          {backLabel}
        </button>

        {rooms.length > 1 && (
          <nav aria-label={roomsLabel} className="flex flex-wrap items-center gap-1.5">
            {rooms.map((room) => (
              <button
                key={room.id}
                type="button"
                aria-pressed={room.id === activeRoomId}
                onClick={() => onSelectRoom?.(room.id)}
                className={
                  room.id === activeRoomId
                    ? 'btn btn-primary btn-sm btn-pill'
                    : 'btn btn-secondary btn-sm btn-pill'
                }
              >
                {room.name}
              </button>
            ))}
          </nav>
        )}

        <span className="ms-auto">
          <button type="button" onClick={() => window.print()} className="btn btn-primary btn-md">
            <Printer className="w-4 h-4" />
            {printLabel}
          </button>
        </span>
      </div>

      {/* ── the paper ──────────────────────────────────────────────────── */}
      <article className="cms-doc-sheet relative">
        <header className="cms-doc-head">
          <div className="min-w-0">
            <h1 className="cms-doc-title" dir="auto">
              {title}
            </h1>
            <p className="cms-doc-sub" dir="auto">
              {meta.schoolName}
            </p>
          </div>
          <div className="cms-doc-stamp">
            <b dir="auto">{meta.roomName}</b>
            {dateLabel}
          </div>
        </header>

        {children}

        <footer className="cms-doc-foot">
          <span>{generatedByLabel}</span>
          <span>
            {t('doc.generatedOn', { date: dateLabel })}
            {meta.printedByName ? ` · ${t('doc.printedBy', { name: meta.printedByName })}` : ''}
          </span>
        </footer>
      </article>
    </div>
  );
}
