'use client';

// AgentApplicationAlert
//
// Phase 3 of agent system fix plan — super-admin banner at top of the
// dashboard that surfaces pending agent applications from the public
// /montree/become-an-agent form.
//
// Mirrors the DemoRequestAlert pattern (inline in super-admin/page.tsx)
// but lifted into its own component file for clarity. Both banners
// stack in the super-admin header.
//
// Per-row actions:
//   ✓ Accept (issue code) — links to Referrals tab with prefill query
//     params, so the existing 🔑 Issue Agent Login modal opens with the
//     applicant's name + email already in. Tredoux finishes the issue
//     manually (sets the share %) then this row flips to 'sent'.
//   ✗ Decline — sets status='declined'.
//   ✉ Reply — opens mailto with a warm short reply.

import { useCallback, useEffect, useState } from 'react';

interface AgentApplication {
  id: string;
  org_name: string;          // affiliation
  contact_person: string | null; // applicant name
  email: string;
  country: string | null;
  status: string;
  created_at: string;
  notes: string | null;
  application_details?: {
    current_role?: string | null;
    why_good_fit?: string | null;
  } | null;
}

function daysSince(iso: string): number {
  return Math.floor((Date.now() - new Date(iso).getTime()) / (1000 * 60 * 60 * 24));
}

function escapeForMailto(s: string): string {
  return encodeURIComponent(s);
}

interface AcceptedAgent {
  name: string;
  email: string;
  loginCode: string;
  loginUrl: string;
  welcomeMessage: string;
}

export default function AgentApplicationAlert({ saToken }: { saToken: string }) {
  const [applications, setApplications] = useState<AgentApplication[]>([]);
  const [busy, setBusy] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  // The reveal-once welcome modal that opens after a successful accept.
  // Contains the plaintext login code — server never returns it again.
  const [accepted, setAccepted] = useState<AcceptedAgent | null>(null);
  const [copiedField, setCopiedField] = useState<'code' | 'link' | 'message' | null>(null);

  const copyToClipboard = async (text: string, field: 'code' | 'link' | 'message') => {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // Fallback for older browsers / non-secure contexts
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      try {
        document.execCommand('copy');
      } finally {
        document.body.removeChild(ta);
      }
    }
    setCopiedField(field);
    window.setTimeout(() => setCopiedField(null), 1400);
  };

  const load = useCallback(() => {
    if (!saToken) return;
    fetch('/api/montree/super-admin/agent-applications?status=agent_applied', {
      headers: { 'x-super-admin-token': saToken },
    })
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => {
        if (d?.applications) {
          setApplications(d.applications as AgentApplication[]);
        }
      })
      .catch((err) => console.error('[AgentApplicationAlert] load failed:', err));
  }, [saToken]);

  useEffect(() => {
    load();
  }, [load]);

  const setStatus = async (id: string, status: 'sent' | 'contacted' | 'declined' | 'dead') => {
    setBusy(id);
    try {
      await fetch('/api/montree/super-admin/agent-applications', {
        method: 'PATCH',
        headers: { 'x-super-admin-token': saToken, 'Content-Type': 'application/json' },
        body: JSON.stringify({ id, status }),
      });
      // Drop from local list — alert is "pending only"
      setApplications((prev) => prev.filter((a) => a.id !== id));
    } catch (err) {
      console.error('[AgentApplicationAlert] status update failed:', err);
    } finally {
      setBusy(null);
    }
  };

  /** Accept = one-shot: find-or-create the agent record + issue an agent
   *  LOGIN code + mark application as 'sent'. Opens a reveal-once welcome
   *  modal containing the plaintext code + a deep-link URL + a ready-to-
   *  paste welcome message Tredoux sends via WhatsApp/email/SMS.
   *
   *  Note: this is the AGENT LOGIN code (their key into the agent
   *  dashboard). Referral codes (the ones the agent shares with schools)
   *  are generated by the agent themselves from inside their dashboard —
   *  no Tredoux involvement needed. */
  const accept = async (app: AgentApplication) => {
    setBusy(app.id);
    try {
      const res = await fetch(
        `/api/montree/super-admin/agent-applications/${app.id}/accept`,
        {
          method: 'POST',
          headers: { 'x-super-admin-token': saToken },
        }
      );
      if (!res.ok) {
        const j = await res.json().catch(() => ({}));
        console.error('[AgentApplicationAlert] accept failed', j);
        window.alert(j?.error || 'Could not accept the application.');
        return;
      }
      const data = await res.json();
      // Drop from pending list — application is now 'sent'.
      setApplications((prev) => prev.filter((a) => a.id !== app.id));
      // Open the reveal-once welcome modal.
      setAccepted({
        name: data?.agent?.name || app.contact_person || 'Agent',
        email: data?.agent?.email || app.email,
        loginCode: data?.login_code || '',
        loginUrl: data?.login_url || '',
        welcomeMessage: data?.welcome_message || '',
      });
    } catch (err) {
      console.error('[AgentApplicationAlert] accept error', err);
      window.alert('Network error.');
    } finally {
      setBusy(null);
    }
  };

  /** Open mail client with a warm short reply (no commitment). Useful when
   *  Tredoux wants to ask a clarifying question before deciding. Marks
   *  'contacted' so the row drops out of the pending banner. */
  const replyWithMessage = (app: AgentApplication) => {
    const firstName = (app.contact_person || '').split(/\s+/)[0] || 'there';
    const subject = `Re: Montree — your agent application`;
    const body =
      `Hi ${firstName},\n\n` +
      `Thanks for applying to be a Montree agent. Quick question before I move forward:\n\n` +
      `[Your question here]\n\n` +
      `Kind regards,\nTredoux\nmontree.xyz`;
    const mailto = `mailto:${escapeForMailto(app.email)}?subject=${escapeForMailto(subject)}&body=${escapeForMailto(body)}`;
    const w = window.open(mailto, '_blank');
    if (w) setTimeout(() => { try { w.close(); } catch { /* */ } }, 500);
    setStatus(app.id, 'contacted');
  };

  const toggleExpanded = (id: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  if (applications.length === 0 && !accepted) return null;

  return (
    <>
    {applications.length > 0 && (
    <div className="mb-4 p-4 bg-amber-500/15 border border-amber-500/40 rounded-xl">
      <div className="flex items-center gap-2 mb-3 flex-wrap">
        <span className="text-amber-400 text-lg">🌱</span>
        <span className="text-amber-200 font-semibold text-sm">
          {applications.length} new agent application{applications.length > 1 ? 's' : ''}
        </span>
      </div>

      <div className="space-y-2">
        {applications.map((app) => {
          const age = daysSince(app.created_at);
          const ageLabel = age === 0 ? 'today' : age === 1 ? '1 day ago' : `${age} days ago`;
          const isExpanded = expanded.has(app.id);
          const pitch = app.application_details?.why_good_fit || app.notes || '';
          const role = app.application_details?.current_role || '';

          return (
            <div
              key={app.id}
              className="rounded-lg px-3 py-2 bg-black/20 border border-amber-500/20"
            >
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-white text-sm font-medium">
                      {app.contact_person || '(no name)'}
                    </span>
                    {app.org_name && app.org_name !== 'Independent' && (
                      <span className="text-amber-200/70 text-xs">— {app.org_name}</span>
                    )}
                    {app.country && (
                      <span className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-slate-700/50 text-slate-300 border border-slate-600">
                        {app.country}
                      </span>
                    )}
                    <span className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-slate-700/50 text-slate-300 border border-slate-600">
                      {ageLabel}
                    </span>
                  </div>
                  <a
                    href={`mailto:${app.email}`}
                    className="text-amber-300 text-xs hover:text-amber-200 underline mt-1 inline-block"
                  >
                    {app.email}
                  </a>
                  {(pitch || role) && (
                    <button
                      onClick={() => toggleExpanded(app.id)}
                      className="block mt-1 text-xs text-amber-300/80 hover:text-amber-200 underline"
                    >
                      {isExpanded ? 'Hide pitch' : 'Read pitch'}
                    </button>
                  )}
                  {isExpanded && (
                    <div className="mt-2 px-3 py-2 rounded bg-black/40 border border-amber-500/20 text-xs text-amber-100/90 whitespace-pre-wrap">
                      {role && (
                        <div className="mb-2">
                          <span className="text-amber-300/70 font-medium">Current role: </span>
                          <span>{role}</span>
                        </div>
                      )}
                      {pitch && (
                        <div>
                          <span className="text-amber-300/70 font-medium">Why a good fit: </span>
                          <span>{pitch}</span>
                        </div>
                      )}
                    </div>
                  )}
                </div>

                <div className="flex flex-col gap-1 shrink-0">
                  <button
                    onClick={() => accept(app)}
                    disabled={busy === app.id}
                    className="text-xs px-2.5 py-1 rounded-lg bg-emerald-500/25 hover:bg-emerald-500/40 text-emerald-100 border border-emerald-500/50 transition-colors disabled:opacity-50 font-medium"
                    title="Open Referrals tab with this applicant's details pre-filled to issue an agent code"
                  >
                    ✓ Accept
                  </button>
                  <button
                    onClick={() => replyWithMessage(app)}
                    disabled={busy === app.id}
                    className="text-xs px-2.5 py-1 rounded-lg bg-amber-500/20 hover:bg-amber-500/35 text-amber-200 border border-amber-500/40 transition-colors disabled:opacity-50"
                    title="Open mail client with a short reply asking for more info. Marks as contacted."
                  >
                    ✉ Reply
                  </button>
                  <button
                    onClick={() => setStatus(app.id, 'declined')}
                    disabled={busy === app.id}
                    className="text-xs px-2.5 py-1 rounded-lg bg-slate-600/30 hover:bg-slate-600/50 text-slate-300 border border-slate-600/50 transition-colors disabled:opacity-50"
                    title="Mark as declined. No email sent — handle that manually if needed."
                  >
                    ✗ Decline
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
    )}

    {/* Reveal-once welcome modal — opens after a successful Accept. The
        plaintext code only appears here once; if Tredoux closes the
        modal without copying, he can reset the code from the Referrals
        tab. */}
    {accepted && (
      <div
        role="dialog"
        aria-modal="true"
        onClick={() => setAccepted(null)}
        style={{
          position: 'fixed',
          inset: 0,
          background: 'rgba(0,0,0,0.65)',
          backdropFilter: 'blur(6px)',
          zIndex: 1100,
          display: 'flex',
          alignItems: 'flex-start',
          justifyContent: 'center',
          padding: '6vh 16px 24px',
          overflowY: 'auto',
        }}
      >
        <div
          onClick={(e) => e.stopPropagation()}
          style={{
            width: '100%',
            maxWidth: 580,
            padding: 22,
            borderRadius: 18,
            background: 'rgba(10, 26, 15, 0.98)',
            border: '1px solid rgba(52,211,153,0.30)',
            boxShadow: '0 24px 64px rgba(0,0,0,0.6)',
            color: 'rgba(255,255,255,0.92)',
            fontFamily: '-apple-system, BlinkMacSystemFont, "Inter", sans-serif',
          }}
        >
          <div style={{ marginBottom: 14 }}>
            <h2
              style={{
                margin: 0,
                fontFamily: 'var(--font-lora), Georgia, serif',
                fontSize: 22,
                fontWeight: 500,
                color: '#34d399',
                letterSpacing: -0.3,
              }}
            >
              {accepted.name} is in
            </h2>
            <p
              style={{
                margin: '6px 0 0',
                fontSize: 13,
                color: 'rgba(234,241,230,0.65)',
              }}
            >
              Share this with them — the link preloads the code so they only
              need to tap Enter on the login screen.
            </p>
          </div>

          {/* Big code display so Tredoux can read it out if needed */}
          <div
            style={{
              padding: 18,
              borderRadius: 12,
              background: 'rgba(232,201,106,0.10)',
              border: '1px solid rgba(232,201,106,0.30)',
              marginBottom: 14,
              textAlign: 'center',
            }}
          >
            <div
              style={{
                fontSize: 11,
                letterSpacing: 1.4,
                textTransform: 'uppercase',
                color: '#E8C96A',
                fontWeight: 600,
                marginBottom: 8,
              }}
            >
              Login code
            </div>
            <div
              style={{
                fontFamily: 'SF Mono, Menlo, monospace',
                fontSize: 32,
                fontWeight: 700,
                letterSpacing: 6,
                color: 'rgba(255,255,255,0.95)',
              }}
            >
              {accepted.loginCode}
            </div>
            <button
              type="button"
              onClick={() => copyToClipboard(accepted.loginCode, 'code')}
              style={{
                marginTop: 12,
                padding: '6px 12px',
                borderRadius: 8,
                background: copiedField === 'code' ? '#34d399' : 'rgba(0,0,0,0.30)',
                border: '1px solid rgba(232,201,106,0.30)',
                color: copiedField === 'code' ? '#0a1a0f' : 'rgba(234,241,230,0.65)',
                fontSize: 12,
                fontWeight: 600,
                cursor: 'pointer',
              }}
            >
              {copiedField === 'code' ? '✓ Copied' : 'Copy code'}
            </button>
          </div>

          {/* Deep-link URL */}
          <div style={{ marginBottom: 14 }}>
            <div
              style={{
                fontSize: 11,
                letterSpacing: 1.4,
                textTransform: 'uppercase',
                color: '#E8C96A',
                fontWeight: 600,
                marginBottom: 6,
              }}
            >
              Deep-link (preloads the code)
            </div>
            <div
              style={{
                display: 'flex',
                gap: 8,
                alignItems: 'center',
              }}
            >
              <input
                readOnly
                value={accepted.loginUrl}
                onClick={(e) => (e.target as HTMLInputElement).select()}
                style={{
                  flex: 1,
                  padding: '10px 12px',
                  borderRadius: 10,
                  background: 'rgba(0,0,0,0.30)',
                  border: '1px solid rgba(52,211,153,0.25)',
                  color: 'rgba(255,255,255,0.92)',
                  fontSize: 12,
                  fontFamily: 'SF Mono, Menlo, monospace',
                  outline: 'none',
                }}
              />
              <button
                type="button"
                onClick={() => copyToClipboard(accepted.loginUrl, 'link')}
                style={{
                  padding: '10px 14px',
                  borderRadius: 10,
                  background: copiedField === 'link' ? '#34d399' : 'rgba(0,0,0,0.30)',
                  border: '1px solid rgba(52,211,153,0.25)',
                  color: copiedField === 'link' ? '#0a1a0f' : 'rgba(255,255,255,0.92)',
                  fontSize: 12,
                  fontWeight: 600,
                  cursor: 'pointer',
                  whiteSpace: 'nowrap',
                }}
              >
                {copiedField === 'link' ? '✓' : 'Copy link'}
              </button>
            </div>
          </div>

          {/* Pre-built welcome message — primary action */}
          <div style={{ marginBottom: 14 }}>
            <div
              style={{
                fontSize: 11,
                letterSpacing: 1.4,
                textTransform: 'uppercase',
                color: '#E8C96A',
                fontWeight: 600,
                marginBottom: 6,
              }}
            >
              Welcome message
            </div>
            <textarea
              readOnly
              value={accepted.welcomeMessage}
              onClick={(e) => (e.target as HTMLTextAreaElement).select()}
              rows={10}
              style={{
                width: '100%',
                padding: '12px 14px',
                borderRadius: 10,
                background: 'rgba(0,0,0,0.30)',
                border: '1px solid rgba(52,211,153,0.25)',
                color: 'rgba(255,255,255,0.92)',
                fontSize: 13,
                fontFamily: '-apple-system, BlinkMacSystemFont, "Inter", sans-serif',
                lineHeight: 1.5,
                outline: 'none',
                resize: 'vertical',
              }}
            />
          </div>

          <div style={{ display: 'flex', gap: 10 }}>
            <button
              type="button"
              onClick={() => copyToClipboard(accepted.welcomeMessage, 'message')}
              style={{
                flex: 1,
                padding: '14px 16px',
                borderRadius: 12,
                background: copiedField === 'message' ? '#34d399' : '#34d399',
                border: 'none',
                color: '#0a1a0f',
                fontWeight: 600,
                fontSize: 15,
                cursor: 'pointer',
              }}
            >
              {copiedField === 'message'
                ? '✓ Copied — paste it anywhere'
                : `Copy welcome message for ${accepted.name.split(/\s+/)[0]}`}
            </button>
            <button
              type="button"
              onClick={() => setAccepted(null)}
              style={{
                padding: '14px 18px',
                borderRadius: 12,
                background: 'transparent',
                border: '1px solid rgba(255,255,255,0.18)',
                color: 'rgba(234,241,230,0.65)',
                fontWeight: 500,
                fontSize: 14,
                cursor: 'pointer',
              }}
            >
              Done
            </button>
          </div>
        </div>
      </div>
    )}
    </>
  );
}
