/**
 * Book Works — lessons 2 to 18.
 *
 * Lesson 1 stays in book-works.ts, hand-authored and shipped; these fifteen are
 * MACHINE-DERIVED from the repo's own curriculum data and must stay that way.
 * Nothing a child reads here was written by hand:
 *
 *   pages[].sentence   scripts/curriculum/flashcards/books_def.py BOOKS[].spreads
 *                      (lead-in `nar` + shout `text`, joined — the same locked
 *                      split splitBookLine() re-derives for the screen), and
 *                      for ant-on-my-apple the storybook manifest's pages[].
 *   cast[]             dp-<slug>.json pages[] (word, sentence, art) verbatim.
 *   matchOrder         dp-<slug>.json matchDisplayOrder — asserted a derangement
 *                      for every lesson, so no card ever faces its own twin.
 *
 * 🚨 DISPLAY 13 (the /ck/ lesson) IS DELIBERATELY ABSENT, and the series stops
 * at 18. Its book, the-cat-sat, has a dp-<slug>.json but NO entry in
 * books_def.py, so there is no verbatim source for its page text — and this
 * file never invents a line a child would read. getBookWorks(13) returns null,
 * which the pickers already handle by simply not offering a card.
 *   rounds[]           the cast's own sentences; only the candidate ORDER is
 *                      computed (a fixed rotation per round, deterministic).
 *   questions[]        dp-<slug>.json yesno[] — wording and art verbatim; only
 *                      WHICH six and in what order is chosen (see below).
 *   endingImage/Line   the book's last page and its printed line.
 *
 * The one thing written by hand is `script[]` — the physical opener. Those are
 * TEACHER stage directions (plain instructions, deliberately my words), and
 * every line the teacher SAYS inside them is quoted verbatim from the book.
 *
 * 🚨 QUESTION SELECTION is a judgement call, recorded here so it can be
 * reversed in one line. The source files hold either 4 questions (alternating
 * true/false) or 10 (five true, then five false). Taking "the first six" of a
 * 10-set would give five YES answers then one NO — which a four-year-old beats
 * by simply always saying yes. So: three trues and three falses are taken in
 * source order and laid out YES NO YES NO NO YES — the same rhythm Lesson 1
 * ships with, mostly alternating with one deliberate break. The 4-question
 * books are reordered YES NO NO YES for the same reason. No wording, answer or
 * image is altered by any of this.
 *
 * REGENERATE rather than hand-edit: the generator reads books_def.py, the
 * dp-<slug>.json letters and the storybook manifest.
 */

import {
  lessonPictureUrl,
  lessonVideoUrl,
} from '@/lib/montree/dark-phonics/live-lesson';
import type { BookWorksLesson } from '@/lib/montree/dark-phonics/book-works';

/** Every page image ships in the build under this committed public directory. */
const P = '/dark-phonics-live/pages';

export const BOOK_WORKS_LESSONS_2_10: Record<number, BookWorksLesson> = {
  2: {
    lessonNumber: 2,
    letter: 'a',
    traceTitle: 'Trace the a',
    title: 'A Is for Apple',
    bookTitle: 'Ant on My Apple',
    coverImage: `${P}/ant-on-my-apple/p1-apple.png`,
    videoUrl: lessonVideoUrl(2),
    videoPosterUrl: lessonPictureUrl(2),
    pages: [
      { art: `${P}/ant-on-my-apple/p1-apple.png`, sentence: 'An apple.' },
      { art: `${P}/ant-on-my-apple/p2-ant.png`, sentence: 'An ant on my apple!' },
      { art: `${P}/ant-on-my-apple/p3-alligator.png`, sentence: 'An alligator on my apple!' },
      { art: `${P}/ant-on-my-apple/p4-anteater.png`, sentence: 'An anteater on my apple!' },
      { art: `${P}/ant-on-my-apple/p5-ambulance.png`, sentence: 'An ambulance on my apple!' },
      { art: `${P}/ant-on-my-apple/p6-recap.png`, sentence: 'An ant, an alligator, an anteater, and an ambulance on my apple?!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'An ant on my apple!', image: `${P}/ant-on-my-apple/p2-ant.png` },
      { id: 'alligator', label: 'alligator', sentence: 'An alligator on my apple!', image: `${P}/ant-on-my-apple/p3-alligator.png` },
      { id: 'anteater', label: 'anteater', sentence: 'An anteater on my apple!', image: `${P}/ant-on-my-apple/p4-anteater.png` },
      { id: 'ambulance', label: 'ambulance', sentence: 'An ambulance on my apple!', image: `${P}/ant-on-my-apple/p5-ambulance.png` },
    ],
    matchOrder: ['anteater', 'ant', 'ambulance', 'alligator'],
    rounds: [
      { sentence: 'An ant on my apple!', answerId: 'ant', candidateIds: ['alligator', 'anteater', 'ambulance', 'ant'] },
      { sentence: 'An alligator on my apple!', answerId: 'alligator', candidateIds: ['anteater', 'ambulance', 'ant', 'alligator'] },
      { sentence: 'An anteater on my apple!', answerId: 'anteater', candidateIds: ['ambulance', 'ant', 'alligator', 'anteater'] },
      { sentence: 'An ambulance on my apple!', answerId: 'ambulance', candidateIds: ['ant', 'alligator', 'anteater', 'ambulance'] },
    ],
    questions: [
      { question: 'is an ant on my apple?', answer: true, image: `${P}/ant-on-my-apple/p2-ant.png` },
      { question: 'is a snake on my apple?', answer: false, image: `${P}/snake-in-my-sock/p2-snake.png` },
      { question: 'is a tiger on my apple?', answer: false, image: `${P}/tiger-in-the-taxi/p4-tiger.png` },
      { question: 'is an alligator on my apple?', answer: true, image: `${P}/ant-on-my-apple/p3-alligator.png` },
    ],
    script: [
      'Hold up a real apple and the toy ant.',
      'Show the apple on its own first. “An apple.”',
      'Walk the ant up onto it, slowly, so they watch it arrive.',
      '“An ant on my apple!” — say it big, then let them say it back.',
      '“Do you have an apple? Do you have an ant?” — send them running to fetch.',
      'Wait for them. When they come back, they hold theirs up and say it with you.',
    ],
    endingImage: `${P}/ant-on-my-apple/p6-recap.png`,
    endingLine: 'An ant, an alligator, an anteater, and an ambulance on my apple?!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  3: {
    lessonNumber: 3,
    letter: 't',
    traceTitle: 'Trace the t',
    title: 'Tick-Tock, T!',
    bookTitle: 'The ___ Sat!',
    coverImage: `${P}/the-sat/sat-p1.png`,
    videoUrl: lessonVideoUrl(3),
    videoPosterUrl: lessonPictureUrl(3),
    pages: [
      { art: `${P}/the-sat/sat-p1.png`, sentence: 'The ant… Sat!' },
      { art: `${P}/the-sat/sat-p2.png`, sentence: 'The snake… Sat!' },
      { art: `${P}/the-sat/sat-p3.png`, sentence: 'The apple… Sat!' },
      { art: `${P}/the-sat/sat-p4.png`, sentence: 'The sun… Sat!' },
      { art: `${P}/the-sat/sat-p5.png`, sentence: 'The star… Sat!' },
      { art: `${P}/the-sat/sat-p6.png`, sentence: 'The cat… Sat!' },
      { art: `${P}/the-sat/sat-p7.png`, sentence: 'Sat! Sat! Sat!', chant: true },
      { art: `${P}/the-sat/sat-p8.png`, sentence: 'And the…?!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant sat!', image: `${P}/the-sat/sat-p1.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake sat!', image: `${P}/the-sat/sat-p2.png` },
      { id: 'star', label: 'star', sentence: 'The star sat!', image: `${P}/the-sat/sat-p5.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat sat!', image: `${P}/the-sat/sat-p6.png` },
    ],
    matchOrder: ['snake', 'cat', 'ant', 'star'],
    rounds: [
      { sentence: 'The ant sat!', answerId: 'ant', candidateIds: ['snake', 'star', 'cat', 'ant'] },
      { sentence: 'The snake sat!', answerId: 'snake', candidateIds: ['star', 'cat', 'ant', 'snake'] },
      { sentence: 'The star sat!', answerId: 'star', candidateIds: ['cat', 'ant', 'snake', 'star'] },
      { sentence: 'The cat sat!', answerId: 'cat', candidateIds: ['ant', 'snake', 'star', 'cat'] },
    ],
    questions: [
      { question: 'did the ant sit?', answer: true, image: `${P}/the-sat/sat-p1.png` },
      { question: 'did the fox sit?', answer: false, image: `${P}/fox-in-a-box/p1-fox.png` },
      { question: 'did the snake sit?', answer: true, image: `${P}/the-sat/sat-p2.png` },
      { question: 'did the horse sit?', answer: false, image: `${P}/horse-in-my-hat/p4-horse.png` },
      { question: 'did the duck sit?', answer: false, image: `${P}/on-a-rock/p1-duck.png` },
      { question: 'did the apple sit?', answer: true, image: `${P}/the-sat/sat-p3.png` },
    ],
    script: [
      'Stand the toy ant on the table where they can see it.',
      '“The ant… Sat!” — sit the ant down hard on the word.',
      'Do it again with the snake, then the cat, letting them shout “Sat!” each time.',
      '“Can you make your toy sit?” — send them running to fetch one.',
    ],
    endingImage: `${P}/the-sat/sat-p8.png`,
    endingLine: 'And the…?!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  4: {
    lessonNumber: 4,
    letter: 'p',
    traceTitle: 'Trace the p',
    title: 'Pop, Pop, P!',
    bookTitle: 'The ___ Spat!',
    coverImage: `${P}/the-spat/p1-basin.png`,
    videoUrl: lessonVideoUrl(4),
    videoPosterUrl: lessonPictureUrl(4),
    pages: [
      { art: `${P}/the-spat/p1-basin.png`, sentence: 'A basin.' },
      { art: `${P}/the-spat/p2-penguin.png`, sentence: 'The penguin… Spat!' },
      { art: `${P}/the-spat/p3-pig.png`, sentence: 'The pig… Spat!' },
      { art: `${P}/the-spat/p4-pelican.png`, sentence: 'The pelican… Spat!' },
      { art: `${P}/the-spat/p5-recap.png`, sentence: 'Spat! Spat! Spat!', chant: true },
      { art: `${P}/the-spat/p6-potato.png`, sentence: 'And the…?!' },
    ],
    cast: [
      { id: 'penguin', label: 'penguin', sentence: 'The penguin spat!', image: `${P}/the-spat/p2-penguin.png` },
      { id: 'pig', label: 'pig', sentence: 'The pig spat!', image: `${P}/the-spat/p3-pig.png` },
      { id: 'pelican', label: 'pelican', sentence: 'The pelican spat!', image: `${P}/the-spat/p4-pelican.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato spat!', image: `${P}/the-spat/p6-potato.png` },
    ],
    matchOrder: ['pig', 'potato', 'penguin', 'pelican'],
    rounds: [
      { sentence: 'The penguin spat!', answerId: 'penguin', candidateIds: ['pig', 'pelican', 'potato', 'penguin'] },
      { sentence: 'The pig spat!', answerId: 'pig', candidateIds: ['pelican', 'potato', 'penguin', 'pig'] },
      { sentence: 'The pelican spat!', answerId: 'pelican', candidateIds: ['potato', 'penguin', 'pig', 'pelican'] },
      { sentence: 'The potato spat!', answerId: 'potato', candidateIds: ['penguin', 'pig', 'pelican', 'potato'] },
    ],
    questions: [
      { question: 'did the penguin spit?', answer: true, image: `${P}/the-spat/p2-penguin.png` },
      { question: 'did the quill spit?', answer: false, image: `${P}/queen-on-the-quilt/p1-quill.png` },
      { question: 'did the rabbit spit?', answer: false, image: `${P}/rabbit-in-the-rocket/p1-rabbit.png` },
      { question: 'did the pig spit?', answer: true, image: `${P}/the-spat/p3-pig.png` },
    ],
    script: [
      'Hold up a real basin or bowl, and the toy penguin.',
      'Show the basin on its own first. “A basin.”',
      'Lean the penguin over it. “The penguin… Spat!” — make the noise, big.',
      '“Do you have a bowl? Do you have an animal?” — send them running to fetch.',
    ],
    endingImage: `${P}/the-spat/p6-potato.png`,
    endingLine: 'And the…?!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  5: {
    lessonNumber: 5,
    letter: 'i',
    traceTitle: 'Trace the i',
    title: 'I, I, Itsy I',
    bookTitle: 'The ___ Sat in the Pit!',
    coverImage: `${P}/the-pit/p1-pit.png`,
    videoUrl: lessonVideoUrl(5),
    videoPosterUrl: lessonPictureUrl(5),
    pages: [
      { art: `${P}/the-pit/p1-pit.png`, sentence: 'A pit.' },
      { art: `${P}/the-pit/p2-ant.png`, sentence: 'The ant sat in the… pit!' },
      { art: `${P}/the-pit/p3-apple.png`, sentence: 'The apple sat in the… pit!' },
      { art: `${P}/the-pit/p4-sun.png`, sentence: 'The sun sat in the… pit!' },
      { art: `${P}/the-pit/p5-star.png`, sentence: 'The star sat in the… pit!' },
      { art: `${P}/the-pit/p6-snake.png`, sentence: 'The snake sat in the… pit!' },
      { art: `${P}/the-pit/p7-cat.png`, sentence: 'The cat sat in the… pit!' },
      { art: `${P}/the-pit/p8-recap.png`, sentence: 'Sat in the pit! Sat in the pit! Sat in the pit!', chant: true },
      { art: `${P}/the-pit/p9-potato.png`, sentence: 'And the…?!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant sat in the pit!', image: `${P}/the-pit/p2-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake sat in the pit!', image: `${P}/the-pit/p6-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat sat in the pit!', image: `${P}/the-pit/p7-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato sat in the pit!', image: `${P}/the-pit/p9-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant sat in the pit!', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake sat in the pit!', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat sat in the pit!', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato sat in the pit!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'did the ant sit in the pit?', answer: true, image: `${P}/the-pit/p2-ant.png` },
      { question: 'did the duck sit in the pit?', answer: false, image: `${P}/on-a-rock/p1-duck.png` },
      { question: 'did the frog sit in the pit?', answer: false, image: `${P}/frog-on-the-fan/p1-frog.png` },
      { question: 'did the cat sit in the pit?', answer: true, image: `${P}/the-pit/p7-cat.png` },
    ],
    script: [
      'Make a pit — a cupped hand, a bowl, a hole in a cushion.',
      'Show it empty first. “A pit.”',
      'Drop the toy ant in. “The ant sat in the… pit!”',
      '“Do you have a pit? Do you have an ant?” — send them running to fetch.',
    ],
    endingImage: `${P}/the-pit/p9-potato.png`,
    endingLine: 'And the…?!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  6: {
    lessonNumber: 6,
    letter: 'n',
    traceTitle: 'Trace the n',
    title: 'N for the Nose',
    bookTitle: 'The ___ Naps!',
    coverImage: `${P}/the-nap/p1-ant.png`,
    videoUrl: lessonVideoUrl(6),
    videoPosterUrl: lessonPictureUrl(6),
    pages: [
      { art: `${P}/the-nap/p1-ant.png`, sentence: 'The ant… naps.' },
      { art: `${P}/the-nap/p2-apple.png`, sentence: 'The apple… naps.' },
      { art: `${P}/the-nap/p3-sun.png`, sentence: 'The sun… naps.' },
      { art: `${P}/the-nap/p4-star.png`, sentence: 'The star… naps.' },
      { art: `${P}/the-nap/p5-snake.png`, sentence: 'The snake… naps.' },
      { art: `${P}/the-nap/p6-cat.png`, sentence: 'The cat… naps.' },
      { art: `${P}/the-nap/p7-recap.png`, sentence: 'Nap! Nap! Nap!', chant: true },
      { art: `${P}/the-nap/p8-potato.png`, sentence: 'The potato doesn’t… nap!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant naps.', image: `${P}/the-nap/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake naps.', image: `${P}/the-nap/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat naps.', image: `${P}/the-nap/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato doesn\'t nap!', image: `${P}/the-nap/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant naps.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake naps.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat naps.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato doesn\'t nap!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'did the ant nap?', answer: true, image: `${P}/the-nap/p1-ant.png` },
      { question: 'did the potato nap?', answer: false, image: `${P}/the-nap/p8-potato.png` },
      { question: 'did the apple nap?', answer: true, image: `${P}/the-nap/p2-apple.png` },
      { question: 'did the unicorn nap?', answer: false, image: `${P}/under-my-umbrella/p1-unicorn.png` },
      { question: 'did the volcano nap?', answer: false, image: `${P}/volcano-in-the-van/p4-volcano.png` },
      { question: 'did the sun nap?', answer: true, image: `${P}/the-nap/p3-sun.png` },
    ],
    script: [
      'Lay the toy ant down on its side, eyes closed.',
      '“The ant… naps.” — say it softly, almost a whisper.',
      'Do the snake and the cat the same way, and let them whisper it with you.',
      '“Can you make your toy nap?” — send them running to fetch one.',
    ],
    endingImage: `${P}/the-nap/p8-potato.png`,
    endingLine: 'The potato doesn’t… nap!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  7: {
    lessonNumber: 7,
    letter: 'm',
    traceTitle: 'Trace the m',
    title: 'Mmm, That\'s Good!',
    bookTitle: 'The ___ Sat on the Mat!',
    coverImage: `${P}/the-mat/p1-ant.png`,
    videoUrl: lessonVideoUrl(7),
    videoPosterUrl: lessonPictureUrl(7),
    pages: [
      { art: `${P}/the-mat/p1-ant.png`, sentence: 'The ant sat on the… mat!' },
      { art: `${P}/the-mat/p2-apple.png`, sentence: 'The apple sat on the… mat!' },
      { art: `${P}/the-mat/p3-sun.png`, sentence: 'The sun sat on the… mat!' },
      { art: `${P}/the-mat/p4-star.png`, sentence: 'The star sat on the… mat!' },
      { art: `${P}/the-mat/p5-snake.png`, sentence: 'The snake sat on the… mat!' },
      { art: `${P}/the-mat/p6-cat.png`, sentence: 'The cat sat on the… mat!' },
      { art: `${P}/the-mat/p7-recap.png`, sentence: 'Mat! Mat! Mat!', chant: true },
      { art: `${P}/the-mat/p8-potato.png`, sentence: 'The potato didn’t sit on the… mat!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant sat on the mat!', image: `${P}/the-mat/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake sat on the mat!', image: `${P}/the-mat/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat sat on the mat!', image: `${P}/the-mat/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato didn\'t sit on the mat!', image: `${P}/the-mat/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant sat on the mat!', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake sat on the mat!', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat sat on the mat!', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato didn\'t sit on the mat!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'did the ant sit on the mat?', answer: true, image: `${P}/the-mat/p1-ant.png` },
      { question: 'did the potato sit on the mat?', answer: false, image: `${P}/the-mat/p8-potato.png` },
      { question: 'did the apple sit on the mat?', answer: true, image: `${P}/the-mat/p2-apple.png` },
      { question: 'did the zebra sit on the mat?', answer: false, image: `${P}/zzz-at-the-zoo/p1-zebra.png` },
      { question: 'did the jellyfish sit on the mat?', answer: false, image: `${P}/jellyfish-in-the-jar/p4-jellyfish.png` },
      { question: 'did the sun sit on the mat?', answer: true, image: `${P}/the-mat/p3-sun.png` },
    ],
    script: [
      'Put a real mat, cloth or placemat on the table.',
      'Sit the toy ant on it. “The ant sat on the… mat!”',
      'Do the snake and the cat, letting them shout “mat!” each time.',
      '“Do you have a mat? Put your toy on it.” — send them running to fetch.',
    ],
    endingImage: `${P}/the-mat/p8-potato.png`,
    endingLine: 'The potato didn’t sit on the… mat!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  8: {
    lessonNumber: 8,
    letter: 'd',
    traceTitle: 'Trace the d',
    title: 'D for the Dog',
    bookTitle: 'The ___ Is Sad!',
    coverImage: `${P}/the-sad/p1-ant.png`,
    videoUrl: lessonVideoUrl(8),
    videoPosterUrl: lessonPictureUrl(8),
    pages: [
      { art: `${P}/the-sad/p1-ant.png`, sentence: 'The ant is… sad.' },
      { art: `${P}/the-sad/p2-apple.png`, sentence: 'The apple is… sad.' },
      { art: `${P}/the-sad/p3-sun.png`, sentence: 'The sun is… sad.' },
      { art: `${P}/the-sad/p4-star.png`, sentence: 'The star is… sad.' },
      { art: `${P}/the-sad/p5-snake.png`, sentence: 'The snake is… sad.' },
      { art: `${P}/the-sad/p6-cat.png`, sentence: 'The cat is… sad.' },
      { art: `${P}/the-sad/p7-recap.png`, sentence: 'Sad! Sad! Sad!', chant: true },
      { art: `${P}/the-sad/p8-potato.png`, sentence: 'The potato is not… sad!' },
      { art: `${P}/the-sad/p9-finale.png`, sentence: 'Now the whole crew is not… sad!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant is sad.', image: `${P}/the-sad/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake is sad.', image: `${P}/the-sad/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat is sad.', image: `${P}/the-sad/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato is not sad!', image: `${P}/the-sad/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant is sad.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake is sad.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat is sad.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato is not sad!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'was the ant sad?', answer: true, image: `${P}/the-sad/p1-ant.png` },
      { question: 'was the potato sad?', answer: false, image: `${P}/the-sad/p8-potato.png` },
      { question: 'was the apple sad?', answer: true, image: `${P}/the-sad/p2-apple.png` },
      { question: 'was the dinosaur sad?', answer: false, image: `${P}/dinosaur-on-a-drum/p4-dinosaur.png` },
      { question: 'was the owl sad?', answer: false, image: `${P}/owl-ate-an-orange/p1-owl.png` },
      { question: 'was the sun sad?', answer: true, image: `${P}/the-sad/p3-sun.png` },
    ],
    script: [
      'Hold up the toy ant and turn its face away, drooping.',
      '“The ant is… sad.” — say it low and slow.',
      'Do the snake and the cat the same way.',
      'Then the potato: “The potato is not… sad!” — big and bright, and they cheer.',
    ],
    endingImage: `${P}/the-sad/p9-finale.png`,
    endingLine: 'Now the whole crew is not… sad!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  9: {
    lessonNumber: 9,
    letter: 'g',
    traceTitle: 'Trace the g',
    title: 'G for the Goat',
    bookTitle: 'The ___ Digs!',
    coverImage: `${P}/the-dig/p1-ant.png`,
    videoUrl: lessonVideoUrl(9),
    videoPosterUrl: lessonPictureUrl(9),
    pages: [
      { art: `${P}/the-dig/p1-ant.png`, sentence: 'The ant… digs.' },
      { art: `${P}/the-dig/p2-apple.png`, sentence: 'The apple… digs.' },
      { art: `${P}/the-dig/p3-sun.png`, sentence: 'The sun… digs.' },
      { art: `${P}/the-dig/p4-star.png`, sentence: 'The star… digs.' },
      { art: `${P}/the-dig/p5-snake.png`, sentence: 'The snake… digs.' },
      { art: `${P}/the-dig/p6-cat.png`, sentence: 'The cat… digs.' },
      { art: `${P}/the-dig/p7-recap.png`, sentence: 'Dig! Dig! Dig!', chant: true },
      { art: `${P}/the-dig/p8-potato.png`, sentence: 'The potato doesn\'t… dig!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant digs.', image: `${P}/the-dig/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake digs.', image: `${P}/the-dig/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat digs.', image: `${P}/the-dig/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato doesn\'t dig!', image: `${P}/the-dig/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant digs.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake digs.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat digs.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato doesn\'t dig!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'did the ant dig?', answer: true, image: `${P}/the-dig/p1-ant.png` },
      { question: 'did the potato dig?', answer: false, image: `${P}/the-dig/p8-potato.png` },
      { question: 'did the apple dig?', answer: true, image: `${P}/the-dig/p2-apple.png` },
      { question: 'did the ox dig?', answer: false, image: `${P}/fox-in-a-box/p2-ox.png` },
      { question: 'did the frog dig?', answer: false, image: `${P}/frog-on-the-fan/p1-frog.png` },
      { question: 'did the sun dig?', answer: true, image: `${P}/the-dig/p3-sun.png` },
    ],
    script: [
      'Scratch at the table with the toy ant\'s front legs.',
      '“The ant… digs.” — dig along with the word.',
      'Do the snake and the cat, and let them dig on the table with you.',
      '“Can you make your toy dig?” — send them running to fetch one.',
    ],
    endingImage: `${P}/the-dig/p8-potato.png`,
    endingLine: 'The potato doesn\'t… dig!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  10: {
    lessonNumber: 10,
    letter: 'o',
    traceTitle: 'Trace the o',
    title: 'O for the Octopus',
    bookTitle: 'The ___ Has a Dog!',
    coverImage: `${P}/the-dog/p1-ant.png`,
    videoUrl: lessonVideoUrl(10),
    videoPosterUrl: lessonPictureUrl(10),
    pages: [
      { art: `${P}/the-dog/p1-ant.png`, sentence: 'The ant has a… dog.' },
      { art: `${P}/the-dog/p2-apple.png`, sentence: 'The apple has a… dog.' },
      { art: `${P}/the-dog/p3-sun.png`, sentence: 'The sun has a… dog.' },
      { art: `${P}/the-dog/p4-star.png`, sentence: 'The star has a… dog.' },
      { art: `${P}/the-dog/p5-snake.png`, sentence: 'The snake has a… dog.' },
      { art: `${P}/the-dog/p6-cat.png`, sentence: 'The cat has a… dog.' },
      { art: `${P}/the-dog/p7-recap.png`, sentence: 'Dog! Dog! Dog!', chant: true },
      { art: `${P}/the-dog/p8-potato.png`, sentence: 'The potato has 5… dogs!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant has a dog.', image: `${P}/the-dog/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake has a dog.', image: `${P}/the-dog/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat has a dog.', image: `${P}/the-dog/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato has 5 dogs!', image: `${P}/the-dog/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant has a dog.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake has a dog.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat has a dog.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato has 5 dogs!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'did the ant have a dog?', answer: true, image: `${P}/the-dog/p1-ant.png` },
      { question: 'did the duck have a dog?', answer: false, image: `${P}/on-a-rock/p1-duck.png` },
      { question: 'did the apple have a dog?', answer: true, image: `${P}/the-dog/p2-apple.png` },
      { question: 'did the chick have a dog?', answer: false, image: `${P}/on-a-rock/p2-chick.png` },
      { question: 'did the rabbit have a dog?', answer: false, image: `${P}/rabbit-in-the-rocket/p1-rabbit.png` },
      { question: 'did the sun have a dog?', answer: true, image: `${P}/the-dog/p3-sun.png` },
    ],
    script: [
      'Hold up the toy ant, and a second small toy as its dog.',
      'Walk them together. “The ant has a… dog.”',
      'Do the snake and the cat, each with their own dog.',
      '“Do you have a dog? Go and fetch it!” — send them running.',
    ],
    endingImage: `${P}/the-dog/p8-potato.png`,
    endingLine: 'The potato has 5… dogs!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  11: {
    lessonNumber: 11,
    letter: 'c',
    traceTitle: 'Trace the c',
    title: 'C for the Cat',
    bookTitle: 'The ___ Sat in a Cot!',
    coverImage: `${P}/the-cot/p1-ant.png`,
    videoUrl: lessonVideoUrl(11),
    videoPosterUrl: lessonPictureUrl(11),
    pages: [
      { art: `${P}/the-cot/p1-ant.png`, sentence: 'The ant sat in a… cot.' },
      { art: `${P}/the-cot/p2-apple.png`, sentence: 'The apple sat in a… cot.' },
      { art: `${P}/the-cot/p3-sun.png`, sentence: 'The sun sat in a… cot.' },
      { art: `${P}/the-cot/p4-star.png`, sentence: 'The star sat in a… cot.' },
      { art: `${P}/the-cot/p5-snake.png`, sentence: 'The snake sat in a… cot.' },
      { art: `${P}/the-cot/p6-cat.png`, sentence: 'The cat sat in a… cot.' },
      { art: `${P}/the-cot/p7-recap.png`, sentence: 'Cot! Cot! Cot!', chant: true },
      { art: `${P}/the-cot/p8-potato.png`, sentence: 'The potato didn’t sit in a… cot!' },
      { art: `${P}/the-cot/p9-potato-naps.png`, sentence: 'The potato… naps.' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant sat in a cot.', image: `${P}/the-cot/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake sat in a cot.', image: `${P}/the-cot/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat sat in a cot.', image: `${P}/the-cot/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato didn\'t sit in a cot!', image: `${P}/the-cot/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant sat in a cot.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake sat in a cot.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat sat in a cot.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato didn\'t sit in a cot!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'did the ant sit in a cot?', answer: true, image: `${P}/the-cot/p1-ant.png` },
      { question: 'did the potato sit in a cot?', answer: false, image: `${P}/the-cot/p8-potato.png` },
      { question: 'did the apple sit in a cot?', answer: true, image: `${P}/the-cot/p2-apple.png` },
      { question: 'did the otter sit in a cot?', answer: false, image: `${P}/owl-ate-an-orange/p2-otter.png` },
      { question: 'did the queen sit in a cot?', answer: false, image: `${P}/queen-on-the-quilt/p4-queen.png` },
      { question: 'did the sun sit in a cot?', answer: true, image: `${P}/the-cot/p3-sun.png` },
    ],
    script: [
      'Make a cot — a shoebox, a folded towel, a cupped pair of hands.',
      'Lay the toy ant in it. “The ant sat in a… cot.”',
      'Do the snake and the cat, letting them shout “cot!” each time.',
      '“Can you make a cot? Put your toy to bed in it.” — send them off to build one.',
    ],
    endingImage: `${P}/the-cot/p9-potato-naps.png`,
    endingLine: 'The potato… naps.',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  12: {
    lessonNumber: 12,
    letter: 'k',
    traceTitle: 'Trace the k',
    title: 'K Says It Too',
    bookTitle: 'The ___ Has a Kit!',
    coverImage: `${P}/the-kit/p1-ant.png`,
    videoUrl: lessonVideoUrl(12),
    videoPosterUrl: lessonPictureUrl(12),
    pages: [
      { art: `${P}/the-kit/p1-ant.png`, sentence: 'The ant has a… kit.' },
      { art: `${P}/the-kit/p2-apple.png`, sentence: 'The apple has a… kit.' },
      { art: `${P}/the-kit/p3-sun.png`, sentence: 'The sun has a… kit.' },
      { art: `${P}/the-kit/p4-star.png`, sentence: 'The star has a… kit.' },
      { art: `${P}/the-kit/p5-snake.png`, sentence: 'The snake has a… kit.' },
      { art: `${P}/the-kit/p6-cat.png`, sentence: 'The cat has a… kit.' },
      { art: `${P}/the-kit/p7-recap.png`, sentence: 'Kit! Kit! Kit!', chant: true },
      { art: `${P}/the-kit/p8-potato.png`, sentence: 'The potato doesn\'t have a… kit!' },
      { art: `${P}/the-kit/p9-crew.png`, sentence: 'The crew helps the… potato!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant has a kit.', image: `${P}/the-kit/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake has a kit.', image: `${P}/the-kit/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat has a kit.', image: `${P}/the-kit/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato doesn\'t have a kit!', image: `${P}/the-kit/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant has a kit.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake has a kit.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat has a kit.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato doesn\'t have a kit!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'did the ant have a kit?', answer: true, image: `${P}/the-kit/p1-ant.png` },
      { question: 'did the potato have a kit?', answer: false, image: `${P}/the-kit/p8-potato.png` },
      { question: 'did the apple have a kit?', answer: true, image: `${P}/the-kit/p2-apple.png` },
      { question: 'did the mouse have a kit?', answer: false, image: `${P}/monkey-in-my-mug/p1-mouse.png` },
      { question: 'did the monkey have a kit?', answer: false, image: `${P}/monkey-in-my-mug/p4-monkey.png` },
      { question: 'did the sun have a kit?', answer: true, image: `${P}/the-kit/p3-sun.png` },
    ],
    script: [
      'Gather a few plasters and a cloth — that is the kit.',
      'Hold it out with the toy ant. “The ant has a… kit.”',
      'Do the snake and the cat, each taking a turn to hold it.',
      'At the end: “The crew helps the… potato!” — everyone helps, nobody is left out.',
    ],
    endingImage: `${P}/the-kit/p9-crew.png`,
    endingLine: 'The crew helps the… potato!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  14: {
    lessonNumber: 14,
    letter: 'e',
    traceTitle: 'Trace the e',
    title: 'Crack the Egg, E!',
    bookTitle: 'The ___ Has an Egg!',
    coverImage: `${P}/the-egg/p1-ant.png`,
    videoUrl: lessonVideoUrl(14),
    videoPosterUrl: lessonPictureUrl(14),
    pages: [
      { art: `${P}/the-egg/p1-ant.png`, sentence: 'The ant has an… egg.' },
      { art: `${P}/the-egg/p2-apple.png`, sentence: 'The apple has an… egg.' },
      { art: `${P}/the-egg/p3-sun.png`, sentence: 'The sun has an… egg.' },
      { art: `${P}/the-egg/p4-star.png`, sentence: 'The star has an… egg.' },
      { art: `${P}/the-egg/p5-snake.png`, sentence: 'The snake has an… egg.' },
      { art: `${P}/the-egg/p6-cat.png`, sentence: 'The cat has an… egg.' },
      { art: `${P}/the-egg/p7-recap.png`, sentence: 'Egg! Egg! Egg!', chant: true },
      { art: `${P}/the-egg/p8-potato.png`, sentence: 'The potato had an… egg!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant has an egg.', image: `${P}/the-egg/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake has an egg.', image: `${P}/the-egg/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat has an egg.', image: `${P}/the-egg/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato had an egg!', image: `${P}/the-egg/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant has an egg.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake has an egg.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat has an egg.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato had an egg!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'did the ant have an egg?', answer: true, image: `${P}/the-egg/p1-ant.png` },
      { question: 'did the unicorn have an egg?', answer: false, image: `${P}/under-my-umbrella/p1-unicorn.png` },
      { question: 'did the apple have an egg?', answer: true, image: `${P}/the-egg/p2-apple.png` },
      { question: 'did the volcano have an egg?', answer: false, image: `${P}/volcano-in-the-van/p4-volcano.png` },
      { question: 'did the whale have an egg?', answer: false, image: `${P}/whale-in-the-wagon/p4-whale.png` },
      { question: 'did the sun have an egg?', answer: true, image: `${P}/the-egg/p3-sun.png` },
    ],
    script: [
      'Hold up a real egg, or a ball, or a rolled-up sock.',
      'Give it to the toy ant. “The ant has an… egg.”',
      'Pass it to the snake, then the cat, letting them shout “egg!” each time.',
      '“Do you have an egg? Go and find one!” — send them running.',
    ],
    endingImage: `${P}/the-egg/p8-potato.png`,
    endingLine: 'The potato had an… egg!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  15: {
    lessonNumber: 15,
    letter: 'u',
    traceTitle: 'Trace the u',
    title: 'Up Goes the Umbrella',
    bookTitle: 'The ___ Is in the Mud!',
    coverImage: `${P}/the-mud/p1-ant.png`,
    videoUrl: lessonVideoUrl(15),
    videoPosterUrl: lessonPictureUrl(15),
    pages: [
      { art: `${P}/the-mud/p1-ant.png`, sentence: 'The ant is in the… mud.' },
      { art: `${P}/the-mud/p2-apple.png`, sentence: 'The apple is in the… mud.' },
      { art: `${P}/the-mud/p3-sun.png`, sentence: 'The sun is in the… mud.' },
      { art: `${P}/the-mud/p4-star.png`, sentence: 'The star is in the… mud.' },
      { art: `${P}/the-mud/p5-snake.png`, sentence: 'The snake is in the… mud.' },
      { art: `${P}/the-mud/p6-cat.png`, sentence: 'The cat is in the… mud.' },
      { art: `${P}/the-mud/p7-recap.png`, sentence: 'Mud! Mud! Mud!', chant: true },
      { art: `${P}/the-mud/p8-potato.png`, sentence: 'The potato isn\'t in the… mud!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant is in the mud.', image: `${P}/the-mud/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake is in the mud.', image: `${P}/the-mud/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat is in the mud.', image: `${P}/the-mud/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato isn\'t in the mud!', image: `${P}/the-mud/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant is in the mud.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake is in the mud.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat is in the mud.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato isn\'t in the mud!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'was the ant in the mud?', answer: true, image: `${P}/the-mud/p1-ant.png` },
      { question: 'was the potato in the mud?', answer: false, image: `${P}/the-mud/p8-potato.png` },
      { question: 'was the apple in the mud?', answer: true, image: `${P}/the-mud/p2-apple.png` },
      { question: 'was the zebra in the mud?', answer: false, image: `${P}/zzz-at-the-zoo/p1-zebra.png` },
      { question: 'was the jellyfish in the mud?', answer: false, image: `${P}/jellyfish-in-the-jar/p4-jellyfish.png` },
      { question: 'was the sun in the mud?', answer: true, image: `${P}/the-mud/p3-sun.png` },
    ],
    script: [
      'Make some mud — a bowl of water and soil, or just mime it, hands and all.',
      'Sit the toy ant in it. “The ant is in the… mud.”',
      'Do the snake and the cat, and let them make the squelching noise with you.',
      '“Can your toy get in the mud?” — send them off to find one.',
    ],
    endingImage: `${P}/the-mud/p8-potato.png`,
    endingLine: 'The potato isn\'t in the… mud!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  16: {
    lessonNumber: 16,
    letter: 'r',
    traceTitle: 'Trace the r',
    title: 'Rrr Goes the Engine',
    bookTitle: 'The ___ Chased the Rat!',
    coverImage: `${P}/the-rat/p1-ant.png`,
    videoUrl: lessonVideoUrl(16),
    videoPosterUrl: lessonPictureUrl(16),
    pages: [
      { art: `${P}/the-rat/p1-ant.png`, sentence: 'The ant chased the… rat.' },
      { art: `${P}/the-rat/p2-apple.png`, sentence: 'The apple chased the… rat.' },
      { art: `${P}/the-rat/p3-sun.png`, sentence: 'The sun chased the… rat.' },
      { art: `${P}/the-rat/p4-star.png`, sentence: 'The star chased the… rat.' },
      { art: `${P}/the-rat/p5-snake.png`, sentence: 'The snake chased the… rat.' },
      { art: `${P}/the-rat/p6-cat.png`, sentence: 'The cat chased the… rat.' },
      { art: `${P}/the-rat/p7-recap.png`, sentence: 'Rat! Rat! Rat!', chant: true },
      { art: `${P}/the-rat/p8-potato.png`, sentence: 'The potato didn\'t chase the… rat!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant chased the rat.', image: `${P}/the-rat/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake chased the rat.', image: `${P}/the-rat/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat chased the rat.', image: `${P}/the-rat/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato didn\'t chase the rat!', image: `${P}/the-rat/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant chased the rat.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake chased the rat.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat chased the rat.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato didn\'t chase the rat!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'did the ant chase the rat?', answer: true, image: `${P}/the-rat/p1-ant.png` },
      { question: 'did the potato chase the rat?', answer: false, image: `${P}/the-rat/p8-potato.png` },
      { question: 'did the apple chase the rat?', answer: true, image: `${P}/the-rat/p2-apple.png` },
      { question: 'did the dinosaur chase the rat?', answer: false, image: `${P}/dinosaur-on-a-drum/p4-dinosaur.png` },
      { question: 'did the duck chase the rat?', answer: false, image: `${P}/on-a-rock/p1-duck.png` },
      { question: 'did the star chase the rat?', answer: true, image: `${P}/the-rat/p4-star.png` },
    ],
    script: [
      'Put a small toy across the table to be the rat.',
      'Run the toy ant after it. “The ant chased the… rat.”',
      'Do the snake and the cat, chasing it around the table.',
      '“Can you chase the rat?” — let them chase you across the room.',
    ],
    endingImage: `${P}/the-rat/p8-potato.png`,
    endingLine: 'The potato didn\'t chase the… rat!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  17: {
    lessonNumber: 17,
    letter: 'h',
    traceTitle: 'Trace the h',
    title: 'H, the Panting Pup',
    bookTitle: 'The ___ Is Hot!',
    coverImage: `${P}/the-hot/p1-ant.png`,
    videoUrl: lessonVideoUrl(17),
    videoPosterUrl: lessonPictureUrl(17),
    pages: [
      { art: `${P}/the-hot/p1-ant.png`, sentence: 'The ant is… hot.' },
      { art: `${P}/the-hot/p2-apple.png`, sentence: 'The apple is… hot.' },
      { art: `${P}/the-hot/p3-sun.png`, sentence: 'The sun is… hot.' },
      { art: `${P}/the-hot/p4-star.png`, sentence: 'The star is… hot.' },
      { art: `${P}/the-hot/p5-snake.png`, sentence: 'The snake is… hot.' },
      { art: `${P}/the-hot/p6-cat.png`, sentence: 'The cat is… hot.' },
      { art: `${P}/the-hot/p7-recap.png`, sentence: 'Hot! Hot! Hot!', chant: true },
      { art: `${P}/the-hot/p8-potato.png`, sentence: 'The potato isn\'t… hot!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant is hot.', image: `${P}/the-hot/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake is hot.', image: `${P}/the-hot/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat is hot.', image: `${P}/the-hot/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The potato isn\'t hot!', image: `${P}/the-hot/p8-potato.png` },
    ],
    matchOrder: ['snake', 'potato', 'ant', 'cat'],
    rounds: [
      { sentence: 'The ant is hot.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake is hot.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat is hot.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The potato isn\'t hot!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'was the ant hot?', answer: true, image: `${P}/the-hot/p1-ant.png` },
      { question: 'was the potato hot?', answer: false, image: `${P}/the-hot/p8-potato.png` },
      { question: 'was the apple hot?', answer: true, image: `${P}/the-hot/p2-apple.png` },
      { question: 'was the ox hot?', answer: false, image: `${P}/fox-in-a-box/p2-ox.png` },
      { question: 'was the frog hot?', answer: false, image: `${P}/frog-on-the-fan/p1-frog.png` },
      { question: 'was the sun hot?', answer: true, image: `${P}/the-hot/p3-sun.png` },
    ],
    script: [
      'Fan yourself and blow out, like a hot day.',
      'Hold up the toy ant. “The ant is… hot.”',
      'Do the snake and the cat, all of them fanning and puffing.',
      '“Are YOU hot?” — let them fan themselves and say it with you.',
    ],
    endingImage: `${P}/the-hot/p8-potato.png`,
    endingLine: 'The potato isn\'t… hot!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
  18: {
    lessonNumber: 18,
    letter: 'b',
    traceTitle: 'Trace the b',
    title: 'B for the Bobbing Boat',
    bookTitle: 'The ___ Saw a Bug!',
    coverImage: `${P}/the-bug/p1-ant.png`,
    videoUrl: lessonVideoUrl(18),
    videoPosterUrl: lessonPictureUrl(18),
    pages: [
      { art: `${P}/the-bug/p1-ant.png`, sentence: 'The ant saw a… bug.' },
      { art: `${P}/the-bug/p2-apple.png`, sentence: 'The apple saw a… bug.' },
      { art: `${P}/the-bug/p3-sun.png`, sentence: 'The sun saw a… bug.' },
      { art: `${P}/the-bug/p4-star.png`, sentence: 'The star saw a… bug.' },
      { art: `${P}/the-bug/p5-snake.png`, sentence: 'The snake saw a… bug.' },
      { art: `${P}/the-bug/p6-cat.png`, sentence: 'The cat saw a… bug.' },
      { art: `${P}/the-bug/p7-recap.png`, sentence: 'Bug! Bug! Bug!', chant: true },
      { art: `${P}/the-bug/p8-potato.png`, sentence: 'The bug saw a… potato!' },
    ],
    cast: [
      { id: 'ant', label: 'ant', sentence: 'The ant saw a bug.', image: `${P}/the-bug/p1-ant.png` },
      { id: 'snake', label: 'snake', sentence: 'The snake saw a bug.', image: `${P}/the-bug/p5-snake.png` },
      { id: 'cat', label: 'cat', sentence: 'The cat saw a bug.', image: `${P}/the-bug/p6-cat.png` },
      { id: 'potato', label: 'potato', sentence: 'The bug saw a potato!', image: `${P}/the-bug/p8-potato.png` },
    ],
    matchOrder: ['cat', 'potato', 'ant', 'snake'],
    rounds: [
      { sentence: 'The ant saw a bug.', answerId: 'ant', candidateIds: ['snake', 'cat', 'potato', 'ant'] },
      { sentence: 'The snake saw a bug.', answerId: 'snake', candidateIds: ['cat', 'potato', 'ant', 'snake'] },
      { sentence: 'The cat saw a bug.', answerId: 'cat', candidateIds: ['potato', 'ant', 'snake', 'cat'] },
      { sentence: 'The bug saw a potato!', answerId: 'potato', candidateIds: ['ant', 'snake', 'cat', 'potato'] },
    ],
    questions: [
      { question: 'did the ant see a bug?', answer: true, image: `${P}/the-bug/p1-ant.png` },
      { question: 'did the potato see a bug?', answer: false, image: `${P}/the-bug/p8-potato.png` },
      { question: 'did the apple see a bug?', answer: true, image: `${P}/the-bug/p2-apple.png` },
      { question: 'did the fox see a bug?', answer: false, image: `${P}/fox-in-a-box/p1-fox.png` },
      { question: 'did the horse see a bug?', answer: false, image: `${P}/horse-in-my-hat/p4-horse.png` },
      { question: 'did the sun see a bug?', answer: true, image: `${P}/the-bug/p3-sun.png` },
    ],
    script: [
      'Put a tiny toy — or your wiggling finger — on the table to be the bug.',
      'Turn the toy ant to look at it. “The ant saw a… bug.”',
      'Do the snake and the cat, each spotting it in turn.',
      'At the end it flips: “The bug saw a… potato!” — the bug does the spotting.',
    ],
    endingImage: `${P}/the-bug/p8-potato.png`,
    endingLine: 'The bug saw a… potato!',
    goodbyeLine: 'Great work today. Put your things somewhere safe — we need them again next time.',
  },
};
