// /api/montree/messages/broadcast/route.ts
// Session 97 — fan-out broadcast. Creates a single broadcast thread + adds all
// scope-resolved recipients as participants + posts the body as the first
// message. Recipients can read but typically cannot reply (broadcast = announce).

import { NextRequest, NextResponse } from 'next/server';
import { getSupabase } from '@/lib/supabase-client';
import { verifySchoolRequest } from '@/lib/montree/verify-request';
import {
  resolveBroadcastScope,
  createThreadWithParticipants,
} from '@/lib/montree/messaging/thread-resolver';
import type { BroadcastScope, SenderRole } from '@/lib/montree/messaging/types';
import { isFeatureEnabled } from '@/lib/montree/features/server';
import { sendAnnouncementEmail } from '@/lib/montree/email';

export const dynamic = 'force-dynamic';

interface PostBody {
  scope: BroadcastScope;
  subject?: string;
  body: string;
  /** Defaults to false — broadcasts are usually one-way announcements. */
  allow_replies?: boolean;
}

export async function POST(request: NextRequest) {
  const auth = await verifySchoolRequest(request);
  if (auth instanceof NextResponse) return auth;
  if (auth.role === 'agent') {
    return NextResponse.json({ error: 'Agents cannot use messaging' }, { status: 403 });
  }

  // Only principals + teachers can broadcast.
  if (auth.role !== 'principal' && auth.role !== 'teacher') {
    return NextResponse.json({ error: 'Not allowed' }, { status: 403 });
  }

  let body: PostBody;
  try {
    body = (await request.json()) as PostBody;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }
  if (!body.scope || !body.body || !body.body.trim()) {
    return NextResponse.json({ error: 'scope and body required' }, { status: 400 });
  }
  if (body.body.length > 10000) {
    return NextResponse.json({ error: 'body exceeds 10000 chars' }, { status: 400 });
  }

  // Teachers can only broadcast to all_parents in their classroom or to other
  // teachers. They CANNOT broadcast to all_parents school-wide or to a custom
  // group they don't own.
  if (auth.role === 'teacher') {
    if (body.scope.kind === 'all_parents') {
      return NextResponse.json(
        { error: 'Teachers can only broadcast within their classroom' },
        { status: 403 }
      );
    }
    if (body.scope.kind === 'classroom_parents' && body.scope.classroom_id !== auth.classroomId) {
      return NextResponse.json({ error: 'Wrong classroom' }, { status: 403 });
    }
    if (body.scope.kind === 'classroom_teachers' && body.scope.classroom_id !== auth.classroomId) {
      return NextResponse.json({ error: 'Wrong classroom' }, { status: 403 });
    }
  }

  const supabase = getSupabase();
  const recipients = await resolveBroadcastScope(supabase, auth.schoolId, body.scope);

  if (!recipients.length) {
    return NextResponse.json({ error: 'No recipients matched the scope' }, { status: 400 });
  }

  const callerRole = auth.role === 'homeschool_parent' ? 'parent' : (auth.role as 'teacher' | 'principal');

  // Resolve sender's display name once.
  let senderName = 'Unknown';
  if (callerRole === 'teacher') {
    const { data: t } = await supabase.from('montree_teachers').select('name').eq('id', auth.userId).maybeSingle();
    senderName = t?.name || senderName;
  } else if (callerRole === 'principal') {
    const { data: p } = await supabase.from('montree_school_admins').select('name').eq('id', auth.userId).maybeSingle();
    senderName = p?.name || senderName;
  }

  // Determine classroom_id hint for the thread.
  let classroomId: string | null = null;
  if (body.scope.kind === 'classroom_teachers' || body.scope.kind === 'classroom_parents') {
    classroomId = body.scope.classroom_id;
  }

  // Subject defaults to a friendly autogenerated label.
  let subject = body.subject?.trim() || '';
  if (!subject) {
    subject =
      body.scope.kind === 'all_teachers'
        ? 'Message to all teachers'
        : body.scope.kind === 'all_parents'
          ? 'Message to all parents'
          : body.scope.kind === 'classroom_teachers'
            ? 'Message to classroom teachers'
            : body.scope.kind === 'classroom_parents'
              ? 'Message to classroom parents'
              : 'Group message';
  }

  // Create the thread with all recipients.
  const thread = await createThreadWithParticipants(supabase, {
    schoolId: auth.schoolId,
    classroomId,
    childId: null,
    threadType: body.scope.kind === 'group' ? 'group' : 'broadcast',
    subject,
    groupId: body.scope.kind === 'group' ? body.scope.group_id : null,
    createdBy: { role: callerRole, id: auth.userId },
    participants: recipients.map((r) => ({
      role: r.role,
      id: r.id,
      canReply: !!body.allow_replies,
      isObserver: false,
    })),
  });
  if (!thread) {
    return NextResponse.json({ error: 'Failed to create broadcast thread' }, { status: 500 });
  }

  // Post the first message.
  const { error: msgErr } = await supabase.from('montree_thread_messages').insert({
    thread_id: thread.id,
    sender_role: callerRole as SenderRole,
    sender_id: auth.userId,
    sender_name: senderName,
    body: body.body.trim(),
  });
  if (msgErr) {
    console.error('[broadcast] message insert failed', msgErr);
    return NextResponse.json({ error: 'Thread created but message failed' }, { status: 500 });
  }

  // 🚨 Phase 3 — Newsletter email push.
  // When the school has the `principal_newsletter` feature flag ON AND
  // the broadcast targets parents (any scope containing parents), fire
  // emails to those parents alongside the in-app delivery. Fire-and-
  // forget — failure here NEVER blocks the broadcast itself.
  const parentRecipients = recipients.filter((r) => r.role === 'parent');
  if (parentRecipients.length > 0) {
    void (async () => {
      try {
        const flagOn = await isFeatureEnabled(
          supabase,
          auth.schoolId,
          'principal_newsletter'
        );
        if (!flagOn) return;

        // Hydrate parent emails. We already have the IDs from recipients.
        const parentIds = parentRecipients.map((r) => r.id);
        const { data: parentRows } = await supabase
          .from('montree_parents')
          .select('id, email, name')
          .in('id', parentIds)
          .eq('is_active', true);

        // Resolve school name once for the email header.
        const { data: school } = await supabase
          .from('montree_schools')
          .select('name')
          .eq('id', auth.schoolId)
          .maybeSingle();
        const schoolName = (school as { name: string } | null)?.name || 'Your school';

        const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://montree.xyz';
        const threadUrl = `${appUrl.replace(/\/$/, '')}/montree/parent/messages/${thread.id}`;

        type ParentRow = { id: string; email: string | null; name: string | null };
        // Cap concurrency to avoid hammering Resend on a 500-parent broadcast.
        // Fire 5 at a time.
        const queue = ((parentRows || []) as ParentRow[]).filter((p) => p.email);
        const concurrency = 5;
        let index = 0;
        async function worker() {
          while (index < queue.length) {
            const myIndex = index++;
            const p = queue[myIndex];
            try {
              await sendAnnouncementEmail(p.email as string, {
                schoolName,
                senderName,
                subject,
                bodyPlain: body.body.trim(),
                threadUrl,
              });
            } catch (err) {
              console.error('[broadcast email] send failed', p.id, err);
            }
          }
        }
        await Promise.all(
          Array.from({ length: Math.min(concurrency, queue.length) }, () => worker())
        );
      } catch (err) {
        console.error('[broadcast email] fan-out failed', err);
      }
    })();
  }

  return NextResponse.json(
    { thread_id: thread.id, recipient_count: recipients.length },
    { status: 201 }
  );
}
