// /api/montree/messages/broadcast/route.ts
// Session 97 — fan-out broadcast. Creates a single broadcast thread + adds all
// scope-resolved recipients as participants + posts the body as the first
// message. Recipients can read but typically cannot reply (broadcast = announce).

import { NextRequest, NextResponse } from 'next/server';
import { getSupabase } from '@/lib/supabase-client';
import { verifySchoolRequest } from '@/lib/montree/verify-request';
import {
  resolveBroadcastScope,
  createThreadWithParticipants,
} from '@/lib/montree/messaging/thread-resolver';
import type { BroadcastScope, SenderRole } from '@/lib/montree/messaging/types';

export const dynamic = 'force-dynamic';

interface PostBody {
  scope: BroadcastScope;
  subject?: string;
  body: string;
  /** Defaults to false — broadcasts are usually one-way announcements. */
  allow_replies?: boolean;
}

export async function POST(request: NextRequest) {
  const auth = await verifySchoolRequest(request);
  if (auth instanceof NextResponse) return auth;
  if (auth.role === 'agent') {
    return NextResponse.json({ error: 'Agents cannot use messaging' }, { status: 403 });
  }

  // Only principals + teachers can broadcast.
  if (auth.role !== 'principal' && auth.role !== 'teacher') {
    return NextResponse.json({ error: 'Not allowed' }, { status: 403 });
  }

  let body: PostBody;
  try {
    body = (await request.json()) as PostBody;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }
  if (!body.scope || !body.body || !body.body.trim()) {
    return NextResponse.json({ error: 'scope and body required' }, { status: 400 });
  }
  if (body.body.length > 10000) {
    return NextResponse.json({ error: 'body exceeds 10000 chars' }, { status: 400 });
  }

  // Teachers can only broadcast to all_parents in their classroom or to other
  // teachers. They CANNOT broadcast to all_parents school-wide or to a custom
  // group they don't own.
  if (auth.role === 'teacher') {
    if (body.scope.kind === 'all_parents') {
      return NextResponse.json(
        { error: 'Teachers can only broadcast within their classroom' },
        { status: 403 }
      );
    }
    if (body.scope.kind === 'classroom_parents' && body.scope.classroom_id !== auth.classroomId) {
      return NextResponse.json({ error: 'Wrong classroom' }, { status: 403 });
    }
    if (body.scope.kind === 'classroom_teachers' && body.scope.classroom_id !== auth.classroomId) {
      return NextResponse.json({ error: 'Wrong classroom' }, { status: 403 });
    }
  }

  const supabase = getSupabase();
  const recipients = await resolveBroadcastScope(supabase, auth.schoolId, body.scope);

  if (!recipients.length) {
    return NextResponse.json({ error: 'No recipients matched the scope' }, { status: 400 });
  }

  const callerRole = auth.role === 'homeschool_parent' ? 'parent' : (auth.role as 'teacher' | 'principal');

  // Resolve sender's display name once.
  let senderName = 'Unknown';
  if (callerRole === 'teacher') {
    const { data: t } = await supabase.from('montree_teachers').select('name').eq('id', auth.userId).maybeSingle();
    senderName = t?.name || senderName;
  } else if (callerRole === 'principal') {
    const { data: p } = await supabase.from('montree_school_admins').select('name').eq('id', auth.userId).maybeSingle();
    senderName = p?.name || senderName;
  }

  // Determine classroom_id hint for the thread.
  let classroomId: string | null = null;
  if (body.scope.kind === 'classroom_teachers' || body.scope.kind === 'classroom_parents') {
    classroomId = body.scope.classroom_id;
  }

  // Subject defaults to a friendly autogenerated label.
  let subject = body.subject?.trim() || '';
  if (!subject) {
    subject =
      body.scope.kind === 'all_teachers'
        ? 'Message to all teachers'
        : body.scope.kind === 'all_parents'
          ? 'Message to all parents'
          : body.scope.kind === 'classroom_teachers'
            ? 'Message to classroom teachers'
            : body.scope.kind === 'classroom_parents'
              ? 'Message to classroom parents'
              : 'Group message';
  }

  // Create the thread with all recipients.
  const thread = await createThreadWithParticipants(supabase, {
    schoolId: auth.schoolId,
    classroomId,
    childId: null,
    threadType: body.scope.kind === 'group' ? 'group' : 'broadcast',
    subject,
    groupId: body.scope.kind === 'group' ? body.scope.group_id : null,
    createdBy: { role: callerRole, id: auth.userId },
    participants: recipients.map((r) => ({
      role: r.role,
      id: r.id,
      canReply: !!body.allow_replies,
      isObserver: false,
    })),
  });
  if (!thread) {
    return NextResponse.json({ error: 'Failed to create broadcast thread' }, { status: 500 });
  }

  // Post the first message.
  const { error: msgErr } = await supabase.from('montree_thread_messages').insert({
    thread_id: thread.id,
    sender_role: callerRole as SenderRole,
    sender_id: auth.userId,
    sender_name: senderName,
    body: body.body.trim(),
  });
  if (msgErr) {
    console.error('[broadcast] message insert failed', msgErr);
    return NextResponse.json({ error: 'Thread created but message failed' }, { status: 500 });
  }

  return NextResponse.json(
    { thread_id: thread.id, recipient_count: recipients.length },
    { status: 201 }
  );
}
