// lib/sanctuary-e2e/gen-vectors.mjs
//
// One-shot generator for vectors.json — the cross-language known-answer
// contract. Run:
//
//   node --experimental-strip-types lib/sanctuary-e2e/gen-vectors.mjs
//
// (.mjs — NOT in the tsconfig include globs — so tsc never trips over the
//  required `./crypto.ts` extension; node's type-stripper strips crypto.ts.)
//
// Inputs are FIXED (not random) so the output is deterministic and stable:
// re-running must produce a byte-identical vectors.json. The Swift XCTest
// (Step 7) loads the SAME vectors.json and asserts swift-sodium reproduces it
// — that is the real cross-implementation parity proof. The TS test merely
// regression-locks this reference impl against the committed vectors.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  ready,
  deriveMaster,
  deriveContentKey,
  deriveAuthSecret,
  authVerifier,
  encryptWithNonce,
  decrypt,
  hex,
  b64,
  unhex,
  CONTENT_KEY_CTX,
  AUTH_SECRET_CTX,
  CONTENT_KEY_SUBKEY_ID,
  AUTH_SECRET_SUBKEY_ID,
  ARGON2_OPSLIMIT,
  ARGON2_MEMLIMIT,
  WIRE_PREFIX,
} from './crypto.ts';

// ── FIXED inputs ────────────────────────────────────────────────────────────
const PASSWORD = 'sanctuary-kat-v1: correct horse battery staple';
const SALT_HEX = '00112233445566778899aabbccddeeff'; // 16 bytes
const NONCE_HEX = '0102030405060708090a0b0c0d0e0f101112131415161718'; // 24 bytes
const PLAINTEXT = "The corner where it's quiet. 🌿 Día uno — café.";

async function main() {
  await ready();

  const salt = unhex(SALT_HEX);
  const nonce = unhex(NONCE_HEX);

  const master = deriveMaster(PASSWORD, salt);
  const contentKey = deriveContentKey(master);
  const authSecret = deriveAuthSecret(master);
  const verifier = authVerifier(authSecret);
  const wire = encryptWithNonce(PLAINTEXT, contentKey, nonce);

  // Self-check: the produced wire must decrypt back to the plaintext.
  const roundTrip = decrypt(wire, contentKey);
  if (roundTrip !== PLAINTEXT) {
    throw new Error(`[gen-vectors] round-trip mismatch: got ${JSON.stringify(roundTrip)}`);
  }

  const vectors = {
    _comment:
      'Known-answer vectors for the Sanctuary E2E crypto core. Generated by ' +
      'lib/sanctuary-e2e/gen-vectors.mjs. Swift swift-sodium must reproduce ' +
      'expected.* byte-for-byte (Step 7 XCTest). Do not hand-edit.',
    spec: 'docs/SANCTUARY_NATIVE_BUILD_RUNBOOK.md §3',
    params: {
      argon2: {
        alg: 'ARGON2ID13',
        opslimit: ARGON2_OPSLIMIT,
        memlimit_bytes: ARGON2_MEMLIMIT,
        keylen: 32,
      },
      kdf: {
        content: { subkey_id: CONTENT_KEY_SUBKEY_ID, ctx: CONTENT_KEY_CTX },
        auth: { subkey_id: AUTH_SECRET_SUBKEY_ID, ctx: AUTH_SECRET_CTX },
      },
      base64_variant: 'ORIGINAL',
      wire_prefix: WIRE_PREFIX,
    },
    input: {
      password_utf8: PASSWORD,
      salt_hex: SALT_HEX,
      nonce_hex: NONCE_HEX,
      plaintext_utf8: PLAINTEXT,
    },
    expected: {
      master_hex: hex(master),
      contentKey_hex: hex(contentKey),
      authSecret_hex: hex(authSecret),
      authSecret_b64: b64(authSecret),
      verifier_hex: hex(verifier),
      verifier_b64: b64(verifier),
      wire,
    },
  };

  const out = join(dirname(fileURLToPath(import.meta.url)), 'vectors.json');
  writeFileSync(out, JSON.stringify(vectors, null, 2) + '\n');
  console.log('wrote', out);
  console.log('master  ', vectors.expected.master_hex);
  console.log('verifier', vectors.expected.verifier_hex);
  console.log('wire    ', vectors.expected.wire);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
