# -*- coding: utf-8 -*-
# Letter I — initial-sound picture book, "Into the Igloo".
#
# 🚨 PHOTO-ILLUSTRATED ON PURPOSE. Like the letter-P book, this book's art is
# hyper-realistic photography, not the locked Montree Phonics pen-and-ink house
# style. This is the SECOND deliberate, sanctioned exception, decided by Tredoux
# 2026-07-28 — it is NOT a repeat of the 2026-07-20 incident where photoreal art
# was generated by mistake. See CLAUDE.md "Letter P photo-illustrated exception"
# and the Jul-27 handoff before regenerating anything.
#
# Built in dpbuild's `sound` mode (the `if 'sound' in book` branch of
# page_words) — the child SHOUTS the picture word, does not decode it. `igloo`,
# `iguana`, `inchworm`, `insect` and `infant` are none of them decodable at the
# letter-i gate; they are picture words, named aloud from the image.
#
# Art source: the Midjourney scenes staged at
#   _incoming-week5-i/book-scenes/  (Mac repo) ->
#   /mnt/user-data/uploads/montree/_incoming-week5-i/book-scenes/  (Cowork)
# When these are filed permanently they should move to
# phonics-images/satpin-v2/books/igloo/ alongside the pig set (that tree is
# gitignored — the PNGs live on Tredoux's Mac only).
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dpbuild import build, BOOKS_ROOT

# Container default; set MONTREE_I_ART / MONTREE_BOOK_OUT to build on a Mac.
ART = os.environ.get('MONTREE_I_ART',
                     '/mnt/user-data/uploads/montree/_incoming-week5-i/book-scenes')
OUT = os.environ.get('MONTREE_BOOK_OUT', '/tmp/work/print')
SLUG = 'into-the-igloo'

BOOK = dict(
    slug=SLUG,
    title_lines=['Into the', 'Igloo'], title_accent='Igloo', title_size=46,
    band='LETTER I  ·  INITIAL SOUND  ·  listen for /i/',
    booknum='LETTER I',
    cover=ART + '/warm-inside-scene.png',
    sound='i',
    sound_note='i says /i/ — every picture starts with it',
    oral_words='igloo · iguana · inchworm · insect · infant',
    # Cumulative decodable gate through week 5 (s a t p i learnt) — mirrors the
    # NEW lists of books three/four/five in books_def.py, newest-first, the same
    # order the SATPIN library ledger renders.
    decodable=['sit · it · is · sip · pit · spit',
               'sap · pat · tap · spat · sat · at'],
    heart='heart word — a',
    oral_note='the teacher reads the grey line — the child shouts the picture word',
    # House layout is ONE grey narration line + ONE big shouted picture word
    # (see bookP.py / the-pig-ate-a-pineapple pages). A two-line shout collides
    # with the narration baseline, so the sentence is split lead-in / shout.
    spreads=[
        dict(nar='The iguana went into the…', text='igloo!', size=92,
             art=ART + '/iguana-scene.png'),
        dict(nar='The inchworm went into the…', text='igloo!', size=92,
             art=ART + '/inchworm-scene.png'),
        dict(nar='The infant went into the…', text='igloo!', size=92,
             art=ART + '/infant-scene.png'),
        dict(nar='The insect went into the…', text='igloo!', size=92,
             art=ART + '/insect-scene.png'),
        dict(nar='And it’s warm inside the…', text='igloo!', style='drop', size=92,
             art=ART + '/warm-inside-scene.png'),
    ],
)

build(BOOK, OUT)
