# -*- coding: utf-8 -*-
# Letter N — initial-sound picture book, "The Nest is in the Nest".
#
# 🚨 PHOTO-ILLUSTRATED ON PURPOSE. Like the letter-P and letter-I books, this
# book's art is hyper-realistic photography, not the locked Montree Phonics
# pen-and-ink house style. This is the THIRD deliberate, sanctioned exception,
# approved by Tredoux 2026-07-30, matching the P (2026-07-27) and I
# (2026-07-28) exceptions — it is NOT a repeat of the 2026-07-20 incident
# where photoreal art was generated by mistake. See CLAUDE.md "Letter P
# photo-illustrated exception" before regenerating anything.
#
# Built in dpbuild's `sound` mode (the `if 'sound' in book` branch of
# page_words) — the child SHOUTS the picture word, does not decode it. `nut`,
# `net`, `napkin`, `nail` and `nest` are picture words, named aloud from the
# image; the decodable gate at letter n covers a different, cumulative word
# list (see `decodable=` below).
#
# Art source: unlike letter I, this art is already filed permanently, at
#   phonics-images/satpin-v2/books/nest/  (Mac repo, real home)
# It is also staged for this week's build at
#   _incoming-week6-n/book-scenes/  (Mac repo) ->
#   /mnt/user-data/uploads/montree/_incoming-week6-n/book-scenes/  (Cowork)
# Do not repeat letter I's debt of building against the incoming tray only —
# `artDir` in letters/n.json points at the permanent nest/ location.
import os, sys
sys.path.insert(0, '/mnt/user-data/uploads/montree/scripts/curriculum/dark-phonics-readers')
from dpbuild import build, BOOKS_ROOT

# Container default; set MONTREE_N_ART / MONTREE_BOOK_OUT to build on a Mac.
ART = os.environ.get('MONTREE_N_ART', '/tmp/n-book-art')
OUT = os.environ.get('MONTREE_BOOK_OUT', '/tmp/work/print')
SLUG = 'the-nest-is-in-the-nest'

BOOK = dict(
    slug=SLUG,
    title_lines=['The Nest is', 'in the Nest'], title_accent='Nest', title_size=40,
    band='LETTER N  ·  INITIAL SOUND  ·  listen for /n/',
    booknum='LETTER N',
    cover=ART + '/cover-scene.png',
    sound='n',
    sound_note='n says /n/ — every picture starts with it',
    oral_words='nut · nest · net · napkin · nail',
    # Cumulative decodable gate through week 6 (s a t p i n learnt), newest-
    # first — mirrors the NEW/REVIEW lists of the week's flashcard books, the
    # same order the SATPIN library ledger renders.
    decodable=['an · ant · in · nap · naps · pan · tin · nip · snap',
               'sit · it · is · sip · pit · spit',
               'sap · pat · tap · spat · sat · at'],
    heart='heart words — a · I',
    oral_note='the teacher reads the grey line — the child shouts the picture word',
    # House layout is ONE grey narration line + ONE big shouted picture word
    # (see bookI.py / bookP.py). A two-line shout collides with the narration
    # baseline, so the sentence is split lead-in / shout.
    spreads=[
        dict(nar='The nut is in the…', text='nest!', size=92,
             art=ART + '/nut-scene.png'),
        dict(nar='The net is in the…', text='nest!', size=92,
             art=ART + '/net-scene.png'),
        dict(nar='The napkin is in the…', text='nest!', size=92,
             art=ART + '/napkin-scene.png'),
        dict(nar='The nail is in the…', text='nest!', size=92,
             art=ART + '/nail-scene.png'),
        dict(nar='And the nest is in the…', text='nest!', style='drop', size=92,
             art=ART + '/nest-in-nest-scene.png'),
    ],
)

build(BOOK, OUT)
