# -*- coding: utf-8 -*-
# Letter P — initial-sound picture book.
#
# 🚨 PHOTO-ILLUSTRATED ON PURPOSE. This book's art is hyper-realistic
# photography, not the locked Dark Phonics pen-and-ink house style. Decided by
# Tredoux 2026-07-27 with the rule in front of him; it is NOT a repeat of the
# 2026-07-20 incident where photoreal art was generated by mistake. See
# CLAUDE.md "Letter P photo-illustrated exception" before regenerating anything.
#
# Built in dpbuild's `sound` mode (the `if 'sound' in book` branch of
# page_words) — the child SHOUTS the picture word, does not decode it. That is
# what allows pineapple/pencil to sit next to pan: only `pan` is decodable at
# the letter-p gate.
import sys
sys.path.insert(0, '/mnt/user-data/uploads/montree/scripts/curriculum/dark-phonics-readers')
from dpbuild import build, BOOKS_ROOT

S = BOOKS_ROOT + '/pig'
SLUG = 'the-pig-ate-a-pineapple'

BOOK = dict(
    slug=SLUG,
    title_lines=['The Pig Ate', 'a Pineapple'], title_accent='Pineapple', title_size=34,
    band='LETTER P  ·  INITIAL SOUND  ·  listen for /p/',
    booknum='LETTER P',
    cover=S + '/' + SLUG + '-p5-pig-sick-v1.png',
    sound='p',
    sound_note='p says /p/ — every picture starts with it',
    oral_words='pineapple · pen · pencil · pan · pig',
    # Cumulative decodable gate at letter p (s a t p learnt) — mirrors the
    # NEW/REVIEW lists of book four ('spat') plus week 3's 'at · sat'.
    decodable='at · sat · pat · tap · sap · spat',
    heart='heart word — a',
    oral_note='the teacher reads the grey line — the child shouts the picture word',
    spreads=[
        dict(nar='The pig ate a…', text='pineapple!', size=92,
             art=S + '/' + SLUG + '-p1-pineapple-v1.png'),
        dict(nar='The pig ate a…', text='pen!', size=92,
             art=S + '/' + SLUG + '-p2-pen-v1.png'),
        dict(nar='The pig ate a…', text='pencil!', size=92,
             art=S + '/' + SLUG + '-p3-pencil-v1.png'),
        dict(nar='The pig ate a…', text='pan!', size=92,
             art=S + '/' + SLUG + '-p4-pan-v1.png'),
        dict(nar='And now the pig is…', text='sick!', style='drop', size=92,
             art=S + '/' + SLUG + '-p5-pig-sick-v1.png'),
    ],
)

build(BOOK, '/tmp/work/print')
