// Tutorial configuration and data constants
import { TutorialStep, Student } from './types';

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Your Classroom',
    message: "This is your classroom overview. Each tile represents a student. Let's explore!",
    target: 'none',
    nextOn: 'manual',
    emoji: '👋',
    position: 'center',
  },
  {
    id: 'select-student',
    title: "Let's Start with Rachel",
    message: 'Tap on Rachel to see her progress and weekly works.',
    target: '[data-student="Rachel"]',
    action: 'tap',
    nextOn: 'click',
    emoji: '👆',
    highlight: true,
    position: 'bottom',
  },
  {
    id: 'student-view',
    title: "Rachel's Work View",
    message: "Here you can see Rachel's assigned works for the week. Each row is a Montessori activity.",
    target: 'none',
    nextOn: 'manual',
    emoji: '📋',
    position: 'top',
  },
  {
    id: 'tap-status',
    title: 'Update Progress',
    message: 'Tap the status badge to cycle through: Not Started → Presented → Practicing → Mastered',
    target: '[data-status-badge]',
    action: 'tap',
    nextOn: 'click',
    emoji: '🎯',
    highlight: true,
    position: 'bottom',
  },
  {
    id: 'expand-work',
    title: 'See More Details',
    message: 'Tap the work name to expand and see notes, video, and photo options.',
    target: '[data-work-row]',
    action: 'tap',
    nextOn: 'click',
    emoji: '📝',
    highlight: true,
    position: 'bottom',
  },
  {
    id: 'add-note',
    title: 'Add a Note',
    message: 'Notes you add here will appear in the weekly parent report. Try typing something!',
    target: '[data-notes-input]',
    nextOn: 'manual',
    emoji: '✍️',
    position: 'top',
  },
  {
    id: 'watch-video',
    title: 'Quick Refresher',
    message: 'Tap "Demo" to watch a presentation video on YouTube. Great for training or review!',
    target: '[data-demo-button]',
    nextOn: 'manual',
    emoji: '🎬',
    highlight: true,
    position: 'bottom',
  },
  {
    id: 'take-photo',
    title: 'Capture the Moment',
    message: "Photos are proof of work. They appear in reports so parents see what their child actually did.",
    target: '[data-capture-button]',
    nextOn: 'manual',
    emoji: '📸',
    highlight: true,
    position: 'bottom',
  },
  {
    id: 'random-work',
    title: '😮 Child Chose a Random Work!',
    message: "This happens all the time! The child picked something not on this week's plan...",
    target: 'none',
    nextOn: 'auto',
    delay: 2000,
    emoji: '😮',
    position: 'center',
  },
  {
    id: 'open-wheel',
    title: 'The Selection Wheel',
    message: 'Hold the area icon (P, S, M, L, or C) to open a wheel of ALL works in that area.',
    target: '[data-area-icon]',
    action: 'hold',
    nextOn: 'manual',
    emoji: '🎡',
    highlight: true,
    position: 'bottom',
  },
  {
    id: 'progress-tab',
    title: 'Progress Overview',
    message: "Now let's check the Progress tab. Get a bird's eye view of where each child stands.",
    target: '[data-tab="progress"]',
    action: 'tap',
    nextOn: 'click',
    emoji: '📊',
    highlight: true,
    position: 'bottom',
  },
  {
    id: 'progress-view',
    title: 'At a Glance',
    message: 'See which areas need attention. Green = mastered, Blue = practicing, Yellow = presented.',
    target: 'none',
    nextOn: 'manual',
    emoji: '👁️',
    position: 'top',
  },
  {
    id: 'grand-finale-intro',
    title: '🎉 The Grand Finale',
    message: "Now for the magic. Where all this data becomes something beautiful...",
    target: 'none',
    nextOn: 'auto',
    delay: 2500,
    emoji: '✨',
    position: 'center',
  },
  {
    id: 'reports-tab',
    title: 'Weekly Reports',
    message: "Tap the Reports tab to see the culmination of everything.",
    target: '[data-tab="reports"]',
    action: 'tap',
    nextOn: 'click',
    emoji: '📄',
    highlight: true,
    position: 'bottom',
  },
  {
    id: 'generate-report',
    title: 'Generate a Report',
    message: "With one tap, all the week's work, notes, and photos become a beautiful parent report.",
    target: '[data-generate-report]',
    nextOn: 'manual',
    emoji: '✨',
    highlight: true,
    position: 'bottom',
  },
  {
    id: 'preview-report',
    title: 'Preview the Magic',
    message: 'Click to preview what parents will see. Professional, beautiful, effortless.',
    target: '[data-report-card]',
    nextOn: 'manual',
    emoji: '👀',
    highlight: true,
    position: 'bottom',
  },
  {
    id: 'conclusion',
    title: 'There We Have It',
    message: '',
    target: 'none',
    nextOn: 'manual',
    emoji: '🏆',
    position: 'center',
  },
];

export const AVATAR_GRADIENTS = [
  'from-emerald-500 to-teal-500',
  'from-blue-500 to-indigo-500',
  'from-amber-500 to-orange-500',
  'from-pink-500 to-rose-500',
  'from-purple-500 to-violet-500',
  'from-cyan-500 to-sky-500',
];

export function getGradient(index: number) {
  return AVATAR_GRADIENTS[index % AVATAR_GRADIENTS.length];
}

export const DEMO_STUDENTS: Student[] = [
  { id: 'demo-1', name: 'Rachel', progress: { presented: 12, practicing: 8, mastered: 24, total: 44 } },
  { id: 'demo-2', name: 'Marcus', progress: { presented: 8, practicing: 15, mastered: 18, total: 41 } },
  { id: 'demo-3', name: 'Sophie', progress: { presented: 5, practicing: 12, mastered: 30, total: 47 } },
  { id: 'demo-4', name: 'James', progress: { presented: 10, practicing: 6, mastered: 22, total: 38 } },
  { id: 'demo-5', name: 'Lily', progress: { presented: 7, practicing: 11, mastered: 26, total: 44 } },
  { id: 'demo-6', name: 'Oliver', progress: { presented: 9, practicing: 14, mastered: 20, total: 43 } },
];
