// lib/montree/english-sequence/lesson-coverage.ts
// GENERATED by scripts/_tmp_group_ids.py from phonics-data lessonNums.
// Lean list of the lessons (1..128) that have at least one generatable
// word-bank group, so the dashboard can gate the "Make materials" link
// WITHOUT importing the heavy phonics-data module. Source of truth for the
// join is lesson-materials.ts (lessonCoverage()); regenerate if lessonNums change.

export const LESSONS_WITH_MATERIALS: ReadonlySet<number> = new Set([5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 54, 55, 56, 57, 58, 59, 71, 72, 73, 74, 75, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 104, 105]);

/** True when lesson N (1..128) has at least one printable word-bank group. */
export function hasLessonMaterials(lesson: number): boolean {
  return LESSONS_WITH_MATERIALS.has(lesson);
}
