// components/cms/documents/PrintFrame.tsx
// ============================================================================
// THE PAPER. Phase 5.
// ============================================================================
// Every generated document renders inside this: a screen-only Harbor toolbar,
// then an A4 sheet with the school, the room and the date at the top and a
// small "Generated by CMS" line at the foot.
//
// 🚨 PAPER IS WHITE. That is a Montree house rule (`lib/onboarding-core/print/
// LabelSheets.tsx`, `PickupSheets.tsx`: "Paper is white. That is a house rule in
// both products and is not a theme"), and CMS keeps it. Harbor blue is SCREEN
// chrome — a branded background on paper costs a teacher a cartridge and makes
// a wall poster harder to read across a room. Colour survives onto paper in
// exactly one place, the allergy severity badges, because there the colour IS
// the information.
//
// 🚨 WHY THE CSS IS IN A <style> TAG AND NOT IN globals.css. (Phase 6 moved the
// rules themselves one file across, to `./print-css.ts`, so the Montree bridge
// surface can render the same paper — the reasoning below is unchanged and is
// why they are still injected here rather than globally.) Two reasons, both
// structural:
//   1. `@page` CANNOT be scoped to a selector. A `@page { size: A4 }` rule in
//      the global stylesheet would apply to every print in the whole repo —
//      Montree's label sheets, PSS's sheets, a parent printing a report. The
//      proven house pattern for this is exactly what `lib/onboarding-core/
//      print/*` does: a plain <style> tag, rendered only on the pages that own
//      the paper. This mirrors it deliberately.
//   2. These are not Harbor classes. `.cms-doc-*` describe INK, not the design
//      system — they have no tokens, no hover states, and no business being in
//      the Harbor section of globals.css. (Documented as CMS_DESIGN_SYSTEM.md
//      §11, "the paper exception".)
//   The screen toolbar around the sheet uses ordinary Harbor `.cms-btn`
//   classes, because the toolbar IS screen chrome.
//
// RTL: every rule uses logical properties (`text-align: start`,
// `padding-inline`, `border-inline-start`), and the sheet inherits `dir` from
// `.cms-root`. An Arabic allergy poster mirrors correctly on paper without a
// single `[dir=rtl]` override.

import Link from 'next/link';
import type { ReactNode } from 'react';
import { PrintButton } from './PrintButton';
import { DOCUMENT_PRINT_CSS } from './print-css';
import { ArrowRightIcon, IconBox } from '@/components/cms/icons';
import type { DocumentMeta } from '@/lib/cms/engine/doc-generator';
import type { TFunction } from '@/lib/cms/i18n/t';

// 🚨 THE INK NOW LIVES IN ./print-css.ts — byte-identical, moved in phase 6 so
// the Montree bridge surface (/montree/dashboard/class-documents/<doc>) can
// render the SAME paper without importing one pixel of Harbor screen chrome.
// This component is unchanged in every other respect.
const PRINT_CSS = DOCUMENT_PRINT_CSS;

export interface PrintFrameProps {
  meta: DocumentMeta;
  /** Localised document title. The engine hands over a kind, not a sentence. */
  title: string;
  /** Localised date, formatted in the reader's locale by the page. */
  dateLabel: string;
  /** Room picker for a teacher who has more than one. */
  rooms?: { id: string; name: string }[];
  activeRoomId?: string;
  /** Slug of this document, so the room picker can stay on the same page. */
  slug: string;
  t: TFunction;
  children: ReactNode;
}

export function PrintFrame({
  meta,
  title,
  dateLabel,
  rooms = [],
  activeRoomId,
  slug,
  t,
  children,
}: PrintFrameProps) {
  return (
    <div className="cms-doc-shell min-h-screen bg-harbor-canvas py-6 px-4 sm:px-6">
      <style dangerouslySetInnerHTML={{ __html: PRINT_CSS }} />

      {/* ── screen-only Harbor toolbar ─────────────────────────────────── */}
      <div className="cms-doc-screen max-w-[190mm] mx-auto mb-5 flex flex-wrap items-center gap-3">
        <Link href="/cms/teacher/documents" className="cms-btn cms-btn-ghost cms-btn-sm">
          <IconBox flip>
            <ArrowRightIcon />
          </IconBox>
          {t('teacher.documents.back')}
        </Link>

        {rooms.length > 1 ? (
          <nav aria-label={t('teacher.documents.room')} className="flex flex-wrap items-center gap-1.5">
            {rooms.map((room) => (
              <Link
                key={room.id}
                href={`/cms/teacher/documents/${slug}?room=${encodeURIComponent(room.id)}`}
                className={`cms-btn cms-btn-chip ${
                  room.id === activeRoomId
                    ? 'cms-btn-primary cms-btn-soft'
                    : 'cms-btn-ghost cms-btn-outline'
                }`}
              >
                {room.name}
              </Link>
            ))}
          </nav>
        ) : null}

        <span className="ms-auto">
          <PrintButton />
        </span>
      </div>

      {/* ── the paper ──────────────────────────────────────────────────── */}
      <article className="cms-doc-sheet">
        <header className="cms-doc-head">
          <div className="min-w-0">
            <h1 className="cms-doc-title" dir="auto">
              {title}
            </h1>
            <p className="cms-doc-sub" dir="auto">
              {meta.schoolName}
            </p>
          </div>
          <div className="cms-doc-stamp">
            <b dir="auto">{meta.roomName}</b>
            {dateLabel}
          </div>
        </header>

        {children}

        <footer className="cms-doc-foot">
          <span>{t('doc.generatedBy')}</span>
          <span>
            {t('doc.generatedOn', { date: dateLabel })}
            {meta.printedByName ? ` · ${t('doc.printedBy', { name: meta.printedByName })}` : ''}
          </span>
        </footer>
      </article>
    </div>
  );
}
