import fs from 'fs';
const P = 'scripts/data/curated-visual-memory/sensorial.json';
const j = JSON.parse(fs.readFileSync(P, 'utf8'));
const NEW = [
  { work_key:'se_geometric_solids', work_name:'Geometric Solids', area:'sensorial',
    visual_description:'A set of solid, three-dimensional geometric shapes in blue-painted wood — a sphere, ovoid, egg (ellipsoid), cube, cuboid (rectangular prism), cylinder, cone, pyramids, and a triangular prism — presented in a basket or on a mat. The child handles them, names them, and often feels them blindfolded or matches them to cards or to flat bases. The defining picture is chunky solid 3D forms (a ball, a cube, a cone, a pyramid) rather than flat shapes.',
    key_materials:['Set of solid 3D wooden shapes (sphere, cube, cone, cylinder, pyramid, prism, ovoid)','Usually blue','Presented in a basket or on a mat','Sometimes with flat bases or nomenclature cards'],
    negative_descriptions:['NOT Geometric Cabinet: Geometric Solids are chunky THREE-DIMENSIONAL forms (spheres, cones, cubes) handled in the hand; the Geometric Cabinet holds FLAT shape insets in drawers.'] },
  { work_key:'se_constructive_triangles_rect', work_name:'Constructive Triangles - Rectangular Box', area:'sensorial',
    visual_description:'A shallow RECTANGULAR wooden box holding an assortment of flat wooden triangles in several colours, with black or coloured guide lines along some edges. The child slides the triangles together edge-to-edge so the marked lines meet, discovering that triangles combine to form larger triangles, rectangles and other figures. The defining picture is loose flat coloured triangles being joined into bigger shapes, stored in a rectangular box.',
    key_materials:['Rectangular wooden box','Assorted flat coloured wooden triangles','Guide lines on some edges','Joined edge-to-edge to build figures'],
    negative_descriptions:['NOT Constructive Triangles - Triangular Box: this set comes in a RECTANGULAR box; the triangular-box set comes in a TRIANGULAR box and its triangles build one large equilateral triangle.'] },
  { work_key:'se_constructive_triangles_tri', work_name:'Constructive Triangles - Triangular Box', area:'sensorial',
    visual_description:'A TRIANGULAR wooden box holding flat wooden triangles whose black guide lines let the child build one large equilateral triangle several different ways (from two, three or four smaller triangles). The child matches the black lines to join the pieces. The defining picture is coloured flat triangles combining into a single big triangle, stored in a triangle-shaped box.',
    key_materials:['Triangular wooden box','Flat coloured wooden triangles','Black guide lines','Build a large triangle multiple ways'],
    negative_descriptions:['NOT Constructive Triangles - Rectangular Box: this set comes in a TRIANGULAR box and builds one large equilateral triangle; the rectangular-box set holds a broader assortment that also forms rectangles and other figures.'] },
  { work_key:'se_constructive_triangles_large_hex', work_name:'Constructive Triangles - Large Hexagonal Box', area:'sensorial',
    visual_description:'A LARGE HEXAGONAL wooden box holding flat wooden triangles (including large obtuse and equilateral triangles) that combine to build hexagons and other figures. Black guide lines direct how the pieces join. The defining picture is coloured flat triangles forming a hexagon, stored in a six-sided box larger than the small hexagonal set.',
    key_materials:['Large hexagonal wooden box','Flat coloured wooden triangles','Black guide lines','Build hexagons and rhombi'],
    negative_descriptions:['NOT Constructive Triangles - Small Hexagonal Box: this is the LARGER hexagonal set; the small hexagonal set is a smaller six-sided box with fewer, smaller triangles.'] },
  { work_key:'se_constructive_triangles_small_hex', work_name:'Constructive Triangles - Small Hexagonal Box', area:'sensorial',
    visual_description:'A SMALL HEXAGONAL wooden box holding flat wooden triangles that combine into a hexagon and related figures, guided by black lines on the edges. The defining picture is coloured flat triangles forming a hexagon inside a small six-sided box.',
    key_materials:['Small hexagonal wooden box','Flat coloured wooden triangles','Black guide lines','Build a hexagon and rhombi'],
    negative_descriptions:['NOT Constructive Triangles - Large Hexagonal Box: this is the SMALLER hexagonal set; the large hexagonal set is a bigger six-sided box with more and larger triangles.'] },
  { work_key:'se_constructive_triangles_blue', work_name:'Constructive Triangles - Blue Triangles', area:'sensorial',
    visual_description:'A box of twelve identical all-BLUE right-angled scalene triangles, all the same size and colour. The child arranges pairs and groups of these blue triangles to form many different figures (rectangle, parallelogram, rhombus, larger triangles), discovering the relationships purely by shape since colour gives no clue. The defining picture is a set of same-size, same-blue flat triangles being rearranged into varied shapes.',
    key_materials:['Box of twelve identical blue right-angled triangles','All one size and one colour','Arranged to form varied figures','No guide lines — relationships found by shape'],
    negative_descriptions:['NOT the coloured Constructive Triangles sets: these are all identical BLUE triangles of one size; the boxed sets (rectangular, triangular, hexagonal) use MULTIPLE colours and guide lines.'] },
  { work_key:'se_superimposed_geometric_figures', work_name:'Superimposed Geometric Figures', area:'sensorial',
    visual_description:'A set of flat outlined geometric figures (often three of each shape) that graduate in size and can be laid one on top of another — nested or overlapping — to compare their forms and sizes. Usually thin coloured card or plastic shapes. The defining picture is flat outline shapes of the same kind in different sizes being stacked or overlapped.',
    key_materials:['Flat outlined geometric figures in graded sizes','Often three of each shape','Laid on top of one another to compare','Thin card or plastic'],
    negative_descriptions:[] },
  { work_key:'se_touch_boards', work_name:'Touch Boards', area:'sensorial',
    visual_description:'Flat wooden boards divided into alternating ROUGH (sandpaper) and SMOOTH strips. The child runs relaxed fingertips lightly across the board (often blindfolded) to feel the contrast between rough and smooth. The defining picture is a single larger board with striped rough/smooth bands, not small loose tablets.',
    key_materials:['Flat wooden board with alternating rough and smooth strips','Sandpaper strips vs bare wood','Felt with fingertips, often blindfolded','Introduces the tactile sense'],
    negative_descriptions:['NOT Touch Tablets: Touch Boards are larger fixed boards with striped rough/smooth bands; Touch Tablets are small loose paired tablets, each a single roughness grade, stored in a box.'] },
  { work_key:'se_sorting_grains', work_name:'Sorting Grains', area:'sensorial',
    visual_description:'Small bowls or a divided tray holding a mixture of two or more kinds of grains, beans or seeds (e.g. rice, beans, lentils) that the child sorts into separate containers by hand or with fingers. The defining picture is loose dry grains being separated into piles or dishes — a tactile/practical sorting activity.',
    key_materials:['Bowls or divided tray','A mix of grains, beans or seeds','Sorted by kind into separate containers','Handled by fingertips'],
    negative_descriptions:[] },
  { work_key:'se_baric_tablets', work_name:'Baric Tablets', area:'sensorial',
    visual_description:'Sets of small flat wooden tablets that look identical but differ in WEIGHT — made from light, medium and dark woods of different densities. The child weighs a tablet in each hand (usually blindfolded) and pairs or grades them by heaviness. The defining picture is plain flat wooden tablets, often in two or three wood tones, being balanced on the fingertips to judge weight.',
    key_materials:['Flat wooden tablets of identical size','Different woods giving different weights (light/medium/heavy)','Judged by weight in the hand, often blindfolded','Introduces the baric (weight) sense'],
    negative_descriptions:['NOT Thermic Tablets: Baric Tablets are matched by WEIGHT (light vs heavy woods); Thermic Tablets are matched by how WARM or COOL each material feels.','NOT Color Box: Baric Tablets are plain natural wood judged by weight; Color Box tablets are painted and matched by colour.'] },
  { work_key:'se_thermic_tablets', work_name:'Thermic Tablets', area:'sensorial',
    visual_description:'Pairs of flat tablets made of different materials — such as felt, wood, cork, metal, glass and stone — that feel warmer or cooler to the touch because they conduct heat differently. The child touches each (often blindfolded) and pairs the ones that feel the same temperature. The defining picture is small tablets of clearly DIFFERENT materials (a metal one, a wooden one, a felt one) matched by how warm or cool they feel.',
    key_materials:['Paired tablets of different materials (metal, wood, felt, cork, glass, stone)','Feel warmer or cooler by touch','Matched by temperature, often blindfolded','Introduces the thermic sense'],
    negative_descriptions:['NOT Thermic Bottles: Thermic Tablets are solid flat tablets of different materials matched by feel; Thermic Bottles are small BOTTLES filled with water at different temperatures.','NOT Baric Tablets: Thermic Tablets are matched by WARMTH; Baric Tablets are matched by WEIGHT.'] },
  { work_key:'se_thermic_bottles', work_name:'Thermic Bottles', area:'sensorial',
    visual_description:'A set of small identical BOTTLES filled with water at different temperatures (cold to warm). The child holds each bottle and pairs the two that feel the same warmth. The defining picture is matching water-filled bottles, grasped in the hands to compare temperature.',
    key_materials:['Small identical bottles filled with water','Water at different temperatures (cold to warm)','Paired by warmth in the hands','Introduces the thermic sense'],
    negative_descriptions:['NOT Thermic Tablets: Thermic Bottles are water-filled BOTTLES paired by temperature; Thermic Tablets are solid flat tablets of different materials.','NOT Smelling Bottles: Thermic Bottles are matched by how WARM the water feels; Smelling Bottles are opaque bottles matched by SCENT.'] },
  { work_key:'se_bells', work_name:'Montessori Bells', area:'sensorial',
    visual_description:'A row of identical-looking bells, each a metal cup mounted on a wooden stem over a small base, arranged on a long stand — plus a small wooden mallet and a damper. The bells look the same but sound different musical notes; the child strikes a bell with the mallet and pairs or grades them by pitch. The defining picture is a line of matching stem-mounted bells with a striker, not shaker cylinders.',
    key_materials:['Row of matching stem-mounted metal bells on a stand','Wooden mallet and damper','Bells look identical but sound different pitches','Paired and graded by musical tone'],
    negative_descriptions:['NOT Sound Boxes: bells are OPEN metal bells struck with a mallet to compare musical pitch; Sound Boxes are sealed wooden shaker cylinders matched by the noise they make.'] },
  { work_key:'se_smelling_bottles', work_name:'Smelling Bottles', area:'sensorial',
    visual_description:'Two sets of small opaque bottles with perforated or coloured lids (one set often red, one blue), each holding a different scent (spices, herbs, essences). The child sniffs a bottle and finds its match in the other set by SMELL. The defining picture is small identical opaque bottles being held to the nose.',
    key_materials:['Two sets of small opaque scented bottles','Coloured lids (e.g. red and blue)','Contents hidden — matched by scent','Introduces the olfactory sense'],
    negative_descriptions:['NOT Sound Boxes: Smelling Bottles are opaque bottles held to the NOSE and matched by scent; Sound Boxes are sealed cylinders shaken beside the EAR and matched by sound.','NOT Tasting Bottles: Smelling Bottles are matched by SMELL; Tasting Bottles/Cups present flavours the child TASTES.'] },
  { work_key:'se_tasting_bottles', work_name:'Tasting Bottles/Cups', area:'sensorial',
    visual_description:'Small bottles with droppers, or little cups, holding liquids of the basic tastes — sweet, salty, sour and bitter. The child tastes a drop (on the tongue or a spoon) and pairs or names the flavour. The defining picture is little cups or dropper bottles of clear liquids being tasted, with water for rinsing nearby.',
    key_materials:['Small dropper bottles or cups of flavoured liquids','Sweet, salty, sour, bitter','Tasted and matched or named','Water to rinse between tastes'],
    negative_descriptions:['NOT Smelling Bottles: Tasting Bottles/Cups present flavours the child TASTES on the tongue; Smelling Bottles are opaque bottles matched by SCENT at the nose.'] },
  { work_key:'se_mystery_bag', work_name:'Mystery Bag', area:'sensorial',
    visual_description:'A soft drawstring cloth bag holding an assortment of small familiar objects. The child reaches in WITHOUT looking, feels an object, names or identifies it by touch alone, then draws it out to check. The defining picture is a fabric bag with a child\'s hand inside, objects hidden from view — identification by feel (stereognostic sense).',
    key_materials:['Soft drawstring cloth bag','Assorted small familiar objects','Identified by touch alone, without looking','Develops the stereognostic sense'],
    negative_descriptions:['NOT Sorting Objects Stereognostically: the Mystery Bag hides a mix of objects to NAME one by touch; the sorting work has the child SORT hidden objects into groups by feel.'] },
  { work_key:'se_sorting_objects', work_name:'Sorting Objects Stereognostically', area:'sensorial',
    visual_description:'Pairs or groups of small objects (often two kinds mixed together) that the child sorts into separate containers by TOUCH — reaching into a bag or working blindfolded, feeling each object and placing it with its kind. The defining picture is hidden objects being separated into groups by feel rather than by sight.',
    key_materials:['Mixed small objects in a bag or covered tray','Sorted into groups by touch, blindfolded or unseen','Two or more object kinds','Develops the stereognostic sense'],
    negative_descriptions:['NOT Mystery Bag: this work SORTS hidden objects into groups by feel; the Mystery Bag has the child identify and NAME a single object by touch.'] },
];
const keys = new Set(j.entries.map(e => e.work_key));
let added = 0;
for (const e of NEW) { if (!keys.has(e.work_key)) { j.entries.push(e); added++; } }
fs.writeFileSync(P, JSON.stringify(j, null, 2) + '\n');
console.log(`sensorial: +${added} → ${j.entries.length} total`);
